.gitattributes, .travis.yml, lint-new-recipes.sh
This is partially a test to see if it works as intended.
=> Lint recipes on Travis-CI on each PR.

dev-lang/yab/yab-1.7.5.recipe
=> Update yab-1.7.5.recipe fix typo

dev-db/postgresql/postgresql-9.3.5.recipe
Improved DESCRIPTION with a bullet list.
Indenting some quotes and such minor things.
=> Removed full-stop in SUMMARY.

haiku-apps/pe/pe-2.4.5.recipe
=> Use latest commit in the repo instead of a year old archive.

media-sound/cmus/cmus-2.7.1.recipe, media-sound/cmus/patches/cmus-2.7.1-gcc2.patch
I hope it is ok now. If not, please, take my changes, fix it and commit it into the haikuports tree.
Sorry, git is too complicated for me.
=> cmus recipe

app-shells/zsh/patches/zsh-5.0.7.patchset, app-shells/zsh/zsh-5.0.7.recipe
=> Updated zsh recipe to use the B_USER_SETTINGS_DIRECTORY

app-shells/zsh/patches/zsh-5.1.patchset, app-shells/zsh/zsh-5.1.recipe
=> zsh 5.1 recipe

media-libs/lib3ds/lib3ds-2.0.0.recipe, media-libs/lib3ds/patches/lib3ds-2.0.0.patchset
http://code.google.com/p/lib3ds but since Google Code is going to close I use my own GitHub backup (http://github.com/AdrianArroyoCalle/lib3ds)
=> Add lib3ds 2.0.0

dev-libs/libbson/libbson-1.1.10.recipe
libbson available here: https://github.com/mongodb/libbson
=> Add recipe for libbson 1.1.10

games-board/gnuchess/gnuchess-6.2.1.recipe, games-board/gnuchess/patches/gnuchess-6.2.1.patchset
=> Add GNU Chess recipe

dev-vcs/git_flow/git_flow-1.8.0.recipe, dev-vcs/git_flow/patches/git_flow-1.8.0.patch
I created a recipe for the git-flow branching model.
=> git-flow: add recipe

sci-visualization/gnuplot/gnuplot-5.0.1.recipe, sci-visualization/gnuplot/licenses/Gnuplot
In this PR, I added a recipe for gnuplot a command-line graphing library.
=> Added recipe for gnuplot

media-gfx/exiftool/exiftool-10.07.recipe
Fairly straightforward, assuming I didn't miss anything.
=> Add exiftool recipe

sci-visualization/gnuplot/gnuplot-5.0.1.recipe
- Added missing dependencies libiconv and libtiff
=> Fix gnuplot recipe

sci-libs/cln/cln-1.3.4.recipe, sci-mathematics/ginac/ginac-1.6.5.recipe
Changes suggested by @korli on the discussion of da12815.
=> Add missing provide in cln and ginac and move ginac to sci-mathematics

sci-libs/cln/cln-1.3.4.recipe, sci-mathematics/ginac/ginac-1.6.5.recipe
Another suggestion from @korli. Thanks for the feedback!
=> cln, ginac: Give lib and devel the actual version of the library

dev-games/box2d/box2d-2.3.1.recipe, dev-games/box2d/patches/box2d-2.3.1.patch
I have disabled the testbed, as it requires GLUI, which doesn't have a port yet.
This is for the following Google Code-in task: https://codein.withgoogle.com/dashboard/task-instances/5869573593104384/
=> Update Box2D to the latest version

haiku-apps/haikuplot/haikuplot-1.0.0.recipe
This PR adds a recipe file for HaikuPlot.
=> Add recipe for HaikuPlot

games-puzzle/dynamate/dynamate-1.0.0.recipe
This PR adds a recipe for DynaMate.
@diversys I used PE so all of the recipe should implement proper tabbing.
=> Add recipe for DynaMate

dev-libs/json_c/json_c-0.12.recipe, dev-libs/libcss/libcss-0.5.0.recipe, dev-libs/libsolv/libsolv-0.3.0_haiku_2014_12_22.recipe, haiku-libs/haikuwebkit/haikuwebkit-1.5.1.recipe, media-libs/libbluray/libbluray-0.9.2.recipe, media-libs/libnsbmp/libnsbmp-0.1.2.recipe, media-libs/libnsgif/libnsgif-0.1.2.recipe, media-sound/fluidsynth/fluidsynth-1.1.6.recipe, net-libs/gloox/gloox-1.0.14.recipe, net-libs/liboauth/liboauth-1.0.3.recipe
I have reformatted one recipe as an example, as per waddlesplash's instructions. If this formatting is correct, I'll do the other nine.
This is for the following Google Code-in task: https://codein.withgoogle.com/dashboard/task-instances/5330222270382080/
=> Reformat ten recipes

haiku-apps/tipster/tipster-1.0.0.recipe
This PR adds a recipe for the Tipster application (which shows Haiku usability tips, see GCI task https://codein.withgoogle.com/dashboard/task-instances/6583422759731200/?sp-page=1 for more info).
=> Add recipe for tipster

dev-libs/xapian/patches/xapian-1.2.21.patch, dev-libs/xapian/xapian-1.2.21.recipe
https://codein.withgoogle.com/tasks/5867226108264448/?sp-organization=6583394590785536
I cannot clain that task just yet as I am locked into vectoroids over at #362.
=> Add xapian recipe

app-accessibility/espeak/espeak-1.48.04.recipe, app-accessibility/flite/flite-2.0.0.recipe, haiku-apps/a_book/a_book-1.1.recipe, haiku-apps/aalibtranslator/aalibtranslator-0.0.1.recipe, haiku-apps/aesaddon/aesaddon-0.3.1.recipe, haiku-apps/album/album-0.9.4.recipe, haiku-apps/aplayer/aplayer-4.0_svn.recipe, haiku-apps/armyknife/armyknife-4.3.0.recipe, haiku-apps/artpaint/artpaint-2.1.0git.recipe, haiku-apps/backup/backup-0.0.1.recipe, haiku-apps/bdhcalc/bdhcalc-1.1.recipe, haiku-apps/beae/beae-1.2.recipe, haiku-apps/beam/beam-1.2.recipe
This PR reformats 10 recipes to bring them up to current standards (https://github.com/haikuports/haikuports/wiki/HaikuPorter-Guidelines).
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5725172489256960/?sp-page=1
=> Reformat 10 recipes

dev-libs/libcss/libcss-0.4.0.recipe, haiku-libs/haikuwebkit/haikuwebkit-1.2.0.recipe, haiku-libs/haikuwebkit/haikuwebkit-1.2.1.recipe, haiku-libs/haikuwebkit/haikuwebkit-1.2.2.recipe, haiku-libs/haikuwebkit/haikuwebkit-1.2.3.recipe, media-libs/libdvdnav/libdvdnav-4.2.0.recipe, media-libs/libmpdclient/libmpdclient-2.11_git.recipe, media-libs/libnsbmp/libnsbmp-0.1.1.recipe, media-libs/libnsgif/libnsgif-0.1.1.recipe, media-libs/libpng/libpng-1.5.25.recipe, media-libs/libsdl2/libsdl2-2.0.0.recipe
https://codein.withgoogle.com/dashboard/task-instances/4796400818716672/?sp-page=1
=> Reformatted 10 recipes

games-roguelike/nethack/licenses/nethack, games-roguelike/nethack/nethack-3.6.0.recipe, games-roguelike/nethack/patches/nethack-3.6.0.patchset
So, with tons of experiments I have managed to fix everything and game runs in terminal. The patches are necessary, as even more work is needed to make it work on Arch Linux (sic!).
=> Nethack 3.6.0: Added patches and recipe

dev-games/mathfu/mathfu-1.0.2.recipe
https://codein.withgoogle.com/dashboard/task-instances/6331223177691136/?sp-page=1
MathFu is a header only library. CMake is used only to build unit tests (but it uses Git submodules for that also).
=> MathFu 1.0.2

app-i18n/enca/enca-1.15.recipe, app-text/libpaper/libpaper-1.1.24.recipe, dev-libs/libedit/libedit-2014_10_30_3.1.recipe, dev-libs/polarssl/polarssl-1.3.9.recipe, media-libs/faad2/faad2-2.7.recipe, media-libs/libebur128/libebur128-1.0.1.recipe, media-libs/libsdl2/libsdl2-2.0.1.recipe, media-libs/pnglite/pnglite-0.1.17.recipe, net-libs/libircclient/libircclient-1.8.recipe, sys-libs/glu/glu-9.0.0.recipe
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5709428917534720/?sp-page=1
=> Reformat 10 Recipes #2

games-engines/hugo/hugo-3.1.03.recipe, games-engines/hugo/licenses/hugo
https://codein.withgoogle.com/dashboard/task-instances/5661131909627904/?sp-page=1
=> Hugo 3.1.03: Added recipe

games-puzzle/gnurobbo/gnurobbo-0.66.recipe, haiku-apps/drive_encryption/drive_encryption-1.0.recipe, haiku-apps/drive_encryption/licenses/TrueCrypt, haiku-apps/transplus/patches/transplus-0.6.patchset, haiku-apps/transplus/transplus-0.6.recipe, haiku-libs/sockhop/sockhop-1.13.recipe, net-mail/dovecot/dovecot-2.2.15.recipe, net-mail/dovecot/patches/dovecot-2.2.15.patchset
I apologize this PR is so large.
In this PR I have added recipes for gnurobbo 0.66, transplus, drive_encryption (which is not working), dovecot, and sockhop. This PR should allow all pr_backup branches at https://github.com/soakbot/haikuports to be closed.
=> Finish backup recipes from soakbot

haiku-apps/bsnow/bsnow-1.0.0.recipe
This PR adds a recipe for BSnow, which is being removed from the Haiku repo.
=> Add recipe for bsnow

dev-games/irrlicht/irrlicht-1.8.3.recipe, dev-games/irrlicht/patches/irrlicht-1.8.3.patchset
https://codein.withgoogle.com/dashboard/task-instances/4889102981791744/?sp-page=1
=> Irrlich 1.8.3

dev-db/libmysqlclient/libmysqlclient-6.1.6.recipe, dev-db/libmysqlclient/patches/libmysqlclient-6.1.6.patchset
I have a doubt about versioning. The library files are 18.3.0 but the source tarball it's 6.1.6.
https://codein.withgoogle.com/dashboard/task-instances/6362508340232192/?sp-page=1
=> libmysqlclient

games-arcade/freegish/freegish-1.0.recipe, games-arcade/freegish/patches/freegish-1.0.patchset
Please have a look at my work. Thank you.
=> [GCI] Add recipe for freegish.

games-arcade/freegish/freegish-1.0.recipe
=> Added a source directory to freegish recipe file.

games-arcade/freegish/freegish-1.0.recipe
Apologies about the previous build still failing, I assumed the change of source directory would have no impact on the layout. I ran the build myself this time and fixed it till it worked so I doubt there should be issues. Sorry for the inconvenience.
=> Fixed failed FreeGish build due to change of directories.

media-libs/libfpx/libfpx-1.3.1.recipe, media-libs/libfpx/licenses/Flashpix
This is to finish the gci task: https://codein.withgoogle.com/dashboard/task-instances/6461249269268480/
This will add the recipe for the library that handles FlashPIX images.
Also corrected the errors pointed out by the last pull request I made.
=> Added libfpx recipe

app-misc/shanty/shanty-0.4.recipe
Hi, please have a look at my work. Also, I have some doubts on the INSTALL() block, I am suppose to install it such that shanty can be run on the terminal by running the command "shanty", but not so sure if I did it correctly (or if I also did redundant stuff). Thanks.
=> [GCI] Add recipe for shanty

media-libs/libpng/libpng-1.5.26.recipe, media-libs/libpng/libpng12-1.2.56.recipe, media-libs/libpng/libpng16-1.6.20.recipe
* libpng12: Update to 1.2.56
* libpng: Update to 1.5.26 & add "?arm" + "?ppc" to ARCHITECTURES.
* libpng16: Add "?ppc" to ARCHITECTURES.
=> libpng: update 1.2 & 1.5 series

games-emulation/vice/patches/vice-2.4.24.patchset, games-emulation/vice/vice-2.4.24.recipe
Commit message:
`The game data goes to /settings/VICE as the files should be edited by user.`
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5113174395191296/?sp-page=1
=> VICE 2.4.24: Added recipe and patches

haiku-apps/armyknife/armyknife-5.1.0.recipe
As of https://codein.withgoogle.com/dashboard/task-instances/4824242864521216/?sp-page=1.
=> Update ArmyKnife to 5.1.0

games-emulation/ja2_stracciatella/ja2_stracciatella-0.12.1.recipe, games-emulation/ja2_stracciatella/licenses/SFI, games-emulation/ja2_stracciatella/patches/ja2_stracciatella-0.12.1.patchset
I am unable to test the game as I don't own it. Running it from command line
prints no data found error (but nothing which could mean that anything is wrong).
Also I use this version, cause the newer version have boost error which I can't fix.
I was not unable to contact Stracciatella team.
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6471749000495104/?sp-page=1
=> Stracciatella 0.12.1: Added recipe and patches

dev-libs/libbson/libbson-1.1.10.recipe, haiku-apps/kovel/kovel-1.0.0.recipe
Recipe for Kovel 1.0.0 and updated libbson recipe to save include files in the correct place
https://codein.withgoogle.com/dashboard/task-instances/5199914376101888/?sp-page=1
=> Kovel 1.0.0

dev-util/lcov/lcov-1.12.recipe, dev-util/lcov/patches/lcov-1.12.patchset
I have created a recipe for lcov.
=> lcov: add recipe

sys-libs/libatomic_ops/libatomic_ops-7.4.2.recipe
A libatomic_ops recipe made for the google code in. Needs to be fixed though. Google Code-in Task URL: https://codein.withgoogle.com/dashboard/task-instances/6400516531683328/?sp-page=1
=> [GCI] libatomic_ops: Add recipe

www-client/w3m/w3m-0.5.3.recipe
Also fix `DESCRIPTION` formatting, switch `SOURCE_URI` to the short SourceForge redirector, use tabs for `COPYRIGHT` and use `$portVersion` instead of the hard-coded version.
=> w3m: reorder sections, ARCHITECTURES += ?x86_64 ?arm ?ppc

dev-libs/nfd/licenses/Zlib-generic, dev-libs/nfd/nfd-1.0.recipe
Hi, please check my work. I used the scons method, is this correct or do I need to manually move the files instead? Thanks.
=> [GCI] Add recipe for Native File Dialog

haiku-apps/haikuporter/haikuporter-1.1.0.recipe
Updates the haiku porter recipe to the current version 1.1.0
=> Add recipe for the newest version of haikuporter

haiku-apps/haikuplot/haikuplot-1.0.1.recipe, haiku-apps/tipster/tipster-1.0.1.recipe
This PR adds new recipes for tipster & haiku plot to reflect the multiple new changes since the recipes were last edited.
=> Update tipster & haikuplot

dev-python/sip/patches/sip-4.17.patch, dev-python/sip/sip-4.17.recipe
Maybe we need further modification in /specs/haiku-g++. It is just the linux one, renamed.
Tested, it works, but i'm not sure about the flags.
=> SIP Initial Recipe

app-cdr/daa2iso/daa2iso-0.1.7e.recipe, app-cdr/uif2iso/uif2iso-0.1.7c.recipe
Also install documentation/packages/daa2iso/daa2iso.txt
=> daa2iso: reorder sections and mark x86_{gcc2,x64} as tested

dev-python/pyqt/pyqt-5.5.1.recipe
=> PyQt5 Initial Recipe

app-arch/gzip/gzip-1.7.recipe, app-arch/gzip/patches/gzip-1.7.patchset
* Bump version.
* Update HOMEPAGE.
* Drop SOURCE_DIR as it is not needed.
* Delete **`$libDir/charset.alias`** as it is not needed.
=> gzip: bump to version 1.7.

dev-vcs/git/git-2.8.0.recipe, dev-vcs/git/patches/git-2.8.0.patchset
=> Git updated to 2.8.0

haiku-apps/drive_encryption/drive_encryption-1.0.recipe
Change homepage back to github repo of Axel Dörfler
=> Update DriveEncryption homepage to upstream repo

games-misc/sdljoytest/sdljoytest-11102003.recipe
changed the old "bep" file to the new haikuporter format
=> sdljoytest, update the recipe to use haikuporter

games-action/tuxracer/patches/tuxracer-0.61.patch, games-action/tuxracer/tuxracer-0.61.recipe, games-action/tuxracer_data/tuxracer_data-0.61.recipe
the library tcl had to be altered to use portVersion >= 8.0 instead of 8.5
best to be played with hardware accelaration :)
=> new recipes for TuxRacer

media-video/live555/live555-2016.01.29.recipe
* Fix install directories.
* Add BUILD_REQUIRES.
* Add REQUIRES_DEVEL.
=> live555: Build and install improvements

media-libs/libpng/libpng-1.5.27.recipe, media-libs/libpng/libpng12-1.2.56.recipe, media-libs/libpng/libpng16-1.6.22.recipe
* libpng16: CONFLICTS_devel **+=** libpng12_devel.
* libpng12: CONFLICTS_devel = libpng_devel + libpng16_devel.
* ~~libpng: CONFLICTS_devel = libpng12_devel + libpng16_devel.~~
* libpng: drop empty $manDir in the base package, libpng.
=> libpng: tune CONFLICTS_devel; cosmetic changes.

media-libs/libpng/libpng16-1.6.23.recipe
Also add back lib:libpng to PROVIDES to allow upgrades from 1.6.20-1.
=> libpng16: bump to 1.6.23.

dev-util/cppunit/cppunit-1.13.2.recipe
Work in progress, don't merge yet.
HP complains:
`POLICY ERROR: no matching provides "cmd:DllPlugInTester_x86" for "bin/DllPlugInTester-x86"`
hovewer it is defined in PROVIDES section.
Any help will be greatly appreciated.
=> WIP CPPUNIT update

media-libs/libmng/libmng-2.0.3.recipe, media-libs/libmng/patches/libmng-2.0.3.patchset
This commit fixes a few errors encountered whilst building libmng on haiku.
=> libmng build issues fix

dev-libs/uchardet/patches/uchardet-0.0.6.patchset, dev-libs/uchardet/uchardet-0.0.6.recipe
https://github.com/BYVoid/uchardet
goes in dev-libs/uchardet/
latest release 0.0.5
License MPL 1.1
=> add uchardet library

net-libs/libtorrent/libtorrent-0.13.6.recipe
=> libtorrent update

app-arch/atool/atool-0.39.0.recipe
=> atool recipe

media-fonts/fontutil/fontutil-1.3.1.recipe
=> Xorg fontutil recipe

dev-libs/libpcre2/libpcre2-10.21.recipe, dev-libs/libpcre2/licenses/PCRE
=> LibPCRE2 recipe

app-text/asciidoc/asciidoc-8.6.9.recipe
~~asciidoc: bump to 8.6.9, move config files to settings/asciidoc/.~~
~~Also switch to ARCHITECTURES="any"~~
=> asciidoc: bump to 8.6.9.

games-kids/tuxtype/additional-files/tuxtype2.rdef, games-kids/tuxtype/patches/tuxtype2-1.5.2.patchset, games-kids/tuxtype/tuxtype2-1.5.2.recipe
This is version 1.5.2 that still works, the future versions use t4k_common library that is not compiling for Haiku (yet), I'm in contact with theire people who are reworking the source ... so maybe we could see an update in the future :)
=> tuxtype, new recipe

games-action/swars/additional-files/ReadmeHaiku, games-action/swars/patches/swars_x86-0.3.patchset, games-action/swars/swars-0.3.recipe
Game crashes on exit, fullscreen was working but at some point frooze my system ... best to play it in windowed mode (default)
=> swars, new recips

net-proxy/torsocks/patches/torsocks-1.3.patchset, net-proxy/torsocks/torsocks-1.3.recipe
re-implemented the patches from previous version
=> torsocks bump version, fix lib dependency

media-libs/fblend/fblend-0.4.recipe
if there is a sollution to just create a devel package alone I would be glad to hear it, this one is working for x86_gcc2 (with the examples from allegro)
=> fblend 0.4 recipe, working

app-arch/unarr/unarr-1.0.0.recipe
based on miqlas previous work :)
=> unarr, recipe based on myqlas PR 491

app-shells/fish/fish-2.3.1.recipe, app-shells/fish/patches/fish-2.3.1.patchset
Thanks for Skipp_OSX for the patch.
Sadly it store the config file in home folder ( https://github.com/fish-shell/fish-shell/issues/3030 ) :( Patches welcomed.
=> Fish 2.3.1 recipe

app-shells/mksh/mksh-53a.recipe, app-shells/mksh/patches/mksh-53a.patch
~~Also switch HOMEPAGE and SOURCE_URI to use the canonical URI.~~
=> mksh: bump to R53a, add cmd:cmp to BUILD_PREREQ for TEST().

games-arcade/opensyobonaction/opensyobonaction-2.rc2.recipe, games-arcade/opensyobonaction/patches/opensyobonaction-2.rc2.patchset
Please help to test it. My haikuporter just goes crazy all the time if i try to build it. Could be hardware problem.
=> Open Syobon Action recipe

sys-libs/readline/readline-7.0.recipe
=> Readline 7 fix

haiku-apps/bescreencapture/bescreencapture-2.1.recipe
I just released BeScreenCapture 2.1 so I created a recipe for it.
=> BeScreenCapture 2.1 recipe

haiku-apps/serviceswatcher/serviceswatcher-1.0.recipe
Working from a new fork this time.
=> Adding ServicesWatcher 1.0 recipe

dev-qt/qt5/qt5-5.6.1.recipe
Fixes the SHA 256 checksum issue in the qt5-5.6.1 recipe.
=> Replaced Qt5 5.6.1 SHA 256 checksum

haiku-apps/einsteinium/einsteinium-1.3.0.recipe
New release of Einsteinium 1.3.0
=> Adding Einsteinium 1.3.0 recipe

haiku-apps/bescreencapture/bescreencapture-2.2.1.recipe
Recipe for BeScreenCapture 2.2.1.
Reorganized PROVIDES and REQUIRES fields,
added $portVersion
=> Recipe for BeScreenCapture 2.2.1

app-emulation/euae/euae-0.8.29~WIP4.recipe
This builds the very last version of e-uae with SDL, JIT and Picasso96 emulation working
=> Added recipe for the latest version of e-uae

dev-libs/librevenge/librevenge-0.0.4.recipe
=> Updated librevenge recipe

dev-libs/libfilezilla/libfilezilla-0.6.1.recipe, dev-libs/libfilezilla/patches/libfilezilla-0.6.1.patchset
I think you know where it goes...
=> Libfilezilla recipe

sys-apps/the_silver_searcher/the_silver_searcher-0.32.0.recipe
=> Silver Searcher updated recipe

dev-util/bencode/bencode_tools-20110315.recipe, dev-util/bencode/patches/bencode_tools-20110315.patchset
per request for issue: https://github.com/haikuports/haikuports/issues/440
=> bencode-tools, new recipe

dev-lang/luajit/luajit-2.1.0~beta2.recipe
=> LuaJit recipe

net-p2p/rtorrent/patches/rtorrent_x86-0.9.6.patchset, net-p2p/rtorrent/rtorrent-0.9.6.recipe
=> Rtorrent update

media-libs/imlib2/imlib2-1.4.9.recipe, media-libs/imlib2/licenses/IMLIB2
=> imlib2 recipe. Looks pretty wrong but works.

app-i18n/libguess/libguess-1.2.recipe
=> Libguess 1.2 recipe

haiku-apps/serviceswatcher/serviceswatcher-1.0.1.recipe
Updated github repo name in serviceswatcher-1.0.recipe and added serviceswatcher-1.0.1-recipe
=> Adding ServicesWatcher 1.0.1

sys-apps/file/file-5.29.recipe, sys-apps/file/patches/file-5.29.patchset
In patchset: Keep -Wformat=2 in configure.ac's WARNINGS definition.
=> file: bump to 5.29, drop libtool file, touch patchset.

net-libs/neon/neon-0.30.2.recipe
Added secondaryarch for libtoolize.
No functional change.
=> Updated neon recipe

media-sound/mpc/musicpc-0.28.recipe
=> Updated musicpc recipe

app-editors/vim/patches/vim-8.0.0046.patchset, app-editors/vim/vim-8.0.0046.recipe
The patchset is just a dirty update, i'll try to get it a bit cleaner later.
It builds and works.
http://chunk.io/f/73233ee286834b58b3868a7c9439b593
=> Vim 8 recipe with updated patchset

sys-devel/gettext/gettext-0.19.8.1.recipe
Also drop devel:lib{iconv,ncurses} from REQUIRES.
=> gettext: drop libtool files, update gettext compat to >= 0.19.

media-gfx/jpegoptim/jpegoptim-1.4.4.recipe
=> Add Jpegoptim

dev-libs/libsodium/libsodium-1.0.11.recipe, dev-libs/libsodium/licenses/ISC, dev-libs/libsodium/patches/libsodium-1.0.11.patchset
Creates a package for libsodium.
=> Added libsodium package.

media-gfx/gifsicle/gifsicle-1.88.recipe
=> gifsicle recipe

haiku-apps/einsteinium/einsteinium-1.3.2.recipe
Recipe for new version, also now builds for both x86_gcc2 and x86.
=> Adding Einsteinium 1.3.2 recipe

dev-libs/libconfig/libconfig-1.5.recipe
libconfig is a C/C++ cross platform library that parses structured config files.
=> new recipe: libconfig

dev-util/xdelta/xdelta-3.1.0.recipe
Currently x86 only. Should I change the default binDir for where it generates? aka, not in bin/x86 to just bin?
=> added xdelta recipe

media-sound/mpc/musicpc-0.28.recipe
=> MusicPC: fix Requires

media-sound/mpg321/mpg321-0.3.2.recipe, media-sound/mpg321/patches/mpg321-0.3.2.patchset
Adding new recipe for mpg321, a simple and lightweight commandline mp3 player.
=> mpg321: new recipe for a commandline mp3 player

sci-libs/primesieve/primesieve-5.7.3.recipe
Adding new recipe for primesieve, Fast C/C++ prime number generator
library.
=> primesieve: Add new recipe

app-text/odt2txt/odt2txt-0.5.recipe, app-text/odt2txt/patches/odt2txt-0.5.patch
Added a recipe for odt2txt, a converter from OpenDocument Text to plain text.
=> (GCI) Added recipe for app-text/odt2txt

haiku-apps/simplebackup/simplebackup-2.0.1.recipe
Request to add SimpleBackup which I have updated to run on Haiku nightly image.
=> Adding new port SimpleBackup v2.0.1

dev-libs/libsigc++/libsigc++3-2.99.7.recipe
=> Updated libsigc++ recipe

dev-lang/r/r-3.3.2.recipe
R is a programming language and software environment for statistical computing and graphics supported by the R Foundation for Statistical Computing. The R language is widely used among statisticians and data miners for developing statistical software and data analysis. Polls, surveys of data miners, and studies of scholarly literature databases show that R's popularity has increased substantially in recent years.
R is a GNU package. The source code for the R software environment is written primarily in C, Fortran, and R. R is freely available under the GNU General Public License, and pre-compiled binary versions are provided for various operating systems. While R has a command line interface, there are several graphical front-ends available.
=> R-lang : new recipe

sci-visualization/gnuplot/gnuplot-5.0.5.recipe
=> Gnuplot: bump version, enabled x64, removed unneded -lm patch

sci-libs/openblas/openblas-0.2.19.recipe, sci-libs/openblas/patches/openblas-0.2.19.patchset
Solves: https://github.com/haikuports/haikuports/issues/964
=> OpenBLAS: fixed port, enabled fortran code

app-text/unrtf/unrtf-0.21.9.recipe
=> unrtf: added recipe

media-libs/libdmtx/libdmtx-0.7.4.recipe, media-libs/libdmtx/licenses/libdmtx v1.0
Added recipe for libdmtx DataMatrix library.
=> libdmtx: added recipe

dev-libs/beecrypt/beecrypt-4.2.1.recipe
Added recipe for beecrypt crypto library.
=> beecrypt: added recipe

net-dialup/cutecom/additional-files/cutecom.rdef.in, net-dialup/cutecom/cutecom-0.22.0.recipe, net-dialup/cutecom/patches/cutecom-0.22.0.patchset
Added recipe for CuteCom graphical serial terminal.
=> cutecom: added recipe

app-crypt/paperkey/paperkey-1.4.recipe
Added recipe for Paperkey secret key data extraction tool.
=> paperkey: added recipe

media-sound/libopenmpt/libopenmpt-0.2.7386~beta20.3.recipe
Added recipe for libopenmpt module player library.
=> libopenmpt: added recipe

media-gfx/iec16022/iec16022-0.2.7.recipe
Added recipe for iec16022 DataMatrix generation tool and library.
=> iec16022: added recipe

media-sound/wavpack/licenses/WavPack, media-sound/wavpack/wavpack-5.0.0.recipe
Added recipe for WavPack audio compression format.
=> wavpack: added recipe

haiku-apps/beohms/beohms-0.1~git.recipe
Added recipe for BeOhms Ohm's Law calculator.
=> beohms: added recipe

media-gfx/icoutils/icoutils-0.31.1.recipe
Added recipe for icoutils icon and cursor file convertor.
=> icoutils: added recipe

dev-libs/libksba/libksba-1.3.5.recipe
Added recipe for liksba X.509 library.
=> libksba: added recipe

haiku-apps/babybe/babybe-2.2~git.recipe
Added recipe for BabyBe children game.
Please do not merge until https://github.com/HaikuArchives/BabyBe/pull/1 has been merged and I've had a chance to update the recipe to use the latest commit. The recipe assumes there is a working Makefile in the source directory.
=> babybe:added recipe

games-board/stockfish/stockfish-8.recipe
Adding new recipe for stockfish, a chess engine claimed to be strongest in the world.
=> stockfish: new recipe for a chess engine

dev-util/kbuild/kbuild-0.1.5.recipe, dev-util/kbuild/patches/kbuild-0.1.5-p2.patch
Reverts haikuports/haikuports#1033
Apparently I was a little hasty in my merging...
=> Revert "KBuild: Build fix, recipe cleanup"

app-emulation/qemu/patches/qemu-2.7.0.patchset, app-emulation/qemu/qemu-2.7.0.recipe
=> Qemu: bump version, updated patchset

dev-libs/libgit2/libgit2-0.24.1.recipe, dev-libs/libgit2/libgit2-0.25.1.recipe
=> LibGIT2 Haiku recipe

app-text/libwps/libwps-0.4.5.recipe
* COPYRIGHT: add years and 1 missing author, sort by # of commits.
* SOURCE_URI: http -> https, tar.bz2 -> tar.xz.
* Add TEST: "make check"
=> libwps: bump to 0.4.5, fix COPYRIGHT, add TEST.

dev-util/capstone/capstone-3.0.4.recipe
This request fixes the library files being packaged properly after compilation.
=> capstone: fix x86 build

dev-libs/botan/botan-2.0.1.recipe
I get this error when i try to build it http://pastebin.com/EDgJUhUC
=> botan-2.0.1:new recipe

dev-libs/libusb/libusb-1.0.21.recipe
I went step by step through each suggested change and tested the build each time for breakage.
The recipe builds on x86_gcc2.
=> Updated libusb recipe to latest and suggested cosmetic fixes

media-libs/opencolorio/opencolorio-1.0.9.recipe
=> OpencolorIO: Fix INSTALL

dev-embedded/cpcsdk/cpctools-0.3.0.recipe, games-arcade/lbreakout2/lbreakout2-2.6.5.recipe
in cpctools and lbreakout2 as it's already in master.
=> Use libpng16 in BUILD_REQUIRES

dev-util/keystone/keystone-0.9.1.recipe, dev-util/keystone/patches/keystone-0.9.1.patchset
Initial keystone recipe, tested on x86 but not on x86_64 but should work on both platforms.
=> keystone: create recipe

app-shells/fish/fish-2.5.0.recipe
Now with less "unknown version" and with more "2.5.0" for free! Just today! Call us: 0900-miqlas!
=> Fish: radical reduced build-time deps, thanks zanchey!

sys-apps/qdirstat/patches/qdirstat-1.2.patchset, sys-apps/qdirstat/qdirstat-1.2.recipe
A Qt based directory statistics application, based on KDirStat. Tested on x86.
=> qdirstat: new recipe

media-sound/amc/amc-1.14.0.recipe
Build fails in makefile on line 60 recipe for target amc.o failed
=> Recipe and patch for AMC

haiku-apps/sync_modular/licenses/Sync_Modular, haiku-apps/sync_modular/sync_modular-2.2.1b.recipe
Why didn't we had this before? It works nicely :)
=> Sync Modular recipe

media-gfx/blender/blender-2.78a.recipe, media-gfx/blender/patches/blender-2.78a.patchset, media-gfx/blender/patches/blender_2.78a.patchset
=> Blender: bump version, updated patchset

haiku-apps/ultradv/ultradv-1.0~git.recipe
=> UltraDV: new recipe

app-crypt/gnupg/gnupg-2.1.19.recipe, app-crypt/gnupg/patches/gnupg-2.1.19.patchset
still needs testing, so not merge yet :)
=> gnupg, bump version

sci-mathematics/amath/amath-1.7.1.recipe
=> new recipe: amath 1.7.1

net-proxy/privoxy/privoxy-3.0.26.recipe
=> Privoxy: bump version

dev-util/gtk_doc/gtk_doc-1.25.recipe, dev-util/gtk_doc/patches/gtk_doc-1.25.patchset
WIP ... the *.pc is still not in the correct place ...
=> gtk-doc, bump version

dev-lang/dmd/dmd-2.067.1.recipe, dev-lang/dmd/licenses/Digital Mars, dev-lang/dmd/patches/dmd-2.067.1.patchset, dev-lang/dmd/patches/dmd-2.073.2.patchset
This recipe isn't the lastest version of dmd, this is would be useful to get lastest version of dmd because any version above 2.067.1 would require bootstrap to build.
I'm not sure if the patches working correctly, because dmd require druntime to work correctly.
And now i'm working on porting druntime and phobos.
I always want to build app based on dlang in haiku lol, helps are welcome!
=> Add dmd v2.067.1 recipe

sci-libs/hdf5/hdf5-1.8.18.recipe
=> HDF5: new recipe

dev-games/godot/godot-2.1.3.recipe, dev-games/godot/patches/godot-2.1.3.patchset
Builds fine, but freaks out at linking stage. Help required.
=> Godot: new recipe

media-video/mplayer/mplayer-1.3.0.recipe
Recipe cleanup, fixed png, reduced REQs
=> Mplayer 1.3.0 fix

sci-mathematics/amath/amath-1.8.1.recipe
=> amath 1.8.1

app-text/enchant/enchant-1.6.0.recipe
wip, no merge yet, hunspell should be looked at if it can be build for the latest version pspel doesn't really get picked up for aspell ...
=> enchant, update recipe to work and install

dev-util/radare2/patches/radare2-1.4.0.patchset, dev-util/radare2/radare2-1.4.0.recipe
Tested on x86_64 and x86, x86_gcc2 still remains untested.
=> radare2: bump version

sci-libs/armadillo/armadillo-7.800.2.recipe
=> Armadillo: new recipe

app-forensics/snowman/snowman-0.1.0.recipe
Snowman is a cross-platform GUI/CLI application for decompiling native code to C/C++ which supports various architectures (x86/x86-64/ARM) and executable file formats (ELF/Mach-O/PE). Tested on x86_64.
=> snowman: new recipe

dev-libs/libpciaccess/libpciaccess-0.13.5.recipe, dev-libs/libpciaccess/patches/libpciaccess-0.13.5.patchset
Untested but builds. This package is a prerequisite for libDRM. If there are issues with the execution of this library, I will fix them as found.
=> Added port for libpciaccess (dep for libDRM)

media-libs/libepoxy/libepoxy-1.4.2.recipe, media-libs/libepoxy/patches/libepoxy-1.4.2.patchset
Needed by LibreOffice. Tested on x86_64.
=> libepoxy: new recipe

dev-cpp/muparser/muparser-2.2.5.recipe, dev-cpp/muparser/patches/muparser-2.2.5.patchset
builds and installs ok on gcc2h (x86 arch), the .pc file doesn't contain the correct directions to the libs nor headers, I disabled $prefix for now, if it's set the pkg-config file is ok but I get a policy error for a top level include folder ... wip (but wanted to share already) :)
=> muparser, new recipe/patch file

dev-lang/python/patches/python-2.7.13.patchset, dev-lang/python/patches/python3-3.6.1.patchset, dev-lang/python/python-2.7.13.recipe, dev-lang/python/python3-3.6.1.recipe
Trying to fix #1120.
Will do other python version ASAP.
=> [python-2.7.13 & 3.6.1] Implement CTypes's find_library() for Haiku.

haiku-apps/ultradv/ultradv-0.0.1.recipe
* Created by miqlas, updated by me to work.
=> Add UltraDV recipe for x86 and x86_64

app-editors/emacs/emacs-25.2.recipe, app-editors/emacs/patches/emacs-25.2.patchset
=> emacs: new recipe

dev-libs/expat/expat-2.2.1.recipe, dev-libs/expat/patches/expat-2.2.1.patchset
Some white spaces cleaned up with the patchset file also ...
=> expat, add patch from hartwork as asked in the issue

sys-apps/less/less-493.recipe, sys-apps/less/patches/less-493.patchset
Could use some checks on x86 and x86_64 (looks ok on x86_gcc2) ...
=> less, bump version

app-editors/vim/patches/vim-8.0.0739.patchset, app-editors/vim/vim-8.0.0739.recipe
they have a new release almost every day.
=> VIM: Missing Copyright end-year.

sci-mathematics/amath/amath-1.7.1.recipe, sci-mathematics/amath/amath-1.8.3.recipe
Update 1.8.1 -> 1.8.3
Update homepage and dist sites
Cleanup description
Primary change: 1.8.3 comes with a nice man page.
=> Update amath version, dist sites & homepage

dev-lang/python/python3-3.6.2.recipe
=> python3: add missing dependency on libffi.

media-sound/mpc/musicpc-0.28.recipe
=> MusicPC: recipe cleanup, iconv not recognised

media-libs/opencv/opencv-3.2.0.recipe, media-libs/opencv/patches/opencv-3.2.0.patchset
Work in progress: do not merge yet.
=> Opencv 3.2.0

dev-lang/yab/yab-1.7.5.4.recipe, haiku-apps/yab_ide/yab_ide-2.2.8.recipe
yab does not require a parchset for x86_64
yab-IDE now works on x86_64
=> new recipie for yab and yab-IDE

haiku-apps/beacon/beacon-27.recipe, haiku-apps/beacon/patches/beacon-27.patchset
=> beacon, fix old bep file

sys-apps/util-linux/patches/util_linux-2.30.1.patchset, sys-apps/util-linux/util_linux-2.30.1.recipe
fish requires ul. this package got it.
=> Util-Linux: new recipe

games-arcade/hermes/hermes-1.02.recipe, games-arcade/hermes/licenses/HERMES
build requires shouldn't needed, but they are.
=> Hermes: new recipe

haiku-apps/radio/radio-0.0.3_14.recipe
=> Haiku Radio, new recipe

games-arcade/hermes/hermes-1.02.recipe
Solved bugs:
- config file was not written
=> Hermes: Updated hashes, bump rev, bugfix version

games-arcade/hermes/hermes-1.02.recipe
=> Hermes: build fix

games-emulation/pin8/pin8-1.0.recipe
Dear repository masters,
Please find the HaikuPorts recipe for Pin8, a native Chip-8 emulator for Haiku OS written in C++.
Kind regards.
=> pin8, new recipe

dev-libs/caffe/caffe-1.0.recipe
Open you eyes, Nicholas!
https://www.youtube.com/watch?v=ALWllFyzLrg
=> Caffe: enable OpenCV

media-plugins/audacious-plugins/audacious_plugins-3.9.recipe, media-plugins/audacious-plugins/patches/audacious_plugins-3.9.patchset
You tricky hacker....
https://www.youtube.com/watch?v=LmE3IhHBGjI
=> Audacious plugins fix

sys-apps/findutils/findutils-4.6.0.recipe, sys-apps/findutils/patches/findutils-4.6.0.patchset
Not tested on x86_64 (yet) ...
=> findutils, bump version

dev-util/ninja/ninja-1.8.2.recipe, dev-util/ninja/patches/ninja-1.8.2.patchset
Imported the patches from previous version
=> ninja, bump version

haiku-apps/einsteinium/einsteinium-1.4.1.recipe
=> Adding recipe for Einsteinium v1.4.1

media-gfx/blender/blender-2.79.recipe, media-gfx/blender/patches/blender-2.79.patchset
=> Blender: bump version

games-puzzle/pingus/pingus-0.7.6.recipe
still some work in progress ...
=> pingus, new recipe

dev-lang/rust/rust-1.12.1.recipe
Question on the side: currently the recipes for rust are marked untested. What is the criterium to change them to tested?
=> rust: Add recipe for rust-1.12.1

app-misc/vifm/vifm-0.9.recipe
Pull request for Vifm recipe, a vi-like, cross-platform and command-line based file manager, using ncurses.
It is a wonderful complement for vi/VIm for users who enjoy such keybindings and who work a lot in the terminal.
=> Recipe for Vifm

dev-libs/libsmdev/libsmdev-20170225.recipe
=> libsmdev, new recipe

media-gfx/hqx/hqx-1.1.recipe, media-gfx/hqx/patches/hqx-1.1.patchset
fails to build with haikuporter
https://github.com/haikuports/haikuports/issues/1686
=> hqx, bump version

dev-libs/zziplib/patches/zziplib-0.13.67.patchset, dev-libs/zziplib/zziplib-0.13.67.recipe
=> zziplib, fix recipe

haiku-apps/einsteinium/einsteinium-1.4.1a.recipe
Fixes the Engine subscriber example make file.
=> New Einsteinium v1.4.1a recipe

media-video/ffmpeg/ffmpeg-3.4.recipe, media-video/ffmpeg/patches/ffmpeg-3.4.patchset
not tested on x86_64 yet, probably would be good if some people tested it before merge ...
=> ffmpeg, bump version

app-doc/zeal/patches/zeal-0.4.0.patchset, app-doc/zeal/zeal-0.4.0.recipe
Tested only on x86_64 and downloadable documentation correctly loads in Haiku.
=> zeal: bump version

haiku-apps/burnitnow/burnitnow-1.1.recipe, haiku-apps/burnitnow/patches/burnitnow-1.1.patchset
Fix #1737 until a new BurnItNow release including its own fix is available...
=> burnitnow: fix crash at launch on x86_64

sci-libs/openblas/openblas-0.2.20.recipe, sci-libs/openblas/patches/openblas-0.2.20.patchset
=> OpenBLAS: bump version

sys-auth/pam_yubico/pam_yubico-2.24.recipe
http://vmpkg.haiku-os.org/master/x86_64/logviewer.html?buildruns/382/builds/2531.log
=> PAM_yubico : build fix

dev-vcs/git/git-2.15.0.recipe, dev-vcs/git/patches/git-2.15.0.patchset
=> Git: version bump

app-arch/lizard/lizard-1.0.recipe
Needs to be tested on gcc2. @Begasus ?
=> Lizard: recipe cleanup and fix

media-libs/glew/glew-2.1.0.recipe, media-libs/glew/patches/glew-2.1.0.patchset
@korli: does it looks good to you, or should i make a "glew2" recipe? A lib is missing from the new version.
=> GLEW: bump version, recipe cleanup

media-sound/auralillusion/auralillusion-4.0.recipe, media-sound/auralillusion/licenses/AuralIllusion
Added a recipe for AuralIllusion from HaikuArchives.
=> Add AuralIllusion 4.0 recipe

mail-client/scooby/scooby-0.9.9.recipe
Added [Scooby](https://github.com/HaikuArchives/Scooby), an open source full featured BeOS native e-mail client.
=> Scooby: new recipe

dev-lang/openjdk/openjdk-1.7.u80_b32.recipe, media-sound/jack2/jack2-1.9.8.recipe, sys-libs/mesa/mesa-10.1.1.recipe
Fix some issues with the SUMMARY in some ports
=> Add some SUMMARY's to ports

media-gfx/apngopt/apngopt-1.4.recipe
Recipe for apngopt, a small utility which optimizes existing APNG animation files. Not tested yet on x86_64 since my computer cannot support it.
=> apngopt: new recipe

haiku-apps/bescreencapture/bescreencapture-2.3.1.recipe
Sorry for the noise.
I had to release a new version shortly after 2.3 to fix a small bug:
Preview wasn't updated on application start.
=> Add recipe for BeScreenCapture 2.3.1

media-libs/libfdk_aac/libfdk_aac-0.1.5.recipe, media-libs/libfdk_aac/licenses/Fraunhofer FDK AAC Codec
=> media-libs/libfdk_aac: add port

haiku-games/bespider/bespider-0.1.1.recipe
This version, as opposed to the previous one, compiles on x86_64.
=> Add a recipe for the new version of BeSpider

sci-mathematics/gimps/gimps-29.4b5.recipe, sci-mathematics/gimps/licenses/GIMPS, sys-libs/hwloc/hwloc-1.11.8.recipe, sys-libs/hwloc/patches/hwloc-1.11.8.patchset
Builds, but running the resulting progran (mprime) causes a Floating point exception for me.
Also includes hwloc as a dependency of mprime.
This pull request is made as part of Google Code-In 2017
=> [GCI2017] gimps, hwloc: new recipe

app-text/wordgrinder/wordgrinder-0.7.1.recipe
This recipe (probably, but unlikely) should work, although there's some error with the source.
* Line 101: https://github.com/davidgiven/wordgrinder/blob/master/Makefile#L101
* Error: `ninja: unknown target 'all', did you mean 'dev'?`
Some help would greatly be appreciated.
=> Recipe for WordGrinder (with lua issues not yet fixed)

haiku-apps/beshare/beshare-2.32.recipe
Still crashes for me when trying to connect to the server Tycom ...
=> beshare, fix build

app-arch/brotli/brotli-1.0.2.recipe
Aside from the fact that the recipe looks ugly, it's working for all architecture, including secondary
=> app-arch/brotli: add port

games-arcade/roadfighter/patches/roadfighter-1.0.1269.patchset, games-arcade/roadfighter/roadfighter-1.0.1269.recipe
=> roadfighter: change settings directory to B_USER_SETTINGS_DIRECTORY

haiku-apps/photograbber/photograbber-2.3.3.recipe
=> Photograbber: x86_64 is a supported architecture

haiku-apps/toner/toner-1.0.0.recipe
I will update COMMIT and CHECKSUM_SHA256 once [the other PR](https://github.com/HaikuArchives/Toner/pull/1) is merged.
=> Toner: create recipe

sci-libs/lapack/lapack-3.8.0.recipe
=> Lapack: fix pkgconfig files

dev-python/funcsigs/funcsigs-1.0.2.recipe, dev-python/pluggy/pluggy-0.6.0.recipe, dev-python/py/py-1.5.2.recipe, dev-python/pytest/pytest-3.3.0.recipe
A Python testing framework and its dependencies.
=> Pytest: new recipe

media-gfx/nomacs/nomacs-3.8.0.recipe
=> Nomacs build fix

haiku-apps/archiver/archiver-1.0.0.recipe
=> Archiver: create recipe

dev-libs/bcunit/bcunit-3.0.2.recipe, dev-libs/bcunit/patches/bcunit-3.0.2.patchset
Changes to BCUnit:
- Fix tests
=> dev-libs/bcunit: new recipe

app-crypt/mhash/mhash-0.9.9.9.recipe, app-crypt/mhash/mhash.OptionalPackageDescription
Creates recipe for mhash, a library that provides a uniform interface to several hash algorithms.
=> mhash: new recipe

haiku-apps/fakbetur/fakbetur-1.0.0.recipe
=> FakBEtur: create recipe

dev-libs/libmcrypt/libmcrypt-2.5.8.recipe, dev-libs/libmcrypt/libmcrypt.OptionalPackageDescription
Create recipe for libmcrypt, a replacements for the old Unix crypt.
=> libmcrypt: new recipe

app-crypt/steghide/patches/steghide-0.5.1.patchset, app-crypt/steghide/steghide-0.5.1.recipe
Creates recipe for [steghide](http://steghide.sourceforge.net/), a steganography program that is able to hide data in various kinds of image and audio files.
=> steghide: new recipe

x11-proto/glproto/glproto-1.4.17.recipe
=> glproto, new recipe

sys-libs/mesa/mesa-17.1.7.recipe
Maybe it should get an own subpackage.
Not tested. Built just fine on x86_64.
=> MESA: enable OSMesa

dev-vcs/git/git-2.15.1.recipe, dev-vcs/git/patches/git-2.15.1.patchset
=> [GCI 2017] git: fix config location

haiku-apps/beaccessible/beaccessible-1.0.0.recipe
=> BeAccessible: create recipe

app-crypt/p11-kit/p11_kit-0.23.9.recipe, app-crypt/p11-kit/patches/p11_kit-0.23.9.patchset
Current status:
- builds are successful
- all commands segfault
=> p11-kit: new recipe [GCI 2017]

media-gfx/blender/blender-2.79.recipe, media-gfx/blender/patches/blender-2.79.patchset
I'm on my way to get the official-release feature-set supported.
Still some road-blocks here and there.
=> Blender : enable some features, cleanup

haiku-apps/qscope/qscope-2.0.recipe
Will update it after this [PR](https://github.com/HaikuArchives/QScope/pull/2) is merged.
=> QScope: create recipe

haiku-apps/benormal/benormal-1.0.recipe
=> BeNormal: creat recipe

app-arch/unshield/patches/unshield-1.4.2.patchset, app-arch/unshield/unshield-1.4.2.recipe
=> app-arch/unshield: new recipe

dev-python/asciinema/python3_asciinema-1.4.0.recipe
Currently broken:
> ❯ asciinema rec                                               ✘ 1 
> /packages/python3_asciinema-1.4.0-1/cmd~python3/bin/python3: can't find '__main__' module in 'asciinema'
=> asciinema : new recipe

media-libs/libpgf/libpgf-7.15.32.recipe, media-libs/libpgf/patches/libpgf-7.15.32.patchset
Done as part of GCI
Changes to libpgf:
- Add Haiku support
=> media-libs/libpgf: new recipe

haiku-apps/voxophone/patches/voxophone-1.0.patchset, haiku-apps/voxophone/voxophone-1.0.recipe
Finally back to recipes 😉 
* Tested on x86_gcc2, and works 🎊 
* Not tested on x86_64 yet... since I don't have it available.
=> Voxophone [recipe] [GCI]

sys-devel/gcc/gcc-5.4.0_2016_06_04.recipe
Closes : https://dev.haiku-os.org/ticket/12791
Ruby configure works with it. No better idea how to test it however.
=> GCC: enable libssp for stack protector

haiku-apps/bshisen/bshisen-1.2.recipe
**This recipe is untested...**
Some information is probably not correct. This will be fixed later.
But anyone is welcome to make/give reviews 😄 
I'll test and fix this recipe once I get home.
=> BShisen [recipe]

media-fonts/ibm_plex/ibm_plex-0.5.3.recipe, www-client/bezilla/bezilla-2.0.0.22.recipe
adding recipe for the IBM Plex font
=> adding recipe for the IBM Plex font

dev-libs/libslz/libslz-1.1.0.recipe, dev-libs/libslz/patches/libslz-1.1.0.patchset
Changes to libslz:
- zenc: Fix build on Haiku
=> dev-libs/libslz: new recipe

media-sound/milkytracker/milkytracker-1.01.00.recipe, media-sound/milkytracker/patches/milkytracker-1.01.00-gcc4.patchset, media-sound/milkytracker/patches/milkytracker-1.01.00.patchset
No idea what happend with the "r4"s.
=> Milkytracker version bump

haiku-apps/memochip/memochip-1.3~git.recipe
- License is `unknown` because i haven't found any license for this
- The package build fine with a placeholder license
- The app opened up but doesn't seems to be functioning
=> MemoChip: Initial recipe

haiku-apps/brie/brie-0.4.recipe
Create recipe for [Brie](https://github.com/HaikuArchives/Brie), an IDE for rapid development of apps. Builds well in x86_64.
=> brie: new recipe

haiku-apps/bdirectconnect/bdirectconnect-0.5.0~git.recipe, haiku-apps/bedc/bedc-0.5.0~git.recipe
=> BeDC: New recipe

haiku-apps/conway/conway-0.9.recipe
Tested on _gcc2 and _64. 
* x86_gcc2 👍 
* x86_64     👎  (I guess I'll mark this arch as broken)
Also, does anyone know how to get rid of the `modification time [x] seconds in the future` warning, without having to use that crazy looking `find` command in BUILD?
=> Conway [recipe]

haiku-games/lightsoff/lightsoff-1.0.recipe
Will update this recipe to reflect the latest upstream commit once this [PR](https://github.com/HaikuArchives/LightsOff/pull/1) is merged.
=> LightsOff: create recipe

media-sound/mp3gain/mp3gain-1.5.2.r2.recipe, media-sound/mp3gain/mp3gain-1.5.2.recipe
~~I need suggestion for `$portVersion`. Not sure if it's ok~~
=> mp3gain: Add recipe

dev-libs/softhsm/patches/softhsm-2.3.0.patchset, dev-libs/softhsm/softhsm-2.3.0.recipe, dev-libs/softhsm/softhsm2-2.3.0.recipe
=> softhsm: new recipe

media-libs/libdiscid/libdiscid-0.6.2.recipe, media-libs/libdiscid/patches/libdiscid-0.6.2.patchset
=> libdiscid: fix recipe

net-misc/gsasl/gsasl-1.8.0.recipe, net-misc/gsasl/patches/gsasl-1.8.0.patchset
=> gsasl: new recipe

mail-client/mailnews/mailnews-2.0.0.25.recipe, mail-client/mailnews/patches/mailnews-2.0.0.25.patchset
Doesn't build yet. I'm not good at this... if anyone wants to continue.
Building fails with:
configure: error: Library requirements (libIDL-2.0 >= 0.8.0) not met;
consider adjusting the PKG_CONFIG_PATH environment variable if your
libraries are in a nonstandard prefix so pkg-config can find them.
FYI, libidl-0.8.14.recipe declares:
PROVIDES_devel="
libidl${secondaryArchSuffix}_devel = $portVersion
cmd:libIDL_config_2$secondaryArchSuffix = $portVersion
devel:libIDL_2$secondaryArchSuffix = 0.0.0 compat >= 0
"
=> Bringing MailNews closer to build

app-shells/bash_completion/bash_completion-2.7.recipe, app-shells/bash_completion/patches/bash_completion-2.7.patchset
=> bash_completion : bump

sys-libs/libedit/libedit-20170329_3.1.recipe, sys-libs/libedit/patches/libedit-20170329-3.1.patchset
Also add a tiny gcc2 patch and drop docs on secondary arch.
Remark: `--enable-widec` is now enabled by default in configure.
=> libedit: bump to 20170329-3.1, add debuginfo package.

media-libs/sdl_rtf/sdl_rtf-0.1.0.recipe
Builds ok for gcc5, didn't test on x86_64 ...
=> sdl-rtf, revive old bep file

app-shells/direnv/direnv-2.14.0.recipe, app-shells/direnv/patches/direnv-2.14.0.patchset
Tested on x86_64 and works as expected.
=> direnv: new recipe [GCI 2017]

media-libs/libbluray/libbluray-1.0.2.recipe, media-libs/libbluray/patches/libbluray-1.0.2.patchset
Also define commandBinDir for cmd:bd_info.
=> libbluray: bump to 1.0.2, add debuginfo.

games-emulation/fbalpha_libretro/fbalpha_libretro-0.2.97.42.20180226git.recipe, games-emulation/fbalpha_libretro/fbalpha_libretro-0.2.97.42_20180306.recipe
Updated libdir with addonsdir and added documentation
Replaced supplements with requires
=> fbalpha_libretro: various fixes

dev-libs/libconfig/libconfig-1.7.2.recipe
Also move $libDir/cmake to the devel package.
=> libconfig: bump to 1.7.2, add debuginfo & SOURCE_FILENAME.

dev-libs/libmaxminddb/libmaxminddb-1.3.2.recipe
Also add `cmd:pkg_config` and call autoreconf.
=> libmaxminddb: bump to 1.3.2, add debuginfo.

dev-libs/libpcre/libpcre-8.42.recipe
Also update `SOURCE_URI` because SF does not have the tarball yet.
=> libpcre: bump to 8.42, add debuginfo.

dev-libs/gtest/gtest-1.9.0~git.recipe, dev-libs/gtest/patches/gtest-1.9.0~git.patchset
Patch based on their own upstream patch ... https://github.com/google/googletest/pull/1160
=> googletest, fix recipe for secondaryArchSuffix

media-libs/libgphoto2/libgphoto2-2.5.17.recipe
Also move `$manDir/man3` & `$binDir/gphoto2{,-port}-config` to devel.
=> libgphoto2: bump to 2.5.17, add debuginfo, add libexif.

dev-libs/udis86/udis86-1.7.2.recipe
=> UDIS86: enable for x86_64

games-emulation/retroarch/retroarch-1.7.2.recipe
=> Retroarch: bump to 1.7.2

net-libs/libs3/libs3-2.0.recipe
not tested on x86_64 (yet) :) seems to be ok for x86
=> libs3, revive old bep file

net-misc/aria2/aria2-1.34.0.recipe, net-misc/aria2/patches/aria2-1.34.0.patchset
Also update `HOMEPAGE` & `SOURCE_URI`.
=> aria2: bump to 1.34.0, fix TEST(), add TEST_REQUIRES.

media-libs/gd/gd-2.2.5.recipe
Also fix `REQUIRES_devel` & `BUILD_REQUIRES`: `s/libpng/libpng16/`
=> gd: build with libvpx.so.5 (from libvpx-1.7.x)

media-libs/libwebp/libwebp-1.0.0.recipe
=> libwebp, bump version

media-libs/libvpx/libvpx-1.7.0.recipe
to add `develop/headers/vpx/svc_context.h` to the devel package.
=> libvpx: pass CONFIG_SPATIAL_SVC=yes, configure with --enable-vp9

sys-block/parted/parted-3.2.recipe
* Also build with `libblkid`, also from `util-linux`.
* Pass `-Wimplicit-fallthrough=0` to make `gcc >= 7` happy.
=> parted: select the libuuid from util-linux.

app-admin/testdisk/testdisk-7.1~git.recipe
Also update to the latest snapshot.
=> testdisk: select the libuuid from util-linux.

dev-libs/ixion/ixion-0.13.0.recipe
Also, set `LIBRARY_PATH` to a nice value in `TEST`. (All tests pass :)
=> ixion: update after #2666 which changed mdds.

net-libs/libwebsockets/libwebsockets-3.0.0.recipe
Well, simply, here's a recipe for libwebsockets.
=> Initial recipe for libwebsockets 3.0.0

haiku-apps/superprefs/superprefs-1.0.recipe
Added the URL to SuperPref's GitHub page, updated some phrasing, removed an extra space.
=> SuperPrefs: Fixed phrasing, added URL, and removed extra space

sys-process/cronie/cronie-1.5.2.recipe
Checked with libpam enabled (for x86_gcc2), didn't really make a difference? ...
=> cronie, bump version

dev-util/cppcheck/cppcheck-1.84.recipe, dev-util/cppcheck/patches/cppcheck-1.84.patchset
Builds ok, test run fine for x86(secondaryArchSuffix) ...
=> cppcheck, bump version

dev-util/ccache/ccache-3.4.2.recipe, dev-util/ccache/patches/ccache-3.4.2.patchset
Test still fails (checked previous version that also fails the check), this one gets a lot further ;)
=> ccache, bump version

media-libs/libaubio/libaubio-0.4.6.recipe
marked x86_gcc2 as broken, no libresample and parse errors in the build, x86 (secondaryarch) builds ok ...
=> libaubio, bump version

games-roguelike/angband/angband-4.1.2.recipe, games-roguelike/angband/patches/angband-4.1.2.patchset
Builds ok on x86 (secondaryArch), not tested (yet) on x86_x64, fix for gcc2 would be minor (mostly parse errors) ...
=> angband, bump version

app-text/aiksaurus/aiksaurus-1.2.2~git.recipe, app-text/aiksaurus/patches/aiksaurus-1.2.2~git.patchset
This is the latest git checkout ...
=> aiksaurus, bump version

games-sports/ballsmacker/ballsmacker-1.0.0.recipe
Solves issue https://github.com/haikuports/haikuports/issues/438
=> ballsmacker, new recipe

dev-libs/wolfssl/wolfssl-3.15.3.recipe
1 test fails (testsuite.test), 4 test are ok
=> wolfssl, bump version

dev-lang/xa65/patches/xa65-2.3.8.patchset, dev-lang/xa65/xa65-2.3.8.recipe
Needed to checkout latest vice release ...
=> xa65, new recipe

dev-libs/popt/patches/popt-1.16.patchset, dev-libs/popt/popt-1.16.recipe
The test still fails, could use some looking into ...
=> popt, fix build

media-libs/libepoxy/libepoxy-1.5.1.recipe
Infected by this update ... https://github.com/haikuports/haikuports/blob/bb0cc2b8eb1525b612507fca88db472248dd5748/app-office/libreoffice/libreoffice-6.2.0.0%7Egit.recipe
=> libepoxy, bump version after changes to util-macros

sci-libs/fftw/fftw-3.3.8.recipe, sci-libs/fftw/patches/fftw-3.3.8.patchset
Soname still the same, all test passes.
=> FFTW: bump, enable fortran, debuginfo, cleanup

sci-libs/arpack/arpack-3.6.2.recipe
Soname still the same, all test passes.
=> Arpack: bump, test fix

sci-libs/armadillo/armadillo-8.600.0.recipe
=> Armadillo: bump

sys-apps/man-pages-posix/licenses/POSIX, sys-apps/man-pages-posix/man_pages_posix-2013.a.recipe
Bringing more man pages to Haiku :) These manual pages will greatly aid developers working on Haiku.
Recipe may need some styling adjustment however. And may be check my grammar as well :P
=> sys-apps/man-pages-posix: add version 2013.a

dev-util/cram/cram-0.7.recipe, sys-apps/the_silver_searcher/the_silver_searcher-2.2.0.recipe
All test passes, but https://github.com/ggreer/the_silver_searcher/issues/1236 and https://github.com/ggreer/the_silver_searcher/issues/1235 still there.
=> Silver Searcher: bump, add cram

sys-cluster/openmpi/openmpi-3.1.1.recipe, sys-cluster/openmpi/patches/openmpi-3.1.1.patchset
Tests built fine and passed all tests outside of HP, not inside.
BTW: this is an important milestone on the road to make Haiku HPC capable.
=> Open-MPI: new recipe

sci-libs/gdal/gdal-2.3.1.recipe
Soname still the same.
Datafiles moved to subdir.
=> GDAL: bump, cleanup

dev-util/cppcheck/cppcheck-1.84.recipe, dev-util/cppcheck/patches/cppcheck-1.84.patchset
closes: https://github.com/haikuports/haikuports/issues/2914
=> cppcheck: Fix config dir

media-libs/opensubdiv/opensubdiv-3.3.2.recipe, media-libs/opensubdiv/opensubdiv-3.3.3.recipe
Needs review, i'm not sure if it is the right way and if it secondary-arch friendly.
Closes https://github.com/haikuports/haikuports/issues/2920
=> OpenSubDiv: Build fix

media-libs/libvorbis/libvorbis-1.3.6.recipe
=> media-libs/libvorbis: cleanup, fix build

media-libs/liblo/liblo-0.29.recipe
=> media-libs/liblo: fix build, update source uri

sys-apps/texinfo/texinfo4-4.13a.recipe
Tag #2933 
~~Note: untested on gcc2~~
=> sys-apps/texinfo4: fix build

dev-python/requests/requests-2.19.1.recipe
Now depends on ca_root_certificates
=> dev-python/requests: update to 2.18.4

sci-libs/lapack/lapack-3.8.0.recipe
At least one test fails on my machine.
Closes #3016
=> LAPACK: Fix packaging on x86, enable tests, cleanup, debuginfo

media-gfx/tuxpaint-stamps/tuxpaint_stamps-2018.09.01.recipe
This is quite a large archive :)
=> tuxpaint-stamps, new recipe, collection of stamps to be used with TuxPaint

games-emulation/atari++/atari++-1.81.recipe, games-emulation/atari++/licenses/TPL, games-emulation/atari++/patches/atari++-1.81.patchset
Builds ok, sdl version starts up but I can't seem to use the mouse in there, ncurses version starts up ok ...
=> atari++, bump version

dev-libs/librevenge/librevenge-0.0.4.recipe, dev-libs/librevenge/patches/librevenge-0.0.4.patchset
Added libVersion(Compat) and defineDebugInfoPackage
=> librevenge, fix recipe

app-arch/zstd/patches/zstd-1.3.5-gcc2.patchset, app-arch/zstd/patches/zstd-1.3.5.patchset, app-arch/zstd/zstd-1.3.5.recipe
Added liblzma, libz and libz4 for _x86 (no liblzma for gcc2), test fails for x86_gcc2, is ok for _x86 ...
=> zstd, bump version

app-arch/gzip/gzip-1.9.recipe, app-arch/gzip/patches/gzip-1.9.patchset
* remove autoreconf
* add TEST_REQUIRES.
=> gzip: add recipe for version 1.9.

sys-apps/dtc/dtc-1.4.7.recipe, sys-apps/dtc/patches/dtc-1.4.7.patchset
=> dtc: bump version.

games-puzzle/neverball/neverball-1.6.0.recipe, media-gfx/yacreader/yacreader-9.0.0.recipe, media-sound/skympc/skympc-1.6.4.recipe, net-p2p/transmission/transmission-2.94.recipe
Also hide x86 secondary arch on x86_64 because the recipe does not provide any library.
=> Change the style of ADDITIONAL_FILES in 4 recipes.

games-engines/instead/instead-3.2.2.recipe, games-engines/instead/patches/instead-3.2.2.patchset
=> instead: use find_directory() to look for user data #3185

haiku-misc/quicktour/additional-files/quicktour-link-on-desktop.sh, haiku-misc/quicktour/quicktour-0.2.recipe
"A quick tour of Haiku, aimed at new users"
=> New recipe: quicktour v0.2

dev-libs/smooth/smooth-0.8.74.0~pre4.recipe
The smooth class library is the system and UI library used by fre:ac.
=> smooth: New recipe for smooth 0.8.74.0-pre4.

media-libs/boca/boca-1.0~alpha20180913.recipe
BoCA is the audio component framework used by fre:ac.
=> BoCA: New recipe for BoCA 1.1 alpha.

dev-games/simgear/patches/simgear-2018.2.2.patchset, dev-games/simgear/simgear-2018.2.2.recipe
SimGear, i.e. Simulator Construction Gear, is a set of open-source libraries used by a variety of software projects including 3d realtime simulations, visualization software, and games.
Version: 2018.2.2
Tested on Haiku R1B1 x86 w/ GCC7
Required for: FlightGear 2018.2.2
Project: FlightGear Flight Simulator
URL: http://home.flightgear.org/
Ref: #3187
NOTE: Successfully compiled on Haiku R1B1 x86_64.
Tag: Test and review
=> Simgear: updated PR

games-arcade/rocksndiamonds/rocksndiamonds-4.1.1.0.recipe
Issue for the save files still remaining
=> rocksndiamonds, bump version

dev-python/html5-parser/html5_parser-0.4.5.recipe
=> html5-parser: new recipe

haiku-apps/vncserver/patches/vncserver-1.30.patchset, haiku-apps/vncserver/vncserver-1.30.recipe
=> vncserver: bump version to 1.30

haiku-apps/paladin/paladin-2.0.recipe
=> Added Paladin 2.0 release and tested

media-sound/mac/additional-files/Makefile, media-sound/mac/licenses/Monkey's Audio SDK and Source Code License Agreement, media-sound/mac/mac-4.38.recipe, media-sound/mac/patches/mac-4.38.patchset
Here's a new recipe for Monkey's Audio. Tested and found working on x86 and x86_64.
=> New recipe: Monkey's Audio 4.38

haiku-misc/space/space-1.2.recipe
This is a recipe for Space, a screensaver.
The `srcGitRev` and the checksum must be updated, though, because Space is waiting on a PR to be merged: https://github.com/HaikuArchives/Space/pull/2
=> Space: new recipe

haiku-apps/heidi/heidi-1.0.recipe
@waddlesplash I feel like I'm missing some crucial things from the description, and I'm not sure of Heidi's portVersion. It would be nice if you could help a little bit :)
=> Heidi [recipe]

haiku-apps/zookeeper/zookeeper-1.0.recipe, haiku-apps/zookeeper/zookeeper-2.1.1.recipe
Just an unrelated question:
does PE have an option to show whitespace as dots or something? I'm struggling with whitespace :(
=> ZooKeeper [recipe]

media-libs/sdl2_gfx/sdl2_gfx-1.0.4.recipe
Fixes also the broken link in developLibDir, added libVersion and defineDebugInfoPackage
=> sdl2_gfx, add secondary architecture

haiku-apps/animator/animator-1.0.recipe, haiku-apps/animator/patches/animator-1.0.patchset
@Begasus @alaviss
Builds on x86_64.
An upstream PR was created... will update recipe once the PR is merged :)
Link to upstream PR: https://github.com/HaikuArchives/Animator/pull/2
=> Animator [recipe] [no license]

haiku-misc/haiku-on/haiku-on-1.0.recipe, haiku-misc/haiku-on/haiku_on_x86-1.0.recipe
This is the recipe for Haiku-On.
Now I am marking this recipe as untested because there is no way to build actual source code (requires openjdk which is still marked as untested according to Haikuports).
Otherwise, here is the recipe with all the details required.
GCI student = arnavbhatt288
=> Recipe for Haiku-On.

media-libs/assimp/assimp-4.1.0.recipe
=> Assimp: bump

dev-games/godot/patches/godot-3.0.6.patchset
Fixes build on x86_64. Still not working hovewer.
=> OpenSSL required

dev-games/godot/godot-3.0.6.recipe, dev-games/godot/patches/godot-3.0.6.patchset
pkg-config is pkg-config_x86 on x86, lets use a platform-dependant variable for it.
=> Godot: Preliminary x86 support

media-libs/libopusenc/libopusenc-0.2.recipe
New recipe for libopusenc which is required by opus-tools 0.2.
=> libopusenc: new recipe

haiku-apps/sidplayer/sidplayer-4.4.recipe
Recipe for SIDPlayer. Keep in mind that it doesn't uses any makefile (even BeOS makefile after updating it didn't work) so I have to use configure to make new makefile for it.
GCI Student: arnavbhatt288
=> Recipe for SIDPlayer.

media-libs/tremor/patches/tremor-1.0.0~git.patchset, media-libs/tremor/tremor-1.0.0~git.recipe
I know it's an old one, but wanted to check this out for another issue that was calling for this library ...
=> tremor, add new recipe for vorbisidec package

dev-db/sqlite/sqlite-3.26.0.0.recipe
=> SqLite: version bump

haiku-apps/keymapswitcher/keymapswitcher-1.2.7.11.recipe
Add Opt+Space keyboard shortcut to switch layout
=> KeymapSwitcher: Bump git revision

media-libs/libshout/libshout-2.4.1.recipe, media-libs/libshout/patches/libshout-2.4.1-gcc2.patchset, media-libs/libshout/patches/libshout-2.4.1.patchset
Checked a clean build for mpd_x86 with libshout enabled, that worked, could use some testing to make sure :)
=> libshout, add extra options

sci-libs/openblas/openblas-0.3.4.recipe
https://github.com/xianyi/OpenBLAS/issues/1916
=> Openblas: disable AVX and AVX512

dev-libs/boost/boost169-1.69.0.recipe, dev-libs/boost/patches/boost-1.69.0.patchset
Test fails as it can't find python. No idea, how to disable it.
Tested, built, packages on x86_64.
=> Boost: bump

media-libs/openal/openal-1.19.1.recipe, media-libs/openal/patches/openal-1.19.1.patchset
Patch adjusted according  to the oss version.
Tested on x86_64, builds, packages. No functionality test, yet.
=> OpenAL: bump

dev-libs/vc/vc-1.4.0.recipe, dev-libs/vc/vc-1.4.1.recipe
=> VC: new recipe

app-dicts/aspell_en/aspell_en-2018.04.16~0.recipe
Not sure how this is used internally so maybe some checks should be used before merging?
=> aspell_en, bump version

media-video/ffmpeg/ffmpeg-4.1.recipe, media-video/ffmpeg/patches/ffmpeg-4.1.patchset
=> FFMPEG: recipe for 4.1

app-misc/peaclock/peaclock-0.1.3.recipe
I'm not sure if I got everything related to the secondary architecture correctly; how are you supposed to build it with HaikuPorter? Also, should we use British or American spellings (or just use the one that the package does) for the `SUMMARY` and `DESCRIPTION`?
=> peaclock: new recipe

games-emulation/retroarch/additional-files/retroarch.rdef.in, games-emulation/retroarch/retroarch-1.7.5.recipe
Trying to close #3419 
I followed the example found in otter-browser
Open for improvement / criticism
Thanks!
=> retroarch - first attempt to add rdef definitions

haiku-data/generaluser_gs/generaluser_gs-1.471.recipe, haiku-data/generaluser_gs/licenses/GeneralUser GS License v2.0
This is - like the TimGS soundfont - in haiku-data. Shouldn't soundfonts go better into media-sounds?
=> New recipe for GeneralUser DS soundfont

dev-libs/nlohmann_json/nlohmann_json-3.4.0.recipe
Add a recipe for https://github.com/nlohmann/json
=> nlohmann_json : new recipe

games-roguelike/scourge_data/scourge_data-0.21.1.recipe
=> scourge_data, add data files for scourge

app-text/aobook/aobook-1.0.3_4.recipe
=> aobook: build with a single job

media-fonts/firacode/firacode-1.206.recipe
=> firacode: bump version

media-fonts/fira_fonts/fira_fonts-4.202.recipe
=> fira_fonts: bump version

sys-devel/distcc/patches/distcc-3.2~rc1.patchset
=> distcc: fix for x86_gcc2

dev-games/flatzebra/flatzebra-0.1.6.recipe
=> flatzebra: fix source uri

app-shells/zsh/patches/zsh-5.7.1.patchset
Closes https://github.com/haikuports/haikuports/issues/3634
=> ZSH: C89 patches from hanya

dev-lang/elixir/elixir-1.4.2.recipe
Elixir is a functional programming language built on top of the Erlang VM and is used for building scalable applications. 
Elixir fails to build from source due to a segfault in the Erlang VM. Until this is patched, the pre-compiled version was tested instead and so far works perfectly on x86_64.
=> elixir: new recipe

games-action/abuse/abuse-0.8.recipe, games-action/abuse/patches/abuse-0.8.patchset
2D side-scrolling platform game
=> abuse: new recipe

games-arcade/rocksndiamonds/patches/rocksndiamonds-4.1.2.0.patchset, games-arcade/rocksndiamonds/rocksndiamonds-4.1.2.0.recipe
SDL 1.2 isn't supported anymore
=> RocksnDiamonds, bump version, switch to SDL2

sci-libs/armadillo/armadillo9-9.300.2.recipe
=> armadillo9, bump version

dev-libs/apr/apr-1.6.5.recipe
Needs testing, builds ok for _x86 (tests ran ok untill the system froze up here)
=> apr, bump version

media-gfx/drawpile/drawpile-2.1.6.recipe
https://github.com/drawpile/Drawpile/releases/tag/2.1.6
=> drawpile, bump to 2.1.6

sys-devel/bmake/bmake-20181221.recipe
=> bmake, fix recipe

media-libs/openjpeg/openjpeg-2.3.1.recipe
=> OpenJPEG: bump, tests

app-text/podofo/patches/podofo-0.9.6.patchset, app-text/podofo/podofo-0.9.6.recipe
Fixes https://github.com/haikuports/haikuports/issues/3609
=> Podofo: bump, debuginfo

app-emulation/euae/euae-0.8.29~wip4.recipe
Commodore [Amiga 4000](https://en.wikipedia.org/wiki/Amiga_4000) emulator.
- AmigaOS 3.1.4
Closes #3762
=> e-uae: Remove sdl-gl from Haiku build

net-im/psi_plus/psi_plus-1.4.672.recipe
+ update build script after changes in upstream.
=> psi_plus: bump version to 1.4.672

dev-lang/janet/janet-0.5.0.recipe, dev-lang/janet/patches/janet-0.5.0.patch
The patch has already been merged into upstream.
=> janet: new recipe

dev-lang/rust/patches/rust_x86-1.33.0.patchset, dev-lang/rust/rust-1.33.0.recipe, dev-lang/rust_bin/rust_bin-1.33.0.recipe
This recipe follows the structure of previous packages.
=> Rust: add recipe for 1.33.0

dev-lang/rust/patches/rust_x86-1.35.0.patchset, dev-lang/rust/rust-1.35.0.recipe, dev-lang/rust_bin/rust_bin-1.35.0.recipe
This is the last one in a series, now we are up to date with the official releases.
=> Rust: add recipe for 1.35.0

dev-games/cegui/cegui-0.8.7.recipe
WIP at this time, the uncommented libraries are not found or causing errors, aside from that it build ok :)
=> cegui, new recipe

app-emulation/cap32_libretro/cap32_libretro-4.2.0_20190529.recipe
=> cap32_libretro: bump to latest git + documentation fix

games-rpg/devilutionx/devilutionx-0.4.0.recipe
Built and ran fine on x86_64 nightly VM.
=> devilutionx: Bump to version 0.4.0

dev-python/mutagen/mutagen-1.42.0.recipe
This adds a recipe for python-mutagen.
Adding as a requirement for MusicBrainz Picard, for which I'll submit a recipe later.
=> mutagen: add recipe for version 1.42.0

media-sound/picard/patches/picard-2.1.3.patchset, media-sound/picard/picard-2.1.3.recipe
As suggested in https://discuss.haiku-os.org/t/musicbrainz-picard-for-haiku/8759
=> picard: add patch to use Haiku Qt style

haiku-apps/takenotes/takenotes-1.0.1~git.recipe
Tested only on x86_64, seems to be working.
=> TakeNotes: bump to latest git

games-arcade/goonies/goonies-1.4.1528.recipe, games-arcade/goonies/patches/goonies-1.4.1528.patchset
Checked and builds ok for _x86 and x86_64, in fullscreen it's looking correctly, in windowed mode the menu isn't looking right ...
=> goonies, fix references to libSDL*, fix build

haiku-apps/drive_encryption/drive_encryption-1.0.recipe
Disabled build because it KDL'd after latest update when installed ...
=> drive_encryption, fix build

games-misc/nyancat/licenses/UIUC, games-misc/nyancat/nyancat-1.5.2.recipe
I tried adding NCSA for the license but HaikuPorter doesn't seem to support it.
But it does support UIUC, and I had to add a license file. Did I handle the licenses correctly?
=> nyancat [recipe]

media-gfx/flameshot/flameshot-0.6.0.recipe, media-gfx/flameshot/patches/flameshot-0.6.0.patchset
Fix crash when config menu selected:
`terminate called after throwing an instance of 'std::runtime_error'
what():  locale::facet::_S_create_c_locale name not valid
Abort
QObject::~QObject: Timers cannot be stopped from another thread`
=> flameshot: version bump

dev-util/kdevelop/kdevelop-5.4.1.recipe
=> Kdevelop 5.4.1

dev-libs/rapidjson/patches/rapidjson-1.1.0.patchset, dev-libs/rapidjson/rapidjson-1.1.0.recipe
No idea, why it is happening.
Fixes https://github.com/haikuports/haikuports/issues/4123
=> PRapidJSON: pkgconfig fix

dev-python/docutils/docutils-0.15.2.recipe
=> docutils: bump, pyversions

dev-python/setuptools/setuptools-41.2.0.recipe
Maybe this could create regressions with older ports.
=> Setuptools: bump

haiku-apps/wonderbrush/wonderbrush-2.1.2.recipe
Bump to latest.
Closes #4271
Closes https://github.com/stippi/WonderBrush-v2/issues/6
=> WonderBrush: bump to latest

dev-python/sip/sip-4.19.19.recipe
WAIT, this will break all pyqt based stuff.
Let me finish the pyqt recipes too.
=> SIP: bump, pyversion

dev-python/pyaes/pyaes-1.6.0.recipe
=> PyAES: new recipe

dev-python/pip/pip-19.2.3.recipe
Seems to be ok, but no idea what everything can go wrong with this update.
It still needs Ctrl-C to exit.
=> PIP: bump, pyversions

dev-python/pyqt/pyqt-5.13.1.recipe
Bump, switched to python 3.7
No PyQt for Python 3.6, one version should be enough.
This recipe depends on https://github.com/haikuports/haikuports/pull/4232
=> Pyqt 5.13.1

www-client/qutebrowser/qutebrowser-1.8.1.recipe
All deps already available, except https://github.com/haikuports/haikuports/pull/4233
=> Qutebrowser: bump for rebuild for Python3.7

sys-libs/mesa/mesa-17.1.10.recipe
The rasterization, fog, lighting, texturing, blending, and anti-aliasing processes operate on floating point values to allow graphic software applications to operate directly on the data in the frame buffer without losing any of the desired range and precision of the data.
=> mesa: enable floating point textures

games-emulation/4do_libretro/4do_libretro-1.3.2.4_20180219.recipe, games-engines/3dengine_libretro/3dengine_libretro-1.0_20171024.recipe, games-puzzle/2048_libretro/2048_libretro-1.0_20180219.recipe
I am currently in the process of building an automated update process for the 50+ libretro cores I maintain. In order to get this to work I need to harmonize versioning : these packages were created before we agreed on a versioning system. This slight update will allow me to include these packages in the automated system.
=> libretro: small updates to a handful of cores

sci-libs/scipy/python_scipy-1.2.0rc2.recipe
python3 version is broken, no idea, why.
=> SciPy: new recipe

dev-python/pandas/pandas-0.23.3.recipe, dev-python/pandas/pandas-0.23.4.recipe
This recipe takes forever to build :(
=> pandas [recipe]

app-office/texstudio/patches/texstudio-2.12.16.patchset, app-office/texstudio/texstudio-2.12.16.recipe
Worked ok for me on _x86, first draft was done by SirMik
=> TEXstudio, new recipe

games-strategy/wesnoth/wesnoth-1.12.6.recipe
Fixes build on x86_64
Closes #4350
=> wesnoth: Add x86_64 and fribidi dependency

app-office/texmaker/patches/texmaker-5.0.3.patchset, app-office/texmaker/texmaker-5.0.3.recipe
=> texmaker, new recipe

dev-cpp/websocketpp/patches/websocketpp-0.8.1.patchset, dev-cpp/websocketpp/websocketpp-0.8.1.recipe
Based on @projectgenesis his work in the PR https://github.com/haikuports/haikuports/pull/4158
=> websocketpp, new recipe

haiku-games/gloom3d/gloom3d-1.0.0.recipe
Working recipe for Gloom3D (I need license).
GCI student : arnavbhatt288
=> Recipe for Gloom3d (Need license)

dev-qt/qt5/qt5-5.13.2.recipe
double_conversion should be merged before this one
PR double_conversion: https://github.com/haikuports/haikuports/pull/4423
=> qt5, revbump after bump for double_conversion

app-emulation/nesalizer/nesalizer-1.0~git.recipe, app-emulation/nesalizer/patches/nesalizer-1.0~git.patchset
Here's a link to the upstream repository of nesalizer: https://github.com/ulfalizer/nesalizer
Relevant issue: #4439
=> Added recipe and patch for nesalizer

app-text/ghostscript_gpl/ghostscript_gpl-9.50.recipe, app-text/ghostscript_gpl/patches/ghostscript_gpl-9.50.patchset
Ghostscript is currently broken, this fixes it.
=> Ghostscript: bump, JBIG2DIC: fix

games-action/powermanga/patches/powermanga-0.93.1.patchset, games-action/powermanga/powermanga-0.93.1.recipe, games-action/powermanga/powermanga-0.94.0.recipe
My first recipe! Wow, that was quite something.
I have a question... The recipe makes a deskbar app list entry symlink when during installation, but when I clicked that entry nothing happens. When I navigated to the apps folder with terminal and ran it with ./powermanga, it worked perfectly. 
Apart from that, the recipe seems all good - but please help me test it!! :)
=> Added recipe for Powermanga

dev-util/gengetopt/gengetopt-2.23.recipe
Relevant issue: #4492
This recipe was made as part of my effort to port the libu2f-host package.
=> Added gengetopt recipe

app-crypt/libu2f_server/libu2f_server-1.1.0.recipe
Relevant pull requests: #4497 #4493
Link: https://developers.yubico.com/libu2f-server/
GitHub repository: https://github.com/Yubico/libu2f-server
=> Added libu2f_server recipe

games-action/dave_gnukem/dave_gnukem-1.0.recipe, games-action/dave_gnukem/licenses/CC-BY-3.0, games-action/dave_gnukem/patches/dave_gnukem-1.0.patchset
Fixes #4413 
Tested on x86_64.
I think I'm getting a grip on this haikuports recipe stuff now :))
=> Added recipe for Dave Gnukem

app-misc/nnn/nnn-2.8.1.recipe, app-misc/nnn/patches/nnn-2.8.1.patchset
Requested in #4083.
This is a backport recipe and patchset for v8.2.1 (The current released version).
The master branch includes a builtin support for Haiku which, of course, will be available in next releases.
=> Add nnn recipe

dev-python/dukpy/dukpy-0.3.recipe
=> Python dukpy lib

dev-games/flatzebra/flatzebra-0.1.6.recipe
=> flatzebra: cleaned up libSDL* dependencies

media-gfx/grafx2/grafx2-2.6.recipe
=> grafx2: cleaned up libSDL* dependencies

games-rpg/fheroes2/fheroes2-r3279.recipe
Reverts haikuports/haikuports#4569
=> Revert "fheroes2: disabled recipe"

app-arch/zopfli/zopfli-1.0.3.recipe
https://github.com/haikuports/haikuports/pull/4560
=> zopfli: move $prefix/include to $includeDir

dev-libs/pkcs11-helper/pkcs11_helper-1.25.1.recipe
This is a work-in-progress (WIP) that I came up with at 12:15 AM and includes a bunch of very weird-looking hacks, lacking a fair amount of details and there are some policy violations as well.
Needless to say, I'm aware that this recipe is currently not ready to be merged in its current state.
=> pkcs11_helper: added recipe

dev-util/sourcetrail/patches/sourcetrail-2019.4.102.patchset, dev-util/sourcetrail/sourcetrail-2019.4.102.recipe
=> recipe for sourcetrail

dev-python/pygame/python_pygame-1.9.4.recipe
Relevant issue: #3878 
This recipe has been tested on x86_64 prior to the creation of this pull request.
=> pygame: fix references to libSDL*

media-libs/mlt/mlt-6.18.0.recipe, media-libs/mlt/patches/mlt-6.18.0.patchset
=> recipe for mlt

app-misc/gcal/gcal-4.1.recipe
I've updated gcal from v3.6.3 to v4.1 (Latest)
Terminal running gcal v4.1:
=> Updated recipe for gcal to v4.1

dev-vcs/qgit/qgit-2.9.recipe
I've added the recipe for [QGit](https://github.com/tibirna/qgit).
I've packaged with haikuporter and tested the package on a clean installation of Haiku (in order to check the package's dependencies).
QGit works nicely without patches.
=> Added recipe for QGit

games-action/endless_sky/endless_sky-0.9.10.recipe, games-action/endless_sky/patches/endless_sky-0.9.10.patchset
Recipe builds fine using secondary architectures, and the game launches, however the game itself crashes on a nightly but runs fine on r1Beta1, don't really know why.
=> Add recipe for EndlessSky

net-p2p/eiskaltdcpp/eiskaltdcpp-2.3.0~git.recipe
Update program version + cosmetic changes in package description.
=> eiskaltdcpp: bump version

dev-python/msgpack/msgpack-0.6.2.recipe
=> MSGPACK: new recipe

sys-apps/fzy/fzy-1.0.recipe
[**fzy**](https://github.com/jhawthorn/fzy) - a simple, fast fuzzy finder for the terminal.
=> fzy: new recipe

sys-apps/fzy/fzy-1.0.recipe
Disable build on x86_gcc2, #4679.
=> fzy: fix architectures

games-rpg/devilutionx/devilutionx-1.0.0.recipe
=> DevilutionX: disable debug

media-fonts/jetbrains_mono/jetbrains_mono-1.0.3.recipe
=> jetbrains_mono, new font, based on the work of 0xtrzy

haiku-apps/scriptureguide/scriptureguide-0.9.1.recipe
I had to create a new release thats why the checjsun changed
=> fixed the build on x86_64 with a updated release

games-arcade/jumpnbump/jumpnbump-1.61.recipe
Some notes:
- I couldn't figure out what copyright statement to use, so I just put a generic one with the dates.
- I wasn't sure whether to package it with the menu or not, so I just decided not to because it's the default.
- ~Networking support doesn't seem to work, not even open a port, but I'm not sure if that's because I'm using it in a VM or something. Would be great if someone could test this on real hardware.~
EDIT: The commands I used didn't work on Linux, either. I guess I'm doing something wrong
EDIT 2: Okay, I tried a different set of commands it works perfectly.
=> jumpnbump: new recipe

games-strategy/dopewars/dopewars-1.5.12.recipe
Networking support only works on x86_gcc2. The UI looks kinda weird for some reason, but I'm not sure if that's just because of the terminal.
=> dopewars: new recipe

net-misc/gerbera/additional-files/config.xml, net-misc/gerbera/additional-files/install_config.sh, net-misc/gerbera/gerbera-1.4.0.recipe, net-misc/gerbera/patches/gerbera-1.4.0.patchset
Needs someone to fix the path to search for the config.xml file (or a way to find to cp the config.xml file to ~/config/settings/gerbera)
=> gerbera, new recipe

games-arcade/starfighter/patches/starfighter-2.0.0.3.patch, games-arcade/starfighter/starfighter-2.0.0.3.recipe
Should the `x86` architecture always be marked as untested?
EDIT: Also, I wasn't sure whether to put this in games-action or games-arcade
=> starfighter: new recipe

games-simulation/lincity_ng/lincity_ng-2.9~git.recipe, games-simulation/lincity_ng/patches/lincity_ng-2.9~git.patchset
Resolves #427 
The issue says that it should the write directory should be changed to `B_USER_SETTINGS_DIRECTORY/lincity`, but I'm assuming it meant `B_USER_SETTINGS_DIRECTORY/lincity-ng` as I don't see any reason to name it `lincity` instead of `lincity-ng`.
The OpenGL GUI doesn't work and the mouse cursor isn't visible on fullscreen, so I simply disabled them by default. I haven't played it much, but it seems to work fine other than that.
=> lincity_ng: new recipe

app-office/libreoffice/libreoffice-6.4.1.1.recipe
This PR adds Turkish localisation support for LibreOffice Haiku port.
=> LibreOffice: Enable Turkish localisation

media-fonts/ukijorgfonts/ukijorgfonts-1.0.recipe
=> ukijorgfonts: updated SOURCE_URI

dev-lang/luajit/luajit-2.1.0~beta3.recipe
=> luajit: added https to homepage

games-emulation/retroarch/patches/retroarch-1.8.4.patchset, games-emulation/retroarch/retroarch-1.8.4.recipe
The main point of this PR is actually for the patch, though; I'm not sure if it somehow works on other machines, but none of the other drivers fully function on mine.
=> retroarch: bump to 1.8.4

media-gfx/blender/blender-2.79b.recipe, media-gfx/blender/patches/blender-2.79b.patchset
Build and run on x86 and x86_64 is confirmed.
=> blender: fix and enable 32 bit build

media-fonts/fantasque_sans/fantasque_sans-1.8.0.recipe
A simple recipe for a new, high-quality, monospaced font.
=> fantasque_sans: new recipe

dev-scheme/guile/guile1-1.8.8.recipe, dev-scheme/guile/patches/guile1-1.8.8.patchset
I've renamed the package guile1 to avoid conflicts with the already existing package guile which is for version 2.2.4. The two versions are incompatible and some programs still require guile 1.8 to run.
=> Package for Guile 1.8.8

app-office/libreoffice/libreoffice-6.4.3.1.recipe
It is still not everything (about 70 % of all LO translations - as a compromise taken only languages I've at least heard about)
=> bunch of LibreOffice translations are enabled to pack

sci-geosciences/routino/routino-3.3.2.recipe
* [Changelog](https://www.routino.org/software/NEWS.txt)
* Check (create routino database):
```sh
$ curl -O https://download.geofabrik.de/russia/northwestern-fed-district-latest.osm.pbf
$ planetsplitter --prefix=RussiaNW --tagging=/boot/system/data/routino/tagging.xml --parse-only northwestern-fed-district-latest.osm.pbf
Parse OSM Data [northwestern-fed-district-latest.osm.pbf]
==============
Read: Bytes=425267830 Nodes=55215460 Ways=4594449 Relations=206316
$ planetsplitter --prefix=RussiaNW --tagging=/boot/system/data/routino/tagging.xml --process-only
Sort OSM Data
=============
Checked Ways for unused Nodes: Ways=864820 Highway Nodes=7008567 
Removed unused Nodes: Nodes=55215460 Highway=7008567 not-Highway=48206893 
Split Ways: Ways=864820 Segments=7429469    
Sorted Way Names: …
```
=> Routino: bump to 3.3.2

media-fonts/libertine/libertine-5.3.0_2012_07_02.recipe
=> libertine, update HOMEPAGE

media-sound/freac/freac-1.1.1.recipe
=> freac: bump to 1.1.1

haiku-apps/helpviewer/helpviewer-1.6.1.1.recipe, haiku-apps/helpviewer/licenses/FatElk
=> add HelpViewer recipe

app-text/ayat_recit_ghamadi/ayat_recit_ghamadi-0.0.1.recipe, app-text/ayat_recit_ghamadi/licenses/Creative Commons Attribution 3.0
for complete experience elforkane app
this recipe provide recitation package that use by elforkane and al-anvar
=> new recipe: ayat_recite_ghamadi

games-simulation/openttd/openttd-1.7.1.recipe
So that we can play with supported language.
=> OpenTTD: Add freetype support
