haikuports/haikuports

dev-lang/yab/yab-1.7.5.recipe

Declare devel:libyab to avoid a policy error.
Fixed typo in SUMMARY.

No _devel package needed.

---

haiku-apps/bookmarkconverter/bookmarkconverter-0.4.3.recipe

Apparently the checksum for bookmarkconverter was wrong. This commit makes the recipe build again (at least on my machine).

Fix the checksum of bookmarkconverter

---

haiku-apps/nanosvgtranslator/nanosvgtranslator-1.0.1.recipe

This adds support for x86_64 as architecture.
I've used the nanosvgtranslator add-on on my x86_64 installation for a few weeks without problems (or let's say: no more than on a gcc2hybrid - there are still some rendering issues), so I assume it should be okay to include x86_64 as supported platform.

add architecture x86_64 for nanosvgtranslator-1.0.1 recipe

---

media-fonts/hack_font/hack_font-2.010.recipe

I have created a recipe for a font called Hack.
My only concern is that the font license is `Modified SIL Open Font License & Bitstream Vera License` but haiku porter did not let me use this string as a value.

Add recipe for the Hack font.

---

app-shells/bash/bash-4.3.42.recipe
app-shells/bash_completion/bash_completion-2.1.recipe
app-shells/bash_completion/patches/bash_completion-haiku.patch

Hello.
I have fixed the recipe and added tab-completion support for pkgman and finddir. The pkgman completion script can even complete package names for the 'install' and 'uninstall' options.
To test it install the package, start a shell and execute `source /system/data/bash-completion/bash_completion`.
To have it automatically enabled you have to put the following code in ~/.bashrc as the README says:
```
[[ $PS1 && -f /system/data/bash-completion/bash_completion ]] && \
. /system/data/bash-completion/bash_completion
```
I have not tested that last part though.

bash_completion: fix the recipe and add support for pkgman and finddir

---

app-cdr/cdrtools/cdrtools-3.02~a01.recipe
app-cdr/cdrtools/patches/cdrtools-3.02-Defaults.haiku.patch
app-cdr/cdrtools/patches/cdrtools-3.02-scsi-beos.c.patch

Adding cdrtools-3.02~a01.recipe and 2 patches:
cdrtools-3.02-Defaults.haiku.patch
cdrtools-3.02-scsi-beos.c.patch
Since the patches will probably be valid for all 3.02{,aXX} releases,
I'm getting rid of the "~aXX" string in the names of the patches.
This means future updates for 3.02aXX (as well as for 3.02 stable)
will only require editing a single file: the recipe.

Update cdrtools to 3.02~a01

---

app-cdr/cdrtools/cdrtools-3.02~a01.recipe

Upstream changed a few lines (credits/thanks) in AN-3.02a01.
Not incrementing REVISION since everything else in the source tarball is unchanged.

SHA256 changed with tiny changes in AN-3.02a01

---

media-libs/freealut/freealut-1.1.0.recipe

This PR updates the freealut recipe with new haikuporter keys and the URL was a dead link, so the mirror from ftp.debian.org was used instead.

Updated freealut recipe.

---

sci-libs/cln/cln-1.3.4.recipe
sci-libs/cln/patches/cln-1.3.4.patch
sci-libs/ginac/ginac-1.6.5.recipe

GCI task to add a ginac recipe. As ginac depends on cln, I ported that too. I only saw that cln already had a recipe after I was done, but the 1.3.2 recipe looks unusable anyway.

Add cln and ginac recipes

---

dev-lang/fpc/fpc-2.6.2.recipe
dev-lang/fpc/fpc_bin-2.6.2.recipe

The whole compilation was crashing cause of badly inserted link. It seems weird, but still, better when downloaded tarball has right name.

FPC 2.6.2: Fixed download link

---

media-libs/speex/speex-1.2~rc2.recipe

Libspeex compilation was broken, cause there is no aclocal-1.13 and autotool-1.13, also there was an error with ./compile and it is fixed with add-mising

Speex 1.2: Fixed compiling problem with aclocal and automake

---

haiku-apps/haikuplot/haikuplot-1.0.0.recipe

@humdingerb graciously took some time yesterday to update HaikuPlot to be able to support gcc4.
This PR updates the recipe to implement gcc4 support.

Implement gcc4 support for haikuplot

---

dev-libs/check/check-0.9.14.recipe
dev-libs/json_c/json_c-0.12.recipe
dev-libs/libcss/libcss-0.5.0.recipe
dev-libs/libnsutils/libnsutils-0.0.1.recipe
dev-libs/libutf8proc/libutf8proc-1.1.6.recipe
media-libs/libnsbmp/libnsbmp-0.1.2.recipe
media-libs/libnsgif/libnsgif-0.1.2.recipe
media-libs/libsvgtiny/libsvgtiny-0.1.3.recipe
net-libs/hubbub/hubbub-0.3.1.recipe
net-libs/libdom/libdom-0.1.2.recipe
www-client/netsurf/netsurf-3.3.recipe
www-client/netsurf/patches/netsurf-3.3.patchset

This PR makes all NetSurf dependencies gcc4 compatible.
Please do not merge, this is a WIP PR. I am using this so I can get responses on the changes that I am making (since I have a really difficult time making recipes).

Update NetSurf to be gcc4 compatible

---

haiku-apps/haikuplot/haikuplot-1.0.0.recipe

In this PR I have updated HaikuPlot's recipe in the following ways
- Update to use latest commit
- Update install to only install the demo and the application (no source files)

Bump HaikuPlot version & update recipe

---

games-arcade/vectoroids/vectoroids-1.1.0.recipe

This recipe builds the version with sound. On my machine, the game has some performance issues when built with sound. [This branch](http://cgit.haiku-os.org/haiku/tree/src/kits/media/SoundPlayNode.cpp#n641) is triggered a lot, so I am unsure whether this is a bug in Haiku, in SDL_mixer or in Vectoroids. I also do not know whether these problems only occurr on my machine or only happen when using VirtualBox. The game runs smoothly on my machine when building without sound.

Add vectoroids recipe

---

media-libs/taglib/patches/taglib-1.10.patchset
media-libs/taglib/taglib-1.10.recipe

~~Unlike the 1.9.1 recipe, this has been patched to build on gcc2, which is nice to have.~~ Removed this by @scottmc's request. [Corresponding GCI task](https://codein.withgoogle.com/dashboard/task-instances/4915095117234176/?sp-page=1).

Update taglib to version 1.10

---

haiku-apps/haikuplot/haikuplot-1.0.0.recipe
haiku-apps/tipster/tipster-1.0.0.recipe

In this PR I have updated both the tipster and haiku plot recipes. I edited the following things:
1) Remove secondaryArchSuffix because it is not needed
2) Update the github links to use archives (which are safe sources)
3) Use the HaikuArchives Tipster repo, not mine

Update HaikuPlot & Tipster

---

dev-db/libmysqlclient/libmysqlclient-6.1.6.recipe

There was a little typo error.

Fix typo in libmysqlclient recipe

---

haiku-apps/xaos/xaos-3.4.recipe

The XaoS recipe has the incorrect SHA256 hash for its version and fails to verify when using haikuporter. This small PR addresses this issue.

Updated XaoS recipe SHA-256 hash

---

sys-libs/zlib/licenses/Zlib
sys-libs/zlib/zlib-1.2.8.recipe

* Switch source tarball format from tar.gz to tar.xz.
* Add "?ppc" to ARCHITECTURES.
* Refresh Copyright year (as shown in http://www.zlib.net/) in recipe and Zlib license file.

zlib: switch source tarball format to tar.xz

---

media-libs/musicbrainz/musicbrainz-5.1.0.recipe
media-libs/musicbrainz/patches/musicbrainz-5.1.0.patchset

Just a small thing that came up when I was working on https://codein.withgoogle.com/dashboard/task-instances/4824242864521216/?sp-page=1.

Make libmusicbrainz usable with the Makefile engine

---

media-video/handbrake/handbrake-0.10.2.recipe
media-video/handbrake/patches/handbrake-0.10.2.patchset
media-video/handbrake/state.md

See #411.
This also marks HandBrake 0.10.2 as broken on x86_gcc2 as there is no version
of FFmpeg which works on x86_gcc2 that provides the library version required
by HandBrake.
As of https://codein.withgoogle.com/dashboard/task-instances/6140613900632064/?sp-page=1

HandBrake: Work on the Haiku GUI

---

dev-util/intltool/intltool-0.51.0.recipe

* Add recipe for 0.51.0
* Fix recipe for 0.40.6: the `PROVIDES` section was missing a `$secondaryArchSuffix`.

intltool: add recipe for 0.51.0 & fix 0.40.6

---

dev-lang/fpc/fpc_bin-3.0.0.recipe

Recipe to construct a fpc 3.0.0 package for Haiku, based on the official package. It will help bootstrapping a more classical recipe that will construct the package from sources. Based on work on 2.6.2 at BeGeistert 029 with Korli.
The corresponding package is available at http://nan.tf/download/fpc_bin-3.0.0-1-x86_gcc2.hpkg

[FPC]Recipe to construct a fpc 3.0.0 package for Haiku, based on the official package.

---

www-servers/lighttpd/patches/lighttpd-1.4.39.patch

Workaround an issue about the configure script not being regenerated from configure.ac.
Instead of changing the BUILD block of the recipe, adding a tiny patch for the configure script is easy and works fine.

lighttpd: also patch configure (std=gnu99 → std=gnu9x)

---

dev-lang/vala/patches/vala-0.30.1.patchset
dev-lang/vala/vala-0.30.1.recipe

This is as close as we can get to to C# folks :)
I separated this in two packages like it is done in portage.
Before this is merged I want to start a discussion on something I am not sure how to do.
Originally I decided to add secondary arch support to the recipe so we could have `vala` and `vala_x86`.
The thing is that the vala compiler works by generating C code and then invoking `cc` and `pkg_config` to configure and compile the code. The executable names can be passed as parameters but by default they  are initialized like [this](https://github.com/GNOME/vala/blob/883284a25f034be8e9cd2d7edde9852b254a04ff/codegen/valaccodecompiler.vala#L91) and [this](https://github.com/GNOME/vala/blob/883284a25f034be8e9cd2d7edde9852b254a04ff/codegen/valaccodecompiler.vala#L55).
So the problem is even …

vala: add recipe

---

games-engines/godot/godot-2.0.recipe

This is the recipe for the recently released 2.0 version of the Godot game engine with native support for Haiku.

godot: add recipe

---

dev-libs/openssl/openssl-1.0.1s.recipe
dev-libs/openssl/openssl-1.0.2g.recipe
dev-libs/openssl/patches/openssl-1.0.1s.patchset
dev-libs/openssl/patches/openssl-1.0.2g.patchset

* bump 1.0.2 series to 1.0.2g with **`enable-ssl2`** to prevent API breakage.
* bump 1.0.1 series to 1.0.1s with **`enable-ssl2`** to prevent API breakage.
* Fix the patchset for the 1.0.1 series:
1. by using a copy of patch «**`Do not use __INTEL__ to detect x86_64`**»
from the 1.0.2 series for **`crypto/evp/e_aes_cbc_hmac_sha1.c`**.
2. by using a copy of the 2nd chunk of patch «**`more __intel__ fixes...`**»
from the 1.0.2 series for **`crypto/evp/e_rc4_hmac_md5.c`**.

openssl: bump version (1.0.2g & 1.0.1s)

---

net-nds/openldap/openldap-2.4.44.recipe

* Bump version to 2.4.44.
* Mark all architectures as tested.
* Remove documentation for secondary architectures.
* Reorder sections.
* Fix **`PATCH()`** to avoid replacing «-lnetwork» by «**`-lnetworkwork`**».

openldap: bump version to 2.4.44.

---

net-libs/gnutls/gnutls-3.4.10.recipe

* Bump version to 3.4.10.
* ~~Install **`systemkey`** as **`systemkey-tool`** (to follow the man page name) as neither the command nor its manual page are being installed by default.~~
* Drop the **`--disable-doc`** switch during configuration and put all docs in a separate package, gnutls_doc.
* Add «**`= $portVersion compat >= 3.4`**» for each «**`cmd:`**» line in PROVIDES.
* Swap the lines for «**`cmd:psktool`**» and «**`cmd:ocsptool`**» as they were not sorted.
* Drop the «**`cmd:systemkey`**» line in PROVIDES as it is not installed by default.

gnutls: bump version to 3.4.10.

---

dev-lang/vala/vala-0.30.1.recipe

The **`$secondaryArchSuffix`** suffix was missing for vala in PROVIDES and for vala_common in PROVIDES_common. This is required on x86_gcc2 because vala_x86 requires vala_common_x86.

vala: fix missing $secondaryArchSuffix in PROVIDES{,_common}.

---

net-misc/curl/curl-7.48.0.recipe

* Bump version.
* Move BUILD_REQUIRES to the recommended place.
* Use **`cmd:libtoolize$secondaryArchSuffix`** instead of **`cmd:libtoolize`** in BUILD_PREREQUIRES to make sure we don't accidentally pull libintl from the primary arch when building for a secondary arch.

curl: bump to version 7.48.0

---

app-shells/mksh/licenses/ISC
app-shells/mksh/licenses/MirOS
app-shells/mksh/mksh-52c.recipe
app-shells/mksh/patches/mksh-52c.patch

* Drop the "r" prefix in version.
* Bump version to 52c and use portVersion where appropriate.
* Fix wrong LICENSE declaration and add missing licenses.
* Move haiku_devel from BUILD_PREREQUIRES to BUILD_REQUIRES to be consistent with most other recipes.
* Add missing cmd:awk to BUILD_PREREQUIRES.
* Add x86{,_64} to ARCHITECTURES with a tiny conditional patch to make the recipe build on these architectures.
* Do not create the «**`sh -> mksh`**» symbolic link anymore as changing the default «**`sh -> bash`**» symbolic link might create problems. Users willing to set /bin/mksh as their default shell just need to edit /etc/passwd.

mksh: bump version, add x86{,_64} with a patch.

---

dev-util/pkgconfig/patches/pkgconfig-0.29.1.patchset
dev-util/pkgconfig/pkgconfig-0.27.1.recipe
dev-util/pkgconfig/pkgconfig-0.29.1.recipe
dev-util/pkgconfig/pkgconfig-0.29.recipe

* Add recipe for version 0.29.1.
* Use the runConfigure wrapper.
* Use exact copy of the patchset for 0.29 as there are no offset mismatches.
For 0.27.1:
* Call configure wuth «**`--with-pc-path`**» instead of «**`--with-pc_path`**».
For 0.28:
* Several changes to make it build and look almost like 0.29.1.
For 0.29:
* Switch to runConfigure in order to prevent pkg-config on secondary arch from shadowing that of the primary arch.
For 0.27.1, 0.28, 0.29 and 0.29.1:
* Fix COPYRIGHT.
* Update HOMEPAGE and SOURCE_URI to avoid «301 Moved Permanently».

pkgconfig: fix 0.27.1, 0.28 and 0.29, add 0.29.1.

---

media-libs/libcaca/libcaca-0.99.beta19.recipe

* Drop the mirror for SOURCE_URI, since the official website is back.
* Add **`TEST()`** with **`make check`** since this target exists.
* No changes in primary arch packages, except for the SOURCE_URI.
* On secondary arch there is no need to ship man pages, data files and runtimes (except for caca-config-*), since they are already in the primary arch packages. All we need for 2nd arch packages is:
* in the base package: the shared libs;
* in the devel package: **`caca-config-*`** and **`develop/{headers,lib}`**.
The only file we need to keep in every package is the licence.
* Cosmetic edits: duplicate white spaces, fake tab, **`-e`** for sed.

libcaca: shrink 2nd arch packages to avoid duplicate files.

---

dev-lang/yab/yab-1.7.5.3.recipe
haiku-apps/yab_ide/yab_ide-2.2.6.recipe

yab Version 1.7.5.3, yab-IDE version 2.2.6
- gcc4 now compiles
- fix system shutdown bug
- remove un-needed BuildFactory files
- add https:// to texturl
- BuildFactory use declared appsig
- yab-IDE use declared appsig, or use filename for appsig

update yab and yab-ide

---

dev-libs/openssl/openssl-1.0.1t.recipe
dev-libs/openssl/openssl-1.0.2h.recipe
dev-libs/openssl/patches/openssl-1.0.1t.patchset
dev-libs/openssl/patches/openssl-1.0.2h.patchset

* Bump versions.
* Use **`-e`** for **`sed`** to make the recipe more portable, since some systems have sed implementations that require it.
* Add **`cmd:cmp`** to BUILD_PREREQUIRES since **`make test`** needs it.

openssl: bump to 1.0.1t and 1.0.2h.

---

dev-libs/check/check-0.10.0.recipe
dev-libs/check/check-0.9.13.recipe
dev-libs/check/check-0.9.14.recipe

* 0.9.13, 0.9.14 and 0.10.0 were missing a **`cmd:gawk`** in REQUIRES.
* Fixed 2nd arch for 0.10.0 and improved the package splitting.
* Switch 0.9.13 and 0.9.14 to the same layout as 0.10.0.

check: fix PROVIDES for secondary arch & improve pkg splitting.

---

media-libs/exiftool/exiftool-10.15.recipe
media-libs/exiftool/exiftool-10.16.recipe

* Drop 10.13 and 10.14, which were in media-gfx/exiftool.
* Add 10.15 and 10.16 in media-libs/exiftool to follow Gentoo.
* Switch to **`ARCHITECTURES="any"`**.
* Use **`cmd:perl`** (in REQUIRES) instead of just **`perl`**.

exiftool: move from media-gfx to media-libs, drop old, add new.

---

haiku-apps/sanity/patches/sanity-0.6.patchset
haiku-apps/sanity/sanity-0.6.recipe

Attempting to build Sanity 0,6 recipe on Haiku fails with error
Welcome to the Haiku shell.
~> haikuporter -S -j4 --get-dependencies --no-source-packages sanity
Checking if package dependencies need to be updated ...
updating dependency infos of sanity-0.6
----------------------------------------------------------------------
haiku-apps::sanity-0.6
/boot/home/haikuports/haiku-apps/sanity/sanity-0.6.recipe
----------------------------------------------------------------------
Downloading: https://github.com/diversys/sanity/archive/f40f575.tar.gz ...
--2016-05-18 10:10:55--  https://github.com/diversys/sanity/archive/f40f575.tar.gz
Resolving github.com... 192.30.252.120
Connecting to github.com|192.30.252.120|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: …

Sanity 0.6 recipe fails

---

sys-devel/make/make-4.2.recipe
sys-devel/make/patches/make-4.2.patchset

Also _revert an upstream commit until a real fix is available_, just like Gentoo did with 4.2-r1.
See https://bugs.gentoo.org/583812
(This was blocking **`haikuporter --test make-4.2`**.)
Finally, remove unneeded call to libtoolize.

make: add recipe for 4.2, add TEST(), switch to mirror.

---

media-sound/mpg123/mpg123-1.23.4.recipe

* Drop unrecognized «**`--disable-aligncheck`**» configure option.
* Add «**` = $portVersion`**» to every **`cmd:`** in PROVIDES.
* Add **`cmd:autoheader`** and **`cmd:automake`** to BUILD_PREREQUIRES.
* Drop **`cmd:{awk,find,autoreconf}`** and unneeded call to autoreconf.
* Drop unneeded «**`LDFLAGS=-lnetwork`**» as configure finds it anyway.

mpg123: bump to 1.23.4 with miscellaneous minor changes.

---

dev-libs/libzip/libzip-1.1.3.recipe
dev-libs/libzip/patches/libzip-1.1.3.patchset

* Add recipe for 1.1.3 but call configure with «**`--disable-static`**». This is OK since there are currently no recipes depending on libzip.
* **`make install`** puts **`zipconf.h`** in **`lib/libzip/include/`** so we need to move it to **`develop/headers/libzip/`** and fix **`libzip.pc`**.
* Change «**`LN=ln -f`**» into «**`LN=ln -frs`**» in **`man/Makefile.am`** to make **`ln`** create relative symlinks. This works fine and also saves space.

libzip: add recipe for 1.1.3, disable static lib, fix install.

---

net-misc/curl/additional-files/curl.rdef
net-misc/curl/curl-7.49.1.recipe

* Bump to 7.49.1 and call **`runConfigure`** with **`CFLAGS=_BSD_SOURCE`** and **`CXXFLAGS=-D_BSD_SOURCE`** otherwise **`make check`** fails to build.
* Drop **`$manDir/man3`** on 2nd arch devel packages.
* Move the manual page of **`curl-config(1)`** to the devel package.
* Use **`install`** (instead of mkdir and cp) to simplify **`INSTALL()`**.
* Keep $binDir for 2nd arch since x86_gcc2 fails many tests.
* No need to call libtoolize. Keep autoconf (needed on x86_64).
* Add version info in rdef file to have "Get Info" show it.

curl: bump to 7.49.1, use _BSD_SOURCE (required for make check).

---

net-misc/openssh/additional-files/fix_openssh_config_paths.sh
net-misc/openssh/openssh-7.1p1.recipe
net-misc/openssh/openssh-7.1p2.recipe
net-misc/openssh/openssh-7.2p2.recipe

I updated my Haiku install, and then tried to log in through sftp. It worked before, but not anymore. I was able to log in through SSH, but not with SFTP.
I located the problem, it is the keep-old flag of the /boot/system/settings/ssh/sshd_config file.
It had the following line:
Subsystem	sftp	/packages/openssh-6.6p1-1/.self/lib/openssh/sftp-server
but the correct path is:
Subsystem	sftp	/packages/openssh-7.1p1-1/.self/lib/openssh/sftp-server
We should somehow update this file after each openssh update.

OpenSSH global-writeable settings with "keep-old" flag

---

media-libs/harfbuzz/harfbuzz-1.2.7.recipe
media-libs/harfbuzz/patches/harfbuzz-1.2.7.patchset

* Bump to version 1.2.7, add **`TEST()`** with **`make check`**.
* Add patch for 3 tests that would otherwise fail or be skipped.
* Add **`cmd:{python,which}`** to BUILD_PREREQ, as **`make check`** needs them.
* Drop explicit call to autoreconf as it is no longer needed.

harfbuzz: bump to 1.2.7, add TEST() with "make check". (WIP)

---

dev-vcs/git/git-2.9.0.recipe
dev-vcs/git/patches/git-2.9.0.patchset

TEST() does not work yet because of haikuports/haikuporter/issues/90 but adding **`BUILD_PACKAGE_ACTIVATION_PHASE=TEST`** and playing with the time stamp of the recipe (once built) can help workaround this error:
```
Testing ...
SUBDIR perl
/bin/sh: /packages/git-2.9.0-1/cmd~perl/bin/perl: No such file or directory
```

git: bump to 2.9.0, add TEST() with "makeGit test".

---

sys-devel/gettext/gettext-0.19.8.1.recipe
sys-devel/gettext/patches/gettext-0.19.8.1.patchset

Some recipes, e.g. mc (Midnight Commander), need libintl.la, but we were previously dropping all **`develop/lib/lib*.la`** files in gettext.
We now ship them and also fix them to make sure they don't become unusable in case devel:libiconv or devel:libncurses get updated.
On x86 and x86_64 we also fix **`$developLibDir/libasprintf.la`** to use a path to libstdc++.la that does not depend on the revision of the gcc package.

gettext: bump to 0.19.8.1, keep & fix lib*.la, sync patch.

---

dev-libs/libebml/libebml-1.3.3.recipe

* On all architectures other than x86_gcc2 the generated definition of dependency_libs in **`libebml.la`** includes a path to **`libstdc++.la`** that hard-codes the full version of the gcc package being used to build libebml. Keeping that path unchanged would result in a hidden dependency of libebml_devel on a specific revision of the gcc package. So fix that path using a _package-links dir_ that starts with e.g. **`/packages/libebml_x86_devel-*/gcc_x86/develop/tools/x86/lib/gcc/...`**
* Add **`gcc$secondaryArchSuffix`** to REQUIRES_devel when building for an architecture other than x86_gcc2 because **`libebml.la`** needs it.
* Add TEST() with **`make check`**.

libebml: fix libebml.la for all archies other than x86_gcc2.

---

sys-devel/gettext/gettext-0.19.8.1.recipe

The search pattern used in the sed call to fix **`libasprintf.la`** did match and work fine on primary architectures, but failed on x86 secondary, resulting in a package that would become invalid if gcc_x86 got upgraded later. The correct search pattern to match e.g. **`develop/tools/x86/lib/gcc/`** is not **`develop/tools/$relativeLibDir/gcc/`** but **`develop/tools$secondaryArchSubDir/lib/gcc/`** and works for all architectures, including secondary, of course.

gettext: fix incorrect sed for libasprintf.la on x86 2nd arch.

---

media-libs/libbluray/libbluray-0.9.3.recipe

* Bump to 0.9.3 ~~with a big gcc2 patch~~, add TEST() with **`make check`**.
* Fix **`Libs.private`** paths in **`pkgconfig/libbluray.pc`**.
* Add **`devel:lib{fontconfig,freetype,xml2}`** to REQUIRES_devel.
* Drop explicit call to autoreconf as configure works without it.
* ~~Drop~~ **Keep** the static lib ~~as~~ **although** handbrake, mpv and vlc do not need it.

libbluray: bump to 0.9.3, fix libbluray.pc and REQUIRES_devel.

---

media-libs/libmatroska/libmatroska-1.4.4.recipe

* **`libmatroska.la`** has a path which will become invalid if libebml gets updated. Dropping that **`.la`** file is OK because we don't need it.
* Add **`devel:libebml`** to REQUIRES_devel.
* ~~Also add gcc to REQUIRES_devel on effective architectures other than x86_gcc2 to make sure it will have libstdc++.~~
* Add **`TEST()`** with **`make check`**.

libmatroska: fix REQUIRES_devel, drop libtool file, add TEST().

---

games-arcade/alex4/alex4-1.0.recipe
games-arcade/alex4/patches/alex4-1.0.patch

**TODO:** Check if it would be OK to also import the patches in:
http://data.gpo.zugaina.org/gamerlay/games-arcade/alex4/files/
and sync with alex4-1.1 in http://gpo.zugaina.org/games-arcade/alex4
Maybe we should use a (modified) rdef instead of the **`alex4_BeOS_src/alex4.rsrc`** in alex4_beos_src.zip, because when Alex4 is launched from command line we see this warning:
```
Signature in rsrc doesn't match constructor arg. (application/x-vnd.Allegro-Alex4, application/x-vnd.freelunchdesign-alex4)
```

games-arcade/alex4: create recipe for Alex the Allegator 4. (WIP)

---

net-libs/gnutls/gnutls-2.8.6.recipe
net-libs/gnutls/gnutls34-3.4.14.recipe
net-libs/gnutls/gnutls35-3.5.2.recipe
net-libs/gnutls/patches/gnutls-3.4.14.patchset
net-libs/gnutls/patches/gnutls-3.5.2.patchset

* Bump to 3.4.14 (current stable) and add 3.5.2, marked untested.
* ~~Fix paths of dependency_libs in **`develop/lib/lib*.la`** to make sure they will still be valid even if these dependencies are updated.~~
* Move **`$binDir`** to a _bin sub-package, for more flexibility with regards to package co-installation. 3.4.x and 3.5.x seem to be causing problems for other recipes, so this layout change, with some other changes (e.g. package basename renames) can help.
* Update the layout of 2.8.x ~~and add x86 and x86_64 as untested~~.
* Change the basename of the recipe of 3.4.x to gnutls34.
* Use gnutls35 as basename for the recipe of 3.5.x.
* Declare CONFLICTS, CONFLICTS_{bin,devel} in a way that allows gnutls-2.8.x to be installed with either gnutls-3.4.x or gnutls-3.5.x. On top of that, a …

gnutls: bump to 3.4.14 + 3.5.2,  drop lib*.la, add TEST().

---

x11-libs/libxpm/libxpm-3.5.11.recipe

* Enable 2nd arch and drop documentation when building for them.
* Drop the libtool library file since we don't need it.
* ~~Remove unneeded **`lib:lib{xau,xcb}`** from REQUIRES.~~
* Add **`devel:lib{x11,xcb,x11}`** to REQUIRES_devel.
* Add **`$secondaryArchSuffix`** to **`cmd:libtoolize`** in BUILD_PREREQUIRES.
* HOMEPAGE: http://xorg.freedesktop.org/ moved to https://www.x.org/.
* ARCHITECTURES: Mark as tested on x86 and x86_64.

libxpm: enable 2nd arch, drop libXpm.la.

---

x11-libs/libx11/libx11-1.6.3.recipe

* Enable 2nd arch and drop documentation when building for them.
* Drop libtool library files since we don't need them.
* ~~Remove unneeded **`{lib,devel}:libxau`** from **`REQUIRES{,_devel}`**.~~
* Add **`devel:libxcb`** to REQUIRES_devel.
* Add **`$secondaryArchSuffix`** to **`cmd:libtoolize`** in BUILD_PREREQUIRES.
* Move section 3 man pages to the _devel sub-package.
* Add **`TEST()`** with **`make check`**. Testsuite summary: TOTAL = PASS = 1.
* HOMEPAGE: http://xorg.freedesktop.org/ moved to https://www.x.org/.
* ARCHITECTURES: Mark as tested on x86 and x86_64.

libx11: enable 2nd arch, drop libtool files.

---

net-fs/curlftpfs/additional-files/readme.txt
net-fs/curlftpfs/curlftpfs-0.9.2.recipe
net-fs/curlftpfs/patches/curlftpfs-0.9.2.patchset

Recipe and patch attached. This goes in net-fs/curlftpfs
I know there are some small scale issues with the way dependencies are listed, but I don't have more time for this now so I wanted to get it submitted before it rots (it does work).
[curlftpfs-0.9.2.recipe.txt](https://github.com/haikuports/haikuports/files/384841/curlftpfs-0.9.2.recipe.txt)
[curlftpfs-0.9.2.patchset.txt](https://github.com/haikuports/haikuports/files/384840/curlftpfs-0.9.2.patchset.txt)

Add recipe for curlftpfs

---

media-libs/fontconfig/fontconfig-2.12.1.recipe
media-libs/fontconfig/patches/fontconfig-2.12.1.patchset

* Convert the **`settings/fonts/conf.d/*.conf`** absolute symlinks into (relative) symlinks to **`../../data/fontconfig/conf.avail/`** instead of **`/packages/fontconfig-2.12.1-1/.self/data/fontconfig/conf.avail/`**.
* Switch HOMEPAGE and SOURCE_URI to https.
* Add **`TEST()`** with **`make check`**.

fontconfig: bump to 2.12.1, reorder sections, sync patch.

---

dev-libs/libgcrypt/libgcrypt-1.7.3.recipe
dev-libs/libgcrypt/patches/libgcrypt-1.7.3.patchset

* Add **`lib:libgpg_error`** to REQUIRES_devel, as **`cmd:mpicalc`** needs it.
* Drop documentation on secondary architectures.
* Add **`TEST()`** with **`make check`**.

libgcrypt: bump to 1.7.3, fix REQUIRES_devel, add TEST.

---

dev-vcs/git/git-2.9.3.recipe
dev-vcs/git/patches/git-2.9.3.patchset

Passing **`/bin/perl`** (instead of **`$portPackageLinksDir/cmd~perl/bin/perl`**) as PERL_PATH to **`make`** in **`makeGit`** solves the issue about perl not being found when **`haikuporter --test git`** is run. FWIW, that path is used to set the PERL and FULLPERL variables in **`$sourceDir/perl/perl.mak`**.

git: bump to 2.9.3, pass PERL_PATH=/bin/perl to make.

---

dev-util/cmark/cmark-0.26.1.recipe

cmark is a CommonMark parser program and rendering library written in C. It is able to generate LaTeX, HTML, groff man and CommonMark XML from plaintext formatted Markdown. x86_gcc2 is currently not supported.

New recipe: cmark

---

media-libs/openjpeg/openjpeg-2.1.2.recipe
media-libs/openjpeg/patches/openjpeg-2.1.2.patchset

* Use **`binDir`** for secondary arch builds.
* Drop **`TEST()`** because it is useless without an additional data file.
* **`LIB_SUFFIX`** is not (or no longer) used so don't pass it to cmake.
* Depend on **`liblcms2`** on all architectures where it is available.
* Add «**`>= 5`**» for the dependency on **`libtiff`** to pull the latest.

openjpeg: bump to 2.1.2.

---

app-shells/fish/patches/fish-2.3.1.patchset

Use /bin/open on Haiku to open files with the associated programs from cli.
Slowly enabling advanced features in fish.....

Haiku mime support for Fish

---

www-servers/lighttpd/additional-files/create-lighttpd-directories.sh
www-servers/lighttpd/additional-files/geoip.shtml
www-servers/lighttpd/additional-files/quickstart-geoip.txt
www-servers/lighttpd/additional-files/quickstart.txt
www-servers/lighttpd/lighttpd-1.4.42.recipe

* This release of lighttpd comes with 7 new modules: mod_deflate, mod_authn_{file,gssapi,ldap,mysql}, mod_uploadprogress and mod_geoip.
* The GeoIP module is being added in a separate sub-package to limit the dependency on the geoip package to that sub-package only.
* Add a quickstart-geoip.txt and a demo geoip page for novice users.
* In lighttpd.conf don't use paths that change when the package is updated.
* Keep lighttpd.pid in **`/var/run`** instead of **`/var`**.
* Switch SOURCE_URI from tar.gz to tar.xz ;-)

lighttpd: bump to 1.4.42, with mod_geoip and 6 other modules.

---

net-misc/curl/curl-7.51.0.recipe

Upstream does not ship **`docs/libcurl/*.html`** anymore. Although these may be generated with "make html", we would need roffit or any other MAN2HTML conversion utility, so let's just drop the html doc.

curl: bump to 7.51.0, drop html documentation.

---

media-gfx/imagemagick/imagemagick-6.9.6.6.recipe
media-gfx/imagemagick/patches/imagemagick-6.9.6.6.patchset

* Remove **`lib:libgomp`** from REQUIRES on x86_gcc2 primary arch, since gcc_syslibs_devel does not provide it on that arch.
* Remove unneeded cmd:svnversion from BUILD_PREREQUIRES.
* Drop libtool files.
* Add TEST with **`make check`**.
* Improve layout by moving some items from the base package to the _devel subpackage: **`lib/pkgconfig/*.pc`** (thanks to fixPkgconfig), **`bin/*-config`** (and their associated man1 manual pages), and some docs: **`data/doc/ImageMagick-6/www/api{.html,/}`**.
* Add two extra download locations to SOURCE_URI to make sure the tarball will still be available after a new version is released.

imagemagick: bump to 6.9.6.6. Improve layout. Minor changes.

---

dev-libs/libsodium/libsodium-1.0.11.recipe

* **`configure --disable-ssp`** to avoid the dependency on libssp.
* Enable x86_64.
* Use 18.1.1 for the lib version, instead of **`$portVersion`**.
* Replace **`cmd:libtool`** by **`cmd:libtoolize$secondaryArchSuffix`**.
* Change prepareInstalledDevel**Libs** to prepareInstalledDevel**Lib**, since we have only one lib here.

libsodium: drop libtool file, configure with --disable-ssp.

---

sci-libs/gdal/gdal-1.11.0.recipe

Don't think it should have been removed, as a lot of changes were made in https://github.com/haikuports/haikuports/commit/1ac39b83d173defd7db80c12ff2f57f8845eb41f. A small change like https://github.com/haikuports/haikuports/commit/1ac39b83d173defd7db80c12ff2f57f8845eb41f#diff-833e49ab9e6069299e254050cccb7874L43 might have gone unnoticed.

Re-add patchset

---

media-libs/libaacs/libaacs-0.8.1.recipe

Remove [lint error](https://gist.github.com/ohnx/676338c83bd396261dd294029387cf7c#file-haikuports-errors-txt-L72).
The file is empty anyways.
(re-submission of https://github.com/haikuports/haikuports/pull/899)

Remove libaacs-0.8.1 patchset file

---

media-gfx/pngquant/pngquant-2.7.2.recipe
media-gfx/pngquant/pngquant-2.8.0.recipe

This recipe adds the pngquant command. It is incompatible with GCC2 so consequently only uses the x86. There are definitely some oddities to the package, such as (how `./configure` only accepts prefix).  As such, I am not rebasing at the moment and will do so once it is determined "done" and to a state where we can merge. :-)

Added pngquant recipe

---

media-gfx/apng2gif/apng2gif-1.7.recipe
media-gfx/gif2apng/gif2apng-1.9.recipe

Created apng2gif recipe

---

app-editors/vim/patches/vim-8.0.0046.patchset

With this patch i was able to build it on x64 Haiku.

Vim patchset: vim GUI requires libstdc++

---

sys-auth/libyubikey/libyubikey-1.13.recipe

Added the recipe for the Yubico YubiKey authentication device library and associated tools.

Added recipe for libyubikey

---

dev-libs/libical/libical-2.0.0.recipe
dev-libs/libical/licenses/MPL v1.0
dev-libs/libical/patches/libical-2.0.0.patchset

Adding new recipe for libcal, an implementation of icalendar protocols and data formats.

libical: Add new recipe

---

app-crypt/stegsnow/stegsnow-20130616.recipe

Added a recipe for SNOW (Steganographic Nature Of Whitespace), a steganography tool for hiding information in plaintext files using trailing whitespace.

(GCI) Added recipe for app-crypt/stegsnow

---

sys-devel/gcc/gcc-5.4.0_2016_06_04.recipe

Work in progress, Any idea or help really appreciated. See my comments in the recipe.
Thanks!

GCC gfortran recipe

---

sys-fs/squashfs_tools/patches/squashfs_tools-4.3-gcc2.patch
sys-fs/squashfs_tools/patches/squashfs_tools-4.3-haiku-compat.patch
sys-fs/squashfs_tools/squashfs_tools-4.3.recipe

Added a recipe for squashfs_tools, a suite of tools for creating and manipulating squashfs filesystems.

(GCI) Added recipe for sys-fs/squashfs_tools

---

app-shells/fish/patches/fish-2.4.0.patchset

Not an ideal solution, but works and doesn't breaks anything.

Fish: hide socket warning at start.

---

media-video/mplayer/mplayer-1.3.0.recipe
media-video/mplayer/patches/mplayer_x86-1.3.0.patchset

> ~ ❯❯❯ mplayer -v
> MPlayer 1.3.0-5.4.0 (C) 2000-2016 MPlayer Team
> CPU vendor name: GenuineIntel  max cpuid level: 10
> CPU: Intel(R) Core(TM)2 Duo CPU     L9300  @ 1.60GHz (Family: 6, Model: 23, Stepping: 6)
> extended cpuid-level: 8
> extended cache-info: 402686016
> Detected cache-line size is 64 bytes
> CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 1 SSE2: 1 SSE3: 1 SSSE3: 1 SSE4: 1 SSE4.2: 0 AVX: 0
> Compiled with runtime CPU detection.
I think the runtime cpu detection works now. We should close this issue: https://github.com/haikuports/haikuports/issues
Oh, and it is already tested on x86_64.

mplayer: bump version, updated patchset

---

mail-client/mutt/mutt-1.7.2.recipe
mail-client/mutt/patches/mutt-1.7.2.patchset

For the sake of IMAP.
Sadly gmail requires SASL.

mutt recipe

---

media-libs/libextractor/libextractor-1.3.recipe
media-libs/libextractor/patches/libextractor-1.3_gcc2.patchset

Added recipe for building and installing GNU libextractor.
At this moment it does not compile because of a missing POSIX library in Haiku (sys/shm.h), and such it is noted as untested. It is noted as broken on x86_gcc2 because some of its dependencies are broken on that architecture.

Added recipe for libextractor

---

www-servers/lighttpd/lighttpd-1.4.44.recipe

* Do not call aclocal, autoconf and automake anymore, as this is no longer required given that we don't need to fix `Makefile.am` anymore.
* Update PROVIDES by commenting out `lib:mod_authn_{gssapi,mysql}`, `lib:mod_mysql_vhost` and `lib:mod_trigger_b4_dl` because 1.4.44 no longer creates empty modules when dependencies are missing.
* Simplify the on-the-fly patch for` lighttpd/conf.d/geoip.conf` as upstream now suggests `GeoLiteCity.dat` instead of `GeoCityLite.dat`.
* Inclusion of mod_geoip before mod_ssi has been applied upstream.

lighttpd: bump to 1.4.44.

---

dev-db/sqlitebrowser/sqlitebrowser-3.9.1.recipe

This is a fix to the broken recipe that was merged in #969. Due to my own misunderstanding of resource files and how they work in Haiku, I did not notice that the wrong filename was being used and that would make the build fail. This PR is a fix to that.

Fixed recipe for sqlitebrowser

---

app-pda/libusbmuxd/libusbmuxd-1.0.10.recipe
app-pda/libusbmuxd/patches/libusbmuxd-1.0.10.patchset

libusbmuxd is needed to build libimobiledevice, libideviceactivation and ideviceinstaller. Tested on x86_64.

new recipe: libusbmuxd

---

haiku-apps/commandtimer/commandtimer-2.0~git.recipe

Added recipe for CommandTimer timed command execution utility.
I unfortunately could not find a year to put in the copyright section. If someone knows the year this program was written, I will update the commit with the correct data.
As with #1030, if needed, I could submit a PR to the CommandTimer repo with the Makefile, in order not to include it with the recipe as an additional file.

commandtimer: added recipe

---

media-sound/flac123/flac123-0.0.12.recipe

Adding new recipe for flac123, a commandline program for playing FLAC audio files.

flac123: new recipe for a commandline FLAC player

---

haiku-apps/bebuilder/bebuilder-0.5.2~git.recipe

Added recipe for BeBuilder BeOS GUI builder. 
Since the source code was not building properly because some parts of it were not standard compliant (using `string` instead of `std::string`, some missing libraries in the makefile, etc.), I had to write a patch to fix this. I think it would be best if I opened a PR on the BeBuilder repo and submit the patch there, like I did in #1030.

bebuilder: added recipe

---

net-dialup/lrzsz/lrzsz-0.12.20.recipe

Added recipe for lrzsz communication package.
I am aware that editing `Makefile.in` is not an optimal solution, but because of the package's age, it does not respond well when attempting to regenerate the configuration scripts with a modern version of the autotools. If someone is able to do it, I will be happy to update the commit, but until then, this is the solution I've come up with.

lrzsz: added recipe

---

sys-boot/gnu-efi/gnu_efi_kernel-3.0.4.recipe

Missing dash in recipe name since haikuporter does not support
having dashes in filename.
Signed-off-by: Mason X <masonx.01@gmail.com>

Add gnu-efi recipe

---

app-text/libepubgen/libepubgen-0.0.0.recipe

Added recipe for libepubgen.
In its current state I'm getting a compile error related to libboost. You can see the errror I'm gettting [here](https://gist.github.com/xdizzaster/258756af114c9ca8828f3e3e00c170dd). To me, it seems to be something wrong inside the boost header files. I got boost from the HaikuDepot.
I tried asking around on IRC, but nobody could figure out what I was doing wrong and I wasn't able to solve it on my own.

libepubgen: added recipe

---

net-libs/tox/patches/tox-0.1.4.patchset
net-libs/tox/tox-0.1.4.recipe

Adding new recipe for tox, an encrypted, P2P, messaging, audio/video calling platform.

tox: new recipe for messaging platform (WIP, do not merge yet)

---

www-client/links/links-2.8.recipe

* Drop unneeded support for secondary architectures.
* Depend on libssl and libcrypto instead of openssl.
* Use **`$effectiveTargetArchitecture`** (instead of **`$targetArchitecture`**) when defining STDCPPLIBS (as **`-lstdc++`** or *``lbstdc++.r5`**) in order to have a working code for both primary and secondary architectures,
should that code snippet be copied to other recipes.
* Add TEST() with **`make check`**.

links: use libpng16 instead of libpng.

---

sys-devel/m4/m4-1.4.18.recipe

* Switch HOMEPAGE & SOURCE_URI to https.
* ~~Add missing cmd:{cmp,diff,help2man} to BUILD_PREREQUIRES as TEST() needs them. Sort BUILD_PREREQUIRES while at it.~~
* ~~BTW, unlike 1.4.17, 1.4.18 fails to build (on Haiku) without help2man.~~
* Do not pass **`--disable-rpath`** to configure, otherwise the build fails if **`cmd:help2man`** is not in BUILD_PREREQUIRES.
* Define TEST_REQUIRES with **`cmd:{cmp,diff,help2man}`**. It might be used by HaikuPorter in the future.
* Remove duplicate **`cmd:awk`** in BUILD_PREREQUIRES (and sort it).

m4: bump to 1.4.18.

---

dev-util/radare2/patches/radare2-1.1.0.patchset
dev-util/radare2/radare2-1.1.0.recipe

Tested on both x86 and x86_64, but not x86_gcc2. This patch fixes issues with the login_pty symbol when running radare2.

radare2: bump version to 1.1.0

---

media-libs/freetype/freetype-2.7.1.recipe
media-libs/freetype/patches/freetype-subpixel.patchset

PATCHES is still commented out in the recipe. Added for easy testing.

Freetype: add patch to activate subpixel rendering

---

app-text/mupdf/mupdf-1.10~a.recipe
app-text/mupdf/patches/mupdf-1.10~a-harfbuzz.patchset
app-text/mupdf/patches/mupdf-1.10~a-openjpeg21.patchset
app-text/mupdf/patches/mupdf-1.10~a.patchset

* Updated patches from 1.8 to 1.10~a.
* Added patches to fix includes for hb.h and hb-ft.h and to skip unneeded workaround in source/fitz/load-jpx.c
* Merged/replaced old patch with one from @korli.
* Add dependency on libharfbuzz and libglib_2.0 too, as it is required by harfbuzz.
**TODO:**
* Build libmupdf.so.
* Do not build libmupdfthird.a.

mupdf: bump to 1.10~a.

---

app-misc/imgcat/imgcat-1.1.1.recipe
app-misc/imgcat/licenses/ISC

Small utility to display images onto the terminal, should work on all architectures and tested only on zsh and bash.

imgcat: new recipe

---

app-doc/zeal/patches/zeal-0.3.1.patchset
app-doc/zeal/zeal-0.3.1.recipe

[Zeal](https://zealdocs.org/) is a documentation browser just like [Dash Docs](https://kapeli.com/dash) iOS and MacOS. Strangely, apps compiled with Qt do run but no windows are visible. Tested only on x86 but should work on x86_64.

zeal: new recipe

---

dev-lang/erlang/erlang-16.03.recipe

This commit fixes a compilation issue with the ifaddrs.h library that Erlang needs. Tested on x86 only. x86_gcc2 needs to be tested.

erlang: fix build

---

haiku-apps/bepdf/bepdf-2.0.1~beta1.recipe

BePDF was building without any additional locales. Added "make bindcatalogs" to BUILD() to correct and bumped revision as instructed.

Build BePDF with locales

---

games-arcade/rocksndiamonds/rocksndiamonds-4.0.0.1.recipe

didn't include the patch from previous version as they changed the source up to a point where I can't find the changes from the previous patchset, all config files are stored/created in ~/home/.rocksndiamonds

rocksndiamonds new recipe for 4.0.0.1

---

dev-libs/libsodium/libsodium-1.0.12.recipe

Reapplies the recently removed suffix, as libraries can be needed for a secondary architecture.

libsodium: reapply SECONDARY_ARCH suffix

---

app-editors/vim/patches/vim-8.0.0473.patchset
app-editors/vim/vim-8.0.0473.recipe

It makes https://github.com/haikuports/haikuports/pull/1210 outdated as it contains this patch already. Thanks @freddietilley !

vim: bump version, updated patchset

---

app-text/hunspell/hunspell-1.6.0.recipe

broken for x86_gcc2, one can nonetheless install hunspell-1.4.2 for x86_gcc2, which can eventually conflict

hunspell-1.6.0, fix recipe

---

sys-libs/mesa/mesa-17.0.3.recipe

The KHR/khrplatform.h header is required by libepoxy for running its testsuite. This commit also adds a
pkg-config entry for EGL, also used by libepoxy.

mesa: add pkg-config entry and missing header(s) for EGL

---

games-kids/tuxmath/patches/tuxmath-2.0.1.patchset
games-kids/tuxmath/tuxmath-2.0.1.recipe

Still haven't been able to disable fullscreen on start-up, otherwise working ok on gcc2h (x86), it can be launched from Terminal with "tuxmath-x86 -w" in windowed mode ...

TuxMath, bump version to the latest version

---

haiku-apps/lnlauncher/lnlauncher-1.1.2.recipe

Translations are working again, builds with gcc5 and on x86_64 are working now.

lnlauncher: various fixes

---

sys-libs/libexecinfo/libexecinfo-1.1.recipe

Swift uses this to support backtracing, but trying to build with libexecinfo support fails due to a broken symlink. This commit fixes this issue.

libexecinfo: fix symlink paths

---

media-gfx/sane_backends/sane_backends-1.0.24.recipe
media-gfx/sane_backends/sane_backends-1.0.25.recipe

This backend still wont be available by default, but it's easier
for SANE frontends developers to uncomment in dll.conf to load it
than having to rebuild their own sane_backends package...

sane_backends: Enable pnm backend build.

---

sys-devel/llvm/llvm-4.0.0.recipe
sys-devel/llvm/patches/clang-4.0.0.patchset

This commit solves issue #789 by enabling TLS support in clang by default. This is known to work on x86_64 by passing the -fPIC flag, but I haven't tested it on x86 yet.

clang: Enable thread-local storage in clang

---

dev-libs/libuv/libuv-1.12.0.recipe
dev-libs/libuv/patches/libuv-1.12.0.patchset

It needs platform specific implementation, so this commit disables it on every arch.

Libuv: update patchset, disable on every archs

---

dev-libs/unibilium/unibilium-1.2.0.recipe

Work in Progress.
Now i get : `undefined reference to`__stack_chk_fail_local'`
Help required.

WIP unibilium recipe

---

app-editors/vim/patches/vim-8.0.0599.patchset
app-editors/vim/vim-8.0.0599.recipe

No need to build a CLI and a GUI version as the GUI version already provides the CLI version.
Tested on x64 with GUI and in Terminal.

VIM: bump version, recipe cleanup, enable python, fix ruby

---

dev-libs/libdwarf/libdwarf-20170416.recipe
dev-libs/libdwarf/patches/libdwarf-20170416.patchset

Still broken, help wanted:
Warning: POLICY ERROR: "/packaging/libdwarf/bin/dwarfdump" needs library "libdwarf.so.1", but the package doesn't seem to declare that as a requirement

libdwarf: bump version

---

dev-libs/libgcrypt/libgcrypt-1.8.0.recipe
dev-libs/libgcrypt/patches/libgcrypt-1.8.0.patchset

for x86_gcc2 I'm getting "`__GNUC_PATCHLEVEL__' undeclared", it is to a change in globals.c as far as I could trace it, 1.7.8 still builds ok for x86_gcc2 .... could use some attention :)

libgcrypt, bump version

---

sys-libs/libedit/libedit-2015_03_21_3.1.recipe

This commit enables libedit to be built with support for wide characters. It is also required to support the integrated REPL in swift which uses the el_wgets symbol which was missing in libedit.

libedit: enable wide-character support

---

app-emulation/fuse/fuse-1.1.1.recipe
app-emulation/fuse/patches/fuse-1.1.1.patchset
app-emulation/libspectrum/libspectrum-1.1.1.recipe

libspectrum and fuse: Tested building on x86_64 - fine for libspectrum, FUSE needed patch to configure script. Added libgcrypt as dependency.

libspectrum and fuse: Build fixes for x86_64 and x86_gcc2

---

games-engines/scummvm/scummvm-1.9.0.recipe

I've played through some Full Throttle, Monkey Island 2 and 3 and Indiana Jones games (a bit of each). All seems just as stable as the gcc2 hybrid build.

scummvm: Removed 'untested' flag after testing with several games on x86_64

---

games-fps/chocolate-doom/chocolate_doom-2.2.1.recipe

Tested with Doom 1 and 2 WADs - works just the same as gcc2 hybrid

chocolate-doom: Enable x86_64 after testing

---

app-admin/keepassx/keepassx-2.0a6.recipe
app-admin/keepassx/patches/keepassx-2.0a6.patchset

Built and tested on x86_64 - just needed the stack protector flagged removed (or complains about libssp.so.0 being missing).

keepassx: Enable on x86_64 and remove stack protector flag

---

dev-lang/rust/rust-1.10.0.recipe
dev-lang/rust/rust-1.9.0.recipe

The recipe for 1.9.0 will build the full compiler suite for x86_gcc2,
and it will 'wrap' a binary stage0 compiler for x86_64.
The recipe for 1.10.0 is a complete build.
These recipes don't create the rust_runtime packages. This package
should be recreated at a later point, but we will need to think about
the package naming, as it will be very much possible to have various
runtime libraries running alongside each other.

Add rust recipes for 1.9.0 and 1.10.0 for both x86_gcc2 and x86_64

---

dev-lang/rust/rust-1.11.0.recipe

Note that this recipe depends in on an older version of binutils
(2.26.1), as the current version of binutils (version 2.28.1) has ld
crash in linking the libLTO.so library from the bundled llvm. This is,
by the way, the same on the recipe of llvm-3.8.1 in this repository.

rust: add recipe for rust-1.11.0

---

sys-libs/libexecinfo/libexecinfo-1.1.recipe

The devel package of libexecinfo_1.1-3 seemed to still install with a broken symlink and some packages that search for 'libexecinfo.so' will fail to do so. This commit fixes this issue.

libexecinfo: fix broken symlink in devel package.

---

media-libs/assimp/assimp-4.0.1.recipe

assimp, new recipe, wip

---

sys-libs/mesa/mesa-17.1.7.recipe
sys-libs/mesa/patches/mesa-17.1.7.patchset

Mesa for Unix platforms is usually built with autoconf instead of scons. This switch should help us to follow build system changes for other platforms more easily, it provides a pkgconfig file for egl, library versioning, etc..
One hack is the use of libglapi for both libGL and libEGL, which is forbidden for the autoconf build system, but was allowed in scons. For the time being I added Haiku as an exception.
This commit is probably not so clean for upstream, I only tested libGL on x86_64. 
Please review.

mesa: switch to autoconf.

---

app-crypt/gpgme/gpgme-1.9.0.recipe

gnupg can't be build for x86_gcc2 (requirement of gpgme)

gpgme, no structural changes, recipe cleanup

---

dev-lang/rust/rust-1.12.1.recipe

In response to the discussion of PR #1668
This fix was actually already employed in the recipe for 1.11.0, so instead of renaming binutils, let's do it again this way.

Rust 1.12.1: Specify the buildtools version

---

dev-lang/rust/patches/rust-1.13.0.patchset
dev-lang/rust/patches/rust-installer-1.13.0.patchset
dev-lang/rust/rust-1.13.0.recipe

The difference with the recipes for versions 1.9.0 through 1.12.1 is that
this one is based off the "official" rust sources, after Alexander
von Gluck integrated the existing patches and added some additional of his
own. The recipe uses some additional patches to fix the build system (and
some oversights). The complete patched source tree can be found at
https://github.com/nielx/rust
This can be applied after rust 1.12.1 builds successfully.

Rust: add recipe for rust 1.13.0

---

dev-lang/rust/patches/rust-1.14.0.patchset
dev-lang/rust/patches/rust-installer-1.14.0.patchset
dev-lang/rust/rust-1.14.0.recipe

This recipe is based on the official sources, but has some additional patches.
The tree with integrated patches can be found at https://github.com/nielx/rust

Rust: add recipe for 1.14.0

---

dev-libs/unibilium/unibilium-1.2.0.recipe

After building the unibilium package and deploying it, the unibilium_devel package deploy reports the following error message, and is unable to deploy:
After the changes seen in this PR, the devel package can be deployed.

Fixing unibilium recipe, the devel package requirement part

---

dev-lang/rust/patches/rust-1.15.1.patchset
dev-lang/rust/patches/rust-installer-1.15.1.patchset
dev-lang/rust/rust-1.15.1.recipe

The recipe is based on the official github sources, plus patches where
applicable. The tree including patches can be found at
https://github.com/nielx/rust

Rust: add recipe for 1.15.1

---

dev-cpp/yaml_cpp/yaml_cpp-0.5.3.recipe

I was building yaml_cpp for qutebrowser, and it wouldn't build because of the incorrect checksum in the recipe.

Fixing yaml_cpp checksum

---

dev-lang/swift_lang/patches/swift_lang-3.1.patchset
dev-lang/swift_lang/swift_lang-3.1.recipe

This port of Swift 3.1 will only work on x86_64 and requires installing llvm-4.0.0-2 because of this [commit](https://github.com/return/haikuports/commit/b6316842ed1d62ccb0a12d8f7353edea96e536bf). 
Further progress and documentation of the swift port can be found on the [swift-haiku-build](https://github.com/return/swift-haiku-build) repository.
What works so far:
* Running Swift programs through the interpreter. 
* Importing libraries. (Passing -sdk '/' to compiler or export SDKROOT="/")
* SIL/IR Code Generation.
* Emitting object code.
* Developer tools.
* Generating executables with swiftc
(UPDATE 18th June 2017):
Partial support for running swift programs via interpreter.
_(Removing some concurrency related code in the MetadataCache class, allows swift programs to run in the …

swift-lang: new recipe

---

dev-lang/rust/rust-1.15.1.recipe

Bump the version number to version 2.
Add the cargo command to the package. Rust's package management tool is now
included in the package. The rationale for inclusion versus external package
is that the cargo command is closely related to the version of the rustc
compiler, and with the future dependency of the rust build system on cargo
they are closely linked.

Rust: several changes to the 1.15.1 recipe

---

app-arch/unarr/unarr-1.0.0.recipe

As notified by selmf (thanks!), actual maintener, we were using obsolete source.
Enabled bz2, xz and zip support too.
Add PkgConfig support.
And now both static and shared libraries are availables.
This should fix #1723.

unarr: use upstream source

---

www-client/qutebrowser/qutebrowser-1.0.2.recipe

QuteBrowser is a web browser based on PyQt 5. It is able to use both QtWebKit and QtWebEngine.
On Haiku it uses only QtWebKit, because QtWebEngine is not available.
Minor changes were made by the maintainer for Haiku, based on my tests, so no external patches are required. It is also very actively developed with a large community.

QuteBrowser: add recipe for version 1.0.2

---

app-text/poppler/poppler-0.60.1.recipe

It seems perl is required: http://vmpkg.haiku-os.org/master/x86_64/logviewer.html?buildruns/382/builds/2533.log

Poppler: build fix

---

dev-libs/boehm_gc/boehm_gc-7.6.0.recipe

Fixes 'depcomp: No such file or directory' build errors in boehm_gc.

boehm_gc: disable dependency tracking

---

haiku-apps/yab_ide/yab_ide-2.2.8a.recipe

remove cmd:yab from BUILD_PREREQUIRES use the yab built from the source for the build.

fix build for buildbots

---

net-analyzer/iperf/iperf-2.0.9.recipe
net-analyzer/iperf/licenses/UIUC

Adding a recipe for iperf v2.0.9. 
iperf is a common network bandwidth testing tool especially for TCP. 
Was pretty easy to port to Haiku!

Add recipe for iperf-2.0.9

---

sci-libs/primegen/patches/primegen-0.97.patchset
sci-libs/primegen/primegen-0.97.recipe

primegen is a small, fast library to generate prime numbers in order.
The recipe added primegen to haikuports at `haikuports/sci-libs/primegen/`.
I intentionally chose to create a git repository since there are a large number of patches required... I hope this is OK.
Please let me know if anything is wrong!

Recipe for primegen 0.97

---

net-libs/mbedtls/mbedtls-2.6.0.recipe

mbed TLS (formerly known as PolarSSL) makes it trivially easy for developers to include cryptographic and SSL/TLS capabilities in their (embedded) products, facilitating this functionality with a minimal coding footprint.

mbedtls: add initial recipe for 2.6.0

---

dev-libs/openssl/openssl-1.0.2m.recipe
dev-libs/openssl/openssl11-1.1.0f.recipe

* ~~Move `cmd:` items to a new `_bin` sub-package.~~
* ~~Base packages openssl11 and openssl now only ship the libs.~~
* ~~Make `openssl11_{bin,devel}` conflict with `openssl_{bin,devel}`.~~
* ~~Skip installation of `lib{ssl,crypto}.so` symlinks in openssl11.~~
The changes detailed below allow to co-install the base packages of 1.0.2 and 1.1.0 (as well as their debuginfo). The _devel (or _man) packages cannot be co-installed.
* Define a debuginfo package for openssl11.
* Fix typo in call to defineDebugInfoPackage for openssl which was producing an incorrect debuginfo on 2nd arch.
* Also add `cmd:openssl{,-1.1}` to their debuginfo packages.
* Move `$docDir/html/man3` to openssl11_devel.
* Add a **`-1.1`** suffix to each `cmd:{openssl,c_rehash}` for openssl11 to allow the co-installation of …

openssl: allow co-installation of 1.0.2 and 1.1.0.

---

haiku-apps/bescreencapture/bescreencapture-2.3.recipe

Added recipe for BeScreenCapture 2.3.
The list of changes include:
In selection mode, add an hint to the user via text instructions on the screen
The selection can be moved after being selected
Added capture frame settings
Added clip duration when recording
If saving a frame fails, the application will now abort and report an error
Layout change: Moved most settings to the options tab
Adapted code to be able to use the Shortcuts preflet to control recording

Added recipe for BeScreenCapture 2.3

---

dev-libs/protobuf/protobuf-3.3.2.recipe

This fixes the following packaging issue:
mv: cannot stat '/packages/protobuf-3.3.2-5/.self/lib/libprotobuf_lite.*': No such file or directory
or
objcopy: '/packages/protobuf-3.3.2-5/.self/lib/libprotobuf_lite.so.13.0.2': No such file

dev-libs/protobuf: package the correct library

---

sci-mathematics/gmp_ecm/gmp_ecm-7.0.4.recipe
sci-mathematics/msieve/msieve-1.53.recipe
sci-mathematics/msieve/patches/msieve-1.53.patchset

Changes to msieve:
- Convert msieve's `printf` format specifiers to their architecture-independent counterpart
- Fixed a small pointer bug: `gzFile*` used instead of `gzFile`
- Add Haiku support:
- Add `HAIKU` switch to Makefile: disable `-ldl` on set
- Disable `ffpoly.c` inline assembly (they won't build, and @waddlesplash said they're not *that* optimized anyway)
- Implemented `set_idle_priority()` for Haiku: set `B_IDLE_PRIORITY` for the calling team

Add sci-mathematics/msieve

---

app-crypt/qca/qca-2.1.3.recipe
app-crypt/rhash/rhash-1.3.5.recipe
app-editors/retext/retext-7.0.1.recipe
app-i18n/mozc/mozc-2.20.2677.102.recipe
app-text/podofo/podofo-0.9.5.recipe
dev-lang/spidermonkey/spidermonkey-1.8.5.recipe
dev-lang/tcc/patches/tcc-0.9.26.patchset
dev-lang/tcc/tcc-0.9.26.recipe
dev-lang/yasm/yasm-1.3.0.recipe
dev-libs/glib/glib2-2.54.2.recipe
dev-libs/jsoncpp/jsoncpp-1.8.3.recipe
dev-libs/libtommath/libtommath-1.0.1.recipe
dev-libs/libxslt/libxslt-1.1.32.recipe
dev-libs/libyajl/libyajl-2.1.0.recipe
dev-libs/zziplib/patches/zziplib-0.13.67.patchset
dev-libs/zziplib/zziplib-0.13.67.recipe
dev-python/pyqt/pyqt-5.9.1.recipe
sys-devel/flex/flex-2.6.4.recipe

This PR add `TEST()` to various ports, with fixes to a few ports I bumped into while running `TEST()`
- app-editors/retext: tests operate on desktop, users should leave their device unattended during test
- app-i18n/mozc: most passes, following fails: `ipc_test`, `prediction_test`, `renderer_server_test`, `session_server_test`. [Log file](https://ghostbin.com/paste/xwsw8)
- dev-lang/spidermonkey: multiple tests failed, all `SIGSEGV`
- dev-lang/tcc: currently broken on Haiku due to [bug#13847](https://dev.haiku-os.org/ticket/13847)
- dev-libs/glib2:
- tests won't build on `x86_gcc2`, `gcc2` lacks `-Wstrict-aliasing=2` 
- most passes, some fails: [log](https://ghostbin.com/paste/47uu9)

Add TEST() to various ports

---

games-action/terrarium/terrarium-0.1.8.recipe

Added [Terrarium](https://github.com/hydren/terrarium)'s recipe, a free and open source Terraria clone game. The recipe is based on the [building instructions](https://github.com/hydren/terrarium/blob/master/BUILDING.md) from the repo and uses SDL2.
Please correct any mistakes in the recipe, thanks!

Terrarium: new recipe

---

dev-libs/libbase58/libbase58-0.1.4.recipe
net-libs/libblkmaker/libblkmaker-0.5.3.recipe

Created recipes for libblkmaker and libbase58.
Both required patches to work with gcc2, largely involving moving declarations and replacing variable-sized arrays with malloc/free.

Add recipes for libblkmaker and libbase58

---

haiku-apps/internalmidi/internalmidi-1.0.recipe

Create recipe for [InternalMIDI](https://github.com/HaikuArchives/InternalMIDI), a MIDI (MidiKit2) node for the internal General MIDI synthesizer of BeOS/Haiku.

InternalMIDI: new recipe

---

haiku-apps/pecobeat/patches/pecobeat-1.0.patchset
haiku-apps/pecobeat/pecobeat-1.0.recipe

Added PecoBeat, a MIDI drum computer for Haiku. Completes #539.
I also patched a printf error (not including stdio.h) and some include path errors.

PecoBeat: new recipe

---

app-crypt/codecrypt/codecrypt-1.8.recipe
dev-libs/crypto++/crypto++-5.6.5.recipe
dev-libs/crypto++/patches/crypto++-5.6.5.patchset

Changes to crypto++:
- Make the build system use more reliable way to detect architecture (this fixes secondary arch, ~~may also fixes x86_gcc2 but untested~~)
- Package a pkg-config file. This file is needed for codecrypt to build
- Install the versioned version of crypto++ instead of doing the rename hack

app-crypt/codecrypt: add port

---

app-crypt/minisign/licenses/ISC
app-crypt/minisign/minisign-0.7.recipe
app-crypt/minisign/patches/minisign-0.7.patchset

Changes to minisign (upstreamed at jedisct1/minisign#36):
- Use unix codepath for Haiku

app-crypt/minisign: add port

---

haiku-apps/photograbber/patches/photograbber-2.3.patchset
haiku-apps/photograbber/photograbber-2.3.recipe

Builds ok for x86_gcc2 x86 and x86_64 (just didn't put in x86 in the recipe) :)

photograbber, fix recipe, bump version

---

app-text/wordgrinder/wordgrinder-0.7.1.recipe

help needed ... I need to manually switch of some ninja settings, but it is only created after make in the OBJDIR directory ... 
build all: phony bin/wordgrinder.1 bin/wordgrinder-lua-curses-release-stripped  test-lua-curses-debug
Needs to be replaced by:
build all: phony bin/wordgrinder.1 bin/wordgrinder-lua-curses-release-stripped
Just can't find out where it takes the settings from ... 
After removing test-lua-curses-debug, the build works ok ...

wordgrinder, fix build

---

app-emulation/aqemu/patches/aqemu-0.9.2.patchset

This pull request fixes total/free memory detection on Haiku. AQEMU still haven't worked properly though :/ (as QEMU is still segfaulting)
This pull request fixes #1850.

app-emulation/aqemu: fix total/free memory detection

---

media-video/mplayer/mplayer-1.3.0.recipe

Binary is in $prefix/bin on secondary arch, instead of $binDir

Install fix for gcc2h

---

app-arch/lrzip/lrzip-0.631.recipe
app-arch/lrzip/patches/lrzip-0.631.patchset

~~Currently won't work as haiku lacks these POSIX functions: [`setpriority()`][0], [`mlock()`][1], [`munlock()`][1]~~ Replaced with no-ops
Changes done to lrzip:
- Moved settings folder to the correct location using [`find_directory()`][2]
- Implemented [`setpriority()`][0], [`mlock()`][1], [`munlock()`][1] as no-ops
~~**NOT TESTED**: x86 secondary arch~~
Known issues:
- x86 secondary arch: hang upon compressing data from stdin. This is traced to be an `malloc()` hung up, so high chances that this is an Haiku bug. To reproduce, run: `seq 1 1000 | lrz > testfile.lrz`
[0]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/setpriority.html
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/functions/mlock.html
[2]: …

app-arch/lrzip: add port

---

app-crypt/johntheripper/johntheripper-1.8.0.recipe
app-crypt/johntheripper/licenses/John the Ripper
app-crypt/johntheripper/patches/johntheripper-1.8.0-upstreamed.patchset
app-crypt/johntheripper/patches/johntheripper-1.8.0.patchset

Changes done to JtR:
- Apply upstream patch to fix non-SSE compilation on x86 and gcc 5 compilation on x86_64 (thanks @bach5000 for the pointer)
- Use set_thread_priority for Haiku (upstreamed)
- Disable SIMD codepath for NT format plugin on Haiku x86_64 as the associated assembly is not PIC-compatible
- Make JtR expand "~config", "~data" to user home settings folder and var folder
- Allow changes to default paths on compile time
Known issues:
~~- JtR [won't build](https://0bin.net/paste/fHQN9wP2nozRpSco#jkq10zu3BVsSuxiHLkXjQX52qlwSiYathG9K3oLbMBh) on x86_64. I would appreciate help on this as I'm stuck now~~
Updates:
~~- JtR **still** won't build, except with 1 less issue now, updated log above~~

app-crypt/johntheripper: add port

---

app-text/htmltidy/tidy57-5.7.0~git.recipe

Build for gcc2 is broken due to unbalanced #endif's and parse errors ...

htmltidy, bump version, fix build

---

app-text/antiword/antiword-0.37.recipe
games-arcade/alienblaster/alienblaster-1.1.0.recipe
games-puzzle/lpairs/lpairs-1.0.4.recipe
haiku-apps/bdhcalc/bdhcalc-1.1.recipe
haiku-apps/helios/helios-1.7.2.recipe
haiku-apps/ppviewer/ppviewer-1.0.0.recipe

I have tested 6 _x86_64_ untested recipes (?x86_64). Here's the result:
1. [haiku-apps/helios-1.7.2](https://github.com/haikuports/haikuports/blob/master/haiku-apps/helios/helios-1.7.2.recipe) - [Failed](https://github.com/haikuports/haikuports/issues/1979)
2. [haiku-apps/ppviewer-1.0.0](https://github.com/haikuports/haikuports/blob/master/haiku-apps/ppviewer/ppviewer-1.0.0.recipe) - [Failed](https://github.com/haikuports/haikuports/issues/1980)
3. [app-text/antiword-0.37](https://github.com/haikuports/haikuports/blob/master/app-text/antiword/antiword-0.37.recipe) - [Success](https://pastebin.com/639Vb6HG)
4. [games-arcade/alienblaster-1.1.0](https://github.com/haikuports/haikuports/blob/master/games-arcade/alienblaster/alienblaster-1.1.0.recipe) - [Success](https://pastebin.com/VkjDpTCX) …

Testing untested recipes for x86_64

---

app-crypt/mcrypt/mcrypt-2.6.8.recipe
app-crypt/mcrypt/mcrypt.OptionalPackageDescription

Add recipe for [mcrypt](http://mcrypt.sourceforge.net/), an enhanced replacement for the old crypt command.

mcrypt: new recipe

---

app-misc/jigdo/jigdo-0.7.3.recipe
app-misc/jigdo/patches/jigdo-0.7.3.patchset

Creates recipe for [jigdo](http://atterer.org/jigdo/), a tool designed to ease the distribution of very large files over the internet, for example CD or DVD images.

jigdo: new recipe

---

app-text/libqxp/libqxp-0.0.1.recipe

Create recipe for [libqxp](https://wiki.documentfoundation.org/DLP/Libraries/libqxp), a library that parses the file format of QuarkXPress documents.

libqxp: new recipe

---

dev-db/sqlcipher/patches/sqlcipher-3.4.2.patchset
dev-db/sqlcipher/sqlcipher-3.4.2.recipe

Changes to sqlcipher:
- Fix build when `OMIT_MEMLOCK` is defined but not `SQLITE_OMIT_WAL`
- Fix tests for Haiku
**NOTE:** I permit anyone to upstream my changes without asking. sqlcipher requires it's contributor to sign an CLA, which I don't want to.

dev-db/sqlcipher: new recipe

---

dev-libs/check/check-0.11.0.recipe
dev-libs/check/check-0.9.13.recipe
dev-libs/check/check-0.9.14.recipe

~Until now, check_86, which builds fine on x86_gcc2, had a runtime dependency on check_common, which is the arch-independent subpackage which can only be built when check is built on x86_gcc2 primary arch.
But since the latter no longuer builds for check 0.11.0, there was no way to obtain check_common on x86_gcc2 and meet check_x86's requirement when installing it.
The workaround for this issue is to simply stop creating the check_common subpackage when building on x86_gcc2. All contents of check_common are now part of check_x86.~
This is required because check 0.11.0 no longer builds on x86_gcc2 primary arch, so the arch-independent check_common could not be built on x86_gcc2, hence preventing the installation of check_x86.

check: unsplit check_common.

---

sys-apps/util-linux/patches/util_linux-2.31.1.patchset
sys-apps/util-linux/util_linux-2.31.1.recipe

* Use the commandBinDir "trick" to fix the policy error.
* Mark x86_gcc2 as broken because a gcc2 patch would be required.
* ~Drop the call to `autogen.sh`.~ (Package contents are identical.) _[Keeping the call to `autogen.sh` because it might be needed if we ever choose to enable some programs]_
* ~x86 secondary arch builds are hanging on two configure tests which crash. Dropping a paragraph in Makefile.am eliminates these crashes and has no impact on the resulting runtimes.~ _[Thanks @alaviss for the hint on passing "have_scanf_alloc_modifier=no" to configure.]_
* On x86, pass "have_scanf_alloc_modifier=no" to configure to skip a conftest which crashes and makes configure hang.
* Switch to tar.xz.

util-linux: bump to 2.31.1, fix policy error in 2nd arch.

---

app-arch/zstd/patches/zstd-1.3.3.patchset
app-arch/zstd/zstd-1.3.3.recipe

Also remove `cmd:gzstd` from `PROVIDES_bin` as it no longer exists.

zstd: bump to 1.3.3, add debuginfo, drop HTML manual.

---

kde-misc/kdiff3/kdiff3-0.9.98.recipe
kde-misc/kdiff3/patches/kdiff3-0.9.98.patchset

... to work. Previously, it only worked without the `--no-git-repo`.
* Shrink the patch a bit by dropping an unneeded indentation change.
* Use `commandBinDir` & `commandSuffix` to move kdiff3 to `$prefix/bin/`.
* Switch `SOURCE_URI` to https and fix `COPYRIGHT`.

kdiff3: fix whitespace issue in patch to allow hp --no-git-repo

---

net-p2p/hefur/hefur-0.6.recipe
net-p2p/hefur/patches/hefur-0.6.patchset
net-p2p/hefur/patches/mimosa-22137aa7f90b0f90bc48172d964deb82d6e4f2f9.patchset

The last PR as part of GCI 2017
Changes to hefur:
- Make packaging easier, also fixes linking on Haiku (https://github.com/abique/hefur/pull/26)
Changes to mimosa:
- Make mimosa works on Haiku (https://github.com/abique/mimosa/pull/5)
Requires: [Ticket#13960](https://dev.haiku-os.org/ticket/13960)
Not tested on x86 secondary architecture due to problems compiling Haiku x86_gcc2 :disappointed:

net-p2p/hefur: new recipe

---

x11-libs/libxfixes/libxfixes-5.0.3.recipe
x11-libs/libxfixes/licenses/libXfixes

* Mark x86_gcc2 as tested.
* Fix `HOMEPAGE`, `COPYRIGHT`, `LICENSE`.
* Add the project's `COPYING` file as `licenses/libXfixes`.
* Sort `BUILD_PREREQUIRES`, add recommended `cmd:` lines.
* Add missing `make $jobArgs` in `BUILD()` to build before `INSTALL()`.
* Move man3 to devel.
* Add `README`.

x11-libs/libXfixes: add debuginfo package.

---

x11-libs/libxrender/libxrender-0.9.10.recipe
x11-libs/libxrender/licenses/libXrender

* Mark x86_64 as tested.
* Fix `COPYRIGHT` years and `LICENSE`.
* Add the project's `COPYING` file as `licenses/libXrender`.
* Add `README` to `$docDir`.
* Move `libXrender.txt` to `$developDocDir`.

x11-libs/libXrender: enable x86_gcc2.

---

sys-block/parted/parted-3.2.recipe

* Mark as untested on all architectures, as parted does not seem to be working correctly on Haiku at the moment.
* Switch `SOURCE_URI` to `ftpmirror.gnu.org`, using https.
* Drop libtool files as well as the unneeded `$infoDir/dir`.

sys-block/parted: add debuginfo package, mark as untested.

---

sys-block/sg3_utils/patches/sg3_utils-1.42.patchset
sys-block/sg3_utils/sg3_utils-1.42.recipe

Changes to sg3_utils:
- Added Haiku support
I would like to have some input for [my fork](https://github.com/alaviss/sg3_utils/tree/haiku) before upstreaming this patch.
**EDIT:** PR made: https://github.com/hreinecke/sg3_utils/pull/24
If you happens to have an SCSI-capable device (they could be found in `/dev/disk/scsi`), please help me test various utilities provided by this package.
Thanks

sys-block/sg3_utils: new recipe

---

dev-libs/geoip/geoip-1.6.12.recipe
dev-libs/geoip/patches/geoip-1.6.12.patchset
dev-libs/geoip/patches/geoipupdate-r6.patchset

Upstream ships a tiny `GeoIP.dat` since 1.6.10 so we can drop the optional steps in `TEST()`.
There seems to be a bug in curl (7.58.0 or earlier) which did not exist in curl 7.50.3 when the patch for geoipupdate.sh was added.
This happens when the script tries to update an up-to-date GeoIP database file. It looks like curl's `--time-cond` option forgets to instruct `--remote-time` to skip its job if a `304 Not Modified` is received.
If the output file exists then this does not get noticed.
But if this file does not exist then curl complains with an unwanted `Failed to set filetime ... on outfile` warning.
Trying to fix this issue in our script would require to redirect curl's stderr to /dev/null (or creating a temporary (empty) file to make curl happy) but doing so would not be a good …

dev-libs/GeoIP: bump to 1.6.12, add debuginfo, shrink TEST().

---

app-i18n/mozc/mozc-2.23.2785.102.1.recipe

lib:libprotobuf is required to run.

mozc: Add libprotobuf as dependent lib

---

dev-go/go-md2man/go_md2man-1.0.7.recipe

This recipe is a dependency of #2078.

go_md2man: new recipe

---

net-misc/youtube_dl/licenses/Unlicense
net-misc/youtube_dl/youtube_dl-2018.02.08.recipe
net-misc/youtube_dl/youtube_dl-2018.02.11.recipe

Changes:
* Bump to 2018.02.11.
* Add man page and bash/fish/zsh completion data.
* Fix/update `LICENSE` & `COPYRIGHT`.
* Drop `cmd:ffmpeg` from `REQUIRES` as ffmpeg is not required but just recommended. youtube-dl only needs ffmpeg if the user downloads DASH video+audio contents and wants these to be combined together.
* Add _python and _python3 subpackages.
Contents:
* `youtube_dl` ships the `youtube-dl` monolithic python2.7 script, as well as the man page and the bash/fish/zsh completion data.
* `youtube_dl_python` ships the `youtube-dl-python` python2.7 script.
* `youtube_dl_python3` ships the `youtube-dl-python3` python3.6 script.
Remarks:    
* The base package, youtube_dl, does not depend on any of the python subpackages.
* The youtube_dl_python and youtube_dl_python3 packages do …

youtube-dl: add man page, completion data, python subpackages

---

net-misc/youtube_dl/youtube_dl-2018.03.10.recipe

"make offlinetest" will fail because flake8 is not available.

youtube-dl: bump to 2018.03.10, add (unusable) TEST().

---

dev-libs/libmspack/libmspack-0.6~alpha.recipe

* Add `cmd:` entries for the runtimes added in this release.
* Call `cabd_test` in `TEST()`. (`ALL 194 TESTS PASSED.`)
* Add patch from Gentoo to fix `cabd_test`.
* Compute arguments being passed to `defineDebugInfoPackage`.

dev-libs/libmspack: bump to 0.6alpha, add debuginfo.

---

net-libs/libpsl/libpsl-0.20.1.recipe
net-libs/libpsl/patches/libpsl-0.20.1.patchset

The tests do not build with gcc2 but psl seems to work fine.

libpsl: bump to 0.20.1, add tiny gcc2 patch, enable x86_gcc2.

---

net-misc/curl/curl-7.59.0.recipe

Added comments after the definition of `TEST_PREREQUIRES`. They should be removed if haikuports/haikuporter/issues/151 is implemented.

curl: bump to 7.59.0, depend on lib{brotlidec,idn2,psl}.

---

x11-libs/libxft/libxft-2.3.2.recipe
x11-libs/libxft/licenses/libXft

I need Xft as a dependency for a complex package that I'm trying to port. I'm aware that there's no X11 server on Haiku, but nonetheless Xft seems to compile.

Add libxft-2.3.2 recipe

---

x11-proto/scrnsaverproto/licenses/scrnsaverproto
x11-proto/scrnsaverproto/scrnsaverproto-1.2.2.recipe

* `SOURCE_URI`: switch to https and to tar.bz2.
* Sort `BUILD_PREREQUIRES`.
* Drop unneeded call to libtoolize.
* Remove empty `$libDir` on secondary arch builds.

scrnsaverproto: Add custom LICENSE, install README.

---

app-arch/zstd/patches/zstd-1.3.4-gcc2.patchset
app-arch/zstd/patches/zstd-1.3.4.patchset
app-arch/zstd/zstd-1.3.4.recipe

Also drop the debuginfo package since we are not compiling with `-g`.

zstd: bump to 1.3.4, enable x86_gcc2 with a few tiny patches.

---

dev-vcs/git/git-2.17.0.recipe
dev-vcs/git/patches/git-2.17.0.patchset

~Also comment out the dependency of `git_svn` on the missing `svn_alien` in order to be able to use haikuporter's `--test` feature after it was taught to examine the `TEST_REQUIRES` variable.~

git: add recipe for 2.17.0 but mark it as untested.

---

dev-libs/atf/atf-0.21.recipe
dev-libs/atf/patches/atf-0.21.patchset
dev-lua/lutok/lutok-0.4.recipe
dev-util/kyua/kyua-0.13.recipe
dev-util/kyua/patches/kyua-0.13.patchset
dev-util/pkgconf/licenses/ISC
dev-util/pkgconf/patches/pkgconf-1.4.2.patchset
dev-util/pkgconf/pkgconf-1.4.2.recipe

| package | arch | status |
| --- | --- | --- |
| dev-libs/atf | x86_gcc2 | `Test cases: 319 total, 7 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-libs/atf | x86_64 | `Test cases: 319 total, 7 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-lua/lutok | x86_gcc2 | `Test cases: 101 total, 4 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-lua/lutok | x86_64 | `Test cases: 101 total, 4 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-util/pkgconf | x86_gcc2 | `Test cases: 109 total, 0 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-util/pkgconf | x86_64 | `Test cases: 109 total, 0 skipped, 0 expected failures, 0 broken, 0 failed` |
| dev-util/kyua | x86_gcc2 | `Test cases: 1215 total, 41 skipped, 4 expected …

dev-util/pkgconf: new recipe

---

sys-devel/lemon/lemon-1.0~src.recipe
sys-devel/lemon/licenses/SQLite

renamed the file to 1.0~src as "lemon -x" reports version 1.0 (comments welcome)
the template lempar.c is included but I'm not sure where it should be installed (yet)

lemon, revive old bep file

---

dev-libs/libsigc++/libsigc++3-2.99.10.recipe

~These changes will require a revbump for:~
* ~`media-libs/paragui/paragui-1.1.8.recipe` (it needs `lib:libsigc_1.2`)~
* ~`dev-cpp/glibmm/glibmm-2.57.1.recipe` (it needs `lib:libsigc_3.0`)~
* ~`net-p2p/rtorrent/rtorrent-0.9.6.recipe` (it needs `lib:libsigc_2.0`)~

libsigc++ (3.0): add CONFLICTS_devel.

---

media-libs/libvpx/libvpx-1.7.0.recipe
media-libs/libvpx/patches/libvpx-1.7.0.patchset

It is safe to drop `libvpx4-1.6.1` because no package is using it at the moment: `games-fps/eduke32`, `media-libs/{gd,gst_plugins_good}`, `media-video/{ffmpeg,handbrake}` and `sci-visualization/gnuplot` are all using `libvpx3-1.5.0`.
Co-authored-by: @extrowerk

libvpx: bump to 1.7.0.

---

media-libs/libvpx/libvpx-1.0.0.recipe
media-libs/libvpx/libvpx-1.7.0.recipe
media-libs/libvpx/libvpx3-1.5.0.recipe

This is required on x86_gcc2 because `cmd:vpx{dec,enc}` are currently provided by both `libvpx-1.0.0` and `libvpx_x86-1.7.0`. Moving these runtimes to a _bin subpackage and adding the appropriate conflicts allows to co-install all the base packages.
Also, for `libvpx3-1.5.0`, don't remove the runtimes on 2nd arch.

libvpx: move the runtimes to a subpackage.

---

app-shells/dash/dash-0.5.10.2.recipe

You will need to delete `download/dash-0.5.10-dumb-echo.patch` before building dash `0.5.10.2` if you downloaded it for building `0.5.10`. That's because there was a typo in the patch.

dash: bump to 0.5.10.2, add another patch from Gentoo.

---

dev-util/byacc/byacc-20180510.recipe

Running the tests with "make check" fails, same thing for the older recipe (also checked for x86)

byacc, bump version

---

sys-apps/util-linux/patches/util_linux-2.32.patchset
sys-apps/util-linux/util_linux-2.32.recipe

~Also build blkid, hexdump and uuidgen.~
Also build blkid, fdisk, hexdump and uuidgen, but put fdisk in a subpackage, marked as untested, as the geometry autodetection is not working, so the default values are not useful at all.
fdisk is working fine but it does not know how to inform Haiku that a partition table was modified. Workaround: reboot.
TODO: teach fdisk and partprobe how to talk to Haiku's kernel.

util-linux: bump to 2.32, build lib{blkid,fdisk,uuid}.

---

dev-lang/python/patches/python3_x86-3.6.3.patchset
dev-lang/python/python3-3.6.3.recipe

#2558 
append method does not exist for strings in python

python3: fix #2558 'str' has no attribute 'append'

---

app-arch/bzip2/bzip2-1.0.6.recipe
app-arch/bzip2/patches/bzip2-1.0.6.patchset

... instead of making copies of bzip2.
Also, install `{bzcmp,bzegrep,bzfgrep,bzless}` using relative symlinks.

bzip2: add debuginfo, install {bunzip2,bzcat} using symlinks

---

sys-apps/util-linux/util_linux-2.32.recipe

~util-linux: Do not define `*ARCHITECTURES_fdisk` as their content upsets the build servers.~
util-linux: fix `INSTALL` when `ALLOW_UNTESTED=no`
* While at it, do not export `CFLAGS` and `LDFLAGS`. Instead, pass `CPPFLAGS` and `LDFLAGS` to both `autogen.sh` and `configure`.
* Now that we don't override the project's default `CFLAGS` anymore we can add the debuginfo package.
**Warning:** If you call haikuporter after the recipe was last modified and then change `ALLOW_UNTESTED` to `yes`, the `.DependencyInfo` file for the fdisk subpackage will be missing.
Workaround: touch the recipe before calling haikuporter. Of course, this is required only once, that is, if you have recently changed `ALLOW_UNTESTED` to `yes`.

util-linux: fix INSTALL when ALLOW_UNTESTED=no

---

games-emulation/retroarch/retroarch-1.7.3.recipe

Title says all.
For now QT frontend interface not enabled because of Issue https://github.com/haikuports/haikuports/issues/2484

retroarch: bump to 1.7.3

---

app-shells/bash/bash-4.4.023.recipe

Avoid `../../sources-$i/` and, instead, use `\$sourceDir$i/` with `eval`.

bash: bump to 4.4.023, avoid hardcoded paths in PATCH().

---

app-office/libreoffice/libreoffice-6.2.0.0~git.recipe
app-text/libepubgen/libepubgen-0.1.1.recipe

* Drop `lib:libcppunit` from `REQUIRES` as it is not needed.
* `lib:librevenge_{stream,generators}` do not seem to be needed, but we can keep them, since `lib:librevenge` already pulls `librevenge`.
* Add `libxml2` because `libepubgen` now needs it.
* Sort `{BUILD_,}REQUIRES`.
* Switch `SOURCE_URI` to `tar.xz`.

libepubgen: bump to 0.1.1, depend on libxml2, add debuginfo.

---

dev-util/ragel/ragel-7.0.0.10.recipe

Unlike ragel `6.9`, which builds on x86_gcc2 primary arch, `7.0.0.10` `BUILD_REQUIRES` `devel:libcolm` which is not available on x86_gcc2. We therefore need to keep `6.9` for x86_gcc2.
So, in order to allow x86_gcc2 hybrid to be able to activate both `ragel-6.9` and `ragel_x86-7.0.0.10`, we cannot install `cmd:ragel` in `$commandBinDir`; we need to install it in `$binDir`.
Minor change: drop the call to autoreconf as it is not needed.

ragel: Mark as broken on x86_gcc2, drop commandBinDir.

---

app-office/libreoffice/libreoffice-6.2.0.0~git.recipe

LibreOffice deserves a few more lines of description. :)
Taken from their website.
Remove full-stop at the end of COPYRIGHT.

libreoffice: add to description

---

app-office/libreoffice/libreoffice-6.2.0.0~git.recipe

* Depend on `libboost* >= 1.65.0` as suggested by @kallisti5 in #2657.
* Add missing `devel:liboost_*` to `BUILD_REQUIRES`.
* Do not use `--with-distro=LibreOfficeHaiku` but, instead, copy upstream's `distro-configs/LibreOfficeHaiku.conf` to the recipe.
* Add `--with-system-libepubgen` to the config options.

LibreOffice: fix build on secondary arch. Minor changes.

---

net-libs/mbedtls/mbedtls-2.10.0.recipe
net-libs/mbedtls/patches/mbedtls-2.10.0.patchset

* Creating the debuginfo package was not appropriate because `-g` is not being passed to the compiler. Bye `defineDebugInfoPackage`!
* Fix the shebang line of all perl scripts which use `/usr/bin/perl` because one of the scripts is called at the end of the build.
* Add a patchset to fix a wrapper script which assumed incorrect paths for 2 runtimes.

mbedtls: bump to 2.10.0, drop debuginfo package.

---

dev-libs/orcus/orcus-0.13.4.recipe

* Lock to the same minimum boost version as LibreOffice.
* Drop `$secondaryArchSuffix` after `devel:mdds` in `BUILD_REQUIRES`.
* Switch `SOURCE_URI` to `tar.xz` & https.

orcus: bump to 0.13.4, depend on boost >= 1.65.0.

---

media-libs/rubberband/patches/rubberband-1.8.2.patchset
media-libs/rubberband/rubberband-1.8.2.recipe

* Add `commandSuffix` and `relativeCommandBinDir`.
* Update the `sed` command in `PATCH()`, mostly `s/@prefix@/$(PREFIX)/`, and also make `make install` check if `librubberband-jni.so` exists before trying to install it. (We need `javac` to build it.)

rubberband: bump to 1.8.2, add debuginfo.

---

app-text/unrtf/unrtf-0.21.9.recipe
media-libs/lcms/lcms-2.9.recipe
media-sound/libopenmpt/libopenmpt-0.2.7386~beta20.3.recipe
media-sound/mpg321/mpg321-0.3.2.recipe
media-video/dvdauthor/dvdauthor-0.7.2.recipe

Adding `commandSuffix` is neutral for all architectures, except for x86 secondary arch on a x86_64/x86 hybrid system, which is not yet available, so we can keep `REVISION` unchanged.

unrtf, lcms, libopenmpt, mpg321, dvdauthor: add commandSuffix.

---

www-servers/lighttpd/lighttpd-1.4.49.recipe

* The `lib:mod_*` in `PROVIDES*` were missing a `$secondaryArchSuffix`.
* Use `"$(getPackagePrefix mod_geoip)"` in `defineDebugInfoPackage`.
* Do not use getPackagePrefix for now, because `getPackagePrefix` makes our scripts on travis-ci.org complain:
```
Checking ports of: lighttpd-1.4.49
lighttpd-1.4.49 [www-servers]
packageEntries: error: "mod_geoip" doesn't seem to be
a valid package suffix.
```
So, instead, use a little hack.

lighttpd: fix PROVIDES*, add debuginfo & commandSuffix.

---

app-cdr/uif2iso/uif2iso-0.1.7c.recipe

Keep `REVISION` unchanged because this is a neutral change for all existing arches. The sole purpose of this change is to make this recipe ready for x86_64/x86 hybrid, as explained in #2690.

uif2iso: add commandSuffix, rework INSTALL.

---

app-pda/libusbmuxd/libusbmuxd-1.0.10.recipe

* `BUILD` was no longer working. We could have replaced `automake` by `automake --add-missing` but it was easier to switch to `autoreconf`.
* Switch `HOMEPAGE` and `SOURCE_URI` to https.

libusbmuxd: use autoreconf, add debuginfo & commandSuffix.

---

games-emulation/reicast_libretro/reicast_libretro-r6_20180711.recipe

There's been a lot of progress made on the Reicast core in the past two months, with SEGA Naomi and Sammy Atomiswave support being added.

reicast_libretro: bump to current git version

---

haiku-apps/bescreencapture/bescreencapture-2.3.3.recipe

Update BeScreenCapture to version 2.3.3.
- Fix build with recent compilers.
- Fix unstoppable capture thread on full-disk conditions.
- Disable controls when recording to avoid possible problems.
- Improved error messages.
- Improved drawing of the deskbar replicant.

Add recipe for BeScreenCapture 2.3.3

---

games-emulation/vice/patches/vice-3.2.patchset
games-emulation/vice/vice-3.2.recipe

From their website:
``
This release marks the end of the legacy ports (native Amiga, BeOS/Haiku, OS/2, DOS, Xaw/Gnome2/Gnome3, Cocoa and Windows) ports, and we will be switching to SDL1/2 and *nix/Windows/OSX native GTK3 ports for all future releases.
``

vice, bump version

---

x11-libs/libice/libice-1.0.9.recipe

Should we use "lib:libICE" or "lib:libice" here?

libice, bump revision after changes to util-macros and xorgproto

---

dev-lang/rust/patches/rust-1.28.0.patchset
dev-lang/rust/rust-1.28.0.recipe
dev-lang/rust_bin/rust_bin-1.28.0.recipe

The source based version is now based on the official source tarball.

Rust: add recipe for 1.28.0

---

sci-mathematics/amath/amath-1.8.5.recipe

Changes since 1.8.3
- Fix build on compilers with broken endian detection.
- Ignore casing in hexadecimal numbers.

Update sci-mathematics/amath to 1.8.5

---

media-gfx/drawpile/drawpile-2.0.10.recipe

Drawpile works on Haiku, still a wip.

drawpile: new recipe

---

sys-devel/llvm/llvm-6.0.1.recipe
sys-devel/llvm/patches/clang-6.0.1.patchset
sys-devel/llvm/patches/llvm-6.0.1.patchset

This supersedes PR (#2298) and adds support for running the LLVM test-suite. Tested on hrev52316 x86_64 with 15 tests failing (2 tests timed out) and I posted a [short](https://gist.githubusercontent.com/return/aecfbb3ae1f3470e5816e1e948d5a192/raw/6d52cbd37ea7fd738e88ccc8a51dd75f04acb79e/llvm-6.0.1-tests-haiku-x86_64.txt) and a [verbose summary](https://gist.githubusercontent.com/return/d8bcaa8500d53b47049af99815c18951/raw/0dadd2e113ca69b0173e1eb7d310154a11963627/llvm-6.0.1-tests-haiku-x86_64-long.txt) of them.  
Please add a 'wip-no-merge' on this. x86 and mesa still remains untested.

[WIP] llvm: bump version to 6.0.1 and add tests.

---

app-shells/command_not_found/command_not_found-0.0.1~git.recipe

Moved the script to `dataDir`, this will make sure the script is removed after the package is deactivated.
Users may override the handle by placing appropriate files in /etc/profile.d
~~Untested, but should work.~~

app-shells/command_not_found: move profile script

---

games-simulation/simutrans/simutrans-120.2.2.recipe
games-simulation/simutrans/simutrans-120.3~nightly.recipe
games-simulation/simutrans_pak128/simutrans_pak128-2.7.recipe
games-simulation/simutrans_pak128/simutrans_pak128-2.7~nightly.recipe
games-simulation/simutrans_pak64/simutrans_pak64-120.2.recipe
games-simulation/simutrans_pak64/simutrans_pak64-120.3~nightly.recipe
games-util/makeobj/makeobj-60.0.recipe
games-util/makeobj/makeobj-60.1~nightly.recipe

Any ideas how to use "secure" source files? Is there a way to get tarballs from sourceforge for a certain revision? As far as I can tell, snapshots must be requested before they are added for a limited time (probably not more than a day).

simutrans and related packages updated to new version 120.2

---

media-libs/fdk-aac/fdk_aac-0.1.6.recipe

Unescaped quotation marks in the description broke this recipe.

Fix FDK-AAC recipe (quotation marks in description)

---

media-sound/lame/lame-3.100.recipe

I've tested LAME 3.100 on x86_gcc2_hybrid and it works without any further changes. This PR removes the untested flag from the x86_gcc2 and x86 architectures.
How do you go about deleting outdated build scripts? Should I delete the old LAME 3.99.5 scripts and patches with this PR?

Enable LAME 3.100 on x86_gcc2 and x86.

---

sys-devel/llvm/llvm6-6.0.1.recipe
sys-devel/llvm/llvm7-7.0.0.recipe
sys-devel/llvm/patches/clang-6.0.1.patchset
sys-devel/llvm/patches/clang-7.0.0.patchset

This patch is required to build a dependency of swift-lang when built with LLVM 6 and higher, and enables support for float128 in the compiler. Tested on Haiku x86_64, untested on x86.

llvm6/7: enable float128 support in clang.

---

haiku-apps/optipngtranslator/optipngtranslator-0.0.1.recipe

* The package was not installable, because it needed
cmd:optipng_x86 on 32bit Haiku. I removed the check of
$buildArchitecture and "targetArchitecture and always
use the plain cmd:optpng.
optipng is available for all architectures.
Does the optipng recipe need to provide a SECONDARY_ARCHITECTURE as well?
* Add 2ndary architecture so _x86 apps can use the
_x86 version of the translator.
* Improved description
* Bumped revision

optipngtranslator: add 2ndary arch

---

app-text/aspell/aspell-0.60.6.1.recipe
app-text/aspell/patches/aspell-0.60.6.1.patchset
haiku-data/be_book/be_book-2008_10_26.recipe

This fixes compilation of aspell on current Haiku.
Also, the 	--enable-compile-in-filters was added. This fixes error with default ngroff filter.
See: http://aspell.net/man-html/Loadable-Filter-Notes.html
Now, flyspell-mode is working in emacs.

aspell: build for gcc7, filters fix

---

app-editors/emacs/emacs-26.1.recipe
app-editors/emacs/patches/emacs-26.1.patchset

Emacs in Hauku builded with CANNOT_DUMP=y.
There is known bug with it: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=14120
The same situation in Termux project (with CANNOT_DUMP=y): https://github.com/termux/termux-packages/issues/423
This bug leads to awful problems, that make emacs almost unusable. For example, you can not install melpa packages and so on...
This patch applies workaround, that is used in Termux project and looks fine.
After that workaround i was able to use melpa packages in emacs and all looks working fine.

emacs: invalid load-history (CANNOT_DUMP) workaround

---

dev-util/fastdep/fastdep-0.16.recipe

As above. Thankfully just the target x86_64 was missing, no need to do anything else.

Added 64 bit build of fastdep and verified it works with Paladin

---

haiku-apps/deeperpeople/deeperpeople-1.0.0.recipe
haiku-apps/deeperpeople/patches/deeperpeople-1.0.0.patchset

Upstream patch: https://github.com/HaikuArchives/DeeperPeople/pull/3
Saw a task on GCI that says "write a recipe for DeeperPeople" but DeeperPeople already has a recipe! However, I noticed that DeeperPeople is marked broken on 64 bit. This patch should fix the build.

DeeperPeople: bump revision, support for x86_64

---

haiku-apps/bescreencapture/bescreencapture-2.4.recipe

Add recipe for BeScreenCapture 2.4.
- Added pause button.
- Added the option to export the captured frames as bitmaps.
- Fixed a memory leak.
- Fixed wrong recording time string in certain cases.
- Disable nonworking output file formats.

Add recipe for BeScreenCapture 2.4

---

app-shells/zsh/zsh-5.6.2.recipe

Help generation requires cmd:col.
Interestingly the current util_linux package (2.33) not available in the depot, only an earlier version (2.32) which doesn't provides cmd:col. The 2.33 builds just fine, this i'm a bit puzzled.

ZSH: install fix

---

media-libs/boca/boca-1.0~alpha20181201.recipe

This declares smooth 0.8.74.0~pre5 as an explicit dependency to fix issues with the previous recipe.
The problem here is that smooth 0.8.74 still is a pre-release and the ~pre5 revision introduced API changes compared to ~pre4. This caused issues with BocA and fre:ac.

BoCA: fix dependencies

---

dev-games/godot/godot-3.0.6.recipe
dev-games/godot/patches/godot-3.0.6.patchset

fixes #3388
Builds till the end but linking fails:
```[Initial build] /boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: modules/libmodules.haiku.tools.64.a(subpixel_mmx.haiku.tools.64.o): relocation R_X86_64_PC32 against symbol `vp8_bilinear_filters_x86_8' can not be used when making a shared object; recompile with -fPIC
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status```

Godot: X86_64 support

---

dev-util/gn/gn-091169b.recipe
dev-util/gn/patches/gn-091169b.patchset

This is the standalone version of the GN build tool developed by the Chromium authors which is used to build V8 and Chromium. There are some problems with versioning and obtaining a reliable build source however.
Firstly, GN doesn't have any particular versioning scheme, so instead I used the last commit made from a release version of V8 instead. Secondly, the checksums of tarballs downloaded from gn.googlesource.com/gn are not deterministic due to this [issue](https://github.com/google/gitiles/issues/84) with Gerrit, which makes it useless to verify. To solve this, the recipe is using my fork of GN with the commits integrated from upstream.
Tested on both x86 and x86_64.

gn: new recipe

---

media-sound/lame/lame-3.100.recipe

This enables x86 asm optimizations for LAME which speeds up the encoder by ~20%.
Unfortunately only for 32 bit architectures. On x86_64 this change has no effect.

lame: Enable x86 asm optimizations

---

net-misc/wget/patches/wget-1.19.5.patchset
net-misc/wget/wget-1.19.5.recipe

The tests fail to start due to an error when compiling them, but most of them failed on the previous version, anyway. Here's the failure:
```
make  -C ../src libunittest.a
make[4]: Entering directory '/sources/wget-1.19.5/src'
make[4]: Leaving directory '/sources/wget-1.19.5/src'
CCLD     wget_css_fuzzer
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status
Makefile:1762: recipe for target 'wget_css_fuzzer' failed
make[3]: *** [wget_css_fuzzer] Error 1
make[3]: Leaving directory '/sources/wget-1.19.5/fuzz'
Makefile:2126: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/sources/wget-1.19.5/fuzz'
Makefile:1501: recipe for target …
```

wget: bump to 1.19.5

---

dev-libs/tinyxml2/tinyxml2-7.0.1.recipe

For some reason I haven't been able to figure out, it's using -fPIC to build the library but -fPIE to build xmltest.
on x86_gcc2 (for secondary architecture) this doesn't fail, for x86_64 it fails with -fPIE so that needs to be -fPIC there

tinyxml2, bump version, use cmake for the build

---

games-simulation/simutrans/patches/simutrans-120.3.patchset
games-simulation/simutrans/patches/simutrans-120.4.1.patchset
games-simulation/simutrans/simutrans-120.3.recipe
games-simulation/simutrans/simutrans-120.4.1.recipe
games-simulation/simutrans/simutrans-120.4~nightly.recipe
games-simulation/simutrans_pak128/simutrans_pak128-2.8.1.recipe
games-simulation/simutrans_pak128/simutrans_pak128-2.8~nightly.recipe
games-simulation/simutrans_pak64/simutrans_pak64-120.3.recipe
games-simulation/simutrans_pak64/simutrans_pak64-120.4.1.recipe
games-simulation/simutrans_pak64/simutrans_pak64-120.4~nightly.recipe
games-util/makeobj/makeobj-60.1.recipe
games-util/makeobj/makeobj-60.2.recipe
games-util/makeobj/makeobj-60.2~nightly.recipe

simutrans: fix compiling under Haiku, update to 120.3 (sdl) / 120.4.1 (sdl2)
pak64: update to 120.3 / 120.4.1
pak128: update to 2.8.1
makeobj: update to 60.1 (sdl) / 60.2 (sdl2)
I had to include patchsets due to a bug in a haiku specific section of the simutrans source code that made it impossible to build newer simutrans versions under haiku. I've opened a thread in the simutrans forum to report the bug. Since the bug (a missing ',' at the end of a line) will probably be fixed in a few days I haven't generated patchsets for the nightly recipes.

simutrans: several updates and bugfixes (incl. for paksets and makeobj)

---

games-simulation/simutrans/simutrans-120.3.recipe
games-simulation/simutrans/simutrans-120.4.1.recipe

I forgot to remove the "$secondaryArchSuffix" for the corresponding pakset in the REQUIRES section after switching to platform agnostic "any" paksets for simutrans release recipes. This prevented the buildbots from compiling packages for gcc2hybrid. Nightlies are not affected because they still need to compile platform-specific paksets from source code.

simutrans: fix build for gcc2hybrid

---

haiku-apps/bamkeys/bamkeys-1.0.0.recipe

Recipe for BamKeys! I have created a PR for changes in BamKeys so check that out so that I can add remaining stuffs in recipe.
https://github.com/bvarner/bamkeys/pull/1

Recipe for BamKeys.

---

dev-lang/nim/nim-0.19.2_20190103.recipe
dev-lang/nim/patches/nim-0.19.2_20190103.patchset

A slightly newer version was used as it includes the walkDir fix for Haiku.
Documentations are now built and packaged as `_doc` subpackage.
Tested on `x86_64`. I'd assume that a lot of tests will fail on `x86_gcc2`, due to nim-lang/Nim#9138.

dev-lang/nim: update to 0.19.2

---

haiku-apps/openoriginpackage/openoriginpackage-1.1.0.recipe

Very strange:  
"make" creates the binary "`Open Origin Package`", but in the package, the binary is named "`Open\ Origin\ Package`". The build process hasn't changed since v1.0.0 and the package in HaikuDepot shows the correct name.
@waddlesplash: Can this change of the makefile_engine be the issue?
https://git.haiku-os.org/haiku/commit/?id=f84c53e4acb4c8a9e4dadd4ce165ca3a126114b1

openoriginpackage: update to v1.1.0

---

dev-libs/gobject-introspection/gobject_introspection-1.56.1.recipe
dev-libs/gobject-introspection/patches/gobject_introspection-1.56.1.patchset

Second try (sorry for the noise) :)
This is still version 1.56.1 as it relies on glib2 (version 2.57.1 atm in haikudepot for secondary architecture), 1.56.1 is the last available version that is in line with glib2's version (there is no 1.57.1, next one is 1.57.2 which needs glib2 2.57.2). Disabled gcc2 as the available version is even older for glib2.

gobject-introspection, new recipe

---

sci-geosciences/gpxsee/additional-files/gpxsee.rdef.in
sci-geosciences/gpxsee/gpxsee-7.2.recipe
sci-geosciences/gpxsee/patches/gpxsee-7.2.patchset

Update to version 7.2.
[Changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes):
>   * Added support for DEM data (SRTM HGT files).
>   * Improved look&feel in dark styles.
>   * Added support for polar stereographic projections + Antarctica
>     map.
>   * Added support for GeoJSON files.
>   * Added Spanish localization.

GPXSee: bump to 7.2

---

dev-lang/rust/patches/rust-1.29.0.patchset
dev-lang/rust/rust-1.29.0.recipe
dev-lang/rust_bin/rust_bin-1.29.0.recipe

This is the recipe for Rust 1.29.0. As always, the binary recipe has been tried and tested, the source recipe is here for reference.

Rust: add recipe for 1.29.0

---

dev-lang/rust/patches/rust-1.32.0.patchset
dev-lang/rust/rust-1.32.0.recipe
dev-lang/rust_bin/rust_bin-1.32.0.recipe

This recipe follows the same structure as PR #3147. This version of Rust supports compiling the Rust 2018 edition, which means that this version will be the minimum required version for a lot of crates for the next few years.

Rust: add recipe for 1.32.0

---

dev-libs/boehm_gc/boehm_gc-8.0.4.recipe

Update from v7.6.12 to v8.0.4
Remove --enable-parallel-mark which is default now

boehm_gc: bump to 8.0.4

---

dev-lang/golang/golang-1.4.3.recipe
dev-lang/golang/patches/golang-1.4.3.patchset

This PR adds a version of Go that makes it possible to bootstrap any Go toolchain which is written in Go (Go 1.5 and above).
This Golang port is based on the GSoC 2014 Go port which uses the Solaris port, but has been updated to work on newer versions of Go with some catches though (direct syscalls are unsupported, no cgo yet, etc)
One can try to bootstrap a higher Go version using this, but note that since this is still a WIP and some bugs may prevent bootstrapping to complete and I'm still documenting these bugs in several go packages.
I also tested the packages under Haiku x86_64 and ran ./all.bash and all of the results can be found in this [gist](https://gist.github.com/return/e76f5ce30c240a6123e916f39f4b930d).

[WIP] golang: add recipe for 1.4.3

---

dev-lang/golang/golang-1.4.3.recipe
dev-lang/golang/patches/golang-1.4.3.patchset

This patches the go compiler for Haiku to fix process
waiting when executing Wait() on a process. Should also fix
the net/url hang [0] when attempting to bootstrap Go 1.5 [1] and
above.
Also changes the GOROOT_FINAL location to a globally writeable
location in the non-packaged folder to allow golang to install
third-party libraries.
[0] For context on this issue, see https://github.com/haikuports/haikuports/pull/3119#issuecomment-424038086
[1] See: https://gist.github.com/return/6e1d24dc67da616b5f828a3b84b12704

golang: Update patchset to enable bootstrapping.

---

net-p2p/eiskaltdcpp/eiskaltdcpp-2.3.0~git.recipe

Some Haiku-specific changes were done in upstream:
* Static core library.
* Fixed loading of translations in UI from non-standard path `<EiskaltDC++ bin dir>/translations`.
Translations for core library are still not available in this package as well as some other resources necessary for UI.
More Haiku-specific changes will be done later. Not sure how soon though.

eiskaltdcpp: bump version.

---

net-p2p/eiskaltdcpp/eiskaltdcpp-2.3.0~git.recipe

This PR is not ready for merging yet.
For some unintelligible reason `addResourcesToBinaries` tool in build script does not see `$appsDir/Eiskaltdcpp/EiskaltDC++` file, which was explicitly installed during `make install`.
Any comments are welcome.

eiskaltdcpp: bump version + improve build script

---

net-im/psi_plus/psi_plus-1.4.672.recipe

It was recently improved in Haiku port of Qt:
https://github.com/haikuports/haikuports/blob/53f29b56/dev-qt/qt5/patches/qt5-5.12.3.patchset#L343

psi_plus: use native DNS resolver from Qt

---

net-im/psi_plus/psi_plus-1.4.675.recipe

+ delete configuration options which default values fit fine Haiku needs
and will not be changed in upstream in the future.
Changes in upstream: fixed segfault on program exit.

psi_plus: bump version to 1.4.675

---

dev-lang/v8/patches/build-7.4.288.28.patch
dev-lang/v8/patches/v8-7.4.288.28.patchset
dev-lang/v8/v8-7.4.288.28.recipe

This version of V8 is from Chrome 74.0.3729.157 as found in the version information in https://omahaproxy.appspot.com.
V8 requires several dependencies defined in its [DEPS](https://chromium.googlesource.com/v8/v8/+/8a28642518a30b588dda7c417fd820a9f2831fee) file which are cloned in before it builds and this recipe uses these git hashes to build the port.
I previously tried using 'depot_tools' to build it, but it doesn't work reliably for several reasons.
See: https://github.com/haikuports/haikuports/issues/2557#issuecomment-389212503
~Needs [GN](https://github.com/haikuports/haikuports/pull/3306) merged first to build correctly.~
EDIT: GN has been merged into HaikuPorts. It is now possible for the buildbots to build V8.

v8: add recipe for version 7.4.288.28

---

dev-lang/v8/patches/v8-7.4.288.28.patchset
dev-lang/v8/v8-7.4.288.28.recipe

This commit fixes the build error [1] when building V8 with GCC.
Tested on x86_64.
[1] https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/3120/builds/13532.log

v8: Fix build error on macro definition.

---

net-libs/nodejs/nodejs-12.3.1.recipe
net-libs/nodejs/patches/nodejs-v12.3.1.patchset

This is a very early and functioning port of Node.js 12.3.1 to Haiku, based on V8 7.4.288.28.
This recipe currently uses the bundled dependencies from libuv, openssl, V8 and brotli. This might change to use shared libraries in the future when the correct dependencies are available in HaikuPorts.
What currently works:
* Node REPL.
* Networking.
* npm (Node modules (global) needs to be in non-packaged folder to download packages)
* Remote Debugging (via Chrome Debugger and inspector)
What does not work:
* CPU activity is missing.
* File Watching (fsevents unimplemented).
Please note that this recipe is very early and is only intended to be used by testers until it is ready to be merged into HaikuPorts.
The patches in this port were adapted and imported from the following ports:
Node.js …

nodejs: add recipe for v12.3.1

---

net-libs/nodejs/nodejs-12.3.1.recipe

This commit fixes the npm installation paths that is required by most npm packages to function in Haiku.
The `node_modules` folder is placed in `/boot/system/non-packaged/lib/`
CLI packages installed via npm are placed in: `/boot/system/non-packaged/lib/node_modules/.bin`.
These packages are then symlinked by npm into the `/boot/system/non-packaged/bin` folder.
The .npmrc (npm user config) is placed in the `/boot/home/config/settings` folder.

nodejs: Fix npm package installation paths.

---

media-libs/freeimage/freeimage-3.18.0.recipe
media-libs/freeimage/patches/freeimage-3.18.0.patchset

The freeimage package only contain libfreeimage-3.18.0.so, but some package (one of these porting in progress :P) need libfreeimage.so.3, and runtime_loader don't find in $developDir.

freeimage: add libfreeimage.so.3 to $libDir

---

games-rpg/devilutionx/devilutionx-0.4.0.recipe

DevilutionX builds a debug version by default, specify the building of a release version. Also bump revision.

devilutionx: Build binary release version

---

dev-python/discid/discid-1.2.0.recipe

This adds a recipe for python-discid.
Adding as a requirement for MusicBrainz Picard, for which I'll submit a recipe later.

discid: add recipe for version 1.2.0

---

media-libs/chromaprint/chromaprint-1.4.3.recipe

This builds chromaprint with the `fpcalc` command line utility.
`fpcalc` can be used to generate fingerprints for audio files on the command line. Among others this tool is needed by MusicBrainz Picard (for which I'm going to provide a recipe later) for audio fingerprinting.
This change introduces ffmpeg as a dependency since `fpcalc` cannot be build without it. However, ffmpeg is also the preferred choice for a FFT library as described in https://github.com/acoustid/chromaprint, so the dependency on libfftw3 is no longer needed.

chromaprint: Build with fpcalc utility

---

dev-python/discid/discid-1.2.0.recipe

The requirement of libdiscid was overwritten for the individual packages.
See also discussion on https://github.com/haikuports/haikuports/pull/4018

discid: fixed missing dependency on libdiscid

---

sys-devel/jam/jam-2.5_2018_11_21.recipe

This updates jam to the latest commit in the buildtools repository (fixing [a crash I encountered today](https://dev.haiku-os.org/ticket/15250)) and adds a debuginfo package to make future debugging easier.

jam: Update to latest commit and add debuginfo

---

media-libs/chromaprint/chromaprint-1.4.3.recipe

fpcalc is installed in $prefix/bin so no $secondaryArchSuffix is needed

chromaprint, fix _x86 build

---

media-libs/libopenmpt/libopenmpt-0.4.6.recipe
media-libs/libopenmpt/patches/libopenmpt-0.4.6.patchset

Patch upstreamed.
Test passes, plays music. Even rebuilt ffmpeg with it (not needed, just to make sure)

libOpenMPT: bump

---

media-sound/picard/picard-2.1.3.recipe

Add back the dependency for `cmd:fpcalc` to the recipe. This got lost in the last update, but actually is required for the fingerprinting to work.

picard: add back dependency on cmd:fpcalc

---

media-sound/picard/patches/picard-2.2.1.patchset
media-sound/picard/picard-2.2.1.recipe

Picard 2.2.1 release. Also gets rid of some minor patches now upstreamed.
The remaining patches are more difficult. One is a strange crash when calling `locale.strxfrm`, which probably is threading related. Not sure right now where this needs to be fixed, so far I haven't found the time to really dig for the root cause here and the patch included here is a workaround (just avoid calling this).
The other patch is opening the proper webbrowser, and this is something I would rather like to add to the Python packages so other programs benefit from this as well. My goal is to submit this as a Python patch for existing Haiku Python packages and also upstream. I just need to find the time for this ;)

picard: Release 2.2.1

---

media-libs/libdiscid/libdiscid-0.6.2.recipe

Removed dependency on libmusicbrainz from libdiscid. libdiscid is a standalone library not requiring anything from libmusicbrainz to build or run.

libdiscid: does not depend on libmusicbrainz

---

dev-lang/python/patches/python-2.7.16.patchset
dev-lang/python/patches/python3-3.6.8.patchset
dev-lang/python/patches/python3-3.7.3.patchset
dev-lang/python/python-2.7.16.recipe
dev-lang/python/python3-3.7.3.recipe
dev-lang/python/python36-3.6.8.recipe

This patches the Python webbrowser module to open the default browser on Haiku.
With this patch code like this actually works and opens the browser:
```python
import webbrowser
webbrowser.open('https://haiku-os.org')  # Will return True and open browser
```
Patch for all currently supported Python versions included (2, 3.6, 3.7). The code was previously already used in the patches for https://github.com/haikuports/haikuports/tree/08258e72b706303a4c61c72b370d670fdf8cd297/media-sound/picard/patches

python: patched webbrowser module for Haiku

---

dev-lang/rust/patches/rust-1.38.0.patchset
dev-lang/rust/rust-1.38.0.recipe
dev-lang/rust_bin/rust_bin-1.38.0.recipe

Due to rust-lang/rust#61861 this will not include clippy, rustfmt and rls

Rust: add recipe for 1.38.0

---

dev-qt/wxqt/wxqt-3.1.3.recipe

This updates wxqt to version 3.1.3.
Compiles fine on x86_64 but is a WIP to make sure that existing applications don't break with this update.
Please mark this as a WIP until apps/libraries using wxqt are tested to function correctly.

wxqt: Bump version to 3.1.3

---

dev-python/mutagen/mutagen-1.43.0.recipe

Update python-mutagen to new upstream release 1.43.0
For release details see https://github.com/quodlibet/mutagen/releases/tag/release-1.43.0
Tested building and running package locally on 64bit Haiku.

mutagen: update to 1.43.0

---

dev-python/pip/pip-19.3.1.recipe

This bumps the version of pip to 19.3.1 and includes the fix for #3420 when installing external packages.
Tested on x86_64 Haiku R1 Beta 1.

pip: bump version to 19.3.1

---

dev-vcs/fossil/fossil-2.10.recipe

It compiles and runs OK on 32 bit x86 (not on GCC2) and 64 bit Haiku.  Didn't have to change the recipe, other than the checksum and new version number.  Though when running you see a lot of log messages about failing to find libroot-addon-icu.so, which is actually there in system/libs.  And some probably harmless warnings when compiling on 32 bit about printing the long int GetPID() with a %d.

fossil: update to version 2.10, circa October 2019.

---

app-crypt/libu2f_host/libu2f_host-1.1.10.recipe
app-crypt/libu2f_host/patches/libu2f_host-1.1.10.patchset

As of the time of this writing, `libu2f_host` depends on `cmd:gengetopt`. Its recipe can be found on #4493 and has not been merged yet and the recipe won't work without gengetopt. For organization reasons, this recipe wasn't included in this pull request.

libu2f_host: added recipe

---

media-sound/picard/additional-files/picard.rdef.in
media-sound/picard/patches/picard-2.2.3.patchset
media-sound/picard/picard-2.2.3.recipe

This adds supported mimetypes to Picard with the ability to open those files from tracker or via drag and drop on deskbar item.
This ads a small patch to fix Picard's handling of argv, but I will upstream so we will be able to remove this patch again in the next release.
Please note that this currently will always ignore the first file provided this way due to a current limitation of qthaikuplugins. We'll hopefully sort this out soon, see https://github.com/threedeyes/qthaikuplugins/pull/14

picard: Support for opening supported mimetypes

---

dev-util/bear/bear-2.4.2.recipe

Tested by building haiku and spot checking the compilation database produced. It appears to work just fine.
```
/Code/haiku/generated.x86_64> bear jam -q -j4 @image
...
/Code/haiku/generated.x86_64> bear -a jam -q -j4 unittests
...
/Code/haiku/generated.x86_64> grep -A 5 -B 30 '"file": "../src/system/kernel/vm/
VMUtils.cpp"' compile_commands.json
"../headers/os/game", 
"-I", 
"../headers/os/interface", 
"-I", 
"../headers/os/kernel", 
"-I", 
"../headers/os/locale", 
"-I", 
"../headers/os/media", 
"-I", 
"../headers/os/mail", 
"-I", 
"../headers/os/midi", 
"-I", 
"../headers/os/midi2", 
"-I", 
"../headers/os/net", 
"-I", 
"../headers/os/storage", 
"-I", 
"../headers/os/support", 
"-I", 
"../headers/os/translation", 
"-I", 
"../headers/private/.", 
"-o", …
```

Package bear 2.4.2

---

games-rpg/fheroes2/fheroes2-r3279.recipe

As of this moment, there's no reliable download link for the `r3279` version of `fheroes2`.
This pull request is meant to disable the recipe itself.

fheroes2: disabled recipe

---

games-action/abuse/abuse-0.8.recipe
games-action/abuse/patches/abuse-0.8.patchset

There is a problem with header FindDirectory.h. When I try to compile it with this header, I get a lot of compilation errors:
[errors.txt](https://github.com/haikuports/haikuports/files/4071135/errors.txt)
For now I only changed this directory to settings without find_directory because this doesn't work.

abuse: change save localization to settings

---

media-libs/netpbm/netpbm-10.88.01.recipe

Looking into bumping version, mark secondary architecture as broken for now

netbpm, mark x86 as broken for now

---

media-libs/dav1d/dav1d-0.5.2.recipe

I've added the recipe for dav1d-0.5.2
The source builds and works on Haiku without patches.
The recipe packages properly now.
Here is the build log when running `haikuporter` with this recipe.
[dav1d-0.5.2_build.log](https://github.com/haikuports/haikuports/files/4093291/dav1d-0.5.2_build.log)

Added recipe for dav1d-0.5.2

---

media-libs/opensubdiv/opensubdiv-3.4.0.recipe

Related posts: https://discuss.haiku-os.org/t/blender-2-81-is-working-on-haiku/9235/11.

opensubdiv: remove RPATH, fixes module search paths on 32 bit x86

---

dev-python/regex/regex-2020.1.8.recipe

No idea why it fails on 32 bit.

regex: mark as untested for 32 bit

---

games-arcade/supertux/patches/supertux-0.6.1.patch
games-arcade/supertux/supertux-0.6.1.recipe

Resolves #4456 
Apparently it tries to move an old config directory, constructed like `~/.$PACKAGE_NAME`, to the new one, and `PACKAGE_NAME` wasn't defined for some reason... resolving in `~/.`. Yikes! I just disabled the entire thing because I don't think we ever had the old config directory, anyway.

supertux: bump to 0.6.1 and fix build

---

media-video/mplayer/mplayer-1.4.0.recipe

* On 32bit running mplayer fails with:
'runtime_loader: /boot/system/bin/mplayer: Could not map image: Out of memory'
See #1978.
* Remove "x86", it's not an official target for Haiku anymore.

mplayer: mark as unsupported on 32bit

---

games-emulation/mgba/mgba-0.8.1.recipe
games-emulation/mgba/patches/mgba-0.8.1.patch

I'm guessing that this was overlooked because it tries to use `XDG_CONFIG_HOME` by default, which is set in the terminal, but not when launched from Deskbar.
Note that I removed `libswresample` as it seems that it didn't seem to link against it. It optionally uses libavresample, but it isn't available in the current version of ffmpeg. Let me know if libavresample works on the build bots or if libswresample does something.

mgba: bump to 0.8.1 and fix config directory

---

games-engines/openmw/openmw-0.45.0.recipe

Not sure if there's supposed to be a better way to fix this; I'm just copying a previous commit.

openmw: rebuild after bullet soname bump

---

games-arcade/openmortal/openmortal-0.7.recipe
games-arcade/openmortal/patches/openmortal-0.7.patch

Notes:
- I didn't know anything good I could set the host to so I left it blank.
- I patched the Perl scripts to use relative paths for `require`; is there a better way to handle this?
- It fails to build in strict mode on x86 secondary architecture because it complains that it `can't find used library "libperl.so"`, but it seems to work fine otherwise. I'm guessing this is because it wants a secondary arch library but Perl doesn't have a secondary arch build enabled for some reason; any ideas on what do to here?
- I didn't split the package data as I felt that the difference isn't too much nowadays, but let me know if you feel otherwise.
- How much space should debug info take to warrant a debuginfo package? The debuginfo package takes 1.2 MB on my system, which I'm guessing is enough.

openmortal: new recipe

---

sys-devel/llvm/llvm9-9.0.1.recipe

* Use ninja instead of make to improve incremental build.
* Use -n option in cp to do not change existing files when installing source code.
Fixes #4786.

llvm: add lld-link, improve incremental build

---

dev-libs/boehm_gc/boehm_gc-8.0.4.recipe
dev-libs/boehm_gc/patches/boehm_gc-8.0.4.patchset

The build of Guile 2.2.7 aborts with the following error
```
mmap(PROT_NONE) failed
```
which is due to the GC. This new patch solves the problem. I've also submitted an issue upstream.  The patch follows what happens in other architectures: see
(https://github.com/ivmai/bdwgc/blob/master/os_dep.c) line 2578 in the upcoming 1.0 version of the GC.

boehm_gc:  fix for "mmap(PROT_NONE) failed" in building GNU Guile 2.2.7 

---

app-shells/mksh/mksh-57.recipe
app-shells/mksh/patches/mksh-57.patchset

Patch mksh to use `~/config/settings/mkshrc` and `~/config/settings/profile` instead of `~/.mkshrc` and `~/.profile`.

mksh: Update user profile paths

---

games-emulation/retroarch/retroarch-1.8.5.recipe

Now that #2484 is closed, we can re-enable the QT interface in the Retroarch build.

retroarch: re-enabled qt5 to allow shiny QT interface build

---

media-libs/gd/gd-2.3.0.recipe

use the github archive instead of the official tarball because it misses a file needed by libtool

gd: bump version and fix build

---

app-text/teckit/licenses/CPL v0.5
app-text/teckit/teckit-2.5.9.recipe

this is another package which is actually part of TeX Live, but can also be used standalone.
It can then be removed from Tex Live, making that package smaller. (see also #4861)

new recipe: TECkit (Text Encoding Conversion Toolkit)

---

dev-python/mutagen/mutagen-1.44.0.recipe

Removed building the Python 2 package, it is no longer supported by mutagen.
We could consider keeping the 1.43 version around for Python 2 only, but there is currently no other package depending on it and Python 2 is deprecated for a long time and unsupported now anyway. So my recommendation is to remove the Python 2 package from the mutagen recipe as I've done here.
See https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-44-0 for upstream changelog.

mutagen: update to 1.44

---

sci-astronomy/fitspng/fitspng-1.4.recipe

Fitspng is a small posix utility used to convert from astronomical FITS image format to PNG.
Pls note that this PR should be merged first: https://github.com/haikuports/haikuports/pull/4847
This because CFITS version currently in Haikuports has a bug that will prevents fitspng working. That PR fixes this.

New Recipe: fitspng

---

dev-lang/rust_bin/rust_bin-1.43.0.recipe

The previous binary build depended on an older libcurl which was built
against a binary-incompatible openssl version. It did not run on recent
Haiku builds. This build has been tested on recent builds that are close
to Haiku R1 beta 2.

Rust: new revision of binary Rust 1.43.0 recipe

---

games-emulation/melonds_libretro/melonds_libretro-0.8.3_20190911.recipe

This should resolve #4802 while keeping the current version numbering (libretro cores don't use strict versioning and are often out of sync with the original emulators / games)

melonds_libretro: bump to 0.8.3 ~ 42c1acd

---

dev-lang/golang/golang-1.4.3.recipe

`https://golang.org/go` returns 404's, so I replaced it with `https://golang.org/` instead.

golang: fixed dead link in HOMEPAGE

---

sci-astronomy/wcslib/patches/wcslib-7.2.patchset
sci-astronomy/wcslib/wcslib-7.2.recipe

WCSLIB is a C library, supplied with a full set of Fortran wrappers, that implements the World Coordinate System (WCS) convention in FITS. Since PGPLOT is not yet available on Haiku, \
this package doesn't include PGBOX (routines for drawing general curvilinear coordinate graticules) and related utilities.
Porting PGPLOT seems to be tricky at first look. I'll probably need much time to port it. That's why I decided to push this library without that (very optional) dependency in the meantime.
SIDE NOTE: I'm not an experienced Fortran dev so there're room for future improvements in this recipe:
- ~~Where exactly the fortran wrappers are supposed to be installed in the tree? Perhaps a sibling package?~~
- ~~I don't know which files must be copied and which files must be not (install doesn't …

New Recipe: Wcslib

---

sys-process/parallel/parallel-2020.04.22.recipe
sys-process/parallel/patches/parallel-2020.04.22.patchset

Adds a recipe for GNU Parallel, tool to run stuff in parallel :) https://www.gnu.org/software/parallel/
The patch disables failing feature to detect the parent shell of `parallel`. It relies on `ps` but since `parallel` gets launched in a different team I don't see a way to get the name of the process which launched `parallel` from its Haiku output. Therefore I set it to default to `/bin/bash` - user can change it using environment variables `PARALLEL_SHELL` and `SHELL`, as described in parallel's docs.

Add sys-process/parallel.

---

media-fonts/cascadia_code/cascadia-2005.15.recipe

This is the font used with the new Windows Terminal.
https://github.com/microsoft/cascadia-code

Cascadia Code: Add recipe

---

media-fonts/cascadia_code/cascadia_code-2005.15.recipe

Correct name is cascadia_code, not cascadia only.

Cascadia Code: Rename package

---

net-misc/openssh/additional-files/fix_openssh_post_install_usergroup.sh
net-misc/openssh/openssh-8.2p1.recipe

Here's a quick fix for https://dev.haiku-os.org/ticket/14382 where we create the user and group in the post-install script too.  Needed for beta 2.  BTW, couldn't download from https when building in Haiku GCC2, changed URL so it works.

openssh: Work around first boot user creation bug.

---

media-gfx/blender/blender-2.79b.recipe

It fails during the build stage:
```
[3075/3075] cd /sources/blender-2.79b/...b/build_haiku/source/creator/blender.1
FAILED: source/creator/CMakeFiles/blender_man_page 
cd /sources/blender-2.79b/build_haiku/source/creator && /sources/blender-2.79b/doc/manpage/blender.1.py /sources/blender-2.79b/build_haiku/bin/blender /sources/blender-2.79b/build_haiku/source/creator/blender.1
env: 'python3': No such file or directory
ninja: build stopped: subcommand failed.
```
Blender 2.79 uses Python3.6 (it builds with 3.7, but @X547 reported missing GUI elements). Python3.6 doesn't provides `cmd:python3`, but `cmd:python3.6`.
Tried to create an `alias` in the recipe, but that didn't worked.
Ofc, we can disable the manpage generation, but grepping the source tree shows plenty scripts referring …

Blender: cleanup, release settings, ninja

---

sci-libs/cfitsio/cfitsio-3.48.recipe
sci-libs/cfitsio/patches/cfitsio-3.48.patchset

They changed the library interface and (finally) added a soname versioning scheme. So, $libVersion had to be added.
I also devoted a general bit more love to the port

cfitsio: bump to 3.48

---

dev-lang/acme/acme-0.96.5.recipe

ACME is a free cross assembler that can produce code for the following processors: \
6502, 6510 (including illegal opcodes), 65c02 and 65816.
I've ported the assembler and the migration tool. I've added some tests using the provided code examples, too.
Source code is packaged very badly. I had no choice other than binding to a particular commit (r190)
tested on x86_64, but the code looks like to be completely portable.

[New Recipe] Acme Cross-Assembler for 65**

---

net-misc/curl/curl-7.70.0.recipe

Test n. 116 fails, dunno if it is blocking or not as there's nothing relevant on curl changelog about it
aside that, business as usual.

curl: bump to 7.70.0

---

sci-libs/armadillo/armadillo-9.880.1.recipe

Changelog:
- bump to 9.880.3
- added a test block
- (fix) added a couple of optional requirements which were already in the recipe but were not enabled at build

armadillo: bump to 9.880.3

---

dev-util/acr/acr-1.9.2.recipe

acr: bump to 1.9.2

---

dev-lang/64tass/64tass-1.55.recipe
dev-lang/64tass/licenses/my_getopt

64tass is cross assembler targeting the 65xx series of micro processors which features the familiar syntax of Omicron TASS and TASM, one of the most popular assembler on C64 during the 80s and 90s.
Port is working perfectly, but has two small defects:
- Licensing is a bit confused. Main package is LGPL, but an embedded component has a custom one (provided) which I'm not sure is compatible with LGPL itself. No real names are provided (but demo scener/crew nicknames)
- In the INSTALL() block I copy the syntax file to vim settings dir. A better version check should be made here to proof which version of vim is installed. Have I to use a post install script?

64tass: new recipe

---

app-admin/keepassxc/keepassxc-2.3.4.recipe

* See 144ddc1 (bump of argon2, which is a dependency of keepassxc).

keepassxc: bump revision

---

haiku-apps/colors/colors-2.3.recipe

Not being a library, Colors isn't needed as a gcc8 _x86 version.
Before, there were two instances of Colors in HaikuDepot, x86 and
x86_gcc2

Colors: remove 2ndary arch

---

haiku-apps/sanity/sanity-0.6.recipe

Ref: https://github.com/haikuports/haikuports/issues/5124
NOTE Recipe W-I-P. Needs further tweaking on x86 (GGC8). Passes manual build test on x86.

sanity: migrate to x86 2ndary arch

---

dev-python/dateutil/dateutil-2.8.0.recipe
dev-python/dateutil/dateutil-2.8.1.recipe

Update python dateutil to latest release and add a dependency on python six. Without six the following fails:
```
>>> from dateutil import parser
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/dateutil/parser/__init__.py", line 2, in <module>
from ._parser import parse, parser, parserinfo
File "/packages/python3-3.7.7-2/.self/lib/python3.7/vendor-packages/dateutil/parser/_parser.py", line 42, in <module>
import six
ModuleNotFoundError: No module named 'six'
```
See also https://github.com/dateutil/dateutil/blob/0905e27cc1e58eb33265d366834cbd55b420c122/setup.cfg#L35

dateutil: update to 2.8.1, add dependency on six

---

haiku-apps/bescreencapture/bescreencapture-2.5.1.recipe
haiku-apps/bescreencapture/patches/bescreencapture-2.5.1.patchset

Bugfix release for BeScreenCapture
I fixed a bug in BeScreenCapture where the GIF export would only export a few frames.
Here's the PR.

Bescreencapture v2.5.1

---

app-misc/pax-utils/patches/pax_utils-1.2.6.patchset
app-misc/pax-utils/pax_utils-1.2.6.recipe

Test suite needs to be fixed but the commands seem to be functioning normally.  This recipe includes a working copy of the lddtree command and might fix issue #4000 if it builds for gcc2.

pax-utils: new recipe for version 1.2.6

---

dev-python/mutagen/mutagen-1.45.0.recipe

New upstream release. See https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-45-0

mutagen: bump version to 1.45

---

net-dialup/minicom/minicom-2.7.1.recipe

Bump to the latest version; addresses CVE-2017-7467.

Bump version to address CVE-2017-7467

---

dev-python/mutagen/mutagen-1.45.1.recipe

New upstream release with write performance improvements, see https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-45-1
Build and tested locally (64bit)

mutagen: bump version to 1.45.1

---

app-editors/hteditor/hteditor-2.1.0.recipe

Since there's no gcc2 version, just the x86 built.

hteditor: avoid putting th in /bin/x86

---

games-action/supermariowar/patches/supermariowar-beta1.1.patch
games-action/supermariowar/supermariowar-beta1.1.recipe

Notes:
- Depends on #4753 
- I was going to put this in `games-arcade`, but Gentoo had it in `games-action`
- I'm not sure if the unzipping should be done in another function
- Am I supposed to put the apps in a directory in `$appsDir`?
- I wasn't sure what to name the version; would it be preferred to make it a `~git` package?
- I create shell scripts to run them because it's designed to have the data directory path passed as an argument, but because of that it uses the icon for text files and has a different name on startup. Does this mean I have to patch the program?
- Should I enable `USE_PNG_SAVE`?
- I was also able to run the original version (this is an unofficial fork); would a recipe for it be accepted if I feel like making one in the future?

supermariowar: new recipe

---

dev-lang/rust/patches/rust-1.45.0.patchset
dev-lang/rust/rust-1.45.0.recipe
dev-lang/rust_bin/rust_bin-1.45.0.recipe

Note that rust_bin does not include rls in this version, as the current
incarnation depends on an unsupported dependency. Rls seems to be
falling out of favour for rust-analyser anyway, so this is not a
blocker.

Rust: Add version 1.45.0

---

haiku-apps/paladin/paladin-2.8~git.recipe

After testing out one of Paladin's templates, a user on social media seemed unable to compile a template which included the lines;
```cpp
#include <Application.h>
#include <Window.h>
```
Consequently, they claim to have resolved that issue by installing `haiku_devel` in their system afterwards.
I believe that if the program itself assumes that the user has the Haiku headers installed on their system, does not check for it and bundles Haiku-specific code that's meant to be illustrating the system's capabilities to users experimenting with the system, then the recipe itself should cover this case scenario.

Paladin: Added Haiku header requirement

---

media-libs/libavif/libavif-0.8.0.recipe

Only decoding is supported for now, as there is no package for [rav1e](https://github.com/xiph/rav1e) yet, because cargo-c fails to build due to https://github.com/alexcrichton/socket2-rs/commit/43b75d3dd4a90e33b4b9ddb764f84f68914c9648 not being in a release yet.
Once rav1e is in haikuports, it will only be a matter of passing `-DAVIF_CODEC_RAV1E=ON` to cmake, and encoding will be possible.

libavif: new recipe for version 0.8.0

---

dev-util/bam/bam-0.5.1.recipe

Ran several tests to verify the x86_64 build of bam 0.5.1 is functional.

bam: enable x86_64

---

games-roguelike/angband/angband-4.2.0.recipe

There should be no problems, but this is untested, I've only checked that it compiles in my x86_64 system.
Once I'm sure this is the kind of change expected from #3878, I'll try and continue sending PR with more than one recipe, if that's OK.

Angband: fix libSDL references

---

dev-lang/tcl/tcl-8.6.10.recipe

This should fix the build for 64 bit Haiku, checked so far with expect and sqlcipher

tcl, revbump, remove sqlite3 dependency (solves build on x86_64)

---

games-fps/eduke32/eduke32-20190304_7392.recipe
games-fps/openarena/openarena-0.8.9~git.recipe
games-fps/uhexen2/uhexen2-1.5.9.recipe
games-kids/abe/abe-1.1.recipe
games-kids/dragonmemory/dragonmemory-1.recipe
games-kids/tuxmath/tuxmath-1.7.2.recipe
games-kids/tuxtype/tuxtype2-1.5.2.recipe
games-misc/sdljoytest/sdljoytest-11102003.recipe

I've built (not installed or run) these for x86_64, x86_gcc2 as primary and x86 as secondary arch for the cases that they are declared compatible or untested, except for eduke32-20190304_7392, that does not compile for me in x86_gcc2, asking for C++11, but so does the unchanged recipe.

Update libSDL references

---

dev-util/kdevelop/kdevelop-5.6.0.recipe

From the report:
```
kdevelop-5.6.0-3-x86_64.hpkg:
requires "lib:libkomparediff2 >= 17.12.0" of package "kdevelop-5.6.0-3" could not be resolved
```

kdevelop, revbump after updated libkomparediff

---

kde-apps/okular/okular-20.12.1.recipe

Failed buildlog for x86_gcc2: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/1029/builds/1750.log
Should be fixed now

okular, revbump for rebuild

---

net-dns/libidn/libidn-1.36.recipe
net-dns/libidn/patches/libidn-1.36.patchset

Primary patch came from Oracle patch: https://www.mail-archive.com/bug-gnulib@gnu.org/msg39296.html

libidn, fix build for gcc2

---

media-libs/avisynthplus/avisynthplus-3.7.0.recipe
media-libs/avisynthplus/patches/0001-CMakeLists-fix-setting-local-plugindir.patch
media-libs/avisynthplus/patches/0002-avisynth_conf.h.in-use-mounted-system-libdir-on-Haik.patch

Hopefully I did this right.  It completes successfully for me on 64-bit, but on 32-bit it kept failing when trying to populate dependencies because it didn't seem to be recognizing $secondaryArchSuffix at all (or in other cases, just erroring out with a 'is broken on this architecture'; I'm hoping that maybe that's just an issue with my local configuration and not with the recipe).
The patch section there is something we'll address upstream.

avisynthplus-3.7.0: new recipe

---

sys-auth/libyubikey/libyubikey-1.13.recipe

Migrate from GCC2 to GCC8 x86.

libyubikey: Rebuild for libusb 1.0.24

---

media-sound/mpg123/mpg123-1.26.4.recipe

Leaving the old 1.25.13 release in the repo as the new version no longer compiles with gcc2.

mpg123: bump to 1.26.4

---

net-im/psi_plus/psi_plus-1.4.1514.recipe

I cannot build latest version of Psi+ (1.5.1477) because it has new build dependency from `usrsctp` library which is nor packaged in Haikuports, nor could be built from sources without additional patches.

psi_plus: bump to 1.4.1514

---

sci-libs/scalapack/scalapack-2.1.0.recipe

Depends on OpenMPI, but i am convincied that it works. Nothing uses this.

Scalapack: disable for every arch

---

net-misc/ytdl-gui/ytdl_gui-2.0.recipe

Updates the app to 2.0, bringing a checkbox to let `youtube-dl` select format options and 1.9's playlist support. At the advice of @Begasus in a prior attempted PR (https://github.com/haikuports/haikuports/pull/5669), `$srcGitTag` has been removed in favour of using `$portVersion` in its place.

ytdl-gui: Update to 2.0

---

media-sound/mac/mac-6.12.recipe

Here's another bump for the Monkey's Audio package as #5717 failed because the upstream author removed the 6.11 zip.

mac: bump to 6.12

---

app-editors/jdtextedit/jdtextedit-8.2.recipe

I totally forgot that programs that are installed with setuptools also need setuptools to run.

jdTextEdit: Add setutools to dependencies

---

app-emulation/aranym/aranym-1.0.2.recipe
app-emulation/aranym/aranym-1.1.0.recipe
app-emulation/aranym/patches/aranym-1.1.0.patchset

Works ok, although this recipe should deserve more love
- Enabled UAE FPU emulation. IEEE emulation doesn't work (@pulkomandy do u know something about that?), but UAE is fine.
- Some minor performance tweaks
- JIT not enabled. This would greatly speed up the emulation, but i don't know if  this works under Haiku actually
All the most relevant optional features (ethernet bridging, disk sharing, etc.) still disabled.

Aranym: bump to 1.1.0

---

media-gfx/blender/blender-2.79b.recipe

Enforces usage of boost 1.69 on buildbots - versus boost 1.70 which breaks build.
Recipe needed to block the installation of boost 1.70 devel package.
[blender-2.79b_buildlog.txt](https://github.com/haikuports/haikuports/files/6062673/blender-2.79b_buildlog.txt)

blender: enforce boost 1.69 depend only build

---

net-misc/openssh/openssh-8.4p1.recipe

The configure tests have been fixed to work upstream.
Switch URL to canonical CDN URL which should be faster in most cases.

Re-enable compiler hardening and zlib check.

---

games-emulation/stella2014_libretro/stella2014_libretro-3.9.3_20210506.recipe
games-emulation/stella_libretro/additional-files/stella_libretro.info.in
games-emulation/stella_libretro/stella_libretro-6.5.3_20210508.recipe

stella2014_libretro: bump of this code, forked from the 2014 codebase of Stella. More stable but less accurate. Also faster on low-end systems.
stella_libretro: new recipe, straight from upstream. Might crash more, but more accuracy. Requires more powerful systems.

stella*_libretro: bump + new recipe

---

games-emulation/mame2003_plus_libretro/additional-files/mame2003_plus_libretro.info.in
games-emulation/mame2003_plus_libretro/licenses/MAME Non-Commercial
games-emulation/mame2003_plus_libretro/mame2003_plus_libretro-1.0_20210508.recipe

Based on a snapshot of the MAME codebase circa 2003 (v0.78), 'MAME 2003-Plus' is compatible with MAME 2003-Plus latest ROM sets. Contributors have backported support for an additional 350 games that are not included in the standard v0.078 ROM set, as well as other functionality not originally present in the underlying codebase. MAME 2003/-Plus cores have tighter integration with libretro features than the more modern snapshots and are significantly faster, though this comes at a substantial reduction in both accuracy and compatibility.

mame2003_plus_libretro: new recipe

---

games-engines/cannonball_libretro/additional-files/cannonball_libretro.info.in
games-engines/cannonball_libretro/cannonball_libretro-0.34_20210308.recipe
games-engines/cannonball_libretro/licenses/Cannonball

Cannonball is a program which allows you to play an enhanced version of Yu Suzuki's seminal arcade racer, OutRun, on a variety of systems. Cannonball is not an emulator; it is a complete rewrite of the original game into portable C++. This is the Libretro port of Cannonball.

cannonball_libretro: new recipe

---

games-emulation/neocd_libretro/additional-files/neocd_libretro.info.in
games-emulation/neocd_libretro/neocd_libretro-0.5_20210425.recipe

A rewrite of the original NeoCD emulator for SNK's NeoGeo CD console, ported to libretro. This core is intended to improve the accuracy of the original project, while still maintaining full/usable speed on low-powered hardware, such as the Raspberry Pi. It is easier to load games with than some of the other, more complex cores that support the NeoGeo CD platform, such as MAME and FBNeo.

neocd_libretro: bump

---

games-emulation/desmume_libretro/additional-files/desmume_libretro.info.in
games-emulation/desmume_libretro/desmume_libretro-0.9.11_20210512.recipe

A port of the mature and longstanding DeSmuME emulator for Nintendo's DS console to libretro. The core has very good compatibility and many modern features, including increased internal resolution (very demanding).

desmume_libretro: new recipe

---

games-emulation/sameboy_libretro/additional-files/sameboy_libretro.info.in
games-emulation/sameboy_libretro/sameboy_libretro-0.9.0_20210314.recipe

A port of the highly accurate Game Boy emulator, SameBoy, to libretro. This core has the highest accuracy of any Game Boy emulator and also supports a variety of fun features and improvements. While its requirements are higher than most other Game Boy cores, it is a good first choice for devices strong enough to run it full speed.

sameboy_libretro: new recipe

---

games-emulation/dosbox_pure_libretro/additional-files/dosbox_pure_libretro.info.in
games-emulation/dosbox_pure_libretro/dosbox_pure_libretro-0.13_20210514.recipe

A port of the mature and well-known DOSBox emulator to libretro with a goal of simplicty and ease of use. This core includes a streamlined workflow for launching games directly from ZIP archives (including disk images therein) with automated mapping of controls to gamepads and a native onscreen keyboard. This is a good core for most users who just want to play games and are not looking for a traditional DOS experience.
(64bit only because of keyb2joypad.cpp)

dosbox_pure_libretro: new recipe

---

app-emulation/tinyemu/patches/tinyemu-2019.12.21.patchset
app-emulation/tinyemu/tinyemu-2019.12.21.recipe

Pulls in @X547's [latest patch for x86-64](https://gist.github.com/X547/4d345a9ebe65ebc954baf13807cf61be) needed to run their [RISC-V Haiku port rev2](https://github.com/X547/Haiku-riscv/releases/tag/rev2).
Screenshot of their Haiku RISC-V port rev2 running inside a x86-64 Haiku install with the new patch:
Authored-by: X512 (@X547)

TinyEMU: X512 rev2 patch for x86-64

---

haiku-misc/pdfwriter/pdfwriter-1.0.recipe

Rebuilt on Haiku R1B2 (+134) x86_64. No build issues as of May 19, 2021.
Closes: https://dev.haiku-os.org/ticket/13313

pdfwriter: bump recipe

---

x11-libs/pango/pango-1.48.5.recipe
x11-libs/pango/patches/pango-1.48.5.patchset

the build system was changed to meson
also, use libVersion and libVersionCompat variables
test results: 5 of the tests crash, the others pass

pango: bump version and add missing REQUIRES_devel declarations

---

media-sound/mpg123/mpg123-1.25.15.recipe
media-sound/mpg123/mpg123-1.28.0.recipe

Update mpg123 versions to 1.28.0 and 1.25.15 (fox x86_gcc2).

mpg123: bump versions

---

media-sound/freac/freac-1.1.5.recipe

Update fre:ac revision to trigger new build after smooth 0.9.8 merge.
This should be merged after BoCA (#6024).

freac: bump revision to trigger new build

---

games-emulation/dosbox_pure_libretro/dosbox_pure_libretro-0.13_20210514.recipe

Thanks to help from @Begasus - this allows building the dosbox_pure libretro core on 32bit Haiku

dosbox_pure_libretro: enabled 32bit build

---

dev-libs/libpurple/libpurple-2.14.5.recipe

Pidgin's icons (including icons for protocols included with libpurple) might be useful to add to the port― this just pops them in.

libpurple, include icons

---

haiku-apps/ponyexpress/ponyexpress-0.1.1.recipe
haiku-apps/ponyexpress/ponyexpress-0.1.2.recipe

This is an app I've been working on for a little while now which lets you connect your Dropbox to Haiku and sync files, etc.
I'd like to get some more people using it and testing it at this point, although I'd recommend perhaps creating a new Dropbox account to use with it as it's still pretty early in development.
Comments, etc. welcomed and would appreciate if someone could test on x86 and gcc2 (I suspect GCC2 won't work as I've been a bit sloppy with the dev, assuming the pre-reqs work though I can try to get it building on GCC2 also.)

New recipe: PonyExpress

---

games-roguelike/scourge/patches/scourge-0.21.1.patchset
games-roguelike/scourge/scourge-0.21.1.recipe

Marked as ? as I can't seem to run the game:
```
~> scourge 
Constructing root path:
not using binreloc...
temp rootDir=/packages/scourge_x86-0.21.1-1/.self/data/scourge
*** Can't find local version of data dir. You're running a distribution.
Looking for localized resources in: /packages/scourge_x86-0.21.1-1/.self/data/scourge/translations
Starting session. Final rootDir=/packages/scourge_x86-0.21.1-1/.self/data/scourge
Setting video mode: 1024x768x32
GalliumContext: CreateScreen: Using llvmpipe (LLVM 5.0, 128 bits) driver.
Unlocking BLocker with sem 1841914 from wrong thread 65333, current holder -1 (see issue #6400).
```

scourge, new recipe

---

net-print/gutenprint/gutenprint9-5.3.4.recipe

Ref: https://dev.haiku-os.org/ticket/16300
Ref: https://github.com/haikuports/haikuports/issues/4980
NOTE: This just adds the packages to the repo. Needs kernel-side updates for newer API.

gutenprint: enable gutenprint9 build

---

sci-libs/openblas/openblas-0.3.17.recipe
sci-libs/openblas/patches/openblas-0.3.17.patchset

Run full build successfully, also launches digiKam, etc. without crashing.
I've also re-enabled AVX since this should be supported now, original issue for disabling it was here: https://github.com/xianyi/OpenBLAS/issues/1916 - this was due to Haiku not supporting AVX at all at the time.
It should be detecting the processor and using AVX if the processor supports it at runtime (basically compiles a bunch of different versions for various x64 cpu types.)  If anyone is concerned about this it can always be taken out again with some performance hit, although if we can find someone with a Prescott x64 CPU, eg. a Pentium 4F and derivative to test, this would be helpful.
Patch should be upstreamed to openblas project so will hopefully not be needed in future.  I can attempt a pull for this …

openblas: bump with patch

---

sci-libs/openblas/openblas-0.3.17.recipe

This will disable AVX512 kernels from building on x86_64 as it appears we do not support AVX512 in Haiku yet.

Openblas bump, remove AVX512

---

dev-scheme/guile/guile-2.2.7.recipe
dev-scheme/guile/guile1-1.8.8.recipe

further changes (for both guile1 and guile2):
* move man page also to tools as it concerns the interpreter
* define debuginfo for guile and the other than main libraries
- note: defining multple debuginfo packages is not possible using the predefined shell scriptlet
* add/fix compat versions for libraries

guile: move the guile interpreter tools to a 'tools' subpackage like guile1

---

media-libs/dav1d/dav1d-0.9.1.recipe

This brings high bit depth (10- and 12-bit) acceleration on amd64 and i686.
This has been tested against the AVIF translator.

dav1d: bump to 0.9.1

---

dev-scheme/guile/guile1-1.8.8.recipe

Fixes #5993
Also, fix the version number of libguile-readline in provides.

guile1: add version-less symlinks for the libraries to facilitate dynamically loading

---

dev-python/scipy/patches/scipy-1.6.3.patchset
dev-python/scipy/scipy-1.6.3.recipe

Python 3.8 and 3.9 versions are enabled.
Commented out ndimage import statement in stats module.
Did not test it on x86

scipy: enable x86_64, stats module fix

---

dev-util/radare2/radare2-5.4.0.recipe

The shlr lib is not suposed to be installed in the system, and the list after prepareInstalledDevelLibs was incomplete. i just updated this, is the CI going to verify that im not pushing something wrong? i dont have time for testing or learning how to build ports from haiku right now, so i would appreicate some help/feedback here if needed.
thanks

Blind fix for the radare2 pkg

---

dev-libs/glib/glib2-2.68.4.recipe
dev-libs/glib/patches/glib2-2.68.4.patchset

On an unrelated note, is it useful to keep all of the old versions here?  glib 2.x is fully backwards compatible from 2.0 (released in 2002) up until latest master, so maybe we could drop those?  I’m also not sure whether glib 1.x is still used anywhere, it has been removed from all Linux distributions I checked and isn’t maintained since 2002.

glib: bump to 2.68.4

---

net-analyzer/netperf/netperf-2.6.0.recipe
net-analyzer/netperf/patches/netperf-2.6.0.patchset

fix download url
add -lnetwork to configure script (and therefore autoreconf is needed now)
builds on 32-bit and 64-bit

netperf: fix build

---

haiku-apps/bescreencapture/bescreencapture-2.5.3.recipe

Bugfix release: Fixed crash / hang after recording many frames with virtual memory enabled
Also removed recipe for BeScreenCapture 2.5.1

Add recipe for BeScreenCapture 2.5.3

---

media-gfx/fig2dev/fig2dev-3.2.8b.recipe

This is an optional dependency of dblatex (see #6078).
Quite a number of tests fail when run via haikuporter that work when running it without. I don't know why.
Tested (building the package) on 64 bit (nightly) and 32 bit (beta 3)

new recipe: fig2dev

---

sys-devel/gcc/gcc-11.1.0_2021_04_27.recipe

It seems @pulkomandy have forgot about the 64 bit users. Lets fix it.

GCC 11: enable for every arch

---

sys-devel/gcc/gcc-8.3.0_2019_05_24.recipe

one more change that seems to be required for a successful arm bootstrap

gcc: enable build for arm

---

games-simulation/raceintospace/raceintospace-v2.0~git.recipe

*Race Into Space* (RIS) is a port to modern operating systems of *Buzz Aldrin’s Race Into Space* (BARIS), a DOS game originally released in 1993 on floppy disk, and a year later in an expanded CD version. BARIS was developed by Fritz Bronner based on his 1989 board game *Liftoff!*. Dr. Aldrin’s name and imagery have been dropped because permission to use them was limited to the old DOS game.
Screenshot of the game working on the latest `x86_64` nightly:

raceintospace: New recipe

---

sys-devel/gcc/gcc-11.2.0_2021_07_28.recipe

linking stack-protected objects on x86 would fail if -fstack-protector
wasn't passed to the linker. Only one symbol is missing, provided by
libssp_nonshared. So merge it in libgcc.a, which is always linked in.

GCC: fix -fstack-protector on x86

---

sys-devel/gcc/gcc-8.3.0_2019_05_24.recipe

This change is meant to (at least partially) tackle issue [#16763](https://dev.haiku-os.org/ticket/16763) and the comments from review [#4703](https://review.haiku-os.org/c/haiku/+/4703)
The libraries libgcc-boot.a, libgcc_eh-boot.a, libsupc++-boot.a are built and packaged similarly to the gcc_bootstrap recipe from haikuports.cross.
I checked it on x86_64 and x86 secondary architecture. The build completes successfully and the new *-boot.a files are added to gcc_syslibs_devel package.

gcc-8.3.0: build bootloader libraries

---

dev-lang/rust_bin/rust_bin-1.56.0.recipe
dev-lang/rust_wasm_bin/rust_wasm_bin-1.56.0.recipe

- This commit adds Rust 1.56.0
- It also adds the target for `wasm32-unknown-unknown` as a binary package
- The source version of Rust (dev-lang/rust) has not been updated for this release; it does not contain any patches that need to be recorded, and unfortunately builds still fail because of memory issues.
- This does not include the security fix in Rust 1.56.1 due to issues with my build setup. I find not including this acceptable (I will build an updated 1.57.0 in December).
- The wasm recipe is new and could use some scrutiny. The main recipe is a continuation of the previous stream of recipes.

Rust: add 1.56.0 with an additional package to support wasm32

---

sys-devel/gcc/gcc-8.3.0_2019_05_24.recipe

current recipe for gcc-8.3.0 has the same issue as we had on gcc11
using retroshare recipe as a "canary":
on rev.14 the build fails
on rev.15 retroshare build is successful again
if I check the package contents:
in rev.14 the files gthr-default.h and c++config.h are overwritten
this change restores these include files to their previous state

gcc-8.3.0: fix headers after building boot libraries

---

haiku-apps/bescreencapture/bescreencapture-2.6.0.recipe

Add recipe for BeScreenCapture 2.6.0
Removed recipe for version 2.5.2

BeScreenCapture: bump version

---

app-benchmarks/stress-ng/patches/stress_ng_x86-0.13.05.patchset
app-benchmarks/stress-ng/stress_ng-0.13.05.recipe

Disabling stress-icache on x86 as runtime_loader complains
about an "unreasonable amount of unused space."
see also issue #6428 
No such problem on x86_64 so stress-icache is still enabled there.

stress-ng: add x86 as secondary architecture

---

app-misc/nnn/nnn-4.3.recipe

[Changelog](https://github.com/jarun/nnn/releases)

nnn: bump to 4.3

---

sys-devel/llvm/llvm12-12.0.0.recipe

This is related to issue #3749. The fixed packages were tested on x86_64 by
building a couple of language servers(ccls and irony-server) which use these
library paths.

llvm12: adjust cmake library paths

---

media-sound/freac/freac-1.1.6.recipe

This needs to be merged after BoCA 1.0.6a.

freac: bump to 1.1.6

---

dev-util/ninja/ninja-1.10.2.recipe

Maybe there is a better way to enforce CMAKE_BUILD_TYPE.  haikuporter gets very unhappy even if you use the command as a build/install tool.

ninja: fix build and add zsh subpackage

---

app-office/libreoffice/libreoffice-7.2.0.4.recipe
app-office/libreoffice/patches/libreoffice-7.2.0.4.patchset

patch was taken directly from the upstream 7.2 branch of the libreoffice repo
I was able to successfully build, package, install, and run on x86_64.  I can also look into the x86 build issues but I'm not sure when I'll have the time.  Could be tomorrow or later in the week.

LibreOffice: fix building with newer bison

---

app-office/scribus/scribus-1.5.7.recipe

The new poppler package is using some c++17 features so we need to enable that in the scribus recipe.  Successfully packaged and installed on both x86_64 and x86.

scribus: fix build for new poppler

---

app-emulation/wasm3/patches/wasm3-0.5.0.patchset
app-emulation/wasm3/wasm3-0.5.0.recipe

the following recipe adds the [wasm3](https://github.com/wasm3/wasm3) interpreter. tested that package built and was able to install and uninstall on x86-64 Haiku (hrev55602)
sample test run (borrowed from [cookbook](
https://github.com/wasm3/wasm3/blob/main/docs/Cookbook.md))
```
~/hellowasm> uname -a
Haiku shredder 1 hrev55602 Oct 29 2021 07:10:38 x86_64 x86_64 Haiku
~/hellowasm> cat hello.zig 
const std = @import("std");
pub fn main() !void {
const stdout = std.io.getStdOut().writer();
try stdout.print("Hello, {s}!\n", .{"world"});
}
~/hellowasm> zig build-exe -O ReleaseSmall -target wasm32-wasi hello.zig
~/hellowasm> wasm3 hello.wasm
Hello, world!
~/hellowasm> 
```

wasm3: new recipe

---

media-libs/x265/x265-3.4.recipe

The recipe for x265-3.4 needed a fix for enabling asm optimizations using nasm.
This PR fixes this.

x265: enable asm

---

media-libs/x265/patches/x265-3.4.patchset
media-libs/x265/x265-3.4.recipe

Allow for x265 proper detection of actual number of cpu cores, instead of using default (2).

x265: fix detection of cpu cores

---

app-text/hoedown/hoedown-3.0.7.recipe

the following recipe adds support for [hoedown](https://github.com/hoedown/hoedown) which includes the hoedown and smartypants utility as well.
sample run:
```
> uname -a
Haiku shredder 1 hrev55910 Feb 26 2022 07:26:08 x86_64 x86_64 Haiku
> hoedown --version
Built with Hoedown 3.0.7.
> smartypants --version
Built with Hoedown 3.0.7.
```

hoedown: new recipe

---

net-misc/lagrange/lagrange-1.11.2.recipe

lagrange: bump to 1.11.2

---

media-sound/fluidsynth/fluidsynth2-2.1.8.recipe
media-sound/fluidsynth/patches/fluidsynth2-2.1.8.patchset

The changes in question add a MidiKit2 backend to FluidSynth2.
I also got rid of the period size mangling code in the MediaKit backend since it doesn't actually seem to be needed and causes high latency issues in audio output and also added support for 32-bit float format.

fluidsynth2: MidiKit2 support and MediaKit backend improvements

---

dev-lang/rust_bin/rust_bin-1.60.0.recipe

Add Rust 1.60.0. Unfortunately the wasm target does not build, so no updated recipe for that this time.

Rust: add version 1.60.0

---

app-misc/nnn/nnn-4.5.recipe

[Changelog](https://github.com/jarun/nnn/releases)

nnn: bump to 4.5

---

net-misc/lagrange/lagrange-1.13.2.recipe

lagrange: bump to 1.13.2

---

dev-lisp/newlisp/newlisp-10.7.5.recipe
dev-lisp/newlisp/patches/newlisp-10.7.5.patchset

the following recipe adds newlisp as a package.
sample run posted below:
```
> newlisp -h
newLISP v.10.7.5 Copyright (c) 2016 Lutz Mueller. All rights reserved.
usage: newlisp [file | url ...] [options ...] [file | url ...]
options:
-h this help (no init.lsp)
-n no init.lsp (must be first)
-x <source> <target> link (no init.lsp)
-v version
-s <stacksize>
-m <max-mem-MB> cell memory
-e <quoted lisp expression>
-l <path-file> log connections
-L <path-file> log all
-w <working dir>
-c no prompts, net-eval, HTTP
-C force prompts
-t <usec-server-timeout>
-p <port-no>
-d <port-no> daemon mode
-http only mode
-http-safe safe mode
-6 IPv6 mode
more info at http://newlisp.org
> newlisp
newLISP v.10.7.5 64-bit on Haiku IPv4/6 UTF-8, options: newlisp -h
> 
```

newlisp: new recipe

---

dev-python/python-poppler-qt5/patches/python_poppler_qt5-21.1.0.patchset
dev-python/python-poppler-qt5/python_poppler_qt5-21.1.0.recipe

This is one of the dependencies of [Frescobaldi](https://www.frescobaldi.org/), a GUI editor for Lilypond based on PyQt5.
I modelled the recipe after pyqtwebengine5. It contained a few statements that are not clear to me, maybe @extrowerk can explain that. I left them in as comments for now.
The included patch is a build fix and is taken directly from an upstream pull request (https://github.com/frescobaldi/python-poppler-qt5/pull/45).
I haven't tested this in any way right now, it just builds successfully on x86_64. The real test will be Frescobaldi, once that is running, but that is still multiple steps away ...

python-poppler-qt5: new recipe

---

net-libs/libslirp/libslirp-4.7.0.recipe
net-libs/libslirp/patches/libslirp-4.7.0.patchset

Left untested for gcc2 because I don't have a gcc2 system.
Adding as it is a dependency of melonDS.

Add libslirp

---

dev-python/python-ly/python_ly-0.9.7.recipe

This is another dependency for Frescobaldi.
I enabled python3 (3.7), python38, python39 and python310 versions. The python3 version uses no suffix for the commands (as it is kind of the "default" version), the others are suffixed with the version number (38, 39, 310).
The documentation is not built and packaged. Should that be added? (edit: that would require Sphinx, which seems not to be available yet ...)

new recipe: python-ly

---

dev-lisp/sbcl/patches/sbcl-2.2.4.patchset
dev-lisp/sbcl/sbcl-2.2.4.recipe

this updates sbcl port to track the latest release. note that this release
* uses previous bootstrapped sbcl for compilation
* remove abcl and jvm bootstrap dependency for bootstrap
```
~> sbcl
This is SBCL 2.2.4-WIP, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.
SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
WARNING: :HAIKU is no longer present in *FEATURES*
*
```

sbcl: bump version

---

app-text/dblatex/dblatex-0.3.12.recipe

This is a python script to convert DocBook to LaTeX.
It is another (optional) dependency of LilyPond.
Note: this depends on texlive and can therefore not be built as long as that is disabled.

new recipe: dblatex

---

media-sound/lilypond/lilypond-2.22.2.recipe
media-sound/lilypond/patches/lilypond-2.22.2.patchset

~Tests fail because of missing `extractbb` command (which should be provided by `texlive_core`).~ fixed in 29e1618 in #6818 
It also cannot be built right now as long as `texlive` is not available (should it be marked as untested?). Texlive is only required for building, not at runtime.
The libgs API is used instead of the GhostScript executable because that crashes on Lilypond's PostScript output (see #6284).

new recipe: lilypond

---

media-libs/opencv/opencv-4.5.5.recipe
media-libs/opencv/patches/opencv-4.5.5.patchset

As mentioned in https://github.com/haikuports/haikuports/pull/6854 `opencv` needs to be rebuilt as part of `gdal` version bump.

opencv: update recipe for 4.5.5

---

app-text/grcompiler/grcompiler-5.2.1.recipe
app-text/grcompiler/licenses/CPL v05

the following recipe adds support for the [Graphite compiler](http://graphite.sil.org/) 
sample run below:
```
> uname -a
Haiku shredder 1 hrev56098 May 13 2022 08:04:13 x86_64 x86_64 Haiku
> grcompiler --help
Graphite Compiler Version 5.2.1  [release build]
Copyright (c) 2002-2021, by SIL International.  All rights reserved.
usage: grcompiler [options] gdl-file input-font-file [output-font-file] [output-font-name]
Options:
-c       - compress graphite tables
-d       - output XML debugger file
-D       - output all debugger files
-e       - error message file; gdlerr.txt by default
-g       - permit and ignore invalid glyph definitions
-nNNNN   - set name table start location
-p       - omit pass-avoidance optimizations
-q       - quiet mode (no messages except on error)
-vN      - set …
```

grcompiler: new recipe

---

media-sound/picard/patches/picard-2.8.patchset
media-sound/picard/picard-2.8.recipe

New release of MusicBrainz Picard, see https://blog.metabrainz.org/2022/05/24/picard-2-8-released/
As usual build and tested locally on 64bit.

picard: release 2.8

---

games-arcade/plee_the_bear/plee_the_bear-0.7.1.recipe

No need for revbump (recipe still disabled, crashes on launch), addresses issue: https://github.com/haikuports/haikuports/issues/3779

plee_the_bear, fix references to libpng16 and libSDL*

---

games-engines/openmw/openmw-0.47.0.recipe

No rebuild, getting `internal compiler error` in 32bit when trying to build.

openmw, fix reference to libpng16

---

app-misc/neo/neo-0.6.1.recipe

the following adds the neo program as a port. sample run below:
```
> uname -a
Haiku shredder 1 hrev56137 May 27 2022 06:24:51 x86_64 x86_64 Haiku
> neo --help
Usage: neo [OPTIONS]
Simulate the digital rain from "The Matrix"
Options:
-a, --async            asynchronous scroll speed
-b, --bold=NUM         control character boldness
-C, --colorfile=FILE   read the colors from a file
-c, --color=COLOR      select the foreground text color
-D, --defaultbg        use the default terminal background color
-d, --density=NUM      set the density of droplets
-F, --fullwidth        use two columns per character
-f, --fps=NUM          set the frames per second target/limit
-G, --glitchpct=NUM    set the percentage of screen chars that glitch
-g, --glitchms=NUM1,2  control how often characters glitch …
```

neo: new recipe

---

net-misc/lagrange/lagrange-1.13.6.recipe

lagrange: bump to 1.13.6

---

media-gfx/xcftools/patches/xcftools-1.0.7.patchset
media-gfx/xcftools/xcftools-1.0.7.recipe

Checked on both 32bit and 64bit, 13 out of 139 tests failed, 2 tests crash (those are removed in the patchset).
I tried to import an upstream PR and it works, but throws extra warnings and 5 extra failed tests on 32bit (and another crashing test on 32bit).

xcftoolx, new recipe

---

media-gfx/tuxpaint/patches/tuxpaint_sdl2-0.9.28.patchset
media-gfx/tuxpaint/tuxpaint_sdl2-0.9.28.recipe

Keeping the older version that still uses SDL1.2, current version has issues with SDL1.2 and support for that will end at some point.

tuxpaint, bump version, use SDL2 now

---

net-misc/krb5/krb5-1.20.recipe
net-misc/krb5/patches/krb5-1.20.patchset

Recipe for krb5-1.20 added.
Build and tests are running well on x86_64 and x86_gcc2 (with secondary x86 architecture). Building on gcc2 is currently failing due to the compiler not supporting some flags.
Thanks to @jessicah for some of the patches in order to get this building properly.
I haven't made any recipe for more than 2 years, sorry if I did something wrong...

krb5: Added recipe for krb5-1.20

---

sys-devel/gcc/gcc-11.2.0_2021_07_28.recipe
sys-devel/gcc/patches/gcc-11.2.0_2021_07_28.patchset

This commit adds the patch submitted [here](https://review.haiku-os.org/c/buildtools/+/5434) to Haiku's GCC toolchain on HaikuPorts.
It has been tested. On the terminal is the output of `readelf --headers test`, where `test` is a binary compiled using a `gcc` built with this recipe.

gcc: Pass --eh-frame-hdr to linker by default

---

games-simulation/openttd/openttd-12.2.recipe
games-simulation/openttd_gfx/openttd_gfx-7.1.recipe
games-simulation/openttd_msx/openttd_msx-0.4.2.recipe
games-simulation/openttd_sfx/openttd_sfx-1.0.3.recipe

Update openttd and its asset packages to the latest version. Upstream
development switched to a new CDN and changed their build system to
CMake, so changes are somewhat more significant than just a version
bump.
Briefly tested and basic functionality seems to work. Saving/loading
games works. Downloading content through their system also works.
Did not confirm whether network play works, although I'm able to browse
the server list.
I considered fiddling with getting their SDL2 build working, but the SDL1
build seems fully functional and upstream supports both so I decided to
stop here and see if anyone here had feedback on whether that is even
desirable.
I've only been using Haiku for a week or so and this is my first time
working with the packaging system, so I look forward to feedback …

Update openttd, openttd_gfx, openttd_sfx, openttd_msx

---

sci-libs/geos/geos-3.11.0.recipe

[Version 3.11.0 released](https://libgeos.org/posts/2022-07-01-geos-3-11-0-released/)

geos: bump to 3.11.0

---

dev-python/pymupdf/pymupdf-1.20.2.recipe

This fixes one of the issues with #7125 and should allow pymupdf to build on 32-bit.

pymupdf: add $secondaryArchSuffix to swig to fix 32-bit build

---

haiku-apps/documentviewer/documentviewer-0.3~git.recipe

This adds a version requirement for libmupdf to the DocumentViewer recipe, which should force it to rebuild as per @korli's advice on #7125.

documentviewer: add version requirement for mupdf

---

sci-geosciences/josm/josm_bin-18543.recipe

[2022-08-30: Stable release 18543](https://josm.openstreetmap.de/wiki/Changelog#stable-release-22.08)

JOSM: bump to 18543
