haikuports/haikuports

net-firewall/hblock/hblock-2.1.6.recipe
=> hblock: new recipe

dev-lang/fpc/fpc-3.0.4.recipe
Mostly done at last year Haiku coding sprint.
=> Finally found some time to push a full source fpc recipe.

dev-lang/64tass/64tass-1.55.2202.recipe, dev-lang/64tass/64tass-1.55.recipe, dev-lang/64tass/licenses/my_getopt
Small fix in version number to be "compliant" with repology
=> 64tass: fix version number

games-emulation/snes9x_libretro/snes9x_libretro-1.60_20200106.recipe
=> snes9x_libretro: bump to 1.60

games-emulation/nestopia_libretro/nestopia_libretro-1.49_20200510.recipe
Complete rewrite of core by RetroArch authors.
=> nestopia_libretro: bumped to version 1.49:20200510

dev-libs/nss/nss-3.46.1.recipe, dev-libs/nss/patches/nss-3.46.1.patchset
Reverts haikuports/haikuports#5003
=> Revert "nss: add NSS 3.52.1 recipe"

dev-util/cppcheck/cppcheck-1.87.recipe
=> cppcheck: make settings files/dir writable

dev-util/kdevelop/kdevelop-5.4.6.recipe
Verified build on hrev54415 x86_64.
Closes: https://github.com/haikuports/haikuports/issues/5190
=> kdevelop: trigger build

dev-util/cppcheck/cppcheck-1.87.recipe
=> cppcheck: only list individual files as writable

media-libs/assimp/assimp-5.0.1.recipe, media-libs/assimp/patches/assimp-5.0.1.patchset
Changelog:
- Bump to 5.0.1, builds fine
- Added a TEST() block with provided unit tests; all tests passed
- Added doxygen build to $developDocDir
=> assimp: bump to 5.0.1

media-sound/picard/patches/picard-2.4.patchset, media-sound/picard/picard-2.4.recipe
New upstream release 2.4
See https://blog.metabrainz.org/2020/08/10/picard-2-4-released/
=> picard: release 2.4

app-misc/nnn/nnn-3.4.recipe
As a heads up, I'm now also officially a contributor to the nnn project! Also, as mentioned in the commit message, I had to add a patch section, as I thought one could make comments in a rdef file using the "#" character :S.
=> nnn: Bump to version 3.4

dev-python/attrs/attrs-20.2.0.recipe
Still some recipes depending on python 2.7 for this
=> attrs, bump version

dev-libs/libmodbus/libmodbus-3.0.8.recipe, net-libs/libmodbus/libmodbus-3.0.8.recipe
=> new recipe: Libmodbus

dev-libs/libmodbus/libmodbus-3.1.6.recipe
i'm just realized that there is another newer version of libmodbus..
=> Update libmodbus: bump version

games-roguelike/sais/sais-1.6.3~git.recipe
[*Strange Adventures in Infinite Space*](https://rich.itch.io/strangeadventures) (SAIS) is one of the first roguelikes made with the genre of science fiction in mind. Now it comes to Haiku via this recipe, based on the [updated GPL source code](https://github.com/kuroneko/sais).
It should be noted that the game needs to be killed manually, as exiting it normally will just blank out the window.
The GPL v3 source code comes with the assets, which are under the different CC-BY-NA 4.0 license. Does that need to be indicated in the recipe in some way or is that unnecessary?
=> SAIS: Add recipe

net-p2p/transmission/additional-files/transmission.rdef.in
Possible fix for the crash at shutdown.
=> Transmission crashfix

app-shells/xonsh/xonsh-0.9.23.recipe
Related problem: https://github.com/xonsh/xonsh/issues/3882
=> Xonsh 0.9.23

dev-lang/rust/patches/rust-1.48.0.patchset, dev-lang/rust/rust-1.48.0.recipe, dev-lang/rust_bin/rust_bin-1.48.0.recipe
This replaces the previous PR for 1.47.0
=> Rust: add version 1.48.0

dev-lang/ruby/patches/ruby-2.7.2.patchset, dev-lang/ruby/ruby-2.7.2.recipe
This should work without any existing ruby.
=> Ruby 2.7.2

sci-libs/scipy/patches/scipy-1.3.3.patchset, sci-libs/scipy/scipy-1.3.3.recipe
solves #4431
Recipe has following limitations:
- ndimage module is disabled
- no x86 build
- stuck on 1.3.3 version, newer falls
BTW, existing recipe doesn't work for me at all, donno why.
=> scipy: python3 recipe

media-video/vlc/vlc-3.0.11.1.recipe
*UNTESTED, unable to test, because "waiting for build package". Removing the worl folder doesn't helps.
Somebody please fix haikuporter or package daemon, this is a really annoying bug.
=> VLC: enable libass, cleanup

sci-geosciences/gpxsee/additional-files/gpxsee.rdef.in, sci-geosciences/gpxsee/gpxsee-8.0.recipe, sci-geosciences/gpxsee/patches/gpxsee-8.0.patchset
[Changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes)
=> GPXSee: bump to 8.0

media-plugins/audacious-plugins/audacious_plugins-4.0.5.recipe, media-sound/audacious/audacious-4.0.5.recipe
=> Audacious: fixed copyright and license

app-arch/zpaq/licenses/zpaq, app-arch/zpaq/zpaq-7.15.recipe
Attempt number two, after I messed up last time and had to delete the branch.
=> zpaq: new recipe

dev-python/astroid/astroid-2.4.0.recipe
Made a mistake when pushing this package yesterday (#5565).
It's missing dependencies which I ignored that aren't in the repo yet... Will work on fixing these. 
Sorry for the mistake!
=> astroid: disable package

sys-devel/make/make-4.3.recipe, sys-devel/make/patches/make-4.3.patchset
Some test fails, but can't check the current recipe, as the test fails with different error.
```
------------------------------------------------------------------------------
Running tests for GNU make on Haiku shredder 1 x86_64
GNU Make 4.3
------------------------------------------------------------------------------
Finding tests...
features/archives ....................................... ok     (12 passed)
features/comments ....................................... ok     (1 passed)
features/conditionals ................................... ok     (5 passed)
features/default_names .................................. ok     (3 passed)
features/double_colon ................................... 
Test timed out after 5 seconds
Error running /sources/make-4.3/tests/../make (expected 0; got …
```
=> make: bump

sys-libs/hwloc/hwloc-1.11.11.recipe, sys-libs/hwloc/hwloc2-2.3.0.recipe, sys-libs/hwloc/hwloc2-2.4.0.recipe
All test passes, but only outside of haikuporter.
Kept the full old version.
=> hwloc: bump

dev-libs/mpfr/mpfr-4.1.0.recipe, dev-libs/mpfr/mpfr3-3.1.6.recipe
AFAIK the patch is not needed anymore.
=> MPFR: bump

dev-python/pygame/patches/pygame-1.9.4.patchset, dev-python/pygame/pygame-1.9.4.recipe
@extrowerk reviving this until there is a sollution for monsterz (didn't find one so far)
```
monsterz-0.7.1-1-x86_gcc2.hpkg:
requires "pygame" of package "monsterz-0.7.1-1" could not be resolved
```
=> pygame, revive python2 version (x86_gcc2 only) for monsterz

games-simulation/simutrans/patches/simutrans-120.4.1.patchset, games-simulation/simutrans/simutrans-120.4.1.recipe
Closes: https://github.com/haikuports/haikuports/issues/5574
=> simutrans: fix build for Haiku R1B2

dev-python/jdtranslationhelper/jdtranslationhelper-2.1.recipe
This is just a small Python library made by me which is used in my programs. It needed to be in the repo to port my programs like [jdTextEdit](https://discuss.haiku-os.org/t/jdtextedit-a-advanced-text-editor/10359). I had modified a recipe for a python package, so I hope everything is OK.
=> jdTranslationHelper: Add recipe

dev-lang/duktape/duktape-2.6.0.recipe
=> Duktape: new recipe

dev-python/pyenchant/pyenchant-3.2.0.recipe
pyencahnt provides Python bindings to the enchant library.
=> pyenchant: Add recipe

media-libs/libopenmpt/libopenmpt-0.5.5.recipe
=> LibOpenMPT: bump

www-client/kristall/kristall-0.7.3~git.recipe
Updates Kristall to https://github.com/MasterQ32/kristall/commit/ba7f39e9f0f329e78710c67e1267c1fbc79ac428, adding some notable changes such as:
* [Use PageUp/Down to switch between tabs](https://github.com/MasterQ32/kristall/commit/a6aecaaa63037023e027f1273f99375f5067638c)
* [Added '+' button to tab bar](https://github.com/MasterQ32/kristall/commit/2091b038ef2a23a85d30d056307b3c405c416256)
* [New-tab button: add preference](https://github.com/MasterQ32/kristall/commit/17a90d8dde55c5f0adc230c1a78da3dd2f8af995)
* [BrowserTab: add Stop/Refresh action to the menu](https://github.com/MasterQ32/kristall/commit/9fffc1ca149c832dcf721d0de38248bb16528b23)
* [Add Ctrl+R reload page shortcut](https://github.com/MasterQ32/kristall/commit/d77f5f1066f21fb047c7d9dec84c28b06aa1c7a6)\*
* [Basic caching …
=> Kristall: Reload shortcut, caching, tab changes, and more

app-misc/jdreplace/jdreplace-2.2.recipe
jdReplace is small mass replacement toll that I had written in 2019.
=> jdReplace: Add Recipe

dev-python/scipy/scipy-1.3.3.recipe
Enough time spent on this, if someone can find a solution to bring this up to python version >= 3.7 I'm around :)
=> scipy, mark as broken on all arch's

media-libs/libavif/libavif-0.8.4.recipe
This has now been tested to work on x86_64!
=> libavif: bump to 0.8.4

dev-lang/rust/patches/rust-1.49.0.patchset, dev-lang/rust/patches/rust-1.50.0.patchset, dev-lang/rust/rust-1.49.0.recipe, dev-lang/rust/rust-1.50.0.recipe, dev-lang/rust_bin/rust_bin-1.49.0.recipe, dev-lang/rust_bin/rust_bin-1.50.0.recipe
As requested, the Rust recipe now explicitly requires python3.
=> Rust haiku 1.50.0

gnome-base/librsvg/librsvg-2.50.3.recipe, gnome-base/librsvg/patches/librsvg-2.50.3.patchset
Not tested on x86_64, would be nice if someone could check this out there before merging, @mazbrili could you check this out for tuxpaint (having some issues here atm with this version and previous, it worked ok before, so not sure what's going on there now)
=> librsvg, bump version, kudos to nielx for the help

media-gfx/tuxpaint/tuxpaint-0.9.25.recipe
enable svg , so svg stamp can be loaded
=> [tuxpaint]  Update tuxpaint enable svg 

haiku-apps/medo/medo-1.0.0~beta1.2.recipe
Fixed some capitalization and added a paragraph pointing out Medo's
beta status. I think that's important so people don't expect a
polished product, but are amazed at its powerful features at this stage.
=> Medo: Improved description

net-misc/gerbera/additional-files/config.xml, net-misc/gerbera/gerbera-1.7.0~git.recipe, net-misc/gerbera/patches/gerbera-1.7.0~git.patchset
Still cant't find its sql file:
```
error: File '/packages/gerbera-1.7.0~git-1/.self/share/gerbera/sqlite3.sql' does not exist
```
Good luck grepping for "share" in the sources of a media sharing program :(
=> Gerbera: bump

media-gfx/blender/blender-2.79b.recipe
Blender 2.79b-22 package running on Haiku R1B2 x86.
closes #5500
[blender-2.79b_x86-buildlog.txt](https://github.com/haikuports/haikuports/files/6055094/blender-2.79b_x86-buildlog.txt)
=> blender: Fixed x86 build

app-editors/jdtextedit/jdtextedit-8.3.recipe
Looks like I missed a 2 at start
=> jdTextEdit: fix checksum

media-video/ffmpeg/ffmpeg-4.2.2.recipe
None requires the --enable-gpl switch, seems to be working ok on 64 bit.
=> FFMPEG: enable some 3rdparty libs

media-libs/embree/embree-3.12.1.recipe, media-libs/embree/patches/embree-3.12.1.patchset
=> Embree3: bump, cpucount

sys-libs/hwloc/hwloc2-2.4.1.recipe
=> hwloc, bump version

dev-python/fasteners/fasteners-0.16.recipe
Package for the Python fasteners module, see https://pypi.org/project/fasteners/
Will be needed for an update of MusicBrainz Picard.
=> package for python fasteners

media-sound/picard/patches/picard-2.6.patchset, media-sound/picard/picard-2.6.recipe
New upstream release 2.6.
Requires https://github.com/haikuports/haikuports/pull/5809
=> picard 2.6

haiku-apps/kottan/kottan-0.10.8.recipe
new recipe for the Kottan BMessage file viewer and editor
=> [New recipe] Kottan 0.10.8

app-misc/nnn/nnn-4.0.recipe
[Changelog](https://github.com/jarun/nnn/releases)
=> nnn: bump to 4.0

games-fps/prboom-plus/patches/prboom_plus-2.5.1.4.patch, games-fps/prboom-plus/prboom_plus-2.5.1.4.recipe
My first contribution, let me know if anything needs to be changed :)
=> prboom-plus: New Recipe

sys-power/iasl/iasl-20210331.recipe
=> iasl: bump

app-backup/luckybackup/luckybackup-0.5.0.recipe, app-backup/luckybackup/patches/luckybackup-0.5.0.patchset
Luckybackup enable extended attribute backup
=> [Luckybackup] enable extended attribute

dev-scheme/chicken/chicken-5.2.0.recipe
=> chicken: bump version

games-fps/tyrquake_libretro/additional-files/tyrquake_libretro.info.in, games-fps/tyrquake_libretro/patches/tyrquake_libretro-0.62_20210410.patchset, games-fps/tyrquake_libretro/tyrquake_libretro-0.62_20210410.recipe
Bump to latest upstream version. Fixed build issue.
=> tyrquake_libretro: bump

games-emulation/mesen_libretro/additional-files/mesen_libretro.info.in, games-emulation/mesen_libretro/mesen_libretro-0.9.4_20210310.recipe, games-emulation/mesen_libretro/mesen_libretro-0.9.4_20210510.recipe
Mesen is a highly accurate NES emulator. With great accuracy comes great resource requirements (relative to other NES emulators, at least), so this core is not a great choice for weak mobile devices or other low-power/embedded platforms. However, it is the best choice for users who seek the most accurate reproduction of the NES hardware. Mesen also supports some fun enhancements, such as HD sprite replacement packs. This is the libretro port of Mesen.
=> mesen_libretro: new recipe

games-puzzle/blobwars/blobwars-1.19.recipe, games-puzzle/blobwars/blobwars-2.00.recipe
Fixing https://repology.org/repository/haikuports_master/problems
=> blobwars, update HOMEPAGE

dev-util/boost_build/boost_build-1.64.0.recipe
Fixes: https://repology.org/repository/haikuports_master/problems
=> boost_build, update HOMEPAGE

net-libs/libquotient/libquotient-0.6.6.recipe
Authored-by: Pascal Abresch (nephele)
=> libquotient, new recipe

media-fonts/tex_gyre/licenses/GUST-FONT-LICENSE, media-fonts/tex_gyre/tex_gyre-2.501.recipe
=> tex_gyre fonts: new recipe

dev-libs/libgnt/libgnt-2.14.1.recipe, dev-libs/libgnt/patches/libgnt-2.14.1.patchset
libgnt's required for Finch, but was recently moved into its own repository― so here's its own recipe.
(It's my first, probably a good few problems here)
=> libgnt: add recipe

www-client/netsurf/netsurf-3.10.recipe, www-client/netsurf/patches/netsurf-3.10.patchset
=> Netsurf: fixed build for R1B3

dev-libs/highway/highway-0.12.2.recipe
In preparation for https://github.com/haikuports/haikuports/issues/6041
=> highway, new recipe

media-fonts/urw_base35_fonts/licenses/AGPL-3.0, media-fonts/urw_base35_fonts/licenses/URW Font License, media-fonts/urw_base35_fonts/urw_base35_fonts-20200910.recipe
This one is another font package.
Lilypond has an optional dependency on these OTF fonts.
This package also contains fontconfig files. Should these also be included in the package (maybe as a subpackage)?
=> new recipe: URW++ Base35 fonts (from Ghostscript)

games-simulation/simutrans/patches/simutrans-122.0.patchset, games-simulation/simutrans/simutrans-122.0.recipe
=> simutrans: Refreshed to 122.0 r9937

haiku-apps/medo/medo-1.0.0~beta1.4.recipe
Update Source URI for Beta 1-4.2
=> Update to R1.0.0-Beta1-4.2

games-roguelike/crawl/crawl-0.27.0.recipe, games-roguelike/crawl/licenses/crawl, games-roguelike/crawl/patches/crawl-0.27.0.patchset
(Patch will be submitted upstream after this gets merged)
=> crawl: new recipe

games-roguelike/crawl/crawl-0.27.0.recipe, games-roguelike/crawl/patches/crawl-0.27.0.patchset
Fixes crash when accessing instructions from in-game
=> crawl: fix docs

app-misc/nnn/nnn-4.2.recipe
[Changelog](https://github.com/jarun/nnn/releases)
=> nnn: bump to 4.2

net-im/purple_discord/purple_discord-20210729.recipe
Had a go at porting a libpurple plugin, probably got a good bit wrong here.
=> purple_discord: add recipe

dev-vcs/fossil/fossil-2.16.recipe
Additional changes from the fossil-2.10 recipe:
- Updated the copyright
- Added $jobArgs to the `make` command in the BUILD()
=> Fossil: Update to version 2.16

sci-libs/libnova/libnova-0.16.0.recipe
=> Libnova 0.16.0

haiku-apps/jxl_translator/jxl_translator-0.1.0.recipe
@Begasus please check this one :)
=> New recipe: JXL Translator

CONTRIBUTING.md
First pass at making a CONTRIBUTING.md doc for HaikuPorts and HaikuArchives.
=> Initial creation of CONTRIBUTING.md

games-sports/speed-dreams/patches/speed_dreams-2.2.3.patchset, games-sports/speed-dreams/speed_dreams-2.2.3.recipe
Enable speed_dreams 2.2.3 for x86 and x86_64
=> speed_dreams: enable recipe

net-misc/lagrange/lagrange-1.7.1.recipe, net-misc/lagrange/patches/lagrange-1.7.1.patchset
=> lagrange: bump to 1.7.1

app-editors/featherpad/featherpad-1.0.1.recipe
=> featherpad: bump version

dev-java/abcl/abcl-1.8.0.recipe
add Armed Bear Common Lisp (Java-based lisp)
=> abcl: new recipe

media-gfx/zbar/zbar-0.23.90.recipe
Adds a recipe for [zbar](http://zbar.sourceforge.net/) providing:
* Main package: cmd:zbarimg - command line program to scan QR codes & barcodes in image files
* Devel package: lib:libzbar - C library/headers exposing API to scan barcodes & QR codes
Currently builds package without GTK, QT, or Python support.
=> Added zbar recipe, first revision.

haiku-apps/kottan/kottan-0.14.3.recipe
- links against libcolumnlistview directly 
- added new and updated language translations
=> Kottan: new maintenance release 0.14.3 

sys-devel/gcc/gcc-11.2.0_2021_07_28.recipe
beware: I haven't checked it on x86 secondary arch yet
=> gcc-11.2.0: build bootloader libraries

app-benchmarks/bonnie++/bonnie++-2.00a.recipe, app-benchmarks/bonnie++/patches/bonnie++-2.00a.gcc2.patchset, app-benchmarks/bonnie++/patches/bonnie++-2.00a.patchset
builds on 32-bit and 64-bit.
i just tried it with small file size to see there's no crash etc, haven't checked the output
please feel free to hit me with some constructive feedback for bon_csv2html.cpp as clearly i don't know what i'm doing :)
=> bonnie++: bump to version 2.00a

app-cdr/cdrtools/cdrtools-3.02~a09.recipe, app-cdr/cdrtools/patches/cdrtools-3.02-clonable-area.patch
as suggested by waddlesplash, thanks!
=> cdrtools: patch cdrecord to use B_CLONABLE_AREA

app-emulation/virtualbox-guest-additions/patches/virtualbox_guest_additions-6.1.26.patchset, app-emulation/virtualbox-guest-additions/virtualbox_guest_additions-6.1.26.recipe
I need to take a break from this one so sharing in case someone else wants to pick it up or help - tested on x64, needs testing on x86.  It may not build at all on x86 which is probably some sort of compiler values that need tweaking.
Enabled: video, mouse, shared folders, tray, console apps (service and control.)
Notes:
Tray:
Crashes on Quit or during shutdown if Quit before shutdown.
NB. you need to run this to enable shared clipboard and the video resizing
Shared folders:
Seems to work generally although Tracker is not updating after deletes, renames, etc.  tried messing about with put nodes and notifications but kind of stuck here.  There's an issue with deleting directories too, the VirtualBox side claims they are always in use - may be a Close or something I'm missing during …
=> WIP: Virtualbox Additions

dev-lang/rust_bin/rust_bin-1.57.0.recipe, dev-lang/rust_wasm_bin/rust_wasm_bin-1.57.0.recipe
Update to the latest version. Includes the wasm build target.
=> Rust: update to 1.57.0

dev-python/pyjwt/pyjwt-2.3.0.recipe
Add recipe for PyJWT library.
Will be required by next picard update.
=> pyjwt: new recipe

haiku-games/peggy/peggy-0.4.2.recipe, haiku-games/peggy/peggy-0.5.2.recipe
Peggy is a mastermind clone for Haiku written in C++ using the native Haiku API
=> New recipe: Peggy

media-libs/freetype/freetype-2.11.0.recipe, media-libs/freetype/freetype_bootstrap-2.11.0.recipe
WOFF File Format 2.0 - The WOFF 2.0 specification is implemented in all major browsers, and is widely used on production websites. It supports the entirety of the TrueType and OpenType specifications, including Variable fonts, Chromatic fonts, and font Collections.
=> freetype: enabled WOFF 2.0

media-gfx/qview/qview-5.0.recipe
Tested on x86_64 nightly and x86 B3
=> qview: update to 5.0

app-text/ghostwriter/ghostwriter-1.7.4.recipe, app-text/ghostwriter/patches/ghostwriter-1.7.4.patchset
=> Ghostwriter: add patch to fix build

dev-libs/smooth/smooth-0.9.9.recipe
=> smooth: Fix libiconv linkage

app-editors/emacs/emacs-29.0.50~git.recipe
Cairo is removed at the suggestion of the developer doing the Haiku port
=> emacs: bump git rev, remove cairo and friends

app-office/libreoffice/libreoffice-6.4.7.2.recipe, app-office/libreoffice/patches/libreoffice-6.4.7.2.patchset
=> libreoffice: rebuild on x86

dev-vcs/fossil/fossil-2.18.recipe
Recipe update for fossil 2.18 and updated the COPYRIGHT date.
=> fossil: bump version

haiku-apps/yab_ide/yab_ide-2.3.4.recipe
=> Yab ide 2.3.4

app-emulation/wine/patches/wine-7.1.patchset, app-emulation/wine/wine-7.1.recipe
Patchset updated with all the latest patches from https://github.com/X547/wine
Seems to be working correctly. Tested with Irfanview and TotalCommander.
=> Wine: bump

media-libs/rtmidi/licenses/RtMidi, media-libs/rtmidi/patches/rtmidi-5.0.0.patchset, media-libs/rtmidi/rtmidi-5.0.0.recipe
This ports the popular RtMidi library to Haiku.
=> rtmidi: new recipe

dev-libs/libfmt/libfmt-8.1.1.recipe
=> LibFMT: bump

dev-libs/icu/icu70-70.1.recipe, dev-libs/icu/patches/icu70-70.1.patchset
still needs a little refactoring.  opening a pr for testing
=> icu70: Add initial icu70 patchset for testing

haiku-apps/bescreencapture/bescreencapture-2.6.1.recipe
=> BeScreenCapture: bump version

dev-python/pip/pip-19.3.1.recipe
Somehow a pip2 materialized in the binfolder, i had no better idea than deleting it.
=> pip: enable Python 3.10

games-kids/tuxtype/additional-files/create-tuxtype-directories.sh, games-kids/tuxtype/tuxtype2-1.8.3.recipe
Somehow tuxtype doesn't seem to create them on first launch
=> tuxtype, add postinstall script

dev-python/pip/pip-19.3.1.recipe
As is is done in: https://github.com/haikuports/haikuports/commit/53e2d007fef2b4bc8e2e8b9927b19460630092bd#diff-f01e5034d05b9fbfc6fb752eac65a49cd183598edd1dff81e9c77c36fa7fea0fR30
=> pip, use python310 instead of python3.10

dev-lang/mujs/mujs-1.2.0.recipe
Tested and working on nightly hrev 56001 64-bit
=> update mujs to version 1.2.0

media-libs/openimageio/openimageio-2.3.10.0.recipe
This reverts commit 986094846725a82818329053e3b49d5b981e60b7.
=> Revert "oiio, revert cmd:git move (#6819)"

app-text/mdp/mdp-1.0.15.recipe
the following recipe adds support for mdp.
sample run below:
```
> uname -a
Haiku shredder 1 hrev56016 Apr 15 2022 06:47:33 x86_64 x86_64 Haiku
> mdp --version
mdp 1.0.15
Copyright (C) 2018 Michael Goehler
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Michael Goehler and others, see <https://github.com/visit1985/mdp/blob/master/AUTHORS>.
```
=> mdp: new recipe

app-editors/mg/mg-7.0.recipe, app-editors/mg/patches/mg-7.0.patchset
the following recipe adds the mg editor
sample post-install below:
```
> uname -a
Haiku shredder 1 hrev56085 Apr 29 2022 07:35:01 x86_64 x86_64 Haiku
> man mg | head
MG(1)                       General Commands Manual                      MG(1)
NAME
mg - emacs-like text editor
SYNOPSIS
mg [-nR] [-b file] [-f mode] [-u file] [+number] [file ...]
DESCRIPTION
mg is intended to be a small, fast, and portable editor for people who
> which mg
/bin/mg
```
=> mg: new recipe

dev-python/pymupdf/licenses/AGPL-3.0, dev-python/pymupdf/patches/pymupdf-1.19.6.patchset, dev-python/pymupdf/pymupdf-1.19.6.recipe
As alluded in my other PR #6823 here is a recipe for PyMuPDF. Working well on hrev 56001.
=> pymupdf: add recipe for 1.19.6

haiku-apps/pdftranslator/pdftranslator-1.0.4.recipe
=> bump pdftranslator to mupdf 1.19 compatible version

haiku-apps/pdftranslator/pdftranslator-1.0.4.recipe
=> pdftranslator, fix build for R1B3

dev-cpp/gflags/gflags-2.2.2.recipe
modified:   dev-cpp/gflags/gflags-2.2.2.recipe
=> gflags, enable 32bit

games-emulation/mgba/mgba-0.9.3.recipe
=> mgba: bump to 0.9.3

app-shells/xonsh/xonsh-0.11.0.recipe
It triggers some bugs in Python3.7, but seems to be working okayinsh with Py3.10
=> Xonsh: bump

games-action/nanosaur/nanosaur-1.4.3.recipe
Reformatting the Nanosaur recipe to match the suggestions given on the other Pangea ports (#6897 #6899 #6900)
Thanks to @korli
=> reformat nanosaur recipe

games-action/nanosaur/additional-files/nanosaur.rdef.in, games-action/nanosaur/nanosaur-1.4.3.recipe
Implements the corrections given by @augiedoggie on #6897
=> Fix rdef mistakes for Nanosaur

dev-vcs/git/git-2.36.1.recipe, dev-vcs/git/patches/git-2.36.1.patchset
git can't be build with gcc2 due to parse errors anymore
=> git add secondary architecture

games-kids/gcompris/gcompris-2.4.recipe, games-kids/gcompris/patches/disable-translations-on-32-bit.patch
translations disabled on 32 bit until lconvert stops crashing
=> gcompris: enable 32 bit

games-strategy/uqm/uqm-0.7.0.recipe
No rebuild needed, new build fails with errors (as does the latest version)
=> uqm, fix references to libpng16 and libSDL*

app-editors/jed/jed-0.99.20_128.recipe, app-editors/jed/patches/jed-0.99.20_128.patchset
switch source to github as the jedsoft site doesn't have this snapshot
=> jed: remove ncurses dependency

media-gfx/sane_backends/sane_backends-1.1.1.recipe
=> sane_backends: fixed x86 build

games-puzzle/laserkombat/laserkombat-1.0.recipe
*Laser Kombat* is a puzzle game from decades ago by David Dewey that was recently open-sourced and ported to SDL2 and C++17 by @sharkwouter.  The player controls a tank and must strategecally destroy all enemy tanks, without being seen.
Tested on `x86_64` with success:
=> laserkombat: Add recipe

dev-python/flit/flit-3.7.1.recipe
=> flit, new python recipe

dev-python/typing-extentions/licenses/Python, dev-python/typing-extentions/typing_extentions-4.3.0.recipe
=> typing-extentions, new python recipe

haiku-apps/trackgit/trackgit-1.0.0~git.recipe
32bit broken, issue filed upstream: https://github.com/HaikuArchives/TrackGit/issues/25
=> trackgit, update srcGitRev with the latest changes

dev-util/geany/geany-1.38.0.recipe
=> geany, revbump for fixed php8

sci-libs/geos/geos-3.11.0.recipe
=> geos: fix libVersion

app-misc/stagit/stagit-1.2.recipe
[**stagit**](https://codemadness.org/git/stagit/file/README.html) - static git page generator.
[![Packaging status](https://repology.org/badge/tiny-repos/stagit.svg)](https://repology.org/project/stagit/versions)
=> stagit: new recipe

app-editors/nano/nano-6.4.recipe
[Changelog](https://nano-editor.org/news.php)
=> nano: bump to 6.4

sci-libs/proj/proj-9.0.1.recipe
[Changelog](https://github.com/OSGeo/PROJ/releases/tag/9.0.1)
=> proj: bump to 9.0.1

sci-libs/geos/geos-3.11.0.recipe
See https://github.com/haikuports/haikuports/pull/7109
cc @Begasus
=> geos: bump revision

media-sound/cmus/cmus-2.10.0.recipe
[Changelog](https://github.com/cmus/cmus/releases)
=> cmus: bump to 2.10.0

media-libs/harfbuzz/harfbuzz-4.0.0.recipe, media-libs/harfbuzz/patches/harfbuzz-4.0.0.patchset
Possible soname change, but it seems no symbols got removed: https://github.com/harfbuzz/harfbuzz/releases
=> Harfbuzz: bump

dev-libs/boehm_gc/boehm_gc-8.2.2.recipe, dev-libs/boehm_gc/licenses/Boehm
=> boehm_gc: update to 8.2.2

haiku-misc/padblocker/padblocker-1.0.recipe
The Padblock input filter has moved into the Haiku tree.
=> padblock: disable for <= r1~beta3_pm_hrev54357

app-text/lout/lout-3.42.1.recipe
Thanks to OscarL for providing the sed command!
=> lout, fix build

dev-python/attrs/attrs-22.1.0.recipe
In preperation to update pytest. (some will probably follow)
=> attrs, bump version, remove python2.7, add python3.10

dev-python/automat/automat-20.2.0~git.recipe
In preparation to bump twisted
=> automat, new python recipe

dev-python/hyperlink/hyperlink-21.0.0.recipe
=> hyperlink, new python recipe

haiku-apps/weather/weather-1.0.0.recipe
Bugfixes (timezone parsing and others) and new features.
=> Weather: bumped to latest git revision

games-strategy/globulation2/globulation2-0.9.4.4.recipe, games-strategy/globulation2/patches/globulation2-0.9.4.4.patchset
This moves the game folder to B_USER_SETTINGS_DIRECTORY.
This should fix #7137
=> globulation2: move config folder

app-i18n/libpinyin/libpinyin-2.6.2.recipe
=> libpinyin: add new recipe, version 2.6.2

app-i18n/libchewing/libchewing-0.5.1.recipe
=> libchewing: add new recipe, version 0.5.1

app-i18n/libcangjie/libcangjie-1.3.recipe
=> libcangjie: add new recipe, version 1.3

sys-devel/haiku-format/additional-files/haiku-format_install_config.sh, sys-devel/haiku-format/haiku_format-10.0.1.recipe
=> haiku-format: update to latest commit

app-editors/ne/ne-3.1.1.recipe
Builds and runs just fine as is.
=> ne: enable building on x86_64

dev-libs/marisa/marisa-0.2.6.recipe
=> marisa: add new recipe, version 0.2.6

dev-util/scons/patches/scons-4.4.0.patchset, dev-util/scons/scons-4.4.0.recipe
=> scons: update to 4.4.0

dev-lang/fennel/fennel-1.2.1.recipe
I've added a new recipe for fennel (https://fennel-lang.org/), a lisp that runs on Lua.
=> fennel: add new recipe

app-i18n/unicode-cldr/licenses/unicode, app-i18n/unicode-cldr/unicode_cldr-42.0.recipe
=> unicode-cldr: add new recipe version 42.0

haiku-apps/weather/weather-1.0.0.recipe
One of the apps affected by #7383, already fixed upstream. Lets use that.
=> Weather: update to latest git-rev to solve missing symbols.

media-sound/lilypond/lilypond-2.22.2.recipe
=> lilypond: also update TEST_REQUIRES

haiku-libs/haikuwebkit/haikuwebkit-1.8.4.recipe, haiku-libs/haikuwebkit/patches/haikuwebkit-1.8.4.patchset
Just enough to make WebPositive run again in master until we have a shiny new version.
**Only tested in master x86_64**
=> haikuwebkit: fix build

net-misc/qputty/patches/qputty-506.patchset, net-misc/qputty/qputty-506.recipe
* fix putty download url
* build debuginfo package
* show putty version in about box
* fix duplicate variable definition in qtwin.cpp
=> qputty: clean up recipe

app-crypt/johntheripper/johntheripper-1.9.0.recipe, app-crypt/johntheripper/licenses/John the Ripper, app-crypt/johntheripper/patches/johntheripper-1.9.0.patchset
=> johntheripper: fixed build for R1B4

sci-astronomy/celestia/celestia-1.6.2.2.recipe
updates the homepage, copyright, and summary to be more up-to-date
also, before this gets merged, is the homepage equal to the project's main website, or its source code repository? i do not know much about haiku, im just here to make sure this unofficial port is still up-to-date. celestia is a cross-platform project, and so i believe everyone on every platform should have an equal experience with it. though in saying that, our amiga boys arent doing too good, being stuck on 1.6.0 and all that :(
=> celestia: update recipe

sys-devel/flex/flex-2.6.4.recipe
add libVersionCompat
add debuginfopackage
=> flex, build shared library instead of a static library

haiku-apps/bescreencapture/bescreencapture-2.6.2.recipe
=> BeScreenCapture: fix checksum

sys-devel/libtool/libtool-2.4.6.recipe
Reverts haikuports/haikuports#7565
=> Revert "libtool, remove libtool file and static library"

media-libs/portsmf/portsmf-239.recipe
=> portsmf: new recipe

net-misc/putty/additional-files/putty.rdef.in, net-misc/putty/patches/putty-0.78.patchset, net-misc/putty/putty-0.78.recipe
* re-add dependency on xlibe
* build with ninja
* add rdef and deskbar link
* adjust folder usage
=> putty: clean up recipe

haiku-apps/pe/pe-2.4.5.recipe
Not many user facing changes, but there are a couple. Why hold these back, right?
Mostly relevant for people working on HaikuPorts recipes, Python code, and/or assigning header copyrights to Haiku Inc.
=> Pe: bump srcGitRev

app-crypt/slunkcrypt/slunkcrypt-2022_12_12.recipe
SlunkCrypt: Updated to release 1.3.0 (2022-12-12)
=> SlunkCrypt: Updated to release 1.3.0 (2022-12-12)

sci-geosciences/josm/josm_bin-18583.recipe
[Changelog](https://josm.openstreetmap.de/wiki/Changelog)
=> JOSM: bump to 18583

www-aps/seeks/seeks-0.4.1.recipe
Seems to have been broken for a long time. No builds on Haiku Depot.
Added some comments and workarounds that help the build progress further, but still are not enough.
=> seeks: mark as disabled.

haiku-data/be_book/be_book-2008_10_26.recipe
This time for real, whatever sniffing rules the builder may have.
=> BeBook: fix CSS mime type

app-emulation/qemu/patches/qemu-6.2.0.patchset, app-emulation/qemu/qemu-6.0.0.recipe, app-emulation/qemu/qemu-6.2.0.recipe
successful build, no policy errors in haikuporter strict mode
smoke test looks OK
=> qemu: update to 6.2.0, enable GTK frontend

app-editors/nano/nano-7.1.recipe
Tested on beta4, both on 64 and 32 bits (x86).
=> nano: update to version 7.1

haiku-apps/streamradio/streamradio-1.0.0.recipe
Build and functionality tested on hrev56707 x86. PASSED.
=> StreamRadio: bumped to fix networking

dev-libs/cjson/cjson-1.7.15.recipe, dev-libs/cjson/patches/cjson-1.7.15-pc.patch
This is needed for updated version of Open Cubic Player
=> Initial support for cJSON

app-editors/efte/efte-1.1.recipe, app-editors/efte/patches/efte-1.1.patchset
Tested on beta4, x86_gcc2 and x86_64.
=> efte: new recipe

app-arch/ancient/ancient-2.0.0.recipe
As usual, all comments are welcome!
This is needed for the future update for opencubicplayer
=> app-arch/ancient: Version bump + added library

media-sound/tenacity/additional-files/tenacity.rdef.in, media-sound/tenacity/patches/tenacity-1.3~beta.patchset, media-sound/tenacity/tenacity-1.3~beta.recipe
Tenacity 1.3 beta is out - so I'm posting a preliminary version of this recipe here.
Build/install/smoketest seems OK on x86_64.
=> tenacity-1.3~beta: new recipe

dev-cpp/antlr-cpp/antlr_cpp-4.11.1.recipe, dev-cpp/antlr-cpp/patches/antlr_cpp-4.11.1.patchset, dev-java/antlr-runtime/antlr_runtime-4.11.1.recipe, dev-java/antlr-tool/antlr_tool-4.11.1.recipe
* antlr_tool is the grammar compiler
* antlr_runtime is the Java runtime (this is also part of antlr_tool)
* antlr_cpp is the C++ runtime
antlr_tool and antlr_runtime are not built from source, they just repack the downloaded JAR files.
=> antlr: new recipes antlr_tool, antlr_runtime and antlr_cpp

media-sound/ocp/ocp-0.2.103.recipe
=> media-sound/ocp: Version bump

games-puzzle/pingus/patches/pingus-0.7.6.patchset, games-puzzle/pingus/pingus-0.7.6.recipe
Tested and working on x86 and x86_64.
=> pingus: Use Boost 1.70

app-text/wdiff/patches/wdiff-1.2.2.patchset, app-text/wdiff/wdiff-1.2.2.recipe
my first new port, please let me know if there is anything I can improve upon
=> wdiff: new port for v1.2.2

dev-util/pkgdiff/patches/pkgdiff-1.7.2.patchset, dev-util/pkgdiff/pkgdiff-1.7.2.recipe
including a patch to make it work for .hpkg
=> pkgdiff: new port for 1.7.2

media-libs/boca/boca-1.0.7.recipe
Attention: This depends on #7923 and needs to be merged thereafter.
=> boca: bump to 1.0.7

media-sound/freac/freac-1.1.7.recipe
Attention: This depends on #7922, #7923 and #7924 and needs to be merged after those.
=> freac: bump to 1.1.7

dev-python/zipp/zipp-3.7.0.recipe
=> zipp: fix versioning.

dev-libs/inih/inih-r56.recipe, net-dialup/tio/patches/tio-2.5.patchset, net-dialup/tio/tio-2.5.recipe
question: should the inih port be called libinih?
(tested on x86_64)
=> new ports: tio + its dependency inih

app-emulation/qemu/patches/qemu-7.2.0-haiku.patchset, app-emulation/qemu/patches/qemu-7.2.0.patchset, app-emulation/qemu/qemu-7.2.0.recipe
Successful build for both 64-bit and 32-bit, no policy warnings :heavy_check_mark: 
Running Haiku inside Haiku :heavy_check_mark: 
Network access with devendored libslirp :heavy_check_mark: 
Wonky mouse pointer :x:
Ctrl/Alt/Shift doesn't work :x:
Edit:
These two issues were there also on 6.2.0
It seems to be much worse on qemu-3.1.1.1 (unless I'm doing something wrong?)
=> qemu-7.2.0: new recipe

dev-python/frozenlist/frozenlist-1.3.1.recipe
=> frozenlist: switch to x86, drop Python 3.7, add Python 3.10.

dev-python/apsw/apsw-3.36.0~r1.recipe
=> aspw: switch to x86, support Python 3.10, provide "non _x86" package name.

dev-python/kiwisolver/kiwisolver-1.3.1.recipe
=> kiwisolver: fix build, support Python 3.10

dev-python/cppy/cppy-1.2.1.recipe
Needed to fix the build for `kiwixsolver` (#8088).
=> cppy: new recipe

dev-python/pycrypto/pycrypto-2.6.1.recipe
Switch to x86. Needs a C99 compiler.
=> pycrypto: fix 32 bits build, support Python 3.10.

dev-python/oslash/oslash-0.6.3.recipe
This is a requirement for newer versions of jsonrpcserver >= 5.0.0.
=> oslash: new recipe.

dev-python/python-markdown-math/python_markdown_math-0.8.recipe
Make TEST() attempt to run the tests for all the package versions.
One test currently fails. Not sure if they where all OK at some point.
=> python-markdown-math: clean up, add Python 3.10 support.

dev-python/jsonrpcserver/jsonrpcserver-5.0.9.recipe
Requires the new `oslash` package from #8210.
=> jsonrpcserver: update to version 5.0.9

dev-python/pyaes/pyaes-1.6.1.recipe
=> pyaes: drop support for Python 2.7/3.7, add it for 3.9/3.10.

net-dns/avahi/avahi-0.8.recipe
=> avahi, fix 32bit build

haiku-apps/paladin/paladin-2.8~git.recipe
Retested build on hrev56889 x64.
For issues and enhancement tracking: https://github.com/adamfowleruk/Paladin/issues
=> paladin: bumped revision

media-libs/libfreehand/libfreehand-0.1.2.recipe
move binaries to tools package
create debug package
=> libfreehand, fix build for werror

media-libs/liblrdf/liblrdf-0.5.0.recipe
Add conflict for the devel package from redland
=> liblrdf, disable static library

sci-libs/armadillo/armadillo-10.8.2.recipe
=> armadillo, cleanup

media-libs/libsndfile/libsndfile-1.1.0.recipe
Libversion(Compat) was declared wrong for this one, needs further testing, guess quite some depending packages will need a revbump for this one.
=> libsndfile, cleanup, move cmake config to dev package, fix libVersion

app-shells/command_not_found/command_not_found-0.0.1~git.recipe, app-shells/command_not_found/patches/command_not_found-0.0.1~git.patchset
* Added TEST()
* Added a couple of minor fixes here and there.
=> command_not_found: switch to Python 3.9.

games-puzzle/monsterz/monsterz-0.7.1.recipe
So it can be found by a QuickLaunch query.
=> Monsterz: Add type and app signature

dev-libs/libfilezilla/libfilezilla-0.42.2.recipe, dev-libs/libfilezilla/patches/libfilezilla-0.42.2.patchset
* <s>disable static library</s>
* update patchset
* update command line for running tests
successful build on 32-bit & 64-bit nightly
=> libfilezilla: update to 0.42.2

app-emulation/qemu/patches/qemu-8.0.0-haiku.patchset, app-emulation/qemu/patches/qemu-8.0.0.patchset, app-emulation/qemu/qemu-8.0.0.recipe
not sure about the old recipes, shall we remove them? maybe at least the ones older than 3.1.1.1?
=> qemu-8.0.0: new recipe

media-gfx/fig2dev/fig2dev-3.2.8b.recipe
=> fig2dev: rebuild for ImageMagick changes (32 bit)

media-gfx/fig2dev/fig2dev-3.2.8b.recipe
=> fig2dev: also update TEST_REQUIRES

haiku-apps/paladin/patches/paladin-2.8~git-gcc2.patchset
=> paladin: now kenmays' patchset (gcc2 only) applies cleanly.

games-board/54321/54321-1.0.2001.11.16.recipe, games-board/54321/patches/54321-1.0.2001.11.16.patchset
- Fix black-screen when starting up from Deskbar link.
- Simplified directory structure a bit.
- Enable build on 64 bits.
=> 54321: fine tunning.

games-action/btanks/btanks-0.9.8083.recipe, games-action/btanks/patches/btanks-0.9.8083.patchset, games-action/btanks/patches/debian/gcc-4.6.patch, games-action/btanks/patches/debian/gcc-4.7.patch, games-action/btanks/patches/debian/python3.patch, games-action/btanks/patches/debian/scons.patch
Applied some of the Debian patches from:
https://sources.debian.org/src/btanks/0.9.8083-9/debian/patches/
Consistent "SDL / BGLView::UnlockGL()" related crash on close. Works nicely otherwise.
Closes #7886.
---
Tested on beta4 32 bits.
=> btanks: fix build, move to $appsDir.

app-text/dblatex/dblatex-0.3.12.recipe
Untested (I don't have the bandwidth to handle Tex :-/).
=> dblatex: switch to Python 3.9

x11-libs/cairo/cairo-1.16.0.recipe
Build tested on hrev57019 x64.
No issues.
=> cairo: fixed build issue

app-text/scdoc/scdoc-1.11.2.recipe
the following recipe adds support for [scdoc](https://git.sr.ht/~sircmpwn/scdoc/)
=> scdoc: new recipe

app-i18n/aquaskk/aquaskk-4.7.0.2.recipe
Should be merged after #8779 gets build on the buildmasters.
=> aquaskk: switch to Python 3.

app-i18n/aquaskk/aquaskk-4.7.0.2.recipe
=> aquaskk: trigger re-build with a rev-bump.

app-emulation/saptools/patches/saptools-2.0.94.patchset, app-emulation/saptools/saptools-2.0.94.recipe
Tested on hrev57063 x64.
Closes: https://github.com/haikuports/haikuports/issues/1024
=> saptools: fixed x64 build

app-shells/fish/fish-3.5.1.recipe
there is already a debug package but without symbols it's useless
=> fish: enable debug symbols

dev-libs/xmlsec/xmlsec-1.2.37.recipe
Reverts haikuports/haikuports#8747
=> Revert "xmlsec, bump version"

dev-python/lazy-object-proxy/lazy_object_proxy-1.5.2.recipe
* Build with build/installer.
* Provide "non _x86" package name.
=> lazy_object_proxy: recipe cleanup.

dev-python/dbuspython/dbuspython-1.2.14.recipe
* Provide "non _x86" package name.
* Remove unneded \n scaping.
=> dbuspython: recipe clean up.

dev-python/asttokens/asttokens-2.2.1.recipe
---
For reference: dependency chain I'm trying to work on:
```
paramiko
-> invoke (new)
-> icecream (new) 
-> executing (new)
-> asttokens (new)
-> astroid
-> wrapt
```
=> asttokens: new recipe.

dev-python/executing/executing-1.2.0.recipe
---
For reference: dependency chain I'm trying to work on:
```
paramiko
-> invoke (new)
-> icecream (new) 
-> executing (new)
-> asttokens (new)
-> astroid
-> wrapt
```
=> executing: new recipe.

dev-python/icecream/icecream-2.1.3.recipe, dev-python/icecream/patches/icecream-2.1.3.patchset
All (35) test pass for both Python 3.9 and 3.10. (running TEST() requires updated nose recipe).
---
For reference: dependency chain I'm trying to work on:
```
paramiko
-> invoke (new)
-> icecream (new) 
-> executing (new)
-> asttokens (new)
-> astroid
-> wrapt
```
=> icecream: new recipe.

games-engines/dragengine/dragengine-1.17.recipe
Create a new branch and re-applied the changes. Maybe it didn't like the branch name
=> dragengine, added cmd:cmake

sys-devel/gcc/gcc-13.1.0_2023_06_20.recipe, sys-devel/gcc/patches/gcc-13.1.0_2023_06_20.patchset
Currently set all supported platforms as unstable, as the recipe requires Haiku hrev56977 or later to build.
=> GCC: Add recipe for 13.1.0

app-shells/xonsh/xonsh-0.11.0.recipe
=> xonsh: fix python package version

games-action/powermanga/patches/powermanga-0.93.1.patchset, games-action/powermanga/powermanga-0.93.1.recipe
Move binary on level up in $appsDir
=> powermanga, fix reference to libpng

media-libs/waave/waave-3.01.recipe
No revbump, disabled recipe ...
=> waave, fix references to lib:libsdl

games-sports/ballsmacker/ballsmacker-1.0.0.recipe
No revbump, recipe is disabled.
=> ballsmacker, fix references for lib:libsdl

dev-lang/lua/lua-5.4.6.recipe, dev-lang/lua/patches/lua-5.4.6.patchset
readline is enabled so the the lua REPL has proper support for line editing/arrow keys(related to #8972)
Also, remove some static library remnants and tweak the TEST command
=> lua: enable readline, misc cleanup

media-gfx/tuxpaint-config/tuxpaint_config-0.0.22~rc1.recipe
=> tuxpaint_config, simplify Deskbar Preferences link

sci-geosciences/josm/josm_bin-18772.recipe
[Changelog](https://josm.openstreetmap.de/wiki/Changelog)
=> JOSM: bump to 18772

media-fonts/noto_emoji/noto_emoji-20230311.recipe, media-fonts/noto_emoji_color/noto_emoji_color-2.038.recipe
Also has the newer version of noto emoji
=> Split noto emoji and noto color emoji

app-text/enchant/enchant-2.5.0.recipe
Needs groff to be merged first (creates html documentation now): https://github.com/haikuports/haikuports/pull/9163
=> enchant, bump version

app-admin/pass/pass-1.7.4.recipe
Adds a recipe for 1.7.4. I have been using this for a couple of days and it seems to work fine.
=> pass: Adding recipe

x11-libs/agg/agg-2.7.0~r138.recipe, x11-libs/agg/patches/agg-2.7.0~r138.patchset
- updated for detailed library description
- added perspective transformation linker patch (Zardshard)
=> agg: perspective transformation update

net-analyzer/nmap/nmap-3.81.recipe
=> nmap: migrate to gcc11

app-office/scribus/scribus-1.5.8.recipe
Tested on beta4 64 bits:
Seems to work with the few (built in) scripts I've tried.
=> scribus: switch to Python 3.10.

sys-devel/llvm/llvm12-12.0.1.recipe, sys-devel/llvm/patches/clang-12.0.1.patchset
=> clang12: Add missing GNU headers include path

games-arcade/tuxpuck/patches/FTBFS-with-fread.patch, games-arcade/tuxpuck/patches/Makefile.patch, games-arcade/tuxpuck/patches/buffer-overflow.patch, games-arcade/tuxpuck/patches/clang-FTBFS.patch, games-arcade/tuxpuck/patches/cross.patch, games-arcade/tuxpuck/patches/haiku.patch, games-arcade/tuxpuck/patches/libpng-transition.patch, games-arcade/tuxpuck/tuxpuck-0.8.2.recipe
Hi,
this is a recipe for Tuxpuck an opensource arcade game.
What's include:
* Tuxpuck source url 
* All the patches from the debian gaming team
* My patch to make it buildable on haiku
As this is the first time that I write a recipe for haiku, please give it a closer look before to merge, thanks :) 
Forum thread as a ref: https://discuss.haiku-os.org/t/i-ported-tuxpuck/13811
=> Tuxpuck: add recipe

sys-devel/gcc/gcc-13.2.0_2023_08_10.recipe, sys-devel/gcc/patches/gcc-13.2.0_2023_08_10.patchset
Synchronize with the fixes in the buildtools repository for arm64 and -rdynamic.
=> Gcc 13.2-2

media-fonts/fontawesome/fontawesome-6.4.2.recipe
=> fontawesome: bumped version

games-puzzle/monsterz/monsterz-0.7.1.recipe, games-puzzle/monsterz/patches/monsterz-0.7.1.patchset
=> monsterz: reduce CPU usage, move to "any" arch.

media-libs/openexr/openexr-2.4.1.recipe
A rebuild seems to fix #9250 and https://dev.haiku-os.org/ticket/18560.
=> openexr, revbump

dev-python/prompt_toolkit/prompt_toolkit-3.0.39.recipe
Tested with the `xonsh` shell (acts as a libedit/realine replacement on steroids).
=> prompt_toolkit: new recipe.

x11-libs/agg/agg-2.7.0~r139.recipe
=> agg: fixed chksum issue

sci-libs/openblas/openblas-0.3.23.recipe
Currently affected by the gfortran issue #9241
=> OpenBLAS: bump

sci-libs/blis/blis-0.9.0.recipe, sci-libs/blis/blis8-0.8.0.recipe
=> Blis: bump

dev-python/pathtools/pathtools-0.1.2.recipe
Should fix watchdog-0.9.0 build issue at buildmasters.
=> pathtools: recipe clean ups, add support for Python 3.10.

net-analyzer/wireshark/wireshark-4.0.8.recipe
This should fix the build issue seen in #9359
=> wireshark: use python3

x11-libs/libxdmcp/libxdmcp-1.1.4.recipe
fixes https://github.com/haikuports/haikuports/issues/2841
=> libxdmcp, bump version, fix test

dev-lang/64tass/64tass-1.59.3120.recipe
A new version came out yesterday.
=> 64tass: update to 1.59.3120

dev-perl/file_sharedir/file_sharedir-1.118.recipe
according to https://metacpan.org/pod/File::ShareDir
fixes #9419
=> file_sharedir: add class_inspector dependency

dev-python/bottle/bottle-0.12.25.recipe
Also, made the usual recipe cleanups.
=> bottle: update to version 0.12.25, support Python 3.10.

dev-python/discid/discid-1.2.0.recipe
Needed if we plan to move `picard` to Python 3.10.
=> discid: add package for Python 3.10.

dev-python/sip/patches/sip-6.7.11.patchset, dev-python/sip/sip-6.7.11.recipe
=> sip: update to version 6.7.11, support Python 3.10.

games-action/another_world/additional-files/another_world.sh, games-action/another_world/another_world-0.0.1.recipe
This is the recipe for Another World (based on NEO-RAW).
The original version of this game is NOT opensource, NEO-RAW is a re-implementation of the original game VM.
Due to this, you have to provide your game files (BANK* and MEMLIST.BIN).
Haiku-OS forum thread (as reference): https://discuss.haiku-os.org/t/another-world-raw-ported-to-haiku/
@Begasus, show no mercy for my scripts! 😇
=> Another World (NEO-RAW): new recipe

dev-python/unrardll/unrardll-0.1.7.recipe
Also switch to build with "build + installer".
=> unrardll: update to version 0.1.7, support Python 3.10.

sys-process/glances/glances-3.1.3.recipe
Recipe is still disabled, as it depends on a working `psutil` package, but at least now looks more decent (and builds without complains).
=> glances: switch to Python 3.10.

net-im/nheko/nheko-0.11.3.recipe, net-im/nheko/patches/nheko-0.11.3.patchset
=> nheko: Add recipe and patchset for 0.11.3

games-util/fteqcc/additional-files/bitflags.txt, games-util/fteqcc/additional-files/classes.txt, games-util/fteqcc/additional-files/csqc_for_idiots.txt, games-util/fteqcc/additional-files/entry_qc.txt, games-util/fteqcc/additional-files/findchain_considered_harmful.txt, games-util/fteqcc/additional-files/fteqcc_manual.txt, games-util/fteqcc/additional-files/sendevent.txt, games-util/fteqcc/fteqcc-20230920~git.recipe
Minimal recipe to get the thing running. The engine itself (FTEQW) should be coming next.
=> Add FTEQCC

haiku-misc/unicode_input_method/unicode_input_method-20230929.recipe
=> unicode_input_method: new recipe.

media-video/ffmpeg/ffmpeg6-6.0.recipe, media-video/ffmpeg/patches/ffmpeg-6.0.patchset
Checked with latest VLC (in our repository), build and playback are fine. (not checked on 32bit yet).
=> ffmpeg, add version 6.0

dev-python/haiku-pyapi/haiku_pyapi-0.1.recipe
=> haiku-pyapi: Release 0.1

media-libs/harfbuzz/harfbuzz-8.2.1.recipe, media-libs/harfbuzz/patches/harfbuzz-8.2.1.patchset
=> harfbuzz, bump version, fix build for pango

x11-libs/pango/pango-1.50.14.recipe, x11-libs/pango/patches/pango-1.50.14.patchset
Closes: https://github.com/haikuports/haikuports/issues/9604
Needs harfbuzz PR to be merged first: https://github.com/haikuports/haikuports/pull/9611
=> pango, bump version, rely on harfbuzz_glib_devel package

media-libs/libsbsms/libsbsms-2.3.0.recipe
will be used in next version of Tenacity
=> libsbsms: new recipe

games-emulation/mame/mame-0.259.recipe, games-emulation/mame/patches/mame-0.259.patchset
As requested on Discuss, a PR for my WIP for MAME 0.259. Current error seems to be in the main Makefile.
```
make: *** No rule to make target 'build/projects/sdl/mame/gmake-haiku/Makefile' needed by 'haiku_x64'.  Stop.
```
Any help gratefully received!
=> mame: Initial work on recipe and patchset

app-forensics/yara/yara-4.3.2.recipe
This is a recipe for yara.
The devel package is included.
Once this package will be available, we will have all the basic tools to do malware analysis on Haiku!
Thanks,
Luca
=> yara: add recipe

net-im/poezio/poezio-0.14.recipe
Smoke-tested with both current slixmpp (1.8.2), and a local build of the newest version (1.8.4).
=> poezio: switch to Python 3.10.

app-misc/cpuminer/cpuminer-2.5.1.recipe, app-misc/cpuminer/patches/cpuminer-2.5.1.patch
Added recipe for CPUMiner
Ported by Luca d'Amico
=> Add recipe for cpuminer

app-admin/chrpath/chrpath-0.16.recipe, app-admin/chrpath/patches/chrpath-0.16.patchset
=> chrpath: fix build with gcc13.

app-emulation/qemu/patches/qemu-8.0.5-backports.patchset, app-emulation/qemu/qemu-8.0.5.recipe
=> qemu: fix bootup issue for Haiku guests on TCG

sys-devel/llvm/llvm17-17.0.1.recipe, sys-devel/llvm/patches/llvm17-17.0.1.patchset
=> llvm17: fix analyzer scripts

app-emulation/x16-emulator/additional-files/x16emu.rdef.in, app-emulation/x16-emulator/patches/x16_emulator-46.patchset, app-emulation/x16-emulator/x16_emulator-46.recipe
=> x16_emulator: new recipe

media-video/ffmpeg/ffmpeg-4.2.9.recipe, media-video/ffmpeg/patches/ffmpeg-4.2.9.patchset
Tested on Haiku R1B4 hrev56578+93) x86_64.
Closes: https://github.com/haikuports/haikuports/issues/9586
=> ffmpeg: fixed GCC 13 build issue

games-strategy/colobot/colobot-0.2.1.recipe, games-strategy/colobot/patches/colobot-0.2.1.patchset, games-strategy/colobot_data/colobot_data-0.2.1.recipe, games-strategy/colobot_data/patches/colobot_data-0.2.1.patchset
Colobot did have some problems under x86_gcc2, however after rebuilding it, it does work fine. The version currently in the repository did not work on my VM, crashing during start
I also changed it to use the latest boost, it seems to work fine with it
=> colobot: bump version

app-office/libalkimia/libalkimia-8.1.2.recipe
Needs https://github.com/haikuports/haikuports/pull/9794 to be merged first.
=> libalkimia, new recipe

app-doc/zeal/patches/zeal-0.7.0.patchset, app-doc/zeal/zeal-0.7.0.recipe
Requires qtwebengine now, so only for 64bit, left older version for 32bit.
=> zeal, bump version, 64bit only

net-analyzer/wireshark/patches/wireshark-4.2.0.patchset, net-analyzer/wireshark/wireshark-4.2.0.recipe
successful build and smoke test on 32-bit & 64-bit, with qt6
=> wireshark: update to 4.2.0

dev-lang/python/patches/python3.11-3.11.7.patchset, dev-lang/python/patches/python3.11_x86-3.11.7.patchset, dev-lang/python/python3.11-3.11.7.recipe
Tested on beta4, 64 and 32 bits.
=> python3.11: update to version 3.11.7

dev-lang/python/patches/python3.12-3.12.1.patchset, dev-lang/python/python3.12-3.12.1.recipe
Tested on beta4, 32 and 64 bits.
=> python3.12: update to version 3.12.1

app-office/texstudio/texstudio-4.7.1.recipe
=> texstudio, set verstion string for poppler

dev-util/xmake/patches/xmake-2.8.5.patchset, dev-util/xmake/xmake-2.8.5.recipe
A cross-platform build utility based on Lua
=> xmake, new recipe

sci-geosciences/josm/josm_bin-18907.recipe
[Changelog](https://josm.openstreetmap.de/wiki/Changelog)
=> JOSM: bump to 18907

sys-libs/libatomic_ops/libatomic_ops-7.8.2.recipe
Update libatomic_ops recipe to v7.8.2.
=> libatomic_ops: bump to 7.8.2

haiku-apps/yab_localizer/yab_localizer-0.0.6.recipe
Bump Version: yab-localizer updated to yab 1.8.2
=> Bump Version: yab-localizer updated to yab 1.8.2

net-fs/libnfs/libnfs-5.0.2.recipe, net-fs/libnfs/patches/libnfs-5.0.2.patchset
=> libnfs: add 5.0.2

dev-lang/python/patches/python3.10-3.10.13.patchset, dev-lang/python/python3.10-3.10.13.recipe
Reference: https://github.com/python/cpython/pull/110239´
Fixes the 3.10/"readline" part of #10001
=> python3.10: fix build with newer libedit.

dev-lang/python/patches/python3.12-3.12.2.patchset, dev-lang/python/python3.12-3.12.2.recipe
=> python3.12: update to version 3.12.2.

dev-libs/udis86/patches/0001-fixes-for-python3.patch, dev-libs/udis86/patches/0002-Fix-oprgen-python3-compat.patch, dev-libs/udis86/patches/0005-Fix-tests-makefile.patch, dev-libs/udis86/udis86-1.7.2.recipe
Patches for Python 3 compatibility, taken from:
https://salsa.debian.org/debian/libudis86/-/tree/master/debian/patches
Tested on beta4 64 bits.
=> udis86: use python3 for the build/tests.

media-libs/opencv/opencv3-3.4.3.recipe, media-libs/openimageio/openimageio-1.8.6.recipe
=> Remove obsolete python2 references

app-editors/turbo/patches/turbo-2024.02.05~git.patchset, app-editors/turbo/turbo-2024.02.05~git.recipe
Still some rough edges, but bet some users will like it.
Needs #10135 merged first.
---
Built/tested on beta4, 32 and 64 bits.
=> turbo: new recipe

haiku-libs/ale/ale-0.9.1.recipe, haiku-libs/ale/patches/ale-0.9.1.patchset
no revbump since it doesn't run on beta4
=> ale: link libale against libshared

games-simulation/singularity/singularity-1.00.recipe
This should add the game music. I've done this rather ugly almost hardcoded path, as I don't know how to generate it with the environment variables on x86
=> singularity: add music

dev-lang/fpc/fpc-3.2.2.recipe, dev-lang/fpc/patches/fpc-3.2.2.patchset
- fixes #10140
- tested on x86_64 master 
Edit: it's still broken
=> fpc: fix script shebang

dev-python/expandvars/expandvars-0.12.0.recipe
Required to build newest version of "yarl" (1.9.4).
=> expandvars: new recipe.

sys-apps/file/file-5.43.recipe
Should fix: https://github.com/haikuports/haikuports/issues/10243
=> file, revbump

games-arcade/kraptor/kraptor-4.4.14.recipe
Just so hp --lint doesn't complains about this one.
=> kraptor: fix PATCHES variable.

app-text/lout/lout-3.43.recipe
=> lout: update to version 3.43.

kde-apps/dolphin-plugins/dolphin_plugins-23.08.5.recipe, kde-apps/dolphin-plugins/licenses/CC0 v1.0
This adds plugins for Bazaar, Dropbox, Git, Mercurial and Subversion
=> dolphin_plugins, new plugins for Dolphing

sci-libs/liborigin/liborigin-3.0.2.recipe
Additional library for labplot2
=> liborigin, new recipe

kde-apps/cantor/cantor-24.02.1.recipe, kde-apps/cantor/patches/cantor-24.02.1.patchset
Update after libqalculate/qalculate-qt update
=> cantor bump version

sci-libs/matio/matio-1.5.26.recipe
=> matio, new recipe

sci-libs/matio/matio-1.5.26.recipe
no need for revbumping, 64bit is fine
=> matio, disable gcc2, set CMAKE_INSTALL_BINDIR

sci-libs/libcerf/libcerf-2.4.recipe
Optional dependency for labplot2
=> libcerf, new recipe

sys-boot/u-boot/patches/u_boot-2024.04.patchset, sys-boot/u-boot/u_boot-2024.04.recipe
previously one marked as vulnerable at repology
=> u_boot, bump version

haiku-apps/yab_buildfactory/yab_buildfactory-2.4.6.recipe
bump version (update to solve issue with yab Version)
=> bump version (update to solve issue with yab Version)

app-emulation/qemu/patches/qemu-8.2.2-haiku.patchset, app-emulation/qemu/patches/qemu-8.2.2.patchset, app-emulation/qemu/qemu-8.2.2.recipe
successful build on 64-bit and 32-bit
Smoke test on hrev57662 x86_64 host with hrev57662 guest (both 64-bit and 32-bit) was successful.
Not tried on 32-bit host.
=> qemu: update to 8.2.2

haiku-apps/batchrename/batchrename-0.2.0.recipe
It's a Tracker add-on, and stand-alone application that I wrote a couple of years back, as I wasn't happy with the existing offerings. It's actual name is just 'rename', but that one is already taken by bbjimmy's add-on.
=> Added batchrename-0.2.0 recipe

dev-lang/qbe/qbe-1.2.recipe
=> Bump QBE to 1.2

net-libs/libssh2/libssh2-1.9.0.recipe
=> libssh2: enable posix error mapper

dev-libs/kdiagram/kdiagram3-3.0.1.recipe
This is one from the KF6 series, not used yet, but beats getting lost
=> kdiagram3, new recipe

kde-apps/kdegraphics-mobipocket/kdegraphics_mobipocket24-24.02.2.recipe
=> kdegraphics_mobipocket24, new recipe

dev-util/clazy/clazy-1.11.recipe
=> clazy, fix for 32bit

dev-qt/libqt6pas/libqt6pas-6.2.7.recipe, dev-qt/libqt6pas/patches/libqt6pas-6.2.7.patchset
=> libqt6pas, revbump/patch for Qt6.7

dev-libs/xapian/xapian-1.4.25.recipe
link *.so back into libDir , fixes build for khelpcenter(still not functiona)
=> xapian, bump version

kde-frameworks/prison/prison-5.115.0.recipe
Also some cleanup/fixing install/packaging
=> prison, revbump, add zxing library for libKF5PrisonScanner

sys-process/cronie/additional-files/0hourly, sys-process/cronie/additional-files/anacrontab, sys-process/cronie/additional-files/cron.deny, sys-process/cronie/additional-files/cronie-finish-setup.sh, sys-process/cronie/additional-files/cronie.launch.in, sys-process/cronie/additional-files/crontab, sys-process/cronie/cronie-1.7.2.recipe, sys-process/cronie/patches/cronie-1.7.2.patchset
move settings back to /system/settings and adjust documentation
create crond user for the daemon to use
fix sendmail paths
fix standard PATH variable for jobs
=> cronie: miscellaneous fixes

app-editors/cudatext/cudatext-1.214.6.0.recipe
=> cudatext, enable 32bit

dev-vcs/git/git-2.45.1.recipe, dev-vcs/git/patches/git-2.45.1.patchset
Seems to work fine on beta4 64 bits.
Opening as draft until I check the build on 32 bits (and *maybe* run the 4+ hours long test suite).
Would be nice to have someone review my changes on the `config.c` part of the .patchset, to make sure I got that one right (some logic from `./builtins/config.c` got moved to `./config.c` between 2.43.2 and 2.45.1 upstream). Thanks in advance.
=> git: update to version 2.45.1

net-irc/irssi/irssi-1.4.5.recipe, net-irc/irssi/patches/irssi-1.4.5.patchset
I'm not sure about the second part here (devel subpackage) ...
=> irssi: perl fixes and cleanup

dev-perl/archive_extract/archive_extract-0.88.recipe
This is a test for #9394. If this works and is accepted, the same pattern could be used for other perl packages.
=> archive_extract: cleanup, add tests

dev-util/clazy/clazy-1.11.recipe, dev-util/clazy/patches/clazy-1.11.patchset
Add upstream patches (prepares for building with LLVM18)
=> clazy, 32bit build fix

games-misc/moonlight-embedded/moonlight_embedded-20240611~git.recipe
Recipe for moonlight-embedded: Gamestream client for embedded systems
=> moonlight_embedded: new recipe

media-libs/raylib/raylib-5.0.recipe
the following recipe adds support for [raylib](https://github.com/raysan5/raylib)
sample run
```
> uname -a
Haiku shredder 1 hrev57768 Jun 20 2024 06:26:28 x86_64 x86_64 Haiku
> cat main.c
#include "raylib.h"
int main(void)
{
InitWindow(800, 450, "raylib [core] example - basic window");
while (!WindowShouldClose())
{
BeginDrawing();
ClearBackground(RAYWHITE);
DrawText("Congrats! You created your first window!", 190, 200, 20, LIGHTGRAY);
EndDrawing();
}
CloseWindow();
return 0;
}
> cc -o helloraylib main.c -lglfw -lraylib
> ls helloraylib
helloraylib
```
=> raylib: new recipe

sys-apps/man-pages-posix/man_pages_posix-2017.a.recipe
Bump to 2017.a
The Open Group Base Specifications Issue 7, 2018 edition
IEEE Std 1003.1-2017
=> man_pages_posix: bump to 2017.a 

sci-visualization/gnuplot/gnuplot-5.4.10.recipe, sci-visualization/gnuplot/patches/gnuplot-5.4.10.patchset
Cleaned up unneded REQUIRES.
~Still no GUI output.~ edit: enabled `--with-x`. Bit buggy, but good enough for now.
=> gnuplot: update to version 5.4.10

dev-libs/libfmt/libfmt-9.1.0.recipe, dev-libs/libfmt/libfmt11-11.0.1.recipe
=> libfmt: add 11.0.1

games-action/classicube/additional-files/launcher.sh, games-action/classicube/classicube-1.3.6.recipe, games-action/classicube/classicube-1.3.6~20240714.recipe
(I have not contributed to anything Haiku related before, sorry if I am getting some stuff wrong)
Also changes git repo from `https://github.com/UnknownShadow200/ClassiCube` to `https://github.com/ClassiCube/ClassiCube`, removes `PATCH` section as it was saying that it wasn't applying anything, removes `-d` argument as it should not be used any more (replaced with `cd ${SETTINGS_DIR} && $APP`
~~1. When you close a running game, it stays running in the background and displays a long error message.~~
~~2. The camera is **_very_** glitchy, you can't move the camera with any mouse (and probably touchpad) properly. (likely https://github.com/ClassiCube/ClassiCube/issues/1105)~~
Noticed problems have been solved (https://github.com/ClassiCube/ClassiCube/commit/9daf872e570bd180dfbc5849ad889447bb3 …
=> (Needs a new release or a patchset, please do not merge!) ClassiCube: bump version

haiku-apps/genio/genio-3.0.0.recipe, haiku-apps/genio/genio-3.0.recipe
Fix 32 bit build:
N.B: I left the liblexilla version check for now. Do you want me to remove it ?
=> Genio 3: Fix 32 bit build

dev-embedded/esputil/esputil-1.0.1.recipe, dev-embedded/esputil/patches/esputil-1.0.1.patchset
Opening as draft, till I have the time to test it with real hardware (assuming I find my ESP8266, and it still works :-D).
=> esputil: new recipe.

haiku-apps/bescreencapture/bescreencapture-2.9.1.recipe
Howdy,
here's the recipe for BeScreenCapture 2.9.1
I fixed a bad memory leak which slipped through latest release.
=> Added recipe for BeScreenCapture 2.9.1

dev-vcs/git/git-2.45.2.recipe
Trying to fix the perl version dependency ...
=> git: add build requirement on vendor_perl

media-gfx/noteshrink/noteshrink-0.1.1.recipe
=> noteshrink: switch to Python 3.10, re-enable recipe.

dev-python/installer/installer-0.7.0.recipe
=> installer: don't use 'build' to avoid circular dependencies.

app-text/poppler/licenses/poppler_24.06.0-2_copyright, app-text/poppler/poppler23-23.09.0.recipe
this should fix some dependencies from tracking wrong Qt version
=> poppler23, revbump, move some requirements around

sci-visualization/labplot/labplot-2.11.1.recipe
previous bump failed on 32bit buildmaster
=> labplot, revbump for rebuild

dev-lang/nhc98/nhc98-1.22.recipe
Related issue: https://github.com/haikuports/haikuports/issues/5344
=> nhc98, add GNU GPL v2 license

media-libs/libdvdread/libdvdread-6.1.3.recipe
=> libdvdread: disabled GCC2 build

dev-util/gdb/gdb-15.1.recipe, dev-util/gdb/patches/gdb-15.1.patchset
This is a comprehensive port built from the ground up.
x86 support is dropped, but can be added in a later commit if absolutely required.
=> gdb: Add recipe for GDB 15.1

media-libs/libinstpatch/libinstpatch-1.1.3.recipe
Related issue: https://github.com/haikuports/haikuports/issues/10815
=> libinstpatch, fix fixPkgconfig

sci-electronics/minipro/minipro-0.7.recipe, sci-electronics/minipro/patches/minipro-0.7.patchset
Also includes:
- manpage support fix
- data location fix
- bash completion support
=> minipro: update to version 0.7

games-roguelike/crawl/crawl-0.29.0.recipe
Build tested on hrev57947, 64 bits.
=> crawl: move to Python 3.10.

media-sound/fluidsynth/fluidsynth-1.1.11.recipe, media-sound/fluidsynth/patches/fluidsynth-1.1.11.patchset
Csound current version still relies on this, so let's keep it around untill csound is updated/fixed.
=> fluidsynth, keep old (bisected) one around for csound

dev-python/wand/wand-0.6.13.recipe
The last one of the dependencies of psutils.
Could you please have a look again @OscarL ?
=> wand: new python recipe

haiku-apps/haiqr/haiqr-2.0.recipe
Remove empty line between PROVIDES and REQUIRES
=> remove empty line

games-engines/scummvm/patches/scummvm-2.8.1.patchset, games-engines/scummvm/scummvm-2.8.1.recipe
Fixes build for timidity backend
=> scummvm, revbump for openssl3 + build fix

net-misc/minidlna/minidlna-1.3.3.recipe, net-misc/minidlna/patches/minidlna-1.3.3.patchset
Built and smoke tested on 32 bits.
Haven't yet tested playing media from other devices, but the server already communicates with clients such as routers and TVs on the same LAN.
=> minidlna: fix build, clean up dependencies, enable recipe.

media-libs/rtaudio/patches/rtaudio-5.2.0.patchset, media-libs/rtaudio/rtaudio-5.2.0.recipe
No mediakit backend at the moment, dummy output only
=> rtaudio: add recipe

games-engines/gemrb/gemrb-0.9.3.recipe
A different fix to the error that made the [last master commit](https://github.com/haikuports/haikuports/commit/898d1d49f7d1b46132ca87015b1e735957c7d027) necessary, this edit to the recipe should make it work on multiple installs (as the results of "make install" do not seem consistent)
=> Fix gemrb recipe

dev-util/ccache/ccache-4.10.recipe
this caused a conflict between ccache_devel and libfmt_devel
=> ccache, revbump, drop fmt devel files/package

sys-boot/limine/limine-8.0.13.recipe
=> limine: add port

app-text/catdoc/catdoc-0.95.recipe
Dependency (runtime) for kfilemetadata
=> catdoc, new recipe

media-gfx/libresprite/additional-files/setup-data.sh, media-gfx/libresprite/libresprite-1.1~git.recipe
Closes: https://github.com/haikuports/haikuports/issues/11226
=> libresprite, fix data install path

dev-libs/qxlsx/qxlsx-1.4.8.recipe
Updating QXlsx to version 1.4.8
=> QXlsx 1.4.8

dev-lang/cppfront/cppfront-0.7.4.recipe
Headers inclusion is missing from original recipe.
=> cppfront : add missing headers

sys-block/di/di-4.54.recipe
=> Add di 4.54

app-emulation/vmware-addons/vmware_addons-1.2.2.recipe
Mostly just to avoid some syslog spam by vwmare_video.
---
Build and tested on 32 and 64 bits nightlies (still not there yet with my beta5 installs for recipe work).
=> vmware_addons: update to latest srcGitRev.

haiku-apps/pe/pe-2.4.5.recipe
Make with "$jobArgs", as using it has been stable for me for quite a while now.
=> pe: update to latest commit.

dev-vcs/fossil/fossil-2.25.recipe
SSL dependancy has been increased to v3 or higher.
=> fossil: update to 2.25

dev-python/tomli/tomli-2.0.1.recipe
No functional change intended.
=> tomli: recipe cleanups.

dev-python/gitpython/gitpython-3.1.40.recipe
Only on-tree user of this package (gertty) is 3.10 only already.
=> gitpython: minor cleanups, drop 3.9 package.

dev-python/gitdb/gitdb-4.0.11.recipe
Only user of this on-tree (gitpython) is dropping 3.9 on #11335.
=> gitdb: minor cleanups, drop 3.9 package.

net-libs/gwenhywfar/gwenhywfar-5.10.2.recipe, net-libs/gwenhywfar/patches/gwenhywfar-5.10.2.patchset
As part of the efforts of porting GnuCash I'll start uploading the recipes for the required dependencies. Please forgive any mistakes as I'm learning along the way (particularly, I'm thinking about possibly needing $secondaryArchSuffix because it probably won't compile with gcc2)
=> Gwenhywfar: new recipe

net-libs/aqbanking/aqbanking-6.5.4.recipe
Part of the Gnucash porting series. Depends on gwenhywfar (already submitted)
=> aqbanking: new recipe

dev-libs/libofx/libofx-0.10.9.recipe
Yet another dependency for GnuCash
=> libofx: new recipe

dev-db/libdbi/libdbi-0.9.0.recipe, dev-libs/libdbi/libdbi-0.9.0.recipe
Getting there... another dependency for GnuCash
=> libdbi: new recipe

app-misc/mc/mc-4.8.32.recipe, app-misc/mc/patches/mc-4.8.32.patchset
Built and tested on beta5 64 bits.
=> mc: update to version 4.8.32.

app-misc/crunch/crunch-3.6.recipe
A wordlist generator.
Not sure about the ARCHITECTURES, should I disable x86_gcc2 and enable x86 in SECONDARY_ARCHITECTURES? This should compile with every compiler under the sun.
=> crunch: new recipe

dev-libs/wayland/wayland-1.21.0~git.recipe
- par request from X512.
- https://github.com/haikuports/haikuports/pull/11368#issuecomment-2501477612
=> wayland: bump to git latest commit

dev-libs/libucl/libucl-0.9.2.recipe
new recipe for libucl
Libucl is a parser and C API to parse and generate ucl objects.
=> libucl: new recipe

x11-libs/gtk3/gtk3-3.24.36.recipe
Required for implementing https://github.com/X547/wayland-server/issues/14.
CC: @kenz-gelsoft, @threedeyes, @waddlesplash
=> gtk3: enable Wayland input method

www-client/iceweasel/iceweasel_bin-128.5.0.recipe
Fixes #11423
[65846f282d1033e2544dfb85f5ac9741e3395162...89fed9f5be5112567e07ef5663ed67cea4750a53](https://github.com/kenz-gelsoft/gecko-dev/compare/65846f282d1033e2544dfb85f5ac9741e3395162...89fed9f5be5112567e07ef5663ed67cea4750a53)
=> Iceweasel: store config in ~/config/settings/Mozilla

dev-lang/nim/nim-2.0.8.recipe
=> nim: fixes and workarounds

app-shells/fish/fish-3.7.1.recipe, app-shells/fish/patches/fish-3.7.1.patchset
Fixes #11300
Still not fully functional, though (tends to hang quite easily).
---
(Had forgotten about this one. Better here than rotting on my disks)
=> fish: recipe cleanups.

net-im/tokodon/tokodon-24.12.0.recipe
solves missing org.kde.desktop
=> tokodon, add missing dependency

dev-python/pygame/pygame-2.0.0.recipe, games-puzzle/monsterz/monsterz-0.7.1.recipe, games-puzzle/pathological/pathological-1.1.3_17.recipe, games-simulation/singularity/singularity-1.00.recipe
=> pygame: fix recipe issues, update affected recipes.

dev-python/gast/gast-0.6.0.recipe
smol, formally independent recipe in a way to pythran and (hopefully) scipy.
=> python: gast, new recipe

dev-perl/text_bibtex/patches/text_bibtex-0.89.patchset, dev-perl/text_bibtex/text_bibtex-0.89.recipe
I need to check this on x86 before merging this.
=> text_bibtex: new perl module recipe

dev-python/numpy/numpy-1.26.0.recipe
(build tested on beta5 32 bits this time)
=> numpy: fix 32 bits build.

dev-python/pbr/pbr-5.5.1.recipe
Only gertty uses this, and that uses Python 3.10 only.
=> pbr: cleanups, drop Python 3.9.

dev-qt/qt6-base/qt6_base-6.7.2.recipe
NULL check.
Default and fallback font names.
=> qt6_base: get latest qt6-haikuplugins

games-emulation/pokemini_libretro/additional-files/pokemini_libretro.info.in, games-emulation/pokemini_libretro/pokemini_libretro-0.60_20241021.recipe
Additional core for Retroarch.
=> pokemini_libretro, new recipe

sci-libs/libsigrokdecode/libsigrokdecode-0.5.3.recipe
=> libsigrokdecode: switch to Python 3.10.

app-misc/ranger/ranger-1.9.3.recipe
Also, switch from setup.py to build/installer.
=> ranger: move to Python 3.10.

dev-util/cram/cram-0.7.recipe, dev-util/cram/patches/cram-0.7.patchset
Also:
- switch from setup.py to build/installer.
- ran --test and added results for reference.
=> cram: move to Python 3.10.

dev-lang/python/patches/python3.12-3.12.9.patchset, dev-lang/python/python3.12-3.12.9.recipe, dev-python/cryptography/cryptography-3.4.8.recipe
Smoke tested on beta5 64 bits.
=> python3.12: update to version 3.12.9.

media-sound/picard/picard-2.13.1.recipe
New release from today. Tested the build on x86 Haiku.
=> picard: bump version to 2.13.1

app-misc/nnn/nnn-5.0.recipe
=> nnn: disable X11 integration

dev-python/pybind11/pybind11-2.13.6.recipe
Update needed by scipy 1.15.1.
Cleaned up recipe, drop Python 3.9.
=> pybind11: update to version 2.13.6.

media-libs/libmygpo-qt/libmygpo_qt-1.1.0.recipe
Optional dependency for Amorak
=> libmygpo_qt5, new recipe

kde-frameworks/kimageformats/kimageformats6-6.11.0.recipe, kde-frameworks/kimageformats/patches/335.patch
Fixes build for Qt6 version prior to 6.8
=> kimageformats6, add upstream patch

sys-apps/findutils/findutils-4.9.0.recipe
=> findutils, revbump, don't call cmd:ld (gcc2)

kde-frameworks/kuserfeedback/kuserfeedback6-6.11.0.recipe
No revbump needed, 64bit was already build.
=> kuserfeedback6, trigger build after php8 changes for 32bit

dev-python/numpy/numpy-2.2.1.recipe
Also: remove cython as runtime dependency.
=> numpy: fix build on 32 bits.

media-libs/flac/flac-1.5.0.recipe, media-libs/flac/flac1.4-1.4.3.recipe, media-libs/flac/licenses/GNU FDL v1.3, media-libs/flac/patches/flac-1.5.0.patchset
~~move commands to tools package to avoid conflicts~~ removed in favor of the new version
=> flac, bump version, rename previous

dev-vcs/tig/tig-2.5.12.recipe
=> tig: update to version 2.5.12.

media-libs/libsndfile/libsndfile-1.0.25.recipe, media-libs/libsndfile/libsndfile-1.2.2.recipe
Fix requirement for libflac on 32bit
=> libsndfile, add missing devel requirement

dev-lisp/sbcl/sbcl-2.5.2.recipe
SBCL is now compiled with SBCL instead of CLIPS. The compilation time is much <s>slower</s> faster.
EDIT: I misspelled "lower" by "slower", which changed the sense to opposite :D
=> SBCL 2.5.2

sys-libs/vulkan/patches/vulkan-1.4.305.patchset, sys-libs/vulkan/vulkan-1.4.305.recipe
=> vulkan: use FindDirectory

dev-util/kdevelop_php/kdevelop_php-24.12.3.recipe
leave disabled, intended for kdevelop KF6
=> kdevelop_php, bump to 24.12.3

net-im/nheko/nheko-0.12.0.recipe, net-im/nheko/patches/nheko-0.12.0.patchset
patches from upstream, master branch already checked and is good without patching for this
=> nheko, revbump, fixes build with new libfmt

dev-cpp/xsimd/xsimd-13.2.0.recipe
this is a requirement to be able to build Krita from master branch
=> xsimd, add version 13.2.0

games-strategy/freesynd/freesynd-0.8.recipe
Fixing a typo that slipped notice
=> Freesynd: fix 32bit build

games-engines/gemrb/additional-files/gemrb-postinstall.sh, games-engines/gemrb/gemrb-0.9.4.recipe
Some touchups to gemrb's recipe. I have more changes for it in the pipeline (like removing the post-install script) but I decided to roll them back because they could ruin the package for beta 5
=> Gemrb: recipe fixes

media-libs/kvazaar/kvazaar-2.3.1.recipe, media-libs/kvazaar/patches/kvazaar-2.3.1-source2.patchset
=> kvazaar, bump to version 2.3.1

app-text/poppler/patches/poppler-23.12.0.patchset, app-text/poppler/patches/poppler-24.12.0.patchset, app-text/poppler/patches/poppler-25.04.0.patchset, app-text/poppler/poppler23-23.12.0.recipe, app-text/poppler/poppler24-24.12.0.recipe, app-text/poppler/poppler25-25.04.0.recipe
=> bump poppler recipes

kde-apps/okular/okular_kf5-23.08.5.recipe
Calligra4 is not in the depot yet, so rely on KF5 for now
=> okular, re-add KF5 version of Calligra

games-emulation/es-de/es_de-3.2.0.recipe
Set version strings for ICU74 and ffmpeg6
Fixed indents (spaces vs tabs)
=> es_de, revbump for poppler changes, keep on poppler24 for now

media-gfx/krita/krita-5.2.9.recipe
Bump boost from 1.83.0 to 1.85.0
=> krita, revbump for poppler changes, move from poppler23 to poppler24

media-libs/opentimelineio/opentimelineio-0.17.0.recipe, media-libs/opentimelineio/patches/opentimelineio-0.17.0.patchset
This is a new dependency for KDenlive
=> opentimelineio, new recipe for version 0.17.0

sys-devel/llvm/llvm18-18.1.7.recipe, sys-devel/llvm/llvm19-19.1.7.recipe, sys-devel/llvm/llvm20-20.1.0.recipe, sys-devel/llvm/patches/llvm18-18.1.7.patchset, sys-devel/llvm/patches/llvm19-19.1.7.patchset, sys-devel/llvm/patches/llvm20-20.1.0.patchset
=> LLVM, bump revision for version 18, 19 and 20

app-emulation/rvvm/rvvm-0.7~git.recipe
Co-authored by: X512 <danger_mail@list.ru>
=> rvvm, add recipe for 0.7~git

dev-python/cson/cson-0.8.recipe, dev-python/speg/speg-0.3.recipe
speg is a dependency of cson.
cson is a dependency of the asymptote GUI (see #12205), so this must be merged before that.
=> cson, speg: new python recipes

dev-python/sphinxcontrib-serializinghtml/sphinxcontrib_serializinghtml-2.0.0.recipe
required to install poetry with pip in Terminal
=> sphinxcontrib_serializinghtml, bump to 2.0.0

games-util/lgogdownloader/lgogdownloader-3.16.recipe
=> lgogdownloader, revbump for new tinyxml2

dev-db/sqlitecpp/sqlitecpp-3.3.2.recipe
SQLiteC++ offers an encapsulation around the native C APIs of SQLite, with a few intuitive and well documented C++ classes.
Tested and working on x64, used when building #12271 with shared libraries.
(which fails due to some other library version mismatch shenanigans)
=> SQLiteC++ port

media-gfx/sane_backends/sane_backends-1.3.1.recipe
add some missing secondaryArchSuffix flags + use pythonVersion string for cmd:python also
=> sane_backends, revbump, fix 32bit (needs optimization flag)

dev-lang/64tass/64tass-1.60.3243.recipe
There was a new release last week, update to it.
=> 64tass: update to 1.60.3243

media-libs/zxing-cpp/zxing_cpp-2.3.0.recipe
tools require external stb sources pulled in by required git
=> zxing_cpp, bump to 2.3.0, drop tools

net-im/abaddon/abaddon-0.2.2~git.recipe
spdlog latest is build against libfmt >= 11
=> abaddon, fix for 64bit, make sure to use the correct libfmt

net-libs/nodejs/nodejs16-16.11.1.recipe, net-libs/nodejs/patches/nodejs-16.11.1.patchset
For now keep this around for 32bit.
=> nodejs16, re-instate, upped some dependencies

dev-libs/ktextaddons/ktextaddons-1.6.0.recipe
=> ktextaddons, bump version, disable for now

net-libs/libproxy/libproxy-0.5.9.recipe
requirement for newer glib-networking
=> libproxy, new recipe

media-gfx/krita/krita-5.2.11.recipe
Add missing requirement on mlt
=> krita, bump version (bugfix) to 5.2.11

app-vim/youcompleteme/youcompleteme-20241216.recipe
Draft for now, as I've only lightly tested it with llvm16 (until I can download llvm20_clang).
=> youcompleteme: recipe clean ups, switch to libclang 20.

sci-libs/opencascade/opencascade-7.8.1.recipe
=> opencascade, no revbump, re-arange for doxygen, fixes consistency report

dev-libs/glib/glib2-2.78.0.recipe, dev-libs/glib/patches/glib2-2.78.0.patchset
* our kqueue implementation is not compatible yet.
=> glib: Disable kqueue on Haiku; solves #12823

app-text/notes/notes-2.3.1.recipe
- Updated from 2.1.0 to 2.3.1
- Added Qt6 QML/Quick dependencies
- Verified build and runtime on Haiku x86_64 (r1beta5)
=> notes: bump to 2.3.1

games-strategy/ja2_stracciatella/ja2_stracciatella-0.16.1.recipe
=> ja2_stracciatella, revbump, bump boost requirement

sci-astronomy/stellarium/stellarium-25.3.recipe
Added compiled translations as external resource for package - I hope it resolves trouble in 32-bit builder
=> Stellarium 25.3: added workaround for NLS feature
