dev-python/paramiko/paramiko-2.11.0.recipe

Test still fails, but invoke/pytest_relaxed are not found, when enabled test will fail due to some known issue there.

paramiko, bump version, add python{3.8,3.9,3.10}

---

app-benchmarks/stress-ng/patches/stress_ng-0.14.06.patchset
app-benchmarks/stress-ng/patches/stress_ng_x86-0.14.06.patchset
app-benchmarks/stress-ng/stress_ng-0.14.06.recipe

some new alignment issues on 32-bit
otherwise the command line from trac ticket 17448 runs successfully:
`stress-ng --cpu 2 --vm 2 --hdd 1 --fork 8 --timeout 2m --metrics`

stress-ng: bump to version 0.14.06

---

net-analyzer/iperf/iperf3-3.12.recipe
net-analyzer/iperf/patches/iperf3-3.12.gcc2.patchset
net-analyzer/iperf/patches/iperf3-3.12.patchset

There are a few kludges, I hope you'll still like it:
* name clash for `get_system_info()` resulting in stack overflow. I just renamed it to `do_get_system_info()`
* iperf3 uses IPv6 by default which doens't really work on Haiku so I changed default to IPv4
* the usual variable declaration issues on gcc2

iperf3: new recipe

---

dev-util/md4c/md4c-0.4.8.recipe

md4c: bump to version 0.4.8

---

haiku-apps/ponpokodiff/ponpokodiff-0.2.0.recipe

The recipe now uses $srcGitRev.
With the latest changes (from Nov 2021) you can now select two files from Tracker, and use "Open With -> PonpokoDiff" and it will show the Diff window right away (as one might have expected) making it SO MUCH more handy!

PonpokoDiff: bump to latest gitrev.

---

media-libs/speex/patches/speex-1.2.1.patchset
media-libs/speex/speex-1.2.1.recipe
media-libs/speexdsp/speexdsp-1.2.1.recipe

Adds a patch for GCC 2.95 compatibility (the definition of ALLOC for variable length arrays generated non-top-of-block variable declarations).
Also adds libspeexdsp as a dependency of speex. This enables two processing options in speexenc that were missing on Haiku.

speex/speexdsp: bump to 1.2.1

---

app-shells/hstr/hstr-2.5.recipe
app-shells/hstr/patches/hstr-2.5.patchset

* Use the proper configuration instructions for bash in Haiku. Big thanks to madmax for finding the issue!
* Reworked the patch about the history files locations.
* Removed the TEST() section, as "make check" had "nothing to do".
* Removed "-I m4" from aclocal, as it was not necessary.
The issue was that, on platforms that lack the TIOCSTI ioctl, a workaround is needed to be able to insert text on the shell's command line. The workaround relies on defining a shell function, and keybinding said function so it gets handled by readline.
Now, following the "hstr --show-configuration" instructions will result in C-r working as expected, at least for bash.
It still won't under zsh (for the lack of a similar workaround, but implemented as a zsh function).

hstr: fix configuration instructions and other minor changes.

---

app-shells/bash_completion/bash_completion-2.11.recipe

Make sure bash_completion.sh is placed under `settings/etc/profile.d/` and not `settings/profile.d`. Otherwise bash would not source it properly.
Fixes #7233

bash_completion: fix location of bash_completion.sh

---

media-libs/portmidi/portmidi-2.0.3~git.recipe

OpenJDK 11 is an LTS version. This is probably the most appropriate version.

portmidi: use fixed java version 11, don't require cmd:java

---

dev-libs/zziplib/zziplib-0.13.72.recipe

Fix zziplib cmake build error by specifying build type.

Fix zziplib cmake build error

---

app-editors/ne/ne-3.3.2.recipe
app-editors/ne/patches/ne-3.3.2.patchset

~~A simple "is the workaround already applied" check is performed before making any change. Not ultra-sophisticated, but seems to work.~~
Should close #7333.
~~Tested with system and home package installations, without a `.keys` file in `~/config/settings/ne`, with one already containing the fix, and with an existing `.keys` with user content, but not the workaround.~~
~~Worked OK for me on these 6 cases. Albeit I've only tested these on 64 bits, I would expect it to work ok on 32 bits too.~~
~~This is my first time using post-install scripts, so... any suggestions/criticisms will be more than welcomed.~~
Thanks! 
Edit: workaround now applied directly on the executable, and not as a post-install keybinding setting.

ne: change default action for backspace key, and build against ncurses to fix redrawing issues.

---

media-libs/libsndfile/libsndfile-1.0.25.recipe
media-libs/libsndfile/libsndfile-1.1.0.recipe

Bump revisions of libsndfile recipes to rebuild with FLAC 1.4.2.
**Should be merged after #7292.**
Needed because devel:libsndfile depends on devel:libflac and will be broken after the libFLAC soname change.

libsndfile: bump revision to rebuild with FLAC 1.4.2

---

media-sound/lilypond/lilypond-2.22.2.recipe

Also improve summaries of doc packages. For the language names, a similar technique to python packages is used.

lilypond: replace texlive package requires with "tex:" ones

---

haiku-apps/bepdf/bepdf-2.1.4.recipe

Switching to latest git commit, and dropping freetype_config in favor of pkg_config fixes the builds on newer Haiku revisions.
Builds and runs OK on both 64 and 32 bits (hrev56584).

BePDF: switch to latest git commit.

---

haiku-apps/bepodder/bepodder-1.5.0.recipe

This solves the missing symbol and build issues, and will also enable the use of the newer/updated translations.
Edit: Tested on both 32 and 64 bits installs.

BePodder: switch to using srcGitRev (and latest git-rev).

---

app-shells/fish/fish-3.5.1.recipe
app-shells/fish/patches/fish-3.5.1.patchset

Thanks to the good work recently by waddlesplash on FIFOs and trungnt2910 on locale_t, the latest version of fish shell now compiles and runs on Haiku with minimal changes.
I tried porting extrowerk's patch to fix the crash on exit from fish 2.7.1, but it doesn't seem to work so I removed it.
I'm submitting this recipe anyway in case someone else can fix it, or it can be lived with for now.

fish: bump version

---

media-sound/audacity/audacity-3.1.3.recipe

We need to disable VST plugins to rebuild with Wayland.
After that the GUI is much better: no more flickering and the hotkeys and toolbar icons work much better.

audacity: disable vst

---

net-ftp/filezilla/filezilla-3.62.1.recipe
net-ftp/filezilla/patches/filezilla-3.62.1.patchset

We need a few kludges:
* enable build with wxWidgets 3.2 - by default filezilla requires 3.0
* stub function ShellUnescape as we don't have `wordexp`
* adjust folder names
With these changes, it's possible to build filezilla without any policy warnings (in haikupoter strict mode as well), filezilla starts up succesfully. I tested connecting to localhost and retrieving directory listing, not much else.

filezilla: new recipe

---

net-analyzer/wireshark/additional-files/wireshark.rdef.in
net-analyzer/wireshark/wireshark-4.0.1.recipe

* rdef used to have hard-coded version 2.0.0 let's replace it with automatically generated version number
* build with ninja
* revbump to trigger rebuild (especially needed for x86_64 as previously the builder was lost)

wireshark: update rdef, enable ninja build

---

net-ftp/filezilla/filezilla-3.62.2.recipe
net-ftp/filezilla/patches/filezilla-3.62.2.patchset

FileZilla 3.62.2 almost officially builds with wxWidgets 3.2.x - we need to cherry-pick only a single commit from upstream.

filezilla: update to 3.62.2

---

net-ftp/filezilla/filezilla-3.62.2.recipe
net-ftp/filezilla/patches/filezilla-3.62.2.patchset

Use BNotification instead of wxNotificationMessage as the latter one misbehaves (causes GUI lockups)
I'm not removing the untested flag yet - preferrably it should be tested by more users before we enable this recipe in HaikuDepot.

filezilla: use BNotification

---

media-video/gnash/gnash-0.8.11~git.recipe

Updated to latest git revision.
1. Fixed build on R1B4 x86 and x64.
2. Disabled x86 build for now.
Closes: https://github.com/haikuports/haikuports/issues/82

gnash: bump to current git version

---

haiku-data/wallpaper_community/licenses/CC-BY 4.0
haiku-data/wallpaper_community/licenses/CC-BY-SA 4.0
haiku-data/wallpaper_community/wallpaper_community-0.1.recipe

This package contains community-made wallpapers from https://github.com/haiku/artwork/pull/9, mostly from the initial submissions of the [Call for Wallpapers](https://www.haiku-os.org/news/2020-10-04-wallpaper-contest/).
Need advice regarding what license to put in the recipe, as the wallpapers are licensed with a mix of CC-BY and CC-BY-SA 4.0-International. `Public Domain` is just a placeholder for now.

wallpaper_community: Add recipe

---

media-sound/audacity/audacity-3.2.2.recipe

Networking was already disabled implicitly but let's make this explicit so that we can ascertain that telemetry is not built.

audacity: disable networking

---

sys-libs/glu/glu-9.0.0.recipe
sys-libs/glu/patches/glu-9.0.0.patchset

Added patchset for: `error: 'NULL' undeclared here (not in a function)` on secondary architecture.

glu, remove static library

---

media-libs/portsmf/portsmf-239.recipe

32-bit builder failed because of a typo, fixing it with this PR

portsmf: fix 32-bit build

---

media-sound/audacity/patches/audacity-3.2.2.patchset

This change allows audacity to find locales and plugins.
I'm not enabling this recipe yet as the crash on exit is still there unfortunately, somehow also related to locales but I couldn't find out what happens exactly.
as an example we can see nyquist plugins in the plugin list with Hungarian locale on the screenshot

audacity: adjust folder names

---

net-analyzer/speedtest-cli/speedtest_cli-2.1.3.recipe

Also: drop unsupported Python versions (and only provide a package for the default Python on beta4).
I saw a commit related to Python 3.10 support on the speedtest-cli repo, but it were newer than the 2.1.3 release, so... let this recipe update stick to 3.9 (works for me on beta4 with Python 3.9).

speedtest_cli: update to latest release, and switch to Python 3.9.

---

media-libs/smpeg2/patches/smpeg2-2.0.0.patchset
media-libs/smpeg2/smpeg2-2.0.0.recipe

Cleaned up the recipe somehow. The resulting "plaympeg" is still non-functional, at least with the sample files I have:
On 64 bits: Shows a white, empty window.
On 32 bits: Shows a black, empty window.
That after properly recognizing the file as a video file, give the correct details of resolution and duration, but repeating the message:
"Warning: picture block before sequence header block".
Previous revisions (smpeg2-2.0.0-4) showed same behavior. Only difference is that old version (on 64 bits at least) loads "add-ons/opengl/Software Pipe" and prints:
"GalliumContext: CreateDisplay: Using llvmpipe (LLVM 12.0.1, 128 bits) driver"

smpeg2: fix build with modern GCC.

---

dev-lua/luv/luv-1.43.0.recipe

devel:libluv_a$secondaryArchSuffix isn't used anywhere

luv, disable static library

---

app-shells/zsh/zsh-5.8.1.recipe

Needed after the update on the libgdbm recipe (#7704).
Tested on 64 bits.
~Not sure if this change is enough, or specifying that the compat is with "4.0" version only.~
~If that's the case, suggestions (or links to a good example) on what's the right syntax for that... are more than welcome.~

zsh: rev-bump to fix libgdbm dependency

---

net-misc/lagrange/lagrange-1.14.1.recipe

lagrange: bump to 1.14.1

---

media-sound/lilypond/lilypond-2.24.0.recipe
media-sound/lilypond/patches/lilypond-2.24.0.patchset

Note: the recipe is still disabled because it requires texlive to build. I will rebase #7316 when this is merged.

lilypond: bump version

---

haiku-data/be_book/be_book-2008_10_26.recipe

The original files have the type attribute set already, with CSS files taken as text/x-source-code.

BeBook: fix mime types

---

haiku-apps/torrentor/torrentor-0.0.5.recipe

Broken since long ago (no packages on Haiku Depot).
Disable until builds gets fixed upstream (might require "transplanting" code from transmission and its .patchset for Haiku.

torrentor: mark as broken for all platforms.

---

dev-lang/tcl/patches/tcl-8.6.13.patchset
dev-lang/tcl/tcl-8.6.13.recipe

The so version is the same as in 8.6.12 therefore the recipe was just renamed. OpenCASCADE's DRAW still runs.
Should I remove version 8.6.11?
Tests don't run successfully. Some tests hang, and one test even crashes with an assertion in free.

tcl: update to version 8.16.13

---

net-print/gutenprint/gutenprint8-5.3.1.recipe
net-print/gutenprint/gutenprint9-5.3.4.recipe
net-print/gutenprint/patches/gutenprint9-5.3.4.patchset

After the changes on Haiku's dirent.h, gutenprint needs a bit of help to figure things out.
Also remove the static libs from the (devel) packages.
Fixes #7550.
Built on 64 bits.
Any simple way of testing the resulting libs?

gutenprint{8,9}: fix build and remove static libs.

---

dev-python/requests-futures/requests_futures-1.0.0.recipe

pypi.org now hosts this file at files.pythonhosted.org, updated to use version 3.9 of python

requests-futures: source URI out of date, changed python 3.7 to 3.9

---

dev-lang/r/r-4.2.2.recipe

Last build on buildmaster failed, issue with cairo vs xcairo? https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/3659/builds/79370.log

R, disable X11 for now

---

media-sound/fluidlite/fluidlite-1.0.9.recipe

This addresses: https://github.com/haikuports/haikuports/pull/7697#issuecomment-1367583768

fluidlite, re-enable and rename static library used by Haiku builds

---

dev-libs/libevent/libevent-2.1.12.recipe

- Remove left-over "CONFLICTS_devel".
- Undo the wrongful addition of `$manDir` to the `packageEntries devel` section.
Built and test-installed on:
64 bits:
- libevent-2.1.12-2-x86_64.hpkg
32 bits:
- libevent-1.4.14b-3-x86_gcc2.hpkg
- libevent_x86-2.1.12-2-x86_gcc2.hpkg
(along with their `_devel` packages)

libevent: fixup, again, errors in the previous PR (#7754).

---

www-client/links/links-2.28.recipe

This seems to have been broken since the update to 2.28, as 2.21 is the last version available on the repositories.
The fix avoids errors resulting from conflicting integer types between the <tiff.h> and <SupportDefs.h> headers.
Needed to also specify "-g -O2 -fopenmp" when defining CFLAGS to avoid linking errors (and to match the default flags).
None of this is necessary on x86_64, thus the conditional on "x86".

links: fix build on x86 (32 bits).

---

net-misc/lagrange/lagrange-1.14.2.recipe

lagrange: bump to 1.14.2

---

net-analyzer/tcpdump/patches/tcpdump-4.99.3.gcc2.patchset
net-analyzer/tcpdump/patches/tcpdump-4.99.3.patchset
net-analyzer/tcpdump/tcpdump-4.99.3.recipe

The patch for `aclocal.m4` is still needed - could be upstreamed.
make check: 1 failed test case `nflog-e`, this is better test result than on any previous version so far.

tcpdump: update to 4.99.3

---

dev-qt/qtwebengine/qtwebengine_bin-5.15.2.recipe

Fixes: https://github.com/haikuports/haikuports/issues/7766

qtwebengine_web, for now depend on libevent >= 6.0.2

---

media-libs/x265/x265-3.5.recipe

The recipe for x265 3.5 contained a statement -DENABLE_ASSEMBLY=OFF which caused encoding libraries for both 10 bit and 12 bit to be built without assembly optimizations.
I removed that statement and now nasm is used to build faster versions of the libs.

x265: enabled assembly for 10bit & 12bit encoding libs

---

sys-apps/dtc/dtc-1.6.1.recipe

We need to reapply this workaround unfortunately. I was a bit too enthusiastic with #7607 and #7674 - while it's true that I was able to get a sucessful qemu build with new libfdt but I tested it only on old libfdt :disappointed:

dtc: re-add libfdt symlink

---

media-libs/portmidi/portmidi-2.0.4.recipe

also fix the requirement of cmd:javac (actually openjdk_default)

portmidi: bump version

---

dev-libs/libiconv/libiconv-1.17.recipe

libiconv should be built with **--enable-extra-encodings**, so that standard items like CP437 used by open cubic player is included.
Fixes #7781

Build libiconv with --enable-extra-encodings

---

app-office/sc-im/patches/sc_im-0.8.3.patchset
app-office/sc-im/sc_im-0.8.3.recipe

`sc-im` is to `sc` as `vim` is to `vi`, or so it seems.
Only enabled the basics to keep dependencies low.
In the future, could require/use `gnuplot` for "charts", `libxml2` and `libzip` for xlsx/ods import support, and/or `lua` for scripting.
----
Tested on beta4, 64 and 32 bits (x86).

sc-im: new recipe

---

app-office/sc/sc-7.16_1.1.2.recipe

Tested on beta4, 64 and 32 bits (x86).
Placed it under `app-office` following the example from Gentoo, that, despite not having `sc` proper, it does has [sc-im](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-office/sc-im) (will submit a PR for that one later).

sc: new recipe

---

app-text/dblatex/dblatex-0.3.12.recipe
app-text/texlive/texlive-2022.recipe
media-sound/lilypond/lilypond-2.24.0.recipe

this enables the texlive recipe and others which depend on it
I noticed that R (dev-lang/r) also has commented-out dependencies of texlive. Maybe this could be checked later as well.

texlive, dblatex, lilypond: enable

---

net-analyzer/wireshark/patches/wireshark-4.0.3.patchset
net-analyzer/wireshark/wireshark-4.0.3.recipe

Build and smoke test successful on 32-bit&64-bit, with the same patch:
* fix build for cpu_info.c and interface_toolbar_reader.cpp - probably these could be upstreamed
* the usual hassle with paths in CMAKE which should probably not be upstreamed
* adjust directories in various places of the source code
For some strange reason i'm getting 'crash on exit' on 32-bit beta4 again. (edit: that seems to be the case also for Wireshark 4.0.2 which used to work fine on 32-bit nightly. So perhaps some difference between nightly and beta?)

wireshark: update to 4.0.3

---

media-sound/lilypond/lilypond-2.24.0.recipe

Ghostscript >= 9.03 is actually [required](http://lilypond.org/doc/v2.24/Documentation/contributor/requirements-for-running-lilypond).
This is untested, but a rather trivial change.
A revision bump shouldn't be needed here, correct?

lilypond: require libgs >= 9

---

net-ftp/filezilla/filezilla-3.63.1.recipe
net-ftp/filezilla/patches/filezilla-3.63.1.patchset

* update to latest release
* now it builds with wxWidgets 3.2 out of the box so we no longer need to patch configure.ac
* add dependency on xlibe - it is actually required
* I think now it's good enough to enable this recipe.

filezilla: update to 3.63.1

---

sys-devel/gettext/gettext-0.21.1.recipe

Fixes #7817
Tested on beta4 64-bits.

gettext_devel: fix #7817 (broken links)

---

sys-apps/texinfo/patches/texinfo-6.7.patchset
sys-apps/texinfo/texinfo-6.7.recipe

Using texinfo 6.7 fixes the `info` files build failure of lilypond reported [here](https://github.com/haikuports/haikuports/pull/7809#issuecomment-1407463711)
Should we delete texinfo-6.1 now?

texinfo 6.7: fix gcc2 build

---

net-libs/libnatpmp/libnatpmp-20150609.recipe
net-libs/libnatpmp/patches/libnatpmp-20150609.patchset

Patch is mostly imported from Gentoo.

libnatpmp, disable static library

---

media-sound/ocp/ocp-0.2.102.recipe

This depends on new version of app-arch/ancient #7793

media-sound/ocp: Version bump and general update of recipe

---

app-text/texlive/additional-files/texlive_update.sh

As it was mentioned on the forums that running the post-install script can take a while. Let's not make the user wonder if installation has failed and show a notification.
I did **not** test this by actually building/installing texlive...

texlive: add notification when post-installing

---

media-libs/libmatroska/libmatroska-1.7.1.recipe

I removed the recipe for 1.6.3 since the packages that require it are the same as for libebml.

libmatroska: update to 1.7.1

---

dev-qt/wxqt/patches/wxqt-3.2.2.patchset
dev-qt/wxqt/wxqt-3.2.2.recipe

similarly to wxgtk:
successful build on 32&64-bit (incl. all demos and samples)
we still need the backported patches
in addition, adopt the fix for `strftime` and `wx-config` from wxgtk

wxqt: update to 3.2.2

---

media-sound/lilypond/lilypond-2.24.1.recipe

When building for a secondaryArch, haikuporter prepends $PATH with the secondaryArch binDir, so just removing the first 2 characters for removing '.' from $PATH doesn't work. This makes that a bit more robust. (Having '.' at the end would still not work though.)

lilypond: fix secondaryArch (x86) build

---

games-emulation/mupen64plus/mupen64plus-2.5.9.recipe

This fixes the `lto1: out of memory` error.

mupen64plus: Disable ASLR to fix x86 build

---

media-sound/mac/mac-9.20.recipe

Attention: SONAME change!
However, fre:ac appears to be the only package using libMAC and I will open a pull request to update it too. So I think the SONAME change shouldn't matter.

mac: bump to 9.20

---

dev-libs/smooth/patches/smooth-0.9.10.patchset
dev-libs/smooth/smooth-0.9.10.recipe

Add a patch to the smooth library to fix a crash when querying CPU information. Unfortunately, this issue was found only now and fre:ac 1.1.7 is unusable on Haiku without this.
This patch is already in the upstream smooth repository, so it will be needed only until the next release.
I have opened a PR at the libcpuid repository as well: anrieff/libcpuid#186 There is no HaikuPorts recipe for libcpuid yet, so smooth uses a bundled version of the library.

smooth: add patch to fix crash in CPUID code

---

.github/workflows/lint.yml

This makes the output of the lint job much shorter - example at https://github.com/Habbie/haikuports/actions/runs/4388705870/jobs/7685501803
(the Set up job became extra verbose because we call `--repository-update` explicitly - this will be solved by https://github.com/haikuports/haikuporter/pull/246)

move haikuporter repo update before Lint job

---

games-mud/mudlet/mudlet-4.0.3.recipe
games-mud/mudlet/patches/edbee-lib-git.patchset

This builds and runs but the main screen complains about a load of missing lua modules. Not sure what needs to be done to fix it, but the old version had the same errors.

mudlet: Use Boost 1.70

---

app-arch/innoextract/innoextract-1.9.recipe

Using Boost 1.69 as 1.70 failed to work. EDIT: Found an alternative solution to use 1.70.

innoextract: Update to 1.9, Use Boost 1.70

---

media-libs/libass/libass-0.16.0.recipe
media-libs/libass/libass-0.17.1.recipe

- cleanup dependencies
- enable x86 assembly usage in builds
- disable static library build *(apparently required for all packages now?)*
- update to 0.17.1

libass: update to 0.17.1, enable assembly and cleanup

---

games-action/ddnet/ddnet-2023.03.12~git.recipe

recipe unexpectedly broke because of ~git suffix, tested on x86_64
See: https://github.com/haikuports/haikuports/pull/7951
Build logs of build mysteriously failing: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/8219/builds/78935.log

ddnet: fix recipe

---

haiku-data/be_book/be_book-2008_10_26.recipe

BAppFileInfo_Overview.html had "text/plain" before.

be_book: make sure that all .html files have the same mimetype

---

app-arch/lizard/lizard-1.0.recipe

Keep binaries as primary target on 32bit is broken.

lizard, remove static library

---

haiku-apps/trackgit/trackgit-1.0.0~git.recipe

When trying to `pkgman install trackgit`, I was getting the error:
> problem 1: nothing provides lib:libgit2>=1.4.3 needed by trackgit-1.0.0~git-3
Additionally, attempting to rebuild locally, build was failing with an error about the `git_status_options` struct not having a "baseline" field (it was pulling in the `libgit2_25-0.25.1-3` packages).
----
Also, seems to me like `dev-libs/libgit2` could use a clean up of the older recipes. Task for someone more experienced than me :-)

trackgit: require libgit2 >= 1.5.0

---

app-i18n/libguess/libguess-1.2_20150906.recipe

Upstream doesn't exist anymore, no releases or tags on github so used latest commit date.

libguess, fix build

---

dev-python/more-itertools/more_itertools-8.14.0.recipe

Switch to "installer" (instead of setuptools). Final package doesn't suffers the problems mentioned on #7962 (no .py files, UKNOWN-0.0.0 as package name-version).
Package can be installed, imported, and looks fine on a first inspection (tested on Python 3.10).

more_itertools: install from the .whl file

---

dev-python/pytest/pytest-7.1.3.recipe

Only list as dependencies those packages that are listed in pytest's setup.cfg.

pytest: fix versioning, cleanup dependencies.

---

app-text/asciidoc/asciidoc-10.1.3.recipe

No functional change for the package per se, so, no change in revision.

asciidoc: use Python 3.9 also for TEST_REQUIRES.

---

dev-python/twisted/twisted-22.8.0.recipe

- use loops for PROVIDES_pythonxx.
- simplify code where possible.
- remove checks related to x86_gcc2.
It should be easier to add support for newer Python versions now.
---
Tested on 64 bits. Compared contents and package info against the `twisted_python39` from the repos. Both match.
I haven't bumped the revision number, as there's no functional change. Will add it if reviewers think it's necessary.
I'm a bash newbie, so if there are suggestions regarding syntax, variables expansions, and such, please be explicit, or it will most likely go over my head.

twisted: recipe clean up

---

dev-python/slixmpp/slixmpp-1.8.2.recipe

`net-im/poezio` is the sole user of this in-tree. This version is needed to update poezio to 0.14 (PR for that will follow).

slixmpp: update to 1.8.2, switch to Python 3.9+

---

dev-python/cffi/cffi-1.15.1.recipe

Should fix the 32 bits build of pycares after #8035.

cffi: Drop Python 3.7. Provide "non _x86" package name on x86_gcc2.

---

dev-python/yarl/yarl-1.6.3.recipe

Build was broken for x86_gcc2.

yarl: switch to x86, drop support for Python 3.7, add it for 3.10.

---

dev-python/multidict/multidict-4.5.2.recipe

Build was broken on x86_gcc2 (requires compiler with C99 support).

multidict: switch to x86, drop support for Python 3.7, add it for 3.10.

---

dev-python/aiohttp/aiohttp-3.8.1.recipe

Build was broken for x86_gcc2.
Provide also the "non _x86" package name. This should fix the build failure for slixmpp after #8036.

aiohttp: switch to x86, drop support for Python 3.7, add it for 3.10.

---

dev-python/aiosignal/aiosignal-1.2.0.recipe

Should help fix the build issue after #8049.

aiosignal: drop support for Python 3.7, add it for 3.10.

---

dev-python/asynctest/asynctest-0.13.0.recipe

Also, switch arch to "any".
This is 3 of 3 of the changes to hopefully fix aiohttp's build for good.
(/me crosses fingers).

asynctest: drop support for Python 3.7, add it for 3.10.

---

dev-python/charset-normalizer/charset_normalizer-2.1.1.recipe

Switch arch to "any".
Needed to fix aiohttp build (two more PRs also for that will follow).

charset_normalizer: drop support for Python 3.7, add it for 3.10.

---

dev-python/pynacl/pynacl-1.5.0.recipe

Also removed unneded dependency on six.
Only package that depended on this one is `paramiko` (see #8026), so it's safe to merge.

pynacl: drop support for Python 3.7 and 3.8.

---

dev-python/twisted/twisted-22.8.0.recipe

Restored erroneously removed (by me, sorry) PROVIDES for the "non _x86" package name.
Fixed REQUIRES.

twisted: clean up

---

dev-python/cryptography/cryptography-3.3.2.recipe

cryptography: drop support for Python 3.7 and 3.8.

---

dev-python/cryptography/cryptography-3.3.2.recipe

No need for PYTHON_LIBSUFFIXES for Python > 3.7.
Fixed cffi requirement on 32 bits.

cryptography: fix build

---

media-libs/gst_plugins_good/gst_plugins_good-1.22.0.recipe

The gdkpixbuf and GTK3 plugins can now be built.

gst_plugins_good: Enable extra plugins

---

dev-python/argh/argh-0.28.1.recipe

Only `orphilia-dropbox` depended on this one, so... Good to merge after #8084.

argh: update to 0.28.1. Drop support for Python 2.7 & 3.7. Add 3.10.

---

dev-python/cssselect/cssselect-1.1.0.recipe

This needs to be merged before the PR for `sigil`. Will add that next.

cssselect: drop Python 2.7 & 3.7, add 3.9/3.10.

---

dev-python/lxml/lxml-4.9.1.recipe

Provide "non _x86" package name for 32 bits.
No PYTHON_LIBSUFFIXES for Python 3.8+.
Should help with the build issues of `qrcode` on 32 bits.
---
~Setting as draft~, as there's still a package recipe (`sigil` #8096) that needs to be updated/merged before this one.

lxml: drop Python 3.7, add 3.10.

---

dev-python/cryptography/cryptography-3.3.2.recipe

Should help fix the build for the pyopenssl packages after https://github.com/haikuports/haikuports/commit/df145a169a3a6063c7107ff4ae0e529f2f639507.

cryptography: restore support for Python 3.8.

---

dev-python/dulwich/dulwich-0.20.32.recipe

Fixed requires for urllib3 (should fix the build on buildmasters).
Use loops for the provides, should help when modifying the list of supported Python versions.

dulwich: support 3.10, provide 'non _x86' package name on 32 bits

---

dev-python/qrcode/qrcode-7.2.recipe

Minor clean up to the provides. Should easy modifying supported python versions in the future.
----
~Opening as draft~, as it sould be able to fix qrcode build on 32 bits, once #8093 gets merged.

qrcode: support 3.10, provide non _x86 package name.

---

media-libs/x265/x265-3.5.recipe

This PR fixes build in 32 bit haiku, where asm is now disabled for hdr libraries - on 64 bit asm is enabled for all libraries.
Further, fixed the missing version number for those hdr libs.

x265: fix build on 32 bit & version string

---

dev-python/python-ly/python_ly-0.9.7.recipe

python 3.7 was dropped, python 3.9 is the new default (with an empty suffix)

python_ly: fix commandSuffixes

---

dev-python/chardet/chardet-4.0.0.recipe

- Use loops to generate the package/version specific PROVIDES.
- Version all the scripts that will end on /bin (except for the one from the default Python version, 3.9 at the moment).

chardet: clean up.

---

dev-python/markdown/markdown-3.1.1.recipe

- Use loops to generate the package/version specific PROVIDES.
- Use version suffixes for the provided cmds, except for the ones from the package for the default Python version (3.9 currently).

markdown: clean up, support Python 3.10.

---

dev-python/mutagen/mutagen-1.45.1.recipe

- Use loops to generate the package/version specific PROVIDES.
- Use version suffixes for the provided cmds, except for the ones from the package for the default Python version (3.9 currently).

mutagen: cleanup, add support for Python 3.10.

---

dev-python/pygments/pygments-2.11.2.recipe
dev-python/pygments/pygments-2.14.0.recipe

Move the PROVIDES_* inside the loop, fix script suffixes for 3.10.
Install from the wheel file instead of using the tarball for faster package buids (1.1 MB vs 4.4 MB file download).

pygments: cleanup, update to version 2.14.0

---

dev-python/pyopenssl/pyopenssl-22.0.0.recipe

Repos still contain revision 1, as the buildmasters [failed to build](https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=3993) revision 2. The issue with its build was resolved by #8090, but seems buildmasters do not auto retry when builds failed due to missing dependencies.

pyopenssl: force rebuild.

---

sys-libs/libatomic_ops/libatomic_ops-7.8.0.recipe

Add new recipe version (libatomic_ops-7.8.0.recipe).

libatomic_ops: bump to 7.8.0

---

sys-apps/ripgrep/ripgrep-13.0.0.recipe

There was an final "s" on "$dataDir/bash-completion/[...]" that wasn't supposed to be there.
---
Untested (too many dependencies, + rust, for my poor PC/connection).
I didn't rev-bump it, as the fix is small, and will be pick up on future updates. Meanwhile user can manually move the files to the proper path.

ripgrep: fix install path for bash completions.

---

dev-python/psutil/psutil-5.6.7.recipe

Package is non-functional: on both 3.7 and 3.9 it gives an error when trying to "import psutil".
The patchset is WIP, so attempting to update to psutil 5.9.4 won't do much.
Still, moving away from 3.7 makes sense.

psutil: move to Python 3.9, add TEST().

---

dev-python/jsonschema/jsonschema-3.2.0.recipe

Fixed dependencies. Now the jsonchema script actually runs.

jsonschema: drop support for Python 3.7, add it for 3.9/3.10.

---

media-libs/libmatroska/libmatroska-1.7.1.recipe

The rebuild should also fix an issue with mkvtoolnix on x86.

libmatroska: Use libVersionCompat

---

dev-python/pyrsistent/pyrsistent-0.17.3.recipe

Trying to install the 3.10 version of jsonschema was complaining about no "pyrsistent_python310".
---
Tested as far as running (with Python 3.10) a test script for `jsonrpcserver`. That module needs `jsonschema`, that needs in turn this `pyrsistent`.

pyrsistent: style clean up, add support for Python 3.10.

---

dev-python/jsonrpcserver/jsonrpcserver-4.1.2.recipe

Added the needed REQUIRES.
I was able to import the module, and run a test server now.
---
The `_python310` version of this will require #8202 merged to work (due to the jsonschema->pyrsistent, dependencies).

jsonrpcserver: drop support for Python 3.7, add it for 3.9/3.10.

---

dev-python/jsonrpcclient/jsonrpcclient-3.3.5.recipe
dev-python/jsonrpcclient/jsonrpcclient-4.0.3.recipe

For the 3.3.5 version:
Also: Fixed REQUIRES. jsonrpclient still won't run as the version of the `click` package in the repos (8.1.3) is too new for this version of `jsonrpclient` (requires click < 7.x).
Updating to 4.0.3 will require either switching to install from the wheel (.whl) file provided by the project over PyPi, or having a working Poetry package in Haiku.
Packaging Poetry and its nearly 30 dependencies is still an on-going quest, so in the meantime we might want to use that .whl after all.
---
Updated it to latest 4.0.3 version (far fewer dependencies, lighter weight), using the wheel (.whl) from PyPi.

jsonrpcclient: drop Python 3.7 support, add it for 3.9/3.10.

---

dev-python/pyopengl/pyopengl-3.1.6.recipe

Also:
- Drop support for Python 3.7
- Add it for 3.9 and 3.10.
- Style clean up.

pyopengl: update to version 3.1.6

---

net-misc/lagrange/lagrange-1.15.7.recipe

lagrange: bump to 1.15.7

---

dev-python/pycurl/pycurl-7.45.2.recipe

- Drop support for Python 2.7/3.7.
- Add it for Python 3.9/3.10.
- Move to x86 in 32 bits.
- Disable creation of "any" pycurl_doc package (for now at least). Its content wasn't that much helpful.

pycurl: update to version 7.45.2

---

dev-python/docutils/docutils-0.18.1.recipe
dev-python/docutils/docutils-0.19.recipe

- Use loops to generate the package/version specific PROVIDES.
- Use version suffixes for the provided cmds, except for the ones from the package for the default Python version (3.9 currently).
Note:
~Moved suffixes after the ".py", as names like "rst2html4310.py" looked weird, and we can't use "rst2html4-3.10.py" due to the "no dashes in PROVIDES or REQUIRES" rule.~
As names like `rst2html4310.py` look weird, use the easier to read: `rst2html4-3.10.py` naming style. See comments below.

docutils: clean up, support Python 3.10.

---

dev-python/pydispatcher/pydispatcher-2.0.7.recipe

- Drops support for Python 2.7, adds it for 3.9/3.10.
- Switched build system from "python3 setup.py" to using the  `build` and `installer` modules (was having versioning issues, otherwise).

pydispatcher: update version to 2.0.7

---

dev-python/pyqt_builder/pyqt_builder-1.7.0.recipe

- Some clean up.
- Fix dependencies.
- Provide versioned script (pyqt-bundle), and a non-suffixed link for the default Python version.
This fixes the following problems with the previous recipe version:
- Trying to do `> python3.9 -c "import pyqtbuild; help(pyqybuild)` was failing with:
> ModuleNotFoundError: No module named 'sipbuild'
- `> pyqt-bundle --help` (after installing `pyqt_builder-1.7.0-2-any.hpkg`) was failing with:
> importlib.metadata.PackageNotFoundError: No package metadata was found for PyQt-builder
Note:  I haven't performed further testing than that.

pyqt_builder: fix up recipe.

---

dev-python/cryptography-vectors/cryptography_vectors-2.8.recipe

Did some recipe clean up as well, removed TEST() as there are no tests on the tarball.

cryptography-vectors: drop Python 2.7/3.7 support, add it for 3.9/3.10

---

net-misc/lagrange/lagrange-1.15.7.recipe

This is a light-weight protocol, right? Older PCs should be able to enjoy it too :-)
Fixes #8114
(according to Lagrange's own [debian/rules](https://github.com/skyjake/lagrange/blob/7fa7024ec5be671afc3190a70734fe807d862cbd/debian/rules#L8) file, seems like the same is done in Debian)

lagrange: disable use of SSE4.1. Give older PCs a chance.

---

media-libs/glew/glew-2.2.0.recipe
media-libs/glew/glew1-1.13.0.recipe
media-libs/glew/glew21-2.1.0.recipe

GLEW_PREFIX is being used to set the path in pkgconfig file, moving the pkgconfig file to $libDir instead of $developLibDir enables fixPkgconfig to do it's work to set the correct path for the headers.

glew, fixes and use libVersionCompat

---

dev-python/pyproject_hooks/pyproject_hooks-1.0.0.recipe

This will be needed when updating the `build` package to version 0.10.0, as it changes dependencies from `pep517` to this one.

pyproject_hooks: new recipe.

---

dev-python/fonttools/fonttools-4.39.2.recipe

No functional change intended. Just aligning the recipe with what has been done on others lately.
Dropping the "REPLACES_*" as nothing in-tree was requiring either "fonttools_python3", nor any of the commands it provides, and that replaces seems to have been there for ages already.

fonttools: recipe cleanup.

---

dev-libs/libxml2/libxml2-2.9.13.recipe

It wasn't used anyway because the wrong option was passed to configure.

libxml2: remove ICU dependency

---

games-puzzle/hex_a_hop/hex_a_hop-1.1.0.recipe
games-puzzle/hex_a_hop/patches/hex_a_hop-1.1.0.patchset

*Hex-a-Hop* is a hexagonal tile-based puzzle game wherein the player must eliminate all green tiles by walking on them. Limitless undos, no time limits, just get rid of the green tiles!  Different kinds of tiles are introduced as the player progresses further for variety.
Running on `x86_64`:

hex_a_hop: Add recipe

---

sci-libs/dlib/dlib-19.21.recipe

Nothing is using this one, so safe to fix the libVersion.

dlib, build fix, fix libVersion

---

www-client/kristall/kristall-0.4.recipe

Updates Kristall to the [0.4 release](https://github.com/MasterQ32/kristall/releases/tag/V0.4) tagged back in September of 2022. Some of the most notable additions of the release since the last commit this recipe was based on are:
* [Improved caching api related to urls and implemented fragment handling](https://github.com/MasterQ32/kristall/commit/9dd660d66e23f02716d4b2bad84ac86764de71a6) (fixes [non-working HTML anchor links](https://github.com/MasterQ32/kristall/issues/237))
* [Option to exit Kristall when the last tab is closed](https://github.com/MasterQ32/kristall/commit/6b39f24484bb0796f3f383401f95904f85b74d7b) (requested in [this issue](https://github.com/MasterQ32/kristall/issues/245))
This PR is also intended to switch the package to tracking tagged releases, instead of Git …

kristall: Move to 0.4 release

---

dev-lang/nim/nim-1.6.12.recipe
dev-lang/nim/patches/nim-1.6.12.patchset

this updates the nim to the latest release
* patched to fix a compilation failure that has cropped up in more recent nim releases
```
~> nim --version
Nim Compiler Version 1.6.12 [Haiku: amd64]
Compiled at 2023-04-20
Copyright (c) 2006-2023 by Andreas Rumpf
git hash: c924167414fa6071fdc1ff8dd807b02fb36e3a75
active boot switches: -d:release
```

nim: bump version

---

net-analyzer/wireshark/patches/wireshark-4.0.5.patchset
net-analyzer/wireshark/wireshark-4.0.5.recipe

folder structure wasn't entirely right either with absolute or relative cmakeDirArgs so I changed the recipe to use hand-crafted args
there was also one more potential crash on exit so I added some code to deregister the log writer on exit.

wireshark: update to 4.0.5

---

app-i18n/becjk/becjk-1.0.1.recipe

SCons will pull the version it needs (3.9 currently).

BeCJK: cleanup requirements, dropping Python 2.x.

---

net-dns/bind_utils/bind_utils-9.16.36.recipe

On 32bit (couldn't find libuv for wrong pkg-config command and wrong install dir for the binaries.

bind_utils, build fix

---

app-text/lout/lout-3.42.1.recipe

* Moved data to $dataDir/lout (no version).
* Added docs in easier to use PDF format.
* Improved description a bit (mentioning docs, and Pe support).

lout: fixups, include PDF docs.

---

media-gfx/sane_backends/sane_backends-1.2.1.recipe

Also enabled parallel build via $jobArgs.
Fixes #8489.
(similar issue in the past was fixed for Links on #7764)

sane_backends: switch to Python 3.9, fix x86_32 build.

---

dev-libs/botan/botan-2.19.2.recipe
dev-libs/botan/patches/botan-2.19.2.patchset

This fixes bad paths in the botan-2.pc file

botan: use $prefix during configure

---

sys-devel/gcc/gcc-11.2.0_2021_07_28.recipe
sys-devel/gcc/patches/gcc-11.2.0_2021_07_28.patchset

Synchronized GCC recipe with changes from https://review.haiku-os.org/c/buildtools/+/6384.

gcc/config: Drop cdecl and stdcall built-in defines

---

dev-lang/ruby/additional-files/gemrc
dev-lang/ruby/ruby-2.7.4.recipe

This is how some Linux distros like Arch handle `gem install`.

ruby: use global gemrc to make --user-install the default

---

dev-libs/icu/icu70-70.1.recipe

This is needed for texlive_core 2023 (#8113).
Also add a conflict for the devel package with icu66_devel. Others, like icu67 should be added as well, when they are made available.

icu70: enable for x86_64 and x86

---

dev-lang/python/python3.10-3.10.11.recipe

This is basically #3834 (removing hard-coded version numbers), but for Python 3.10.
Only two "310" references remain, but those will go away for newer Pythons.
~Not changing the revision, as this is~ just a cleanup, no functional change intended.
(only doing it for the newest recipe, as the older ones will just be faced out eventually).

python3.10: cleanups, no functional changes.

---

haiku-apps/armyknife/armyknife-5.1.2.recipe

With neon not available for primary arch on 32bit, musicbrainz needed a change.

armyknife, switch so gcc11

---

dev-python/pyqt_builder/pyqt_builder-1.7.0.recipe

We don't have a sip_python38 anymore, and all users of this recipe are using the 3.9 version already.

pyqt_builder: drop support for Python 3.8.

---

app-text/texlive/texlive-2023.recipe

This would bind the texlive packages to a fixed version (and revision!) of texlive_core. Also, they couldn't be shared between x86 and other architectures, because the packages are named `texlive_core_x86` on x86 because of secondaryArch.
Revbump for rebuild (texlive was built against texlive_core 2022 before and is therefore broken right now.)

texlive: fix references to texlive_core package links directory

---

sci-libs/armadillo/armadillo-12.2.0.recipe
sci-libs/armadillo/armadillo10-10.8.2.recipe

This moves the older armadillo into the armadillo10 package so libraries are kept around for depending packages.

armadillo, bump version

---

dev-util/rizin/rizin-0.3.4.recipe

Added a temp workaround to fix the build. Shouldn't be necessary anymore once we update rizin to a newer release.

rizin: switch to Python 3.9

---

app-emulation/spice/spice-0.15.1.recipe

ProTip™ (or note to myself): make sure to uninstall tk${secondaryArchSuffix}_devel before building this one. Sigh...

spice: switch to Python 3.9

---

games-action/btanks/btanks-0.9.8083.recipe
games-action/btanks/patches/btanks-0.9.8083.patchset

Ensure we're pulling lua 5.3 (wasn't the case for some reason on my machine).

btanks: fix build issues related to lua.

---

dev-util/rizin/rizin-0.3.4.recipe

Nothing of this is needed for newer versions, but seems like our Cutter port fails to link with newer ones for some reason.´
---
Builds OK on 32 bits (even after `hp -c rizin_x86`)

rizin: ugly hack to make it build.

---

dev-libs/gtest/gtest-1.11.0.recipe

Passes all tests on 32 bits x86.

gtest: use default cmd:python3 (3.9 at the moment) to build.

---

app-misc/ranger/ranger-1.9.3.recipe

Only build it for the default Python version (3.9 at the moment), as this is just intended to be used as a command line utility.

ranger. update to version 1.9.3

---

dev-util/cram/cram-0.7.recipe

- Dropped Python2 version.
- No need to version-suffix `cmd:cram`.
Notice: upstream repo has been archived in 2022, and while the repo mentions an 0.8 release, the link for that is broken, and no 0.8 tag exists on its git repo.
Considering only one package in HaikuPorts needs `cmd:cram` (the silver searcher, and only for its `TEST()`)... impact of these changes is pretty minimal.
(Will fix "the silver searcher"'s  recipe next).

cram: switch to Python 3.9.

---

sys-apps/the_silver_searcher/the_silver_searcher-2.2.0.recipe

All tests pass using newely built `cmd:cram` (Python 3.9).

the_silver_searcher: fix build, simplify TEST_REQUIRES

---

net-libs/grpc/grpc-1.53.0.recipe

* Added a missing PROVIDES, and a couple to PROVIDES_devel (both match now).
* Fixed libVersion/libCppVersion/libVersionCppCompat variables.
~* Use -DgRPC_BUILD_TESTS=OFF, as it makes the build require far less time/storage.~

grpc: switch to Python 3.9, drop Python 2.x, fix provides/versions.

---

dev-lisp/sbcl/patches/sbcl-2.2.4.patchset
dev-lisp/sbcl/sbcl-2.2.4.recipe

I was going to wait until I had accumulated a larger patchset to contribute, but this has just been sitting on my hard drive for a few months untouched. This contains a fix for UIOP inadvertedly removing `:HAIKU` from `*FEATURES*`, a fix for SBCL hanging on stack overflow due to the lack of an alternate stack for signal handling and a change for the test suite not to assume `env` is located under `/usr/bin`. I've also disabled 2 tests which hung while repeatedly segfaulting, but have yet to investigate the issue.
As a result, the test suite now runs to completion, with 21 failures, 10 expected failures and 2 skipped (as mentioned above):
<details>
<summary>Test results</summary>
```
Finished running tests.
Status:
Expected failure:   compiler-2.pure.lisp / (MAP-ALLOCATED-OBJECTS …
```

sbcl: miscellaneous fixes, test routine

---

dev-lisp/ecl/ecl-21.2.1.recipe
dev-lisp/ecl/patches/ecl-21.2.1.patchset

I've also reenabled parallel builds, as it seems to have been fixed in the meantime. Note I've kept TEST as-is, but I don't know how it's supposed to work, as ecl's `make check` expects ecl to already be installed in the system, which doesn't seem to be the case by the time haikuporter calls TEST.

ecl: fix build, update to 21.2.1, drop old versions

---

games-fps/chocolate-doom/chocolate_doom-3.0.1.recipe

* Drop usage of Python 2.x.
* Drop python_imaging dependency.
* Drop _x86 suffixes.
* Include basic docs.
* Create _debuginfo package.
Python dependency is optional, needed for generating man pages, for example.
Those weren't included before, and to switch to Python 3, we need to update to newer versions of chocolate_doom (no new release > 3.0.1 yet), so just drop that requirement.
"python_imaging" can be replaced by "pillow" (which supports python3), but it is really only needed to re-create font files, or convert icons.
Neither is strictly needed when building under Haiku.
Instead if providing a _debuginfo package, we might want to just strip the binaries ("make install-exec-strip").

chocolate_doom: recipe cleanups.

---

dev-python/psutil/psutil-5.6.7.recipe
dev-python/pycurl/pycurl-7.45.2.recipe

The psutil recipe remains disabled (so no rev-bump there).

psutil, pycurl: provide "non _x86" package name.

---

dev-python/dukpy/dukpy-0.3.recipe

* Enable recipe for 32 bits.
* Provide "non _x86" package name.
* Remove unneeded \n escaping.

dukpy: recipe clean ups.

---

dev-python/argon2-cffi-bindings/argon2_cffi_bindings-21.2.0.recipe

* Build with build/installer.
* Provide "non _x86" package name.
* Remove unneded \n scaping.

argon2_cffi_bindings: recipe cleanups.

---

dev-python/pyopenssl/pyopenssl-22.0.0.recipe

I guess this could use REPLACES, at least for 32 bits, but I didn't find anything in-tree actually requiring `pyopenssl`, so I think we can do without it.

pyopenssl: switch to "any" arch, add Python 3.10

---

dev-python/pymupdf/pymupdf-1.20.2.recipe

Also: switch SOURCE_URI to github. The tarball there is 7.28 MB, versus the previous 86.25 MB (due to the inclusion of mupdf.tar.gz, which we don't need here, and weights 84.36 MB).

pymupdf: cleanups, provide "non _x86" package name.

---

dev-python/twisted/twisted-22.8.0.recipe

* Remove some clutter.
* Provide non-suffixed "cmd:"s for default Python version.
* Drop unnecessary gcc BUILD_PREQUIRES, and switch recipe to "any".
* Add missing typing_extensions dependency.
All "cmd:" now work at least with "--version" parameter, except for `tkconch`, that deadlocks (known issue for Python + Tk: #6967).

twisted: swith to "any" arch, recipe clean ups.

---

dev-python/nose/nose-1.3.7.recipe
dev-python/nose/patches/debian/2to3-fixups.diff
dev-python/nose/patches/debian/coverage4.1.diff
dev-python/nose/patches/debian/disable-unstable-tests.diff
dev-python/nose/patches/debian/docs-sys.path.diff
dev-python/nose/patches/debian/no-distribute_setup.diff
dev-python/nose/patches/debian/no-google-analytics.diff
dev-python/nose/patches/debian/no-versioned-entry-point.diff
dev-python/nose/patches/debian/python3-conf-py.diff
dev-python/nose/patches/debian/python3.11-testcase-str.diff
dev-python/nose/patches/debian/python3.11.diff
dev-python/nose/patches/debian/python3.6-modulenotfounderror.diff
dev-python/nose/patches/debian/sphinx-body-max-width.diff
dev-python/nose/patches/debian/sphinx-class-directives.diff
dev-python/nose/patches/debian/sphinx-html_sidebars.diff

Due to changes in setuptools, we need to run 2to3 ourselves. While we're at it, lets apply relevant patches from Debian.
https://salsa.debian.org/python-team/packages/nose/

nose: clean up, support Python 3.10.

---

games-arcade/plee_the_bear/plee_the_bear-0.7.0.recipe

Solves:
```
plee_the_bear_x86-0.7.0-7-x86_gcc2.hpkg:
requires "lib:libboost_filesystem_x86 >= 1.57.0" of package "plee_the_bear_x86-0.7.0-7" could not be resolved
```
Crashes on launch though (not sure how it did before because I never tested it).

plee_the_bear, use boost169

---

games-fps/lab3d/additional-files/lab3d-3.0.1.rdef.in
games-fps/lab3d/lab3d-3.0.1.recipe
games-fps/lab3d/patches/lab3d-3.0.1.patchset

Add Ken's Labyrinth by Ken Silverman to Haiku, via the [LAB3D-SDL port](http://icculus.org/LAB3D/) originally created by Jan Lönnberg.
Changes:
- Add wrappers for open(), fopen() and SDL_LoadBMP() to respect Haiku user/data/etc directories.
- Pull game data from [Ken Silverman's website](http://advsys.net/ken/klab.htm) (v2.1 registered).
Issues:
- OpenGL renderer crashes for unknown reasons. The SDL fallback software renderer works, though.
- If you generate a config, there's no way to regenerate it without going to the terminal and running it with the `-setup` switch.
- No application icon.

Add Ken's Labyrinth (LAB3D-SDL)

---

dev-rust/cargo_c/cargo_c-0.9.8.recipe

Rebuilt for openssl 1.1.1t on x86.

cargo_c: revbumped, updated cargo_c-0.9.8.recipe

---

games-engines/openscenegraph/openscenegraph-3.6.5.recipe

No revbump, recipe is marked broken on all architectures.

openscenegraph, fix references for lib:libsdl

---

dev-lang/ruby/patches/ruby-3.2.2.patchset
dev-lang/ruby/ruby-3.2.2.recipe

The port appears to be working as well as the ruby-2.7 version but I haven't tried to run the test suite.  I'm not sure if we want to go the same path as the python recipes and call this one `ruby32-3.2.2.recipe` since there are very few things using ruby and most of them will probably support 3.x.  The [Arch package information](https://archlinux.org/packages/extra/x86_64/ruby2.7/) only shows a couple of things depending on 2.x

ruby: add 3.2.2 (disabled)

---

sci-astronomy/celestia/celestia-1.6.3.recipe

updates the copyright and homepage, since celestia.space went offline and was taken by cybersquatters, so it had to move to celestiaproject.space. not sure about the `REVISION` field though, @Begasus changed it from `2` back to `1` in #9005, so for now I'm just leaving it at `1`. is it because the `REVISION` gets reset back to `1` each time an application is updated to its' newest release or something like that?
also, is there any way that the screenshots shown on the Haiku Depot page could be updated? they look over a decade old lol

celestia, update recipe

---

dev-rust/cargo_c/cargo_c-0.9.8.recipe

Only needed for 64bit, 32bit already fine (no revbump).

cargo-c, try to fix build for 64bit

---

dev-libs/libebml/libebml-1.4.4.recipe
dev-libs/libebml/patches/libebml-1.4.4.patchset

Pulled from upstream development version with the necessary changes to work with the stable release.

libebml: Patch to use standard integer types

---

dev-libs/libunibreak/libunibreak-5.1.recipe
dev-libs/libunibreak/libunibreak4.0-4.0.recipe

Tuxpain-config and FBReader are still using the older library, FBReader download link is broken so can't be rebuild, hence keeping the older recipe around (renamed).

libunibreak, bump version, keep old around

---

app-admin/keepassxc/keepassxc-2.6.2.recipe

Needs https://github.com/haikuports/haikuports/pull/9103 to be merged first.

keepassxc, revbump for qrencode

---

sys-devel/gcc/gcc-13.1.0_2023_06_20.recipe

I spread the changes out over two commits so that they can be reviewed independently.
Initially this PR as following the GCC JIT packaging instructions to build GCC twice, once for JIT, and once for the rest of the languages. This was based on the assumption that the second build would be without position independent code. However, on Haiku all executables are PIE, so there is no advantage in building twice.
Previous note.
~~Note that the recipe for building GCC became more complex than it was, due to the packaging instructions. I do want to note that FreeBSD chose not to build GCC twice, and instead also builds the main compiler with `--enable-host-shared`. ~~

GCC 13: add gcc_jit and other fixes

---

sys-devel/gcc/gcc-13.1.0_2023_06_20.recipe

It is now time to enable the recipe, everything is set to continue the build and merge process.

GCC 13: enable recipe

---

app-arch/zstd/patches/zstd-1.5.5-gcc2.patchset
app-arch/zstd/patches/zstd-1.5.5.patchset
app-arch/zstd/zstd-1.5.5.recipe

Maybe remove older recipes here too (only keep 1.5.2 for x86_gcc2)?
x86_gcc2 build fails with at least parse errors, didn't investigate further.

zstd, bump version, drop x86_gcc2

---

app-arch/tar/tar-1.35.recipe

Shouldn't be needed for 64bit, but I guess it will be fixed by 2038? :)

tar, revbump for 32bit, use --disable-year2038

---

www-client/retawq/patches/retawq-0.2.6c.patchset
www-client/retawq/retawq-0.2.6c.recipe

the following recipe adds support for [retawq](https://retawq.sourceforge.net/)
```
> uname -a
Haiku shredder 1 hrev57104 Jun 22 2023 06:25:10 x86_64 x86_64 Haiku
> retawq --version
retawq 0.2.6c - Copyright (C) 2001-2006 Arne Thomassen <arne@arne-thomassen.de>
retawq is basically released under certain versions of the
GNU General Public License and WITHOUT ANY WARRANTY.
The project home page is <http://retawq.sourceforge.net/>.
```

retawq: new recipe

---

dev-lang/perl/perl-5.32.1.recipe

this is needed for building the 'rigged' source packages during bootstrap

perl: enable recipe for arm

---

dev-lang/python/python3.10-3.10.12.recipe
dev-lang/python/python3.9-3.9.17.recipe

Python 3.9 is a bit broken (no readline/editline), so let's move on to 3.10 which works better.

Python: make Python 3.10 the main one.

---

media-sound/ocp/ocp-0.2.106.recipe

Version 0.2.106 adds support for libgme (game-music-emu)

ocp: bump version

---

dev-python/pybind11/pybind11-2.11.1.recipe

Also, provide a non-versioned pybind11-config symlink to the 3.10 version (matching our current default Python version).
This should (might?) help with packages as `contourpy` that expect to find a non-versioned "pybind11-config".

pybind11: update to version 2.11.1

---

dev-python/contourpy/contourpy-1.1.0.recipe

Listed as a dependency for matplotlib.
Only providing a Python 3.10 for now, as this is a new recipe, and its only inmediate target user would be matplotlib (that should also be moved to 3.10).
In any case, I've tested the recipe works for multiple versions, by locally building it for both 3.9 and 3.10.
Note: built (and very lightly tested) on 64 bits only.
(Also: depends on the updated pybind11 from #9220)

contourpy: new recipe.

---

app-office/libreoffice/libreoffice-6.4.7.2.recipe

Untested, but we don't have Python 2.7 anymore, a similar change was made for LibreOffice 7.3.7 (64 bits), and both recipes have `--enable-python=no`, so let's see if this can be rebuild, or we're stuck with the current revision.

libreoffice 6.4.7: (32 bits only), remove Python build dependencies.

---

dev-lang/perl/perl-5.32.1.recipe
media-sound/lilypond/lilypond-2.24.2.recipe
sys-apps/texinfo/texinfo-7.0.3.recipe

LilyPond requires a newer texinfo than the 6.1 that is available for x86_gcc2. Provide a secondary architecture version of texinfo 7 to fix that.
Perl (secondary) is required for texinfo.
@Begasus @pulkomandy This needs a thorough review please. I am not sure if this is a good solution.

perl, texinfo-7: provide a secondaryArch package

---

games-rpg/runescape_launcher/runescape_launcher-0.9.0.recipe

I wrote a simple launcher script for old school runescape, based on [https://gitlab.com/coringao/runescape/](https://gitlab.com/coringao/runescape/). It also has a check in it to kill the game when it's closed, as it otherwise will hang when it's quit (maybe something to do with the audio?). I hope I did everything correctly with the licensing.
Currently the game does not load when run outside of the terminal. On x86_64 it gets stuck on loading and x86_32 it cannot find the java executable. For what I could tell, the problem seems to have to do with differing environment variables when run from the terminal compared to otherwise. On x86_32 $JRE11_HOME is missing when run normally compared to the terminal. jre 11 is required as the game won't start with newer ones. I'll have a look at …

runescape_launcher: add recipe

---

media-fonts/opendyslexic/opendyslexic-0.91.12.recipe

I decided to use the newer
https://github.com/antijingoist/opendyslexic
repository instead of
https://github.com/antijingoist/open-dyslexic
even though the gpo recipe uses the older repository,
as the newer one is linked to by the old repository and has a different license

opendyslexic: new recipe

---

dev-lang/python/patches/python3.11-3.11.5.patchset
dev-lang/python/patches/python3.11_x86-3.11.5.patchset
dev-lang/python/python3.11-3.11.5.recipe

Mayor selling point of this version: it brings several speed-related improvements over 3.10.
I'm adding it here just to make it available, gather some feedback, but with the hopes it is used only for testing purpose, and not to start adding support for it to our Python packages' recipes ("_python311" versions of packages).
Python 3.12.0 will be released on October. The 3.12.0 betas, so far, run fine on Haiku, so we might want to "skip" 3.11, and add 3.12 instead (while/after dropping 3.8), specially considering that 3.12 brings up more "breaking" changes (deprecated modules, changes in packaging, etc.) than previous versions.
Run `hp --test python3.11`, results are in-line with what we normally get on Haiku:
363 tests OK. 29 tests failed. 21 tests skipped. (and a bunch of test disable to …

python3.11: new recipe for Python 3.11

---

net-analyzer/speedtest-cli/patches/0001-Python-3.10-support.patch
net-analyzer/speedtest-cli/speedtest_cli-2.1.3.recipe

No need to have this for multiple versions of Python, as this is just a cli program/tool.
This is still technically version 2.1.3 (no new release yet), but with a patch that adds a commit from upstream, which adds Python 3.10 support.

speedtest-cli: switch to Python 3.10, recipe clean ups.

---

sys-devel/llvm/llvm16-16.0.6.recipe
sys-devel/llvm/patches/llvm16-16.0.6.patchset

This is my attempt at llvm toolchain... trying to build on the current llvm12 recipe as well as the earlier attempts from @extrowerk  in #6741 and @jessicah in #7871
Successful build and packaging on x86_64, i tested the resulting llvm-clang toolchain by building libpcap and tcpdump, so far it looks promising.
Successful build and packaging on x86_gcc2 secondary arch. The resulting toolchain is able to build libpcap or tcpdump.
The additional patches from https://github.com/X547/llvm-project/tree/llvm-haiku are included and one more patch to reuse `GCCInstallationDetector`

llvm16: new recipe

---

dev-python/setuptools_scm/setuptools_scm-7.1.0.recipe

Should fix buildmaster issues for:
- importlib_metadata
- importlib_resourses
- iniconfig
- pyparsing
- zipp

setuptools_scm: fix requirements.

---

dev-python/importlib_metadata/importlib_metadata-6.8.0.recipe

The presence of HaikuPorter's work git repo interferes with the operation of some python packages used at build time, causing builds with "hp -G" to succeed, but fail without that flag, unless these work-arounds are applied:
- exporting a `SETUPTOOLS_SCM_PRETEND_VERSION` variable
- `rm -rf dist`

importlib_metadata: hopefully fix the build for good this time.

---

dev-python/importlib_resources/importlib_resources-5.4.0.recipe
dev-python/iniconfig/iniconfig-1.1.1.recipe
dev-python/pyparsing/pyparsing-3.0.7.recipe
dev-python/watchdog/watchdog-0.9.0.recipe
dev-python/zipp/zipp-3.7.0.recipe

Just revision bumps to trigger builds at buildmasters, and some minor recipe cleanups.
No functional changes intended or expected.
This should leave only 4 recipes that need fixes after #9328 (and fixes in #9338).

Follow up to PR 9328.

---

net-vpn/openvpn/openvpn-2.6.4.recipe
net-vpn/openvpn/patches/openvpn-2.6.4.patchset

Reflects change made [here](https://review.haiku-os.org/c/haiku/+/6608/31/src/add-ons/kernel/drivers/network/tun/driver.cpp#24) to the driver

OpenVPN Add Path to Where Driver gets Published

---

sys-devel/llvm/llvm16-16.0.6.recipe

Trying tackle issues #9324 and #9333
* adjust path for `libunwind` so that we always look for it in `$prefix/lib` (also in case of x86 secondary architecture)
* expand the list of `libclang...` when invoking `prepareInstalledDevelLibs` so that the libs land in the correct folders
* move `libclang` and `libclang-cpp` to the `llvm16-clang` package
* adjust provides and requires accordingly

llvm16: fix build on 32-bit; fix deps for clang package

---

dev-python/tqdm/tqdm-4.66.1.recipe

- Switched build to use build/installer.
- Switched default version to Python 3.10.
- Only install man page / bash completions for the default Python version.
- Changed SOURCE_URI to avoid:
> LookupError: setuptools-scm was unable to detect version
for /sources/tqdm-4.66.1.
(that error message suggested using PyPI's tarballs instead of Github ones)

tqdm: update to version 4.66.1

---

dev-python/sgmllib3k/licenses/Python
dev-python/sgmllib3k/sgmllib3k-1.0.0.recipe

Needed only for `feedparser` >= 6.0 (and thus also by newer `calibre` versions).
License on PyPI appears as `BSD`, but the original code was from the Python standard library (just converted via the 2to3 tool), thus why I think `LICENSE="Python"` is correct here.
As soon as `feedparser` drops this dependency, we should get rid of this one.

sgmllib3k: new recipe.

---

sys-devel/llvm/llvm16-16.0.6.recipe

Following up on the suggestions from @augiedoggie 
* move scan-build-py scripts to clang_analysis package
* move other clang scripts to clang package
* remove empty folders from llvm16 base package
successful build on 32-bit&64-bit

llvm16: clean up recipe

---

sys-devel/llvm/llvm16-16.0.6.recipe
sys-devel/llvm/patches/llvm16-16.0.6.patchset

this should help with #9407
successful build on 32-bit & 64-bit

llvm16: fix C++ include paths

---

dev-python/py_pathtools/py_pathtools-0.1.2.recipe
dev-python/watchdog/watchdog-0.9.0.recipe

This seems somehow deprecated (latest commit 2016), whatchdog depends on this, but has seen newer versions upstream, could be newer ones don't depend on this anymore, if not on a version bump there this could be removed from the repository.

python pathtools, rename recipe (conflicts)

---

dev-python/watchdog/watchdog-3.0.0.recipe

Drops requirements for `argh` and `py_pathtools` (we might just want to get rid of the latter).

watchdog: update to version 3.0.0

---

dev-python/dbuspython/dbuspython-1.3.2.recipe

Only user of this package, Calibre, dropped this dependency in favor of the "pure-Python" `jeepney` package on newer versions.
For now, this will do.

dbuspython: update to version 1.3.2, support Python 3.10.

---

dev-python/dnspython/dnspython-1.16.0.recipe

Not updating this one for now, as the one needed by the only package on-tree that uses it (`calibre`) requires not the latest version but version 2.1.0, and to build that version and up, we need to have the `poetry` build system available first.

dnspython: cleanup, support Python 3.10.

---

dev-python/whichcraft/whichcraft-0.6.1.recipe

Nothing uses this on-tree. Seems this is (or was) needed by webkit's unit tests, but `haikuwebkit` already has moved to Python 3.10.

whichcraft: cleanup, support only Python 3.10 for now.

---

dev-python/pythonzeroconf/pythonzeroconf-0.29.0.recipe

Just the necessary bits to get it to work with Python 3.10.
Not updating to the latest version, for now at least, as that requires building it with `poetry` (which we currently do not have).

pythonzeroconf: cleanup, support Python 3.10.

---

dev-python/pretend/pretend-1.0.9.recipe

Doesn't seems to be used on-tree but, it's up-to-date, works, and looks useful for writing tests.

pretend: cleanup, support Python 3.10.

---

dev-python/svgwrite/svgwrite-1.4.3.recipe

Not used anywhere on-tree, and project is marked as inactive/unmaintained on GitHub. We might just want to drop this one next time.
(`pip3.xx install svgwrite` will still work for those that might need it)

svgwrite: update to version 1.4.3, support Python 3.10.

---

dev-python/pypeg2/pypeg2-2.15.2.recipe

Nothing uses this old package (no new releases since 2015) on-tree. We might want to just drop this one next time (users will be able to use it via `pip install` if they miss it).

pypeg2: cleanups, support Python 3.10.

---

dev-python/editorconfig-core-py/editorconfig_core_py-0.12.3.recipe

Removed TESTS(), as the packages contains no tests at all, less so making use of cmake/ctest.

editorconfig_core_py: clean ups, support Python 3.10.

---

dev-python/rdflib/rdflib-5.0.0.recipe

Instead of dropping it, just move it to Python 3.10.
Original PR description follows:
---
Nothing uses it on-tree. Still available via `pip install`.

rdflib: switch recipe to Python 3.10.

---

dev-python/pip/pip-23.2.1.recipe

This silly typo prevented the inclusion of `/bin/{pip,pip3}` along with `/bin/pip-3.10` (for the default Python version, it is always nice to provide non-version-suffixed commands).

pip: fix typo.

---

dev-python/psutil/psutil-5.6.7.recipe

Still disabled, as it fails on import (same as before).
---
This one is required by the (also disabled) `sys-process/glances` recipe. Will move that to Python 3.10 next.

psutil: switch to Python 3.10.

---

dev-util/mdds/mdds2.1-2.1.1.recipe

Required for newer ixion and orcus. Doesn't conflict with mdds2-2.0.1.

mdds2.1, add new version

---

dev-libs/ixion/ixion0.18-0.18.1.recipe

0.18.1 new version, add conflicts for tools package Both versions can be co-installed aside from the binaries

xion, 0.17.0, move binaries to tools package

---

sys-devel/llvm/llvm17-17.0.1.recipe
sys-devel/llvm/patches/llvm17-17.0.1.patchset

the patchset from llvm16-16.0.6-4 can be applied with minor changes
successful build on 32-bit & 64-bit
new llvm17 toolchain seems to behave well, I can compile C and C++, include folders also looking OK

llvm17: new recipe

---

app-shells/command_not_found/command_not_found-0.0.1~git.recipe
app-shells/command_not_found/patches/command_not_found-0.0.1~git.patchset

Dropped usage of the `mock` backported module, and fixed some quotation issues.

command_not_found: switch to Python3.

---

sys-devel/gcc/gcc-13.2.0_2023_08_10.recipe
sys-devel/gcc/patches/gcc-13.2.0_2023_08_10.patchset

This fixes libfortan.so.
Closes #9241

GCC: disable the use of dl_iterate_phdr in libbacktrace

---

net-irc/weechat/weechat-4.0.4.recipe

Lightly tested on beta4 64 bits (was able to connect and chat over the OFTC's `#haiku` channel).

weechat: update to version 4.0.4, move to Python 3.10.

---

sci-libs/proj/proj-9.3.0.recipe

this updates proj to a more recent release (9.3.0)
```
> proj
Rel. 9.3.0, September 1st, 2023
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

proj: bump version

---

sys-apps/ed/ed-1.19.recipe

Switch SOURCE_URI to upstream. HaikuPorter can handle .tar.lz files transparently thanks to Python's tarfile module.
Fix #9548.

ed: update to version 1.19

---

dev-libs/capstone/capstone5-5.0.1.recipe

Include paths are already correct on x86_64 and x86 without it. Fixes #9591

capstone: remove sed editing of .pc file

---

dev-lang/python/patches/python3.12-3.12.0.patchset
dev-lang/python/python3.12-3.12.0.recipe

Tested on beta4, both 32 and 64 bits, including `hp --test`. Seems to work more or less the same as previous versions (most errors/problems/fails in tests still related to `fork` and `locale/datetime` issues).
Besides the standard massaging of the patchset to make it apply over the new code... I've re-worked a bit some of the commits on the .patchset file, trying to separate changes "by topic", combining changes where necessary, etc.
In part for easier maintenance, and hoping to make them easier to upstream (if someone is willing to do that).
Mayor pain point in this version are `PyOS_AfterFork_Child` errors (related to fork), so much so that only by switching to `spawn` I was able to get the build to complete at all (see commit "Use spawn instead of fork for multiprocessing." on the …

python3.12: add recipe for Python version 3.12.0.

---

dev-python/setuptools/patches/setuptools-68.2.2.patchset
dev-python/setuptools/setuptools-68.2.2.recipe

removed the `export SETUPTOOLS_USE_DISTUTILS=local`, as that's the default behavior (again) since 60.0.0.

setuptools: update to version 68.2.2, add support for Python 3.12.

---

dev-python/pip/pip-23.2.1.recipe

This needs #9613 to be merged first (for the `setuptools_python312` dependency).

pip: add support for Python 3.12.

---

net-misc/lagrange/lagrange-1.17.0.recipe

lagrange: bump to 1.17.0

---

sys-devel/haiku-format/haiku_format-17.0.1.recipe

Add -DCMAKE_SKIP_RPATH=On to the flags in order to prevent bogus rpath entries in the executable. Fixes #6817

haiku-format: fix 32 bit rpath errors

---

sys-devel/llvm/llvm17-17.0.1.recipe
sys-devel/llvm/patches/llvm17-17.0.1.patchset

This is already part of the upstream patch but somehow went missing in the downstream patch for llvm17. This results in quirky .init/.fini sections (i.e. stack frame setup is not entirely correct)
This change adds crti.o so that we can have proper stack frame setup in the .init/.fini sections.

llvm17: link binaries against crti.o

---

games-fps/quakespasm/quakespasm-0.96.1.recipe

QuakeSpasm updated, so I'm bumping the version here. I've also bumped the revision number to 3, since I forgot to do it on the last update.
QuakeSpasm changelog:
- Fix demo recording as client-only after connection to server (was
broken by signon changes in 0.96.0. Thanks to Jozsef Szalontai for
issue report.)
- Fix potential buffer overflow in COM_Parse(), e.g. with maps with
oversized 'wad' fields. (Thanks to Andrei Drexler.)
- Minor code cleanups.

QuakeSpasm: bump to 0.96.1 and fix revision number

---

app-misc/deark/deark-1.6.5.recipe

Compiled with no patches. Did some tests with some old Psion files and it works fine.
I have only one concern. The developer describes the license as "MIT-style," and then mentions that some files might be under other licenses.
> Starting with version 1.4.x, Deark is distributed under an MIT-style license. See the [COPYING](https://github.com/jsummers/deark/blob/master/COPYING) file for the license text.
>
> The main Deark license does not necessarily apply to the code in the "foreign" subdirectory. Each file there may have its own licensing terms.
I've set `"MIT"` as the `LICENSE` in the recipe as that was the closest option. I've also seen a Gentoo overlay that has also used `"MIT"`. Please let me know if there is a more appropriate option.

deark: new recipe

---

sys-devel/llvm/llvm16-16.0.6.recipe
sys-devel/llvm/patches/llvm16-16.0.6.patchset

I guess this is still good to have, in case we'd like to do llvm16 vs llvm17 comparison for any reason.

llvm16: link binaries against crti.o

---

sys-libs/timezone_data/patches/timezone_data-2023c.patchset
sys-libs/timezone_data/timezone_data-2023c.recipe

Set make flags also on BUILD(), otherwise tzselect ended up with the wrong location for TZDIR.
Previous version failed with:
`/bin/tzselect: time zone files are not set up correctly`
Now it finds the files ok, but trying to use it further causes /bin/date to crash around 7 times in a row (?!).
`> zdump -v America/Buenos_Aires` also works now, while previously failed with:
`America/Buenos_Aires: No such file or directory`,
or with:
```
> ln -s /boot/system/data/zoneinfo/America/Buenos_Aires /etc/localtime
> zdump -v /etc/localtime
/etc/localtime: No error
```
Now the latter also works OK.

timezone_data: update to version 2023c

---

sys-libs/timezone_data/timezone_data-2023c.recipe

This workaround works for now. In the future we should probably move this recipe to "_x86".
See details on #9519.

timezone_data: fix 32 bits build.

---

app-admin/chrpath/chrpath-0.16.recipe
app-admin/chrpath/patches/chrpath-0.16.patchset

Tested (*very* lightly) only on beta4 64 bits (now also lightly tested on 32 bits).
----
I assume we're supposed to use stuff as `CMAKE_SKIP_RPATH` instead if that's available, or disable `rpath` via some `sed` patching if the build system doesn't provides an easier mechanism.
I just had a "complex to build" project (still no proper .recipe for it), and I'll probably need either this `chrpath` thing, or some serious `sed` scripts :-D.
~Leaving it as Draft for now,~ as I'm not sure my .patchset is correct, or if this `chrpath` is something we actually want/need.
----
Drop Draft status:
If we have `cmd:patchelf`, I guess having this one also available can't hurt that much :-)

chrpath: new recipe

---

sys-devel/llvm/llvm17-17.0.1.recipe
sys-devel/llvm/patches/llvm17-17.0.1.patchset

This PR changes the --no-undefined-version flag in the LLD linker to be set to report a warning instead of an error and to not require the version script assignment when lld is used for linking. It is also a patch to revert this change introduced in LLVM 16: https://reviews.llvm.org/D135402 and was set to a warning in a patch release of LLVM 16 in this PR: https://github.com/llvm/llvm-project-release-prs/pull/347/files 
This change is also useful for the purpose of LLD being able to compile itself under the host OS and in situations where Clang (not gcc/g++) is required. Otherwise you will get this error:
```
[3153/4369][ 72%][11549.390s] Linking CXX shared library lib/libIndexStore.so.13git
FAILED: lib/libIndexStore.so.13git 
: && /bin/clang++ -fPIC -Wno-unknown-warning-option …
```

llvm17: turn --no-undefined-version into a warning for lld and clang

---

app-emulation/qemu/patches/qemu-8.0.5-haiku.patchset
app-emulation/qemu/patches/qemu-8.0.5.patchset
app-emulation/qemu/qemu-8.0.5.recipe

Almost straightforward update, no regressions.
The already known issues are still there.

qemu: update to 8.0.5

---

net-misc/lagrange/lagrange-1.17.3.recipe

lagrange: bump to 1.17.3

---

media-video/ffmpeg/ffmpeg-4.2.9.recipe
media-video/ffmpeg/patches/ffmpeg-4.2.9.patchset

Review for: https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=5386&viewMode=expanded
- Fixed patchset formatting.

ffmpeg: refreshed for GCC2 build

---

app-emulation/qemu/patches/qemu-8.1.3-haiku.patchset
app-emulation/qemu/patches/qemu-8.1.3.patchset
app-emulation/qemu/qemu-8.1.3.recipe

Successful build and smoke test on x86_64 and x86 secondary arch.
x86: the startup issue for SDL frontend is still there, it throws an exception in roughly 50% of the cases. In other cases it starts successfully. Perhaps a race condition in SLD GL context initialization?
New patches:
- Don't use `-fno-pie` / `-no-pie` - I just commented these out in `meson.build`
- Don't include `main-loop.h` from `haiku.cpp` as it tries to pull in everything and the kitchen sink which doesn't work very well when compiling for C++. - even though we only need the function prototypes for the io thread mutex - therefore I just copied the required 2 function prototypes. This might not be the cleanest solution but at least this way we don't have to figure out how to recompile all the qemu headers in C++.

qemu: update to 8.1.3

---

app-shells/zsh/patches/zsh-5.8.1.patchset
app-shells/zsh/zsh-5.8.1.recipe

* remove completions for other operating systems.  commands borrowed from the Arch Linux recipe
* disable completions that need Haiku support to function properly
* quick path fixes for hosts, known_hosts, and resolv.conf files
existing users can 'rm -r /system/settings/zsh/functions' before updating or they will have stale files left around from the previous package

zsh: completion fixes and cleanup

---

dev-lang/luajit/luajit-2.1.1702296283.recipe
dev-lang/luajit/patches/luajit-2.1.patchset

luajit has switched to a rolling release model using the Unix timestamp of the latest commit as the version number

update luajit 2.1 package

---

app-crypt/qca/patches/qca-2.2.1.patchset

no rev-bump because an update is pending anyway with #9941

qca: fix build

---

sys-fs/fuse-nfs/fuse_nfs-1.0.0~git.recipe
sys-fs/fuse-nfs/patches/fuse_nfs-1.0.0~git.patchset

Mounting and listing files/directires works for NFSv3/NFSv4.
Copying files from an NFSv3 share causes an SMAP violation and stalls with NFSv4.
It doesn't seem possible to unmount a share.  Tracker doesn't give the option in the context menu and running `unmount` in a Terminal fails with a device busy message.

fuse-nfs: add disabled recipe for 1.0.0~git

---

app-shells/bash/bash-5.2.026.recipe

Fixed to apply additional patches for bash5.2.

bash: updated recipe for bash 5.2.26

---

net-misc/lagrange/lagrange-1.17.6.recipe

lagrange: bump to 1.17.6

---

sci-electronics/minipro/minipro-0.6.recipe
sci-electronics/minipro/patches/minipro-0.6.patchset

Minipro is an open source software used to control Minipro TL866xxx MCU programmers/logic testers/... (Over 13000 supported chips).
Considering that it is a rather small program, I looked like a nice exercise to make my first recipe. I did my best to follow the documentation and it seems like files are at the right places after install, at least for my understanding.
I tested the basic functionalities of the program, especially the ones using the local data files and it seems to work fine so far.
There's a few things I'm not sure about:
- Is there any way to support the bash completion files ? I didn't see anything that allows me to put them somewhere relevant.
- I put `all !x86_gcc2` for the architectures. I believe this program should work everywhere since it only depends on `libusb` …

minipro: new recipe

---

dev-lang/qbe/qbe-1.1.recipe

A neat tool to aid in programming language development. Package consists of one executable and several documentation files. Tested and works under Haiku x86_64 on hrev56578+95.
Since this tool only supports 64-bit architechtures (amd64, arm64, rv64) I have disabled secondary architechtures alltogether.

Add QBE Compiler Backend port

---

media-libs/libvisio/libvisio-0.1.7.recipe

Looked like a rebuild for scribus still wanted to pull in the icu66 devel package, hence bumping icu version here.

libvisio, switch to icu74

---

app-text/grcompiler/grcompiler-5.2.1.recipe

Can't be build with newer ICU version, no activity upstream for 3 years, repology doesn't give lot's of hits for it anymore.
If no one is using it I guess it's safe to drop it.

grcompiler, drop recipe, no updates after icu66

---

media-fonts/noto/noto-20240201.recipe

The default display font in Haiku, the Noto Sans Display variant, is no more.
As a consequence, when testing, the default font switched to Noto Sans Thai.

noto: add recipe for version 24.2.1

---

dev-lang/python/patches/python3.10-3.10.13.patchset
dev-lang/python/python3.10-3.10.13.recipe

Fixes #10001 (for 3.10 at least, rest of the versions will come later :-D)
Also:
- Use same way of excluding tests as in 3.11/3.12.
- Disable some more tests that hang reliably.
(built and `hp --test`ed on both hrev57578, and on beta4, both 64 bits)
Thanks a bunch to @korli for his guidance on how to address his one.

python3.10: fix builds on nightlies that include kqueue.

---

dev-libs/caffe/caffe-1.0.recipe

caffe, remove reference to python2.7

---

dev-vcs/git/git-2.43.2.recipe
dev-vcs/git/patches/git-2.43.2.patchset

Switch dependencies for git-svn from alien_svn (obsolete), to subversion.
Built and smoke-tested (bot `git` and `git svn`) on beta4, 64 bits.
Edit: same on 32 bits now.

git: update to version 2.43.2.

---

dev-python/sphinx/sphinx-7.2.6.recipe

It's listed as a required package for the project and gets automatically installed when using pip

sphinx: move snowballstemmer to the REQUIRES section

---

dev-libs/tvision/licenses/TVISION
dev-libs/tvision/patches/tvision-2024.02.04~git.patchset
dev-libs/tvision/tvision-2024.02.04~git.recipe

TVision apps not looking 100% right, same issue as in `mc`: Terminal drawing leaving "vertical gaps" between "line/box drawing" chars.
Other than that, seems pretty functional.
Patched it to build/use shared libs.
The `turbo` editor (scintilla + tvision based), will follow after this one.
---
tested on beta4, both 32, and 64 bits.

tvision: new recipe.

---

net-misc/nextcloud-client/nextcloud_client-3.11.1.recipe

cmocka is only used for testing and can be removed from REQUIRES.
Fix typo in the rm command to remove the applications and icons directories. Also, add several more directories to be pruned.

nextcloud_client: remove cmocka dependency, remove extra files

---

dev-qt/qt6-positioning/qt6_positioning-6.6.0.recipe

This is needed to run NeoChat 24.02.0 and KF6

qt6_positioning, remove "replaces" for qt6_locale

---

media-libs/pnglite/pnglite-0.1.17.recipe

A user over IRC pointed out the missing "libpnglite.so".
For reference, this is what Fedora does:
https://src.fedoraproject.org/rpms/pnglite/blob/rawhide/f/pnglite.spec
---
Tested on 32 bits (gcc2 and x86), and 64 bits.

pnglite: add a symlink on the _devel package.

---

games-simulation/simutrans/patches/simutrans-123.0.1.patchset
games-simulation/simutrans/simutrans-123.0.1.recipe

This should make simutrans compile on x86 again. I also found out that compiling on a 20+ year old laptop is slow, especially with 512 mb of RAM.

simutrans: fix x86 build

---

sys-fs/android_file_transfer/patches/android_file_transfer-4.3.patchset

Should now compile again. I cannot test it because
I currently don't have a working cable with me but I guess it should work as it worked before

android_file_transfer: fix build

---

dev-vcs/tig/tig-2.5.8.recipe

`make install-doc-man` is just too unreliable, for some reason.

tig: fix build.

---

net-irc/irssi/irssi-1.2.3.recipe
net-irc/irssi/irssi-1.4.5.recipe

Not sure if we require a revbump on this case.
Tested on 32 bits. I was able to connect to the Haiku channel on OFTC.
Might as well try to update to newest version thou, so opening as draft for now.

irssi: enable build on 32 bits (x86).

---

dev-python/aiohttp/aiohttp-3.8.1.recipe
dev-python/aiosignal/aiosignal-1.2.0.recipe
dev-python/frozenlist/frozenlist-1.3.1.recipe
dev-python/multidict/multidict-4.5.2.recipe

These packages are needed only by `slixmpp` (which is needed only by `poezio`).
As `poezio` and `slixmpp` are already Python 3.10 only, drop 3.9 from these recipes too.
---
Smoke tested each package on beta4 32 bits. Poezio still functional after installing these.

aiohttp (and dependencies): recipes cleanup.

---

dev-build/autoconf/autoconf-2.72.recipe
dev-build/autoconf/autoconf2.71-2.71.recipe

retain version 2.71 for compatibility, similar to the existing older versions.
Questions for the experts:
- do we need to keep version 2.71?
- the current, version-less version (2.71 before, 2.72 now) uses `compat >= 2.60`. Should that be changed?

autoconf: update to version 2.72

---

games-emulation/mame/mame-0.264.patchset
games-emulation/mame/mame-0.264.recipe

Can someone please check that I've disabled the x86 build properly? Thank you!

mame: Version bump; disable x86 as buildmaster runs out of RAM

---

games-board/peg-e/peg_e-1.3.3.recipe

This PR updates *Peg-E* to `1.3.3` and to switch from Qt 5 to Qt 6.
Confirmed working on `x86_64`:

Peg-E: Update to Qt 6

---

games-puzzle/hexalate/hexalate-1.2.3.recipe

This recipe updates *Hexalate* to `1.2.3` and use Qt 6.
Confirmed working on `x86_64`:

Hexalate: Update to Qt 6

---

games-emulation/geolith_libretro/additional-files/geolith_libretro.info.in
games-emulation/geolith_libretro/geolith_libretro-0.2.1_20240217.recipe

As title says : this is a new libretro core, Geolith, a highly accurate SNK Neo Geo AES/MVS emulator

geolith libretro core : new recipe

---

games-action/xash3d/xash3d-0.20~git.recipe

Just a quick hack, to make sure we still can use this version.
Will try to update to a newer Xash3D later on.
----
Build went just fine on beta4, 64 bits. Installs, and "Xash3D Launcher" starts OK.
~(I haven't, yet, tried to run games with it, thou, nor with the version from the repos).~
Half-Life seems to run fine on beta4 64 bits (my PC is slow, so I had to use the Software Renderer, and keep resolution at no more than 1024x768 or 1360x768).

xash3d: switch to Python 3 for building.

---

media-libs/jasper/jasper-2.0.33.recipe

See: https://jasper-software.github.io/jasper-manual/releases/version-2.0.33/html/index.html
- Tested on Haiku R1B4 x64.
- Don't bump the x86_gcc2 (GCC2) at the moment.
- Passed all unit tests on Haiku x64.
- Passed all unit tests on Haiku x86.

jasper: updated to version 2.0.33 for x86/x64

---

mail-mta/dma/additional-files/dma-finish-setup.sh.in
mail-mta/dma/dma-0.14~git.recipe
mail-mta/dma/patches/dma-0.14~git.patchset

Untested with internet delivery but delivering to local users works.
The recipe is a bit ugly since the `dma` executable wants to have setgid of the group that is created by the package itself.  The package could be made to run as uid/gid 0, but, using a post-install script to make the spool dirs and a copy of the dma executable with correct ownership seems to work ok for now.

dma: add recipe for 0.14~git

---

sys-process/at/additional-files/at-finish-setup.sh.in
sys-process/at/additional-files/atd.launch.in
sys-process/at/at-3.2.5.recipe
sys-process/at/patches/at-3.2.5.patchset

The recipe needs the ugly post-install script to fix directory and executable permissions, similar to the 'dma' recipe, in order to run with reduced permissions.

at: add recipe for 3.2.5

---

haiku-apps/trax/trax-1.1.1.recipe

trax: new recipe

---

sys-devel/llvm/llvm17-17.0.6.recipe

Also fixes building Qt5 on 32bit: https://github.com/haikuports/haikuports/pull/10453

llvm17, move binaries back to /bin (reverts previous move)

---

dev-libs/openssl/openssl3-3.0.13.recipe
dev-libs/openssl/patches/openssl3-3.0.13.patchset

I guess this one is long overdue... the recipe might be not the most beautiful and it has seen only limited testing so far but at least it's a start.
Successful build on x86_64, x86_gcc and x86 secondary arch.
There are a few failed test cases from "make test" - I'll try to add more details on that soon.
So far I marked the recipe as untested which more or less covers the current situation, and this way it should not interfere with existing openssl-1.1.1w recipe.

openssl3: new recipe

---

dev-lang/perl/perl-5.32.1.recipe

This is an alternative solution to #9394

perl: drop gcc2, making perl_x86 the default

---

media-fonts/inter/inter-4.0.recipe

Apparently it's rendered more accurately, see
https://discuss.haiku-os.org/t/what-font-you-are-using/9878/14

inter font: switch from ttf ot otf

---

haiku-apps/genio/genio-2.1.0.recipe

Removed dependency to specific llvm version

Genio: Depend on cmd::clang instead of a specific library version

---

sys-apps/texinfo/texinfo-6.1.recipe
sys-apps/texinfo/texinfo-7.0.3.recipe

to drop the dependency on libperl_x86.
installs binaries in $prefix/bin on x86.

texinfo: move commands to $prefix/bin and update for secondaryArch perl

---

net-dns/mdnsresponder/additional-files/mdnsresponder-finish-setup.sh
net-dns/mdnsresponder/mdnsresponder-2200.120.24.recipe
net-dns/mdnsresponder/patches/mdnsresponder-2200.120.24.patchset

Alright... here's half of the ZeroConf/Bonjour puzzle. With these we can advertize services from a Haiku system, and get to find them from other machines.
The other half, being able to resolve hostnames in the .local domain, requires building a `nss_mdnsd.so` [Name Service Switch](https://en.wikipedia.org/wiki/) module, as I have done so [here](https://github.com/OscarL/mDNSResponder/commit/d95cab2961935f21dbca9b2728a43dfec404eccb), but that requires work on Haiku's side to load without runtime_loader errors (after we patch libnetwork.so's [code](https://cgit.haiku-os.org/haiku/tree/src/system/libnetwork/netresolv/net/nsdispatch.c#n189) to actually attempt to load the nss_mdns.so module).
The module I took from NetBSD, expects some resolv functions not present on Haiku's copy of those …

mdnsresponder: new recipe.

---

dev-lang/perl/patches/perl-5.40.0.patchset
dev-lang/perl/perl-5.40.0.recipe

See https://perldoc.perl.org/perl#History for details of changes. Fixes CVE-2023-47038. (the other security fix affects only Windows)
Because this is a major update of perl, this requires rebuilding all perl packages.
- including git, among others! -- which is why this is still a draft.
Enable threads, which are enabled by most Linux distros as well, apparently. This required some additional patches.
- maybe this helps with sdl_perl on x86 (we will see)
Don't install the `sitecustomize.pl` script any more. I don't think it is actually needed. If it is retained though, it would need some changes to support secondaryArch. The patches which create the script are still included for now, but they could be removed if this change is accepted.
Fixes #10624.

perl: bump version, enable threads, don't install sitecustomize.pl

---

dev-libs/libxml2/libxml2-2.12.5.recipe

Hello,
I ran into  a string encoding problem with a Python package that uses lxml.
```
Traceback (most recent call last):
[...irrelevant bits snipped...]
File "/boot/home/.venv/nikola/non-packaged/lib/python3.10/site-packages/lxml/html/__init__.py", line 806, in fragment_fromstring
elements = fragments_fromstring(
File "/boot/home/.venv/nikola/non-packaged/lib/python3.10/site-packages/lxml/html/__init__.py", line 769, in fragments_fromstring
doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
File "/boot/home/.venv/nikola/non-packaged/lib/python3.10/site-packages/lxml/html/__init__.py", line 736, in document_fromstring
value = etree.fromstring(html, parser, **kw)
File "src/lxml/etree.pyx", line 3307, in lxml.etree.fromstring
File "src/lxml/parser.pxi", line 1989, in …
```

add libiconv support to libxml2

---

net-misc/openssh/openssh-9.8p1.recipe
net-misc/openssh/patches/openssh-9.8p1.patchset

Smoke tested on beta4, 64 bits.
`hp --test openssh` seems broken (since before this update). Tests log ends in:
```
make[1]: Entering directory '/sources/openssh-9.8p1/regress'
run test connect.sh ...
Missing privilege separation directory: /packages/openssh-9.8p1-1/.self/data/openssh/empty
/sources/openssh-9.8p1/regress/test-exec.sh: line 528: /sources/openssh-9.8p1/regress/ssh.log: No such file or directory
cat: /sources/openssh-9.8p1/regress/ssh.log: No such file or directory
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
FATAL: /sources/openssh-9.8p1/regress/test-exec.sh: line 528: /sources/openssh-9.8p1/regress/ssh.log: No such file or directory
cat: /sources/openssh-9.8p1/regress/ssh.log: No such file or directory
tar: Removing leading …
```

openssh: update to version 9.8p1.

---

haiku-misc/barrier_haiku/barrier_haiku-1.0~git.recipe
haiku-misc/barrier_haiku/patches/barrier_haiku-1.0~git.patchset

Opening as draft for now. I was trying to update `synergy_haiku`, but couldn't make it work with a barrier server running on Windows... then... found @kallisti5's [barrier-haiku](https://gitlab.com/kallisti5/barrier-haiku), and it worked (almost) right away.
Leaving it as draft for now (in case @kallisti5 has some feedback on the recipe), and because I want to see if I can address an issue I found with the settings file monitoring code.
Still..., pretty handy!
Tested (for now) only on nightly (hrev57509) 64 bits (connecting to a Barrier server version 2.4.0-release-330d758b running on Windows 10).

barrier_haiku: new recipe.

---

dev-build/muon/muon-0.2.0.recipe

Fixes "Error: COPYRIGHT must not contain e-mail addresses". (not bumping rev, as this is only a lint clean up).

muon: resolve 'hp --lint' error.

---

dev-python/lxml/lxml-4.9.1.recipe

Tested on 32 bits.
After `sigil` (and `beautifulsoup4`'s `TEST()`) gets switched to 3.10, we could just drop the `_python39` version of this package.

lxml: added TEST(), fixed build requirements.

---

dev-util/codeblocks/codeblocks-20.03.recipe
dev-util/codeblocks/patches/codeblocks-20.03.patchset

This is an initial work in progress recipe for CodeBlocks and addresses #2797 and I have disabled this recipe by default (Needs some improvements to wxqt first.)
First it soft-crashes after the splash screen on a missing implementation in the wxqt port.
If you skip and continue running CodeBlocks, the IDE will show up. But closing down the editor will hard crash the app (wxqt related). See: https://gist.github.com/return/e58b55c65300b88d8ee13709ca9857f4 for the report.
Mark this as WIP.

codeblocks: new recipe

---

x11-libs/cd/cd-5.12.recipe

- Removed provides for libs that are not present.
- Make sure you can't install `cd_devel` without the base package.
(built on beta4 64 bits)

cd: fix PROVIDES and REQUIRES_devel.

---

x11-libs/iup/iup-3.8.recipe
x11-libs/iup/patches/iup-3.8.patchset

Build still broken. Fails while trying to link led.c (code generated by yacc) due to several undefined references.
Commented out lua52 stuff, following changes for "cd" on https://github.com/haikuports/haikuports/pull/10684.
Whoever ends up fixing this build can either uncomment, or remove, them as necessary.

iup: re-enable patch, keep recipe disabled.

---

dev-libs/libxml2/libxml2-2.12.5.recipe

Now that libxml2 use iconv, this avoids having to add "devel:libiconv" as build requirements for (at least some) packages that require "devel:libxml2" (as imagemagick and lxml, for example).

libxml2: make _devel package require iconv_devel.

---

dev-python/scipy/scipy-1.6.3.recipe

Rev-bump to address the following:
- Recipe cleanup.
- Dependencies cleanup (checked all the .so modules via `readelf -d <module> | grep NEEDED`).
- #8806.
- Move to Python 3.10, as the only user package on tree (noteshrink) will move there too.
This PR needs #10696 to be merged first, otherwise the build will fail.
ToDo: update to latest `scipy`, once we resolve some missing dependencies for that. This version is at least good enough to re-enable `noteshrink` (despite some benign warnings about mismatched `numpy` version).
Tested on beta4, 32 and 64 bits (heads up: build fails on machines with only 2 GB of RAM).

scipy: recipe cleanups, drop Python 3.9 support.

---

dev-python/scipy/scipy-1.6.3.recipe
media-gfx/noteshrink/noteshrink-0.1.1.recipe

Keeps getting the buildmasters stuck (despite working for me on both 64 and 32 bits, on my Phenom II X4 with 8 GB of RAM).
Fix noteshrink while we're at it, even if will not work still (at least on 32 bits) due to missing "scipy" package.

scipy: disable recipe for now.

---

dev-python/build/build-1.2.1.recipe

Use build from the source dir instead of requiring `build` to be installed. (can also use the commented out `$python -m flit_core.wheel` alternative, if needed).
Part of the fixes for #10717.

build: update to version 1.2.1.

---

app-backup/borgbackup/borgbackup-1.4.0.recipe

Used `readelf -d | grep NEEDED` on the compiled modules to make sure we only require what is actually needed at runtime.
Double checked documented runtime dependencies on Python modules, grepped the sources for the "dependencies" I removed, and smoke tested the provided `cmd:`s after install.
Cleaned up build requirementes while at it. In particular, `cmd:pip` wasn't actually required, (and we should avoid using it on recipes, in any case, IMO, at least in a way we don't control, and using `--no-deps` while at it).

borgbackup: recipe/dependencies cleanup.

---

games-action/classicube/classicube-1.3.6~20240714.recipe

Failure: https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/6528/builds/83773.log
Previous PR: https://github.com/haikuports/haikuports/pull/10229

classicube, disable 32bit, failure on buildmaster

---

dev-python/paramiko/paramiko-2.11.0.recipe

Just a quick cleanup. Moving it to "any", as this is just a pure-python module.
Tests do not run, as we're missing the "invoke" depedency for "pytest.relaxed", and that means bringing in at least 6 more new recipes.
Similar with trying to update paramiko to newer versions.
Seems like too much work for a package that is not used by anything in-tree (thus, just this clean up for now).

paramiko: recipe cleanup.

---

dev-lang/python/patches/python3.12-3.12.4.patchset
dev-lang/python/python3.12-3.12.4.recipe

Built and tested on 64 bits ~only~ and 32 bits too (beta4).
`venv` install scheme additions are untested, but doesn't seems to make things worse than before at least. (I haven't worked with venvs so far, and not really planning to start anytime soon... I prefer PEP-582 :-D).

python3.12: update to version 3.12.4.

---

dev-lang/python/patches/python3.10-3.10.14.patchset
dev-lang/python/python3.10-3.10.14.recipe

Re-worked the patchset, mostly to avoid having scattered changes to the same areas, trying to keep each "commit" on a narrower focus/topic.
Fixes #10211, and attempts to fix some remaining _INSTALL_SCHEMES issues. (makes `platinclude` point to the system headers for the default scheme, which should avoid having to set HAIKU_USE_VENDOR_DIRECTORIES=1 when bulding gdb).
---
Built and tested (hp --test python310) on 64 bits. Built and smoke-tested on 32 bits too.

python3.10: patch set re-work.

---

dev-python/pkgconfig/python_pkgconfig-1.5.5.recipe

While this module could be "any" in theory, doing so means the "x86_gcc2" version of "pkg-config" gets called (that causes problems when packages that use this module to build stuff, get the wrong info on 32 bits, no sane python3 package would be asking for, or expecting, GCC2 stuff).
Cleaned up a bit the recipe while at it, and droped 3.9, as the only user on-tree of this module is Python 3.10 only already (borgbackup).
---
Tested builds of this and `borgbackup` (after reverting #10741) on both 32 and 64 bits. If this gets merged, will open a PR removing from `borgbackup` the transitive/indirect requirement for `cmd:pkg_config$secondaryArchSuffix`.

python_pkgconfig: recipe cleanup/fixes.

---

dev-lang/python/patches/python3.10-3.10.14.patchset
dev-lang/python/python3.10-3.10.14.recipe

Also:
- consolidate recipe 'options' near the top.
- remove pyvenv from provides (removed on Python 3.8).

python3.10: fix a 'ctypes' bug I introduced on the 3.10.14 patchset.

---

dev-lang/python/python3.10-3.10.14.recipe

No revbump, to avoid a rebuild on 64 bits.

python3.10: fix build on 32 bits.

---

dev-python/setuptools_scm/setuptools_scm-7.1.0.recipe

Was only really needed for Python < 3.8.
Should fix #10809.

setuptools_scm: drop importlib_metadata dependency.

---

sys-apps/texinfo/texinfo-6.1.recipe
sys-apps/texinfo/texinfo-7.1.recipe

This is needed to distinguish the two versions on x86.

texinfo: fix compat versions

---

media-libs/libpostproc/libpostproc-10~20172510.recipe

Although old, seems to be still in use, so use ffmpeg5_devel for now.

libpostproc, depend on ffmpeg5_devel for now

---

dev-util/gdb/gdb-15.1.recipe
dev-util/gdb/patches/gdb-15.1.patchset

Fix issues, including random hangs, attach issues in multithreaded programs, and memory read failures.
Full list of fixes is available [here](https://github.com/trungnt2910/gdb-haiku/commits/b74dc3ba/).

gdb: Improve GDB 15 stability

---

dev-python/lxml/lxml-5.3.0.recipe

Fix crash on "import lxml.etree" related to calling xmlInitParser() too late. See: https://github.com/lxml/lxml/pull/370
---
Tested `lxml_python39` with `Sigil` (loaded even an almost 20 MB .epub), and `lxml_python310` with `hp --test gtk_doc`.
The latter has one test failing, but that's the same case with the older lxml 4.9.1.
Didn't tested with Calibre because it has way too many depedencies for my taste.

lxml: update to version 5.3.0.

---

dev-qt/qt5/patches/qtbase-5.15.14.patchset
dev-qt/qt5/qt5-5.15.14.recipe

Fixes #10836 and #10818
Only built and tested on a recent x86_64 nightly with openssl3.
Just below the changed lines, the typical unix lib paths are added, maybe those should also be changed to finddir calls for Haiku.

Qt5: look for SSL library with version 3 suffix

---

dev-python/argparse-manpage/argparse_manpage-4.6.recipe

This is needed for the new version of [psutils](https://github.com/rrthomas/psutils).
Versions < 3 of psutils were written in C and Perl, for version 3 they were rewritten in Python. Currently they are shipped as part of texlive_core (in version 1.23) but I would like to "unbundle" them.
As I'm not that skilled with python recipes yet, could someone please review this? @OscarL

argparse-manpage: new python recipe

---

games-emulation/vice_libretro/additional-files/vice_x128_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_x64_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_x64dtv_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_x64sc_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xcbm2_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xcbm5x0_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xpet_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xplus4_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xscpu64_libretro.info.in
games-emulation/vice_libretro/additional-files/vice_xvic_libretro.info.in
games-emulation/vice_libretro/vice_libretro-3.7_20240827.recipe

VICE is a Commodore 8-bit emulator. This is a new recipe, porting the libretro core.

vice_libretro: new recipe

---

net-dns/yaddns/patches/yaddns-1.1.2.patchset
net-dns/yaddns/yaddns-1.1.2.recipe

Tests do not compile without some minor modifications. (added a comment about that before TEST()).
Test results are all PASS.

yaddns: update to version 1.1.2.

---

dev-build/cmake/cmake-3.28.3.recipe
dev-build/cmake/patches/cmake-3.28.3.patchset

/boot/system/lib/x86 may not be the last path in the list, as is the case with clang after packaged version 12.
Related: #10864
Doesn't build due to an unrelated problem, though. `arc4random_buf` is not detected, but while compiling Utilities/cmlibarchive/libarchive/archive_random.c stdlib.h does include it, leading to a redefinition. Don't know where and how to add _DEFAULT_SOURCE and libbsd, all that I've tried has failed. But then I don't know cmake.

cmake: fix detection of secondary arch

---

media-libs/raptor/patches/raptor-2.0.15-libxml2-2.11.patch?h=lib32-raptor
media-libs/raptor/raptor-2.0.15.recipe

From: https://aur.archlinux.org/cgit/aur.git/tree/raptor-2.0.15-libxml2-2.11.patch?h=lib32-raptor

raptor, revbump for openssl, add Arch patch for libxml2

---

games-emulation/vice_libretro/vice_libretro-3.7_20240827.recipe

Found out that when building the vice cores without cleaning up the intermediate files, they ended up using the wrong symbols and while building would not load at all in RetroArch. As such only the vice_x64 core would work, and none other.
Adding a clean in between each core solves the issue without sacrificing too much of the logic in the recipe.

vice_libretro: release bump to fix extra cores

---

media-libs/libass/libass-0.17.3.recipe

I’m not sure if revision should be bumped if the change is part of the same PR as a version bump; for now i included a bump so both commits also work in isolation

libass: upgrade to 0.17.3 and enable libunibreak

---

net-analyzer/speedtest-cli/patches/800.patch
net-analyzer/speedtest-cli/speedtest_cli-2.1.3.recipe

Patch taken from https://github.com/sivel/speedtest-cli/pull/800

speedtest_cli: use https by default.

---

dev-python/sqlalchemy/sqlalchemy-1.3.24.recipe

This is the newest of the 1.3.x series. As this is a requirement for gertty, and that package hasn't seen development in years, better stick to an older version of sqlalchemy (1.4 *might* work? 2.x surely will not).

sqlalchemy: update to version 1.3.24.

---

dev-util/gertty/gertty-1.6.0.recipe

This is a stand-alone utility. No need to build it for multiple Python versions (switched to "default" Python 3.10).
Removed unneeded or indirect depedencies.
For example, `mako` is really a dependency of `alembic_py`. That package should be fixed instead of listing deps here (not sure what, if any, actually requires `typing-extensions`).
---
Draft for now, until `alembic_py` gets fixed, and I manage to test gertty against some real server.

gertty: Recipe cleanups. Build only once.

---

dev-lang/nim/nim-2.0.8.recipe

this updates nim to release 2.0.8
```
~> uname -a
Haiku shredder 1 hrev58146 Sep 18 2024 06:37:00 x86_64 x86_64 Haiku
~> nim -v
Nim Compiler Version 2.0.8 [Haiku: amd64]
Compiled at 2024-09-19
Copyright (c) 2006-2023 by Andreas Rumpf
git hash: de8282bca5fab25ada92987099e3304278ab3d14
active boot switches: -d:release
```

nim: update to 2.0.8

---

dev-cpp/gflags/gflags-2.2.2.recipe

This fixes errors when including GFlags as build dependency.

gflags: Fix include directories.

---

games-emulation/mame/mame-0.270.recipe
games-emulation/mame/patches/mame-0.270.patchset

First release compiled on R1B5, includes the fix for https://github.com/haikuports/haikuports/issues/10402.
I've switched the package to using the version of boost asio in HaikuPorts, rather than the one bundled with MAME.
The upgrade to R1B5 required defining `_DEFAULT_SOURCE`, as per this thread: https://discuss.haiku-os.org/t/porting-issues-r1b4-vs-nightly/13968
~I've also added an upstream fix for a bug in MAME's Psion SIBO (ASIC5 serial) emulation. https://github.com/mamedev/mame/commit/67b8c40e253a5bd60681590c8d454596ec21d490~ I was able to bump the version to 0.270, which already includes this fix.
Please let me know if anything I've done here needs to be improved.

mame: Bump version; use system asio; define _DEFAULT_SOURCE

---

sys-devel/gcc/gcc-13.3.0_2023_08_10.recipe

* Without gcc as required package, requiring "cmd:gfortran" results in missing libraries
Fixes #11011

gcc-13.3.0: gcc_fortran requires gcc

---

games-strategy/opendune/opendune-0.9.recipe
games-strategy/opendune/patches/opendune-0.9.patchset

I noticed Opendune saves some stuff in `~/.config` so I went ahead and fixed it, changing all references to that with `~/config/settings/opendune`
Also removed `~/config/settings/opendune/savegames` from USER_SETTINGS_FILES as it was (and is) unused (the user can specify the save folder by editing the .ini file either way)

Opendune Home Fix

---

dev-libs/libxml++/libxml++2-2.42.3.recipe
dev-libs/libxml++/libxml++5-5.4.0.recipe

Well, I missed a header while making recipes for these libs so the dev packages error out at compile time when used as dependencies. This patch moves the needed header and fixes the issue. :)

libxml++: Fix stray config header

---

games-engines/gemrb/gemrb-0.9.3.recipe

Well, current build succeded, but [log shows](https://build.haiku-os.org/buildmaster/master/x86_gcc2/logviewer.html?buildruns/6908/builds/84508.log):
```
Warning: POLICY WARNING: no matching provides "cmd:extend2da.py_x86" for "bin/extend2da.py-x86"
Warning: POLICY WARNING: no matching provides "cmd:gemrb_x86" for "bin/gemrb-x86"
```

gemrb: fix build on 32 bits.

---

sys-libs/zlib/patches/zlib-1.3.1.patchset
sys-libs/zlib/zlib-1.3.1.recipe

~Only difference I notice is that current package revision, 1.3.1-3 (built with CMake) has a `libz.so.1` symlink to `libz.so.1.3.1` (on the base package), while this one (1.3.1-4) does not.~
~The`_devel` package content do match.~
~Adding said symlink shouldn't be too hard, if it is really necessary.~
Edit: fixed the above differences.

zlib: build without cmake. 

---

haiku-apps/genio/genio-3.0.recipe
haiku-apps/genio/genio-3.1.recipe

Hi, here's the recipe for Genio 3.1.
The executable is now put in /system/apps and data into /system/data/Genio.

Add recipe for Genio 3.1

---

games-util/lgogdownloader/lgogdownloader-3.12.recipe
games-util/lgogdownloader/patches/lgogdownloader-3.12.patchset

* Needs #11203
There is no cmake configuration files in `devel:libiconv`, so we need to override the cmake bundled `FindIconv`.

lgogdownloader: Fix linking against iconv.

---

haiku-apps/beezer/beezer-0.99.recipe

I have been using this version for quite a few months already. I use the new .hpkg support quite a lot, so I want to just be able to install a version of Beezer that already includes that (I'm too lazy to copy my custom builds around several machines/installs :-D).

beezer: update to a version with SquashFS and .hpkg support.

---

dev-libs/rocksdb/rocksdb-9.6.1.recipe

* Disable unsupported optimizations for 32-bit Haiku
* Fix install directory for `tools` subpackage for 32-bit Haiku.

rocksdb: fix build for 32-bit.

---

dev-libs/libxml++/libxml++5-5.4.0.recipe

Applying #11253 's fix for pkgconfig to libxml++5 as well, since, as far as I can tell, the situation would be the same for this library if used in CMake.
(Sorry for not catching this, I only tested these libraries under GNU Make & friends)

libxml++5: applying libxml++2's pkgconfig fix

---

dev-python/html5-parser/html5_parser-0.4.10.recipe

Only use in-tree of this is from calibre, and that's 3.10 only.
Use beautifulsoup4 for tests instead of the older "beautifulsoup" that isn't there anymore.
---
Tested by installing it, then freshly installing calibre, and making sure it was able to open and show .epub files correctly.

html5_parser: recipe cleanup, dropping Python 3.9 support.

---

dev-python/beautifulsoup4/beautifulsoup4-4.12.3.recipe

Drop Python 3.9 support (only users of this in-tree are all on 3.10).

beautifulsoup4: clean ups.

---

dev-lisp/clisp/clisp-2.49.93~git.recipe

Initial CLISP recipe. It contains CLISP runtime plus modules `asdf` and `rawsock`. It does not contain Haiku specific text editor and web browser applications setup. Other modules are intended to be available also here: `i18n`, `regexp`, `syscalls` and `readline`. A selection of other modules will go to a separate package.

Initial CLISP recipe

---

dev-cpp/gstreamermm/gstreamermm-1.10.0.recipe
dev-cpp/gstreamermm/patches/gstreamermm-1.10.0.patchset

"GStreamerMM provides C++ bindings for the GStreamer streaming multimedia library.  With gstreamermm it is possible to develop applications that work with multimedia in C++.
gstreamermm is developed over glibmm, libsigc++ and libxml++ and the functionalities they provide."
I ported this library because it's a requirement for some stuff I want to build, the recipe works fine but I'm not sure all the files are placed in the package they're meant to be in.

Recipe for gstreamermm

---

app-editors/ecode/ecode-0.6.2.recipe

This recipe updates to the latest ecode release. I also renamed the application since the original name is all in lower-case.

ecode: Bump to 0.6.2

---

games-arcade/hikounomizu/hikounomizu-1.1.recipe

Update of the `games-arcade/hikounomizu` recipe to version 1.1.
It has no major changes except the dropping of GLU and the addition of enet.

Update hikounomizu to 1.1

---

games-arcade/ecwolf/ecwolf-1.4.1.recipe

Making this Pull Request to try and fix the ECWolf recipe for the buildmasters, according to people more knowledgeable than me in coding stuff, currently the buildmaster requires to have both DEFAULT_SOURCE and GNU_SOURCE enabled while compiling the binary, so yeah, I hope this works :)

ECWolf: Fix buildmaster build

---

games-arcade/ecwolf/ecwolf-1.4.1.recipe

As @OscarL mentioned in the last, failed attempt to fix this package on buildmaster, since the build fails on a cpp file maybe the needed flags were meant to be defined as c++ flags.
To me that sounds like a good theory so... here I go again with another patch I cannot test as the problem it's meant to solve isn't reproducible here.

Another attempt at fixing ECWolf on buildmasters

---

dev-python/pyenet/pyenet-20221216.recipe

Nothing currently uses it on-tree.
Only known user, "unknown-horizons", is broken on-tree, upstream is porting the game to Godot, and considers current engine "dead".

pyenet: recipe cleanup. Drop _python39 package.

---

dev-python/pyzmq/pyzmq-25.1.2.recipe

Only on-tree user of this package is 3.10 only (openshot).

pyzmq: recipe clean up. Drop _python39 package.

---

dev-libs/expat/expat-2.6.4.recipe
dev-libs/expat/patches/expat-2.6.4.patchset

* Old versions have been renamed in SourceForge downloads to discourage people from downloading vulnerable versions, so recipes are broken.

expat: Update to 2.6.4

---

dev-lisp/clisp/clisp-2.49.95~git.recipe

New recipe updates CLISP Git revision to current one. In this revision, CLISP updates upstream ASDF module that includes Haiku specific fix.
- Before this fix, :HAIKU symbol was removed from features and CLISP on Haiku was treated as CLISP on Unix.
- After this change, :HAIKU, OS-HAIKU, :UNIX and :OS-UNIX symbols are all present in features, making it clear that CLISP runs on Haiku, which is quite Unix-like.

CLISP: Update ASDF to latest upstream

---

dev-libs/wayland-server/patches/wayland_server-0.1.20241126.patchset
dev-libs/wayland-server/wayland_server-0.1.20241126.recipe

- Text drag&drop support
- Initial support for Firefox port
- Internal stability and performance fix

Update wayland-server to latest commit (20241126)

---

media-libs/libid3tag/libid3tag-0.16.3.recipe
media-libs/libid3tag/patches/libid3tag-0.16.3.patchset

Somewhat like the follow-up to #11349 by also switching libid3tag to Tenacity's fork for the same reasons.

libid3tag: update to 0.16.3

---

dev-lang/luajit/luajit-2.1.1727870382.recipe
dev-lang/luajit/patches/luajit-2.1.patchset

Also need to patch INSTALL_SHARE in the Makefile now to make sure the built-in luajit package path doesn't point to "share"

luajit: update to 2.1.1727870382 (Wed Oct 2 13:59:42 2024 +0200)

---

games-action/classicube/classicube-1.3.7.recipe

I noticed that occasionally when holding `CTRL` + `SHIFT` to move faster in-game, the game will crash, not entirely sure why. I haven't noticed anything else right now.

classicube: bump version (1.3.6 -> 1.3.7)

---

www-client/iceweasel/iceweasel-128.5.0.recipe
www-client/iceweasel/iceweasel_bin-128.5.0.recipe

- no more warnings from haikuporter output

Iceweasel: add libevent to runtime dependency

---

net-dns/mdnsresponder/mdnsresponder-2200.140.11.recipe
net-dns/mdnsresponder/patches/mdnsresponder-2200.140.11.patchset

Enabled *some* IPv6 code paths (untested).
----
Tested on beta5, 64 bits. Edit: and on 32 bits too.

mDNSResponder: update to version 2200.140.11.

---

app-shells/dash/dash-0.5.12.recipe
app-shells/dash/patches/0007-Don-t-execute-binary-files-if-execve-returned-ENOEXE.diff
app-shells/dash/patches/0009-dash-Fix-stack-overflow-from-infinite-recursion-in-s.patch
app-shells/dash/patches/0010-exec-Check-executable-bit-when-searching-path.patch
app-shells/dash/patches/0018-builtin-Don-t-early-exit-when-first-hash-r-is-found.patch
app-shells/dash/patches/0019-builtin-Actually-accept-ulimit-r.patch
app-shells/dash/patches/0021-jobs-Implement-pipefail-option.patch

Removed old Gentoo patches (Debian has a bunch that might be worth adding, perhaps).
Removed spurious readline dependency.
Apparently, libedit could be used instead ("--with-libedit" option of ./configure), but then it fails to compile. Easily fixed, but resulting binary still doesn't do proper line editting at all.
Removed TEST() as "make check" doesn't do anything meaningful.
Smoke tested (on beta5 64 bits) by using it to "jam -q -j4 Terminal" on Haiku's source tree (making sure dash was set as JAMSHELL, of course).

dash: update to version 0.5.12.

---

dev-libs/boost/boost1.85-1.85.0.recipe
dev-libs/boost/patches/boost1.85-1.85.0.patchset

Had to add a patch to avoid a couple of instances of:
`error: invalid application of 'sizeof' to incomplete type 'char []'`
related to the `d_name` field of the `dirent` structure.
(no idea how it got build before without a patch).
----
Smoke tested by installing and executing `innoextract`, and doing `pkgman install vcmi` (but cancelling it after noticing it didn't complained about a missing ICU75 anymore).
Not 100% sure if my build-fix patch is correct. Reviewers welcomed.
Build took almost 40 minutes (work dirs on RAMFS, used `hp -G`), and I almost ran out of RAM (4 GB), so... beware.

boost1.85: link against icu74 instead.

---

dev-python/pandas/pandas-1.3.2.recipe

This version fails to build against Cython >= 3, but newer pandas versions require numpy > 2. So just disable it for now until the needed dependencies get sorted out.
(this should not break things on-tree, as nothing currently requires pandas)

pandas: recipe cleanup, drop _python39 package.

---

media-gfx/krita/krita-5.2.6.recipe

- Retested build on hrev58455 x64 and libjxl 0.6.1.
- Fixed for x86 buildbot build.

Krita:  fixed for R1B5 x86 build

---

haiku-apps/beezer/beezer-0.99.recipe

This allows registering the squashfsimage filetype which Beezer handles. Related to #11542

beezer: force squashfs_tools to load in BUILD_PREREQUIRES

---

dev-perl/alien_build/alien_build-2.84.recipe
dev-perl/alien_build_plugin_download_gitlab/alien_build_plugin_download_gitlab-0.01.recipe
dev-perl/ffi_checklib/ffi_checklib-0.31.recipe
dev-perl/file_chdir/file_chdir-0.1011.recipe
dev-perl/path_tiny/path_tiny-0.146.recipe
dev-perl/test_fatal/test_fatal-0.017.recipe
dev-perl/try_tiny/try_tiny-0.32.recipe
dev-perl/unicode_utf8/unicode_utf8-0.62.recipe
dev-perl/variable_magic/variable_magic-0.64.recipe

Alien::Build is a build-time dependency of one of the dependencies ([XML::LibXML](https://metacpan.org/pod/XML::LibXML)) of [Biber](https://biblatex-biber.sourceforge.net/) which I am [porting](https://github.com/jmairboeck/haikuports/tree/biber) currently. (Most of the perl packages don't have many real build time dependencies, but only runtime ones, and therefore can be built independently.)
Alien::Build would be an "any" package content-wise but requires `pkg-config` at runtime, so it can't be "any" because on x86, `pkg-config-x86` is the correct one, so at least the metadata must be different. (This is a similar situation as with the existing Alien::SDL recipe.)
Note that, for me, "dependencies" also include (mandatory) test requirements, so that the tests at least run successfully. …

Alien::Build + dependencies: new perl module recipes

---

dev-lisp/sbcl/patches/sbcl-2.5.0.patchset
dev-lisp/sbcl/sbcl-2.5.0.recipe

This recipe contains upstreamed Haiku specific patches for:
- Configuration
- Runtime
- Threads support
The following patches are not (yet) upstreamed and provided with this recipe:
- BSD sockets fixes
- Fix ASDF
The tests are not analyzed deeply. Many of them fail at this stage.

SBCL 2.5.0

---

dev-lang/perl/patches/perl-5.40.0.patchset
dev-lang/perl/perl-5.40.0.recipe

Otherwise, packages which install man pages will install them into $prefix/man.
----
Currently I can't build perl on x86_64 nightly (hrev58500) because miniperl crashes in strcmp during the build.

perl: set site and vendor man dirs

---

games-puzzle/monsterz/monsterz-0.7.1.recipe
games-puzzle/monsterz/patches/monsterz-0.7.1.patchset

Taken from https://github.com/0-wiz-0/monsterz/commit/c76690baffe4e7588c1e3061c9baa6e9fcaf9206
----
Tested with both numpy 1.26.0 and 2.2.1 on 64 bits. Runs fine with either.
Next update to `monsterz` might be switching upstream to https://github.com/0-wiz-0/monsterz/

monsterz: apply patch to fix compatibility with numpy 2.x

---

dev-python/alabaster/alabaster-0.7.13.recipe
dev-python/sphinx-argparse/sphinx_argparse-0.4.0.recipe
dev-python/sphinx/sphinx-7.2.6.recipe
dev-python/sphinx_rtd_theme/sphinx_rtd_theme-1.2.1.recipe
dev-python/sphinxcontrib-applehelp/sphinxcontrib_applehelp-1.0.4.recipe
dev-python/sphinxcontrib-devhelp/sphinxcontrib_devhelp-1.0.2.recipe
dev-python/sphinxcontrib-htmlhelp/sphinxcontrib_htmlhelp-2.0.1.recipe
dev-python/sphinxcontrib-jquery/sphinxcontrib_jquery-4.1.recipe
dev-python/sphinxcontrib-jsmath/sphinxcontrib_jsmath-1.0.1.recipe
dev-python/sphinxcontrib-qthelp/sphinxcontrib_qthelp-1.0.3.recipe
dev-python/sphinxcontrib-serializinghtml/sphinxcontrib_serializinghtml-1.1.5.recipe

Also cleanup and drop _python39 from related recipes:
- alabaster
- sphinx_rtd_theme
- sphinx_argparse
- sphinxcontrib_applehelp
- sphinxcontrib_devhelp
- sphinxcontrib_htmlhelp
- sphinxcontrib_jquery
- sphinxcontrib_jsmath
- sphinxcontrib_qthelp
- sphinxcontrib_serializinghtml

sphinx: clean up, drop _python39 package.

---

net-libs/grpc/grpc-1.53.0.recipe

Even if untested (for how long the build process is)... it can't be worse than the currently nonsensical mix of `cmd:python3` and a `_python39` package.
Not touching REVISION, as this only affects `TESTS()`.

grpc: switch tests to Python 3.10. (Untested)

---

haiku-apps/genio/genio-3.1.recipe

Genio uses a glyph only available in noto_emoji which app_server uses as fallback.
Also updated dependency to libgit2

Genio: added dependency to noto_emoji

---

dev-python/coverage/coverage-7.6.10.recipe

* switch to using build/installer instead of setup.py.
* drop Python 3.9 package (nothing requires it on-tree).

coverage: update to version 7.6.10.

---

dev-python/argon2-cffi-bindings/argon2_cffi_bindings-21.2.0.recipe
dev-python/bcrypt/bcrypt-3.2.0.recipe
dev-python/cffi/cffi-1.15.1.recipe
dev-python/pycares/pycares-3.1.1.recipe
dev-python/pynacl/pynacl-1.5.0.recipe

On-tree recipes that depend on cffi:
- argon2_cffi_bindings
- bcrypt
- pycares
- pynacl
So we're doing the same on those too in one go.

cffi: clean up recipe, drop Python 3.9.

---

sys-devel/distcc/distcc-3.3.5.recipe

Warning, running this tends to leave many lingering distccd processes running.
(you're forced to unmount after running "hp distcc --test", and need to manually kill those "rouge distccd"s)

distcc: use Python 3.10.

---

dev-python/lxml/lxml-5.3.0.recipe

Compiled extensions do no link to libpython3.xx.so, so just depend on cmd:python for a matching version.

lxml: drop Python 3.9. Do not REQUIRE libpython3.xx.so.

---

dev-lang/python/patches/python3.13-3.13.2.patchset
dev-lang/python/python3.13-3.13.2.recipe

Only smoke-tested on 64 bits beta5.

python3.13: update to version 3.13.2.

---

dev-python/pycurl/pycurl-7.45.2.recipe

- Don't REQUIRE libpython, but cmd:python3.xx instead.
- Switch from setup.py to build/intaller.

pycurl: recipe cleanups.

---

app-arch/brotli/brotli-1.1.0.recipe

As current TEST() produces no output, tried modifing it in several ways: calling ctest, make -C tests test, etc, etc. Mostly got zero test runs, except once that I got:
> 0% tests passed, 14 tests failed out of 14
but couldn't reproduce :-/
Help on figuring out what's the proper way to execute tests much appreciated.
Smoke tested on beta5 64 bits, both on `python3.10` and with `links` (that requires brotli).
----
UPDATE: fixed silly mistake an now TEST() runs OK.

brotli: minor clean up, drop Python 3.9.

---

dev-python/html5-parser/html5_parser-0.4.10.recipe

- do not REQUIRE libpython3.xx but cmd:python3.xx.
- use suffixless version for lxml_python3xx.

html5_parser: minor cleanups.

---

dev-python/cryptography/cryptography-3.4.8.recipe

Do not depend on libpython3.xx.so, but on cmd:python3.xx.
Untested, as I don't have the necessary rust dependencies to build this one.

cryptography: recipe cleanups.

---

media-libs/libsdl3/libsdl3-3.2.4.recipe
media-libs/libsdl3/patches/libsdl3-3.2.4.patchset

I have added the initial recipe for libsdl3. The recipe is basically taken from the SDL2 recipe. Things related to SDL2main, sdl2-config and SDL2-2.0 are gone since they are not relevant for SDL3. SDL_main is now a header only library and there is no sdl3-config as now pkg-config provides everything (I hope a fixPkgconfig suffices for that).
Known issues:
1. ~~I have only tested in a VM but keyboard related events don't seem to be registered (I will look into this).~~
I have run the tests to check for issues but I think they don't cover all the subsystems well so some more thorough testing of the various subsystems is needed.

Added recipe for libsdl3

---

dev-python/numpy/numpy-2.2.1.recipe
dev-python/numpy/patches/numpy-2.2.1.patchset

Known incompatibilities on-tree were already solved, and I was able to build scipy 1.15.1 against this new version (updated scipy recipe still WIP).
If anything breaks, is surely on outdated software, and we should fix that instead of keeping numpy on an older version.

numpy: update to version 2.2.1.

---

sci-libs/lapack/lapack-3.10.0.recipe

We're making lapack rely on OpenBLAS's implementaiton of BLAS... and the latter already provides its own "cblas".
Unless we make the _devel package conflict with one another, we better disable cblas here.
Also: `lapack.pc` still referenced a "blas" .pc file (as would be the case if we wre using the lapack-provided BLAS).
Changing that to point to openblas.pc instead fixes the meson-based build of `scipy` (and with no missing symbols at runtime).
Fixes #11784.

lapack: disable cblas, make lapack.pc require openblas.pc.

---

dev-python/pygame/pygame-2.0.0.recipe

AFAICS, cython is only used by upstream devs to turn some cython code into .c files (that are already included in the tarball we use).
(Tested with the 3 on-tree games that require pygame. All work without cython).
Side note: numpy dep is documented as "optional", so we may want to remove that REQUIRES from this package, and just add it on packages that use that "extra" functionality.
PyGame's README.rst says:
"The surfarray module requires the Python NumPy package for its multidimensional numeric arrays.".

pygame: drop spurious cmd:cython dependency.

---

app-emulation/spice/patches/spice-0.15.2.patchset
app-emulation/spice/spice-0.15.2.recipe

Builds fine on beta5 64 bits.
Apparently nothing on-tree requires this?

spice: update to version 0.15.2.

---

media-libs/libsndfile/libsndfile-1.2.2.recipe

Fixes requirement reported by the buildmasters:
```
requires "devel:libflac >= 12.0.0" of package "libsndfile_devel-1.1.0-4" could not be resolved
```

libsndfile, bump version

---

media-gfx/yacreader/yacreader-9.15.0.recipe

Both poppler24 and poppler25 provide the same libVersion

yacreader, force poppler_qt5 package usage

---

app-text/booksorg/booksorg-0.3.recipe

Both poppler24 and poppler25 provide the same libVersion

booksorg, force poppler_qt5 package usage

---

app-text/qpdfview/qpdfview-0.4.18.recipe

Both poppler24 and poppler25 provide the same libVersion

qpdfview, force poppler_qt5 package usage

---

dev-libs/litehtml/litehtml-0.9.recipe
dev-libs/litehtml/patches/litehtml-0.9.patchset

What is working so far : 
- compilation OK
- structure of the packaging directory OK
- fix the policy errors for the devel part OK 
- generate .a lib instead of .so lib OK 
- add containers part in the include OK 
- missing litehtml.h in the include OK
What is remaining : 
- improve containers include location
- patch containers part to make it work on haiku with litehtml version 0.9

Litehtml : tentative to port

---

net-misc/youtube_dl/youtube_dl-2021.12.17.recipe
net-misc/yt_dlp/yt_dlp-2025.02.19.recipe

This gets rid of the `yt_dlp` vs `yt_dlp_python310` and `youtube_dl` vs `youtube_dl_python310` distinction.
We only need one of each (as there's really no need to have, say, `yt_dlp` packages for more than one Python version.
This also switches `/bin/yt-dlp` (and `/bin/youtube-dl`) from a "standalone" program (they were "pyinstaller" bundles), into a small wrapper script that calls yt_dlp's entry point from the Python module installed under vendor-packages.
~Using the "standalone" version stopped making much sense once the `requests_python310` "optional dependency" was added to the recipe.~ (edit: read the logs wrong. requests was added only to `yt_dlp_python310` previously, not to the standalone version).

yt_dlp and youtube_dl: cleanup recipes.

---

app-misc/mc/mc-4.8.32.recipe

Hello,
I'm preparing the migration to a new website. As part of this, we will be dropping the www prefix. Also, the site will be statically hosted on GitHub and will no longer support outdated redirects. I have updated the package source to use our official OSU OSL mirror directly.
Thank you!
P.S. We have also been using GPLv3 for quite some time now...

mc: update project links and license

---

games-fps/prboom-plus/prboom_plus-2.6.66.recipe

The current PrBoom+ recipe gets stuck on 32 bit because of a wrong path, this updated recipe should fix that, build on 32 bit is untested but it works fine in x86-64

PrBoom+, fix 32bit build

---

games-strategy/freeciv/freeciv-3.1.4.recipe

Some cleanup of the recipe to remove an obsolete reference to the post install script, use "$prefix/bin" and remove unnecessary linux-related files in the package.
I tested the resulting package and the files removed do not affect the Haiku build, let me know in case you think some of the removed files should stay.

Freeciv: Recipe cleanup, fix strict build errors

---

app-crypt/libmd/libmd-1.1.0.recipe

Nothing seems to actually use this on-tree, but old version is from 2018, and newest is from 2023.
Might be useful if someone manages to port `got` (Game of Trees).

libmd: update to version 1.1.0.

---

games-action/openjazz/openjazz-20240919.recipe

Updates OpenJazz to the latest release. Works on both x86 and x64.

Update OpenJazz to release 20240919

---

games-action/omnispeak_keen4/omnispeak_keen4-1.4.recipe

Its requirements aren't detected on x86, this change should fix it and doesn't affect 64 bit.

Omnispeak Keen4: fix 32 bit

---

dev-vcs/libfossil/libfossil-2025.04.04.recipe

Also, use `$srcFossilRev` as variable name for the Fossil's commit hash (as analogous to `$srcGitRev`).

libfossil: fix build on 32 bits.

---

games-fps/doom_shareware/doom_shareware-1.9.recipe

Apparently Doomworld doesn't want the x64 buildmaster to get DOOM1.WAD from them (exits with 403 - forbidden) even though it worked for 32 bit, so I'm changing the download location to a zip stored at the Internet Archive.
Good news is, this new download location comes with the shareware's documentation so that's being packed as well (except for those files that talk about the included Dos-only utilities, DM and DWANGO)

Doom Shareware: change download location, add docs

---

dev-lang/python/patches/python3.12-3.12.10.patchset
dev-lang/python/python3.12-3.12.10.recipe

Re-run the test suite on both bare-metal nightly 32 bits (hrev58812), and beta5 64 bits under VMware, to double check which tests still hang and which work.
Did my best to add some notes on possible causes for the failing ones.

python3.12: update to version 3.12.10.

---

games-rpg/devilutionx/devilutionx-1.5.4.recipe
games-rpg/devilutionx/patches/devilutionx-1.5.4.patchset

The current package would only work if installed system-wide, so I expanded DevilutionX's patch a bit. 
After this patch it will look into "system/data" first, then fall back to "home/data", so both cases are covered.

DevilutionX: "home" install fix

---

dev-lang/openjdk/openjdk19-19.0.2.1.recipe

> i backported jdk18 haiku patches to jdk19, updated code to make jdk19 working!
(DEPENDS to #12188) to be built.
Tell me if i need to squash commit first.

openjdk19: New Openjdk19 port

---

games-fps/assaultcube/assaultcube-1.3.0.2.recipe
games-fps/assaultcube/patches/assaultcube-1.3.0.2.patchset

A patch to disable the pthread command unavailable in current buildmasters. Crossing fingers and hoping this works.
Note: the package builds fine on the latest Beta 5 version.

AssaultCube: another attempt at buildmaster fix

---

sys-firmware/intel-microcode/intel_microcode-20250211.recipe

Tested package installation on a Celeron N4020 (Gemini Lake), but microcode for that CPU hasn't changed.
More details on the [full release notes](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/blob/main/releasenote.md).

intel_microcode: update to release 20250211.

---

games-fps/yamagi-quake2/patches/yamagi_quake2-8.50.patchset
games-fps/yamagi-quake2/yamagi_quake2-8.50.recipe

This is an update to Yamagi Quake 2 that solves a bunch of issues. (Only tested on x86_64)
Issues fixed since 7.45:
- Copyright is correct #12212
- Fullscreen now covers the whole screen instead of being limited to a quarter of it
- The binary uses "/boot/home/config/settings/yq2" instead of "/boot/home/.yq2"
- Provided backtrace (libexecinfo) during build
Issues present in both versions:
- Binary doesn't find Curl
- Segfaults on exit / loading mods in "native fullscreen" mode (SDL2 issue?)
A part of the old patch was scrapped as the check it was supposed to modify has changed a bunch between versions, I *think* whatever issue it was supposed to prevent should not occur anymore as the binary recognizes my gamepad when it's plugged in.
Let me know if I should add some disclaimer in the …

Update Yamagi Quake 2 to 8.50

---

dev-libs/libigloo/libigloo-0.9.2.recipe

This will be needed when updating Icecast to >= 2.5.

libigloo: new recipe.

---

dev-libs/libigloo/libigloo-0.9.2.recipe

See: https://github.com/haikuports/haikuporter/issues/325.

libigloo: build fix when not using RAMFS workdirs (as in builders).

---

media-gfx/asymptote/additional-files/xasy.rdef.in
media-gfx/asymptote/asymptote-3.02.recipe
media-gfx/asymptote/patches/asymptote-3.02.patchset

This is still work in progress.
It builds and probably works mostly, but isn't integrated well yet.
TODOs:
* the default config files are stored in ~/.asy
* the GUI doesn't work out of the box, it needs cson_python310, which we don't have yet (but is installable via pip)
* should use `open` to open files, like on macOS (easy)
* move the GUI symlink to $appsDir? add resources and a Deskbar symlink? (I didn't find an icon)
It probably makes sense to put the GUI into its own package to avoid the python and Qt dependencies on the main one.

asymptote: new recipe, version 3.02 (part of texlive)

---

dev-qt/qt5/patches/qtbase-5.15.16.patchset
dev-qt/qt5/qt5-5.15.16.recipe
dev-qt/qthaikuplugins/qthaikuplugins-5.15.2.38.recipe

I'm not a user of Qt apps, I've only done light testing with Calligra Words and Qt Designer. That's been enough to find issues even without variable fonts, though. The infrastructure supports variations in weight, width and slant, but as is it would seem some parts or apps just worked with bold and italic bits. Trying the different weights of the standard Noto Sans, the end result was always either regular or bold. In Calligra's font dialog I don't even get different previews for others weights. Likewise with condensed/expanded styles within one font family.
This patch includes changes to font matching that seem to make weights work for me, but for which I'm not confident at all. They are in code shared with other backends, so the issues should not be there.
Variable fonts can have other …

Qt5: support for variable fonts

---

media-fonts/noto_sans_cjk/noto_sans_cjk-2.004.recipe

We probably should add a new package with the fixed-width fonts for compatibility with applications that don't support variable-width fonts yet. (Haiku itself and Qt 6 should already, though.)

Noto Sans CJK: Use variable width font

---

dev-qt/qthaikuplugins/qthaikuplugins-5.15.2.38.recipe

The build in the last update didn't take latest qt5, despite seemingly being built after it.

qthaikuplugins: rebuild

---

dev-libs/libigloo/libigloo-0.9.2.recipe

This side-steps the issue of ./configure thinking that some files got modified, and thus wanting to call automake, when the work-dirs are in a BFS volume.
See https://github.com/haikuports/haikuporter/issues/325 and https://dev.haiku-os.org/ticket/19213.

libigloo: remove unneeded build deps. Kudos to korli for the trick.

---

dev-lang/openjdk/openjdk23-23.0.2.1.recipe

- backported jdk22u patches from it
- fixed build tooling (backported some stuff)
- do some tests
- Native Terminal stuff builtin from java still lagging behind + IDEA doesn't use the builtin API now so i need find a solution for Java Terminal PTY stuff.

openjdk23: new recipe

---

dev-libs/stormlib/stormlib-9.30.recipe

As noted by korli, stormlib's development package should require the base library, this PR fixes that.

Make Stormlib-devel require base lib

---

app-arch/smpq/smpq-1.6.recipe

Update Smpq's recipe after Stormlib's changes in https://github.com/haikuports/haikuports/pull/12275
Keeping it as a draft until the other PR is merged.

Smpq, revbump to build with newer stormlib

---

dev-lang/openjdk/openjdk24-24.0.0.1.recipe

- TODO: I need to port pandoc for rendering manpages
- Backported jdk23u patches
- Fixed build
- Do some tests and do some real cases tests
Ok now i can focus on another things, like porting spotifyd or patch IDEA 2025.1,
btw we have now jdk18..24 before GTA6!

openjdk24: new recipe

---

games-rpg/devilutionx_extras/devilutionx_extras-v4.recipe

This recipe packs a couple of extra assets to be used with DevilutionX.
- CJK support
- ES,PL,RU (fan?)dubs
Tested CJK with Japanese for a bit and it looks fine.
Note: these can be built from source in theory but require porting a specific tool for it.

DevilutionX: extras package

---

dev-lisp/sbcl/sbcl-2.5.4.recipe

Compilation with `CLISP` is available again.

SBCL 2.5.4

---

media-gfx/sane_backends/patches/sane_backends-1.3.1.patchset
media-gfx/sane_backends/sane_backends-1.3.1.recipe

Upgrade sane_backends to latest released version, 1.3.1.
Due to some c++11, we now needs m4 macros from autoconf_archive.
Run ./autogen.sh script before calling configure, as required now.

Upgrade sane_backends to 1.3.1

---

haiku-apps/bescreencapture/bescreencapture-2.9.9.recipe

Not really a big release, although the version number could hint at one: various changes made in previous months which should handle error situations a bit better.
What's new:
Fixed rounding of FPS during recording
Avoid allocating a new bitmap at every frame
Full Changelog: https://github.com/jackburton79/bescreencapture/compare/v2.9.1...v2.9.9

Updated to BeScreenCapture 2.9.9

---

app-arch/libarchive/libarchive-3.7.9.recipe

- Function "readpassphrase" is correctly detected now, so can remove the "ac_vc_func_*" hack.
- Added missing _devel requirements, that should fix detection/usage of libarchive via pkg-config (like for the muon recipe).
- Split commands into a _tools package.
- Removed unnecessary library search paths from libarchive.pc.

libarchive: update to version 3.7.9.

---

dev-libs/yazpp/yazpp-1.9.0.recipe

YAZ++ is a C++ toolkit for development of Z39.50 and SRU clients and servers. It is built on top of the YAZ toolkit and provides additional C++ classes and utilities for building library catalog search systems.
Packages created:
- yazpp: main runtime libraries
- yazpp_devel: development headers and yazpp-config tool
- yazpp_debuginfo: debug symbols

yazpp: add recipe for version 1.9.0

---

sys-firmware/intel-microcode/intel_microcode-20250512.recipe

Tested working on a Celeron N4020 (microcode updates from 0xc to 0x26).

intel_microcode: update to version 20250512.

---

dev-lang/nim/nim-2.2.4.recipe

this updates nim to release 2.2.4
```
> uname -a
Haiku shredder 1 hrev58867 May 18 2025 06:24:28 x86_64 x86_64 Haiku
> nim --version
Nim Compiler Version 2.2.4 [Haiku: amd64]
Compiled at 2025-05-19
Copyright (c) 2006-2025 by Andreas Rumpf
git hash: 5ff0501419c80a972344b4460cc0875745a63b13
active boot switches: -d:release
```
note: required an [update](https://github.com/nim-lang/nimble/pull/1398) to nimble as the nim build process relies on nimble

nim: update to 2.2.4

---

haiku-apps/jxl_translator/jxl_translator-0.1.1.recipe

Originally developed by Craig Watson, now updated and maintained by me after being abandoned by the original developer. The updated version actually functions with the latest version of Haiku and has numerous bug fixes related to reading and writing JPEG-XL files.
If you run into any issues or bugs with the updated port, don't hesitate to report it to me, preferrably on the Codeberg repository but anythere else I'm reachable is fine, too.

jxltranslator: change in upstream

---

gnome-base/librsvg/librsvg-2.58.0.recipe

harfbuzz is indirectly pulled by freetype, make this a direct dependency

librsvg, fix for 32bit build(master)

---

dev-lang/perl/perl-5.40.2.recipe

This contains the needed changes for the perl package after https://github.com/haikuports/haikuporter/pull/321 is merged and deployed on the builders.
This is just an example for now, there are a few more affected packages.

perl: fix doc subpackage (after haikuporter changes)

---

games-emulation/mame/mame-0.279.recipe
games-emulation/mame/patches/mame-0.279.patchset

This build now uses `lld` from `llvm20_lld`. It's significantly quicker than GCC's `ld`, so shouldn't tie up buildmaster for as long!
This also includes two patches from upstream (https://github.com/mamedev/mame/commit/95f7d841988286de21c03f48bfcce45b1aed7bc6 and https://github.com/mamedev/mame/commit/468dfe69a4ba94411359252fca284b69601d56d7), fixing two separate bugs that stopped MAME from compiling.

mame: Bump to 0.279; use lld for linking; small upstream patch

---

net-misc/nextcloud-client/nextcloud_client-3.13.3.recipe
net-misc/nextcloud-client/patches/nextcloud_client-3.13.3.patchset

This is the last version using Qt 5. (with 3.14 they switched to Qt 6)
Can someone maybe test this? I don't have a NextCloud server to test with.

nextcloud_client: bump to version 3.13.3, fix docDir on x86

---

haiku-apps/bsnow/bsnow-1.0.0.recipe

Also, don't forget to "make bindcatalogs" for proper locale support.
----
Tested on hrev58996, x86_64 bits.

bsnow: fix build for non-gcc2 systems.
